### ISSUE TITLE
Enable one click to grants home

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10001]
**User Story:**
As a visitor to the Gitcoin homepage
I want to easily get to the Grants page
So that I can quickly learn more about the Grants program and find grants to fund

**Acceptance Criteria**
GIVEN I am on the Gitcoin homepage (gitcoin.co)
WHEN I look at the "Fund" box
THEN I see the updated body copy and CTA copy

GIVEN I am on the Gitcoin homepage (gitcoin.co)
WHEN I click on the CTA button in the "Fund" box
THEN I go directly to gitcoin.co/grants

**Product & Design Links:**
Designs are available in [this Figma file](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=0%3A1). See the "Ticketed: Navigation" page.

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
hey @schultztimothy this looks good, just one minor tweak: the CTA box should read "View Grants"

Thanks!

**Comment by EmHsiehGitcoin** [comment]
hiii, that's my bad. I got both _View Grants_ and _Explore Grants_ in Figma. Updated the file and keeping _Explore Grants_ for homepage.

In this case, I'd like to update the CTA copy on gitcoin.co/grants from _Explore Grants_ to **View All Grants**. Otherwise, the user would be seeing _Explore Grants_ twice in a roll. 

I think _Explore Grants_ makes sense for Homepage, kinda big-picture-y. _View All Grants_sounds more practical = fits the tone of the grant page more. Open to feedback!
