### ISSUE TITLE
the big "workers going MIA" thread

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1003]
once the new profile is done, i wonder if we want to have it show some sort of demerit on profiles of people who abandon tickets.

possibly even freeze their ability to start work on gitcoin for some amount of time.

maybe i have too high expectations but this is totally unacceptable 
<img width="617" alt="screen shot 2018-04-27 at 8 38 24 am" src="https://user-images.githubusercontent.com/513929/39368406-b95c92e6-49f6-11e8-90f8-2a49ce30aa98.png">

**Comment by owocki** [comment]
@vs77bb per your comment on slack theres a lot more 'started work' issues on the platform.  i think that some of them are likely in the 'abandoned' status

**Comment by owocki** [comment]
also cc @PixelantDesign to see what she thinks.

**Comment by mbeacom** [comment]
I agree with this...  We need to convey to potential bounty hunters there is some sort of penalty for abandoning work.  The impact of a would-be contributor picking up an issue and sitting on it could be devastating for some tasks.
Obviously, things come up... but in a case like the one referenced, it's entirely avoidable with responsible and open communication.

It sounds like we need to explore profile ratings/scores and possibly get more aggressive with kicking contributors off issues if they don't meet the minimum criteria (maybe post a follow up within so many hours) and ding the score appropriately.

**Comment by owocki** [comment]
> It sounds like we need to explore profile ratings/scores and possibly get more aggressive with kicking contributors off issues

i agree with this.. also, maybe making users stake some ETH that they lose if they go MIA would help

**Comment by owocki** [comment]
just put in a change to start logging abandoned work

**Comment by PixelantDesign** [comment]
It's too easy to start work. Wonder if we'll see improvement here when the work schemes are implemented. This is definitely an area where the reputation system can help!

**Comment by thelostone-mc** [comment]
Reminder to self: A % of the bounty put up as collateral when a bad actor attempts to start work on a bounty

**Comment by davidkaufman** [comment]
There is a more positive way of looking at this problem: think of it as opportunity!  A challenge, even...  While it may very well *seem* to be "too easy" for would-be contributors to start work, we have to remember that coding is the whole point of Git, of GitHub and of Gitcoin itself so IMO *lowering* any perceived barriers to entry for new coders is paramount, and that they are so low -- that starting work is so easy --- is, i think, why Gitcoin has been so successful!  Of **course** there will be more people starting work than completing any it, or even making progress -- but this is human nature.  Wanting to do more than is humanly possible, I would argue, is programmer nature :-)

So if we look at the problem as: Clicking on the "Start Work" button is an expression of ```desire to help``` and, since we don't want to discourage new coders from joining up, Gitcoin shouldn't attach any sort of negative consequences risk to that expression-- *certainly* not the risk of some kind of automated loss of reputation for failing to follow through -- that would alienate far more developers than it would help repo owners I honestly believe.  Most OSS contributors are as motivated by building their reputation as by earning money!

As a project, I think we should consider the pressing of the Start Work button like a customer asking for more info about your product.  And if our website doesn't close that sale, then it's the website that needs work (not the potential customer that needs punishing! :-)) Let's look at this as a question of what new, better, jucier **carrots** we can come up with, to dangle in front of new users who take this (often intimidating) first step towards becoming an open source contributor! --- rather than what sticks we can add, to swat them away with :-)

**Comment by thelostone-mc** [comment]
@davidkaufman I do agree with what you say but the context here is penalizing a contributor who takes up a task (aka calls dibs) & is not responsive and does not click stop work thus preventing others from taking it up.

>  And if that interested programmer doesn't go on to become a successful open source contributor -- if our website doesn't Close That Sale 

We'd expect the contributor to be transparent and click on stop work so that others can take it up and the funder would get their issue resolved.

Again we haven't decided anything we are still brainstorming keeping in mind what the best solution for both funder and contributor would be ^_^
