### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1025]
possibly related to https://github.com/gitcoinco/web/pull/790

```
TypeError: Cannot read property 'split' of undefined
1
File https://gitcoin.co/static/v2/js/pages/bounty_details.61a7dfc7b1b2.js line 139 col 50 in Object.issue_keywords
2
File https://gitcoin.co/static/v2/js/pages/bounty_details.61a7dfc7b1b2.js line 472 col 31 in build_detail_page
3
File https://gitcoin.co/static/v2/js/pages/bounty_details.61a7dfc7b1b2.js line 654 col 9 in Object.success
4
File https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js line 2 col 28017 in i
5
File https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js line 2 col 28783 in Object.fireWith [as resolveWith]
6
File https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js line 4 col 14035 in A
7
File https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js line 4 col 16323 in XMLHttpRequest.<anonymous>
```

**Comment by eswarasai** [comment]
@owocki -- Sure. I don't have access to the Rollbar though. My guess is, there's a null check missing for already existing localStorage values.

**Comment by mbeacom** [comment]
@eswarasai I sent you an invitation to rollbar.

**Comment by eswarasai** [comment]
Thanks @mbeacom for the invitation. As I can see from the above logs, the error occurs in `bounty_detail.js` which is left untouched in #790 as you can see in this [commit](https://github.com/gitcoinco/web/commit/6b3b41641c44f519363886473cd0fe61aa8bf973).

I think I might know the root cause for this. There might be a GitHub Project for which we couldn't retrieve any `Keyword`. If it's easy, try looking up in the DB to see which `Bounty.metadata` has `issueKeywords` as empty string.
