### ISSUE TITLE
Gitcoin.co Banner Carousel

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#10271]
#### Description

- Create a carousel for hero banners
- Add in the the GR13 banner 

#### Acceptance Criteria

- [ ] When user goes to landing, they see the carousel 
- [ ] On clicking the carousel, they should be able to toggle between the 2 slides

#### Links needed

![Screen Shot 2022-03-07 at 4 31 27 PM](https://user-images.githubusercontent.com/96255151/157166440-80021874-f98a-4ebe-86e9-06e01c75ab38.png)

[Figma Prototype ](https://www.figma.com/proto/8QjqOzDBd4HiE37YqcocK7/GR13?page-id=311%3A12775&node-id=947%3A51896&viewport=241%2C48%2C1.16&scaling=min-zoom&starting-point-node-id=947%3A51896)

[Figma File: ✍️ Gitcoin homepage](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=311%3A12775)

**Comment by EmHsiehGitcoin** [comment]
@schultztimothy Please note that the text in the middle is changed to "Web3's Biggest Funding & Building Event". I've also updated the carousel indicator to flat lines instead of circles 
<img width="1440" alt="Homepage p 1" src="https://user-images.githubusercontent.com/96255151/157293283-30e71318-7822-4bec-967d-6edec0ff0499.png">

Here are the details: 

"Web3's Biggest Funding & Building Event" = Miriam Libre / Regular / 20pt / 150% Line Height / #000000
March 9-24, 2022 = Miriam Libre / Bold / 32pt / 150% Line Height / #02E2AC


Banner for desktop (2x)
<img width="1440" alt="desktop_HP_GR13_Banner" src="https://user-images.githubusercontent.com/96255151/157291786-f5f21884-6264-4e3b-9ca7-79d6838219fc.png">

(1x)
![desktop_HP_GR13_Banner](https://user-images.githubusercontent.com/96255151/157293652-5d270c2a-7dde-4ae5-979f-2ac13d6621ed.png)

**Comment by EmHsiehGitcoin** [comment]
Cross-posting for visibility: 

can we restrict the GR13 logo size in desktop and not let it scale with the window. this looks perfect for the normal screen
![Screen Shot 2022-03-09 at 9 06 56 AM](https://user-images.githubusercontent.com/96255151/157458839-d421e2c7-a8d9-4d56-a94b-639254a18777.png)
 
but when I stretch my window the Logo scales at the same time when it doesn't have to and it's pushing the spacing which cause the elements to overlap
![Screen Shot 2022-03-09 at 9 06 56 AM](https://user-images.githubusercontent.com/96255151/157459149-d4ef270c-1cf5-4ba5-ae63-236e2f6f2fe6.png)
