### ISSUE TITLE
Unable to manually add missing Polygon contributions

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10330]
**User Story:**
As Gitcoin support
I want to manually add missing contributions from Polygon
So that I can help donors get their funds accounted for

**Details**
Yuki has run into some issues adding manually missing contributions via https://gitcoin.co/grants/add-missing-contributions
When she's tried to add contributions from Polygon she's been seeing an error that reads "Error adding contributions as Signature could not be verified" — this was also seen by the user on their end. 

**Known tx with error**
tx id: 0x0f185fe6afc21a3399ccb605c98669038ba52ea994346ea5bcb6cded55fbbcfd
username: godtest2021

tx id: 0xf6095fc4473cb28baae06df885bf6bbd818f87f92dde3eb1ffc1c3949272aa70

**Acceptance criteria**
GIVEN that I am a user of the [manual contributions form](https://gitcoin.co/grants/add-missing-contributions)
WHEN I try to submit a transaction
THEN the submission goes through successfully

**Comment by schultztimothy** [comment]
I was running into an error when trying to replicate this saying that the tx could not be found. It was changing my network to mumbai instead of polygon mainnet. https://github.com/gitcoinco/web/pull/10334

The error Yuki is seeing seems to be related to her role. There is this block saying that if you are staff that the signature does not need to be verified. In my current role I am able to sign and continue
`
if profile.is_staff:
            return  # Skip signature verification for staff so staff can ingest contributions on behalf of a user
`

I just impersonated her and got the following error when trying to add the contribution manually
<img width="1696" alt="Screen Shot 2022-03-14 at 1 09 28 PM" src="https://user-images.githubusercontent.com/6887938/158244359-83831cc4-a4e7-4637-a71b-670f4965bba2.png">
Looking at the [tx](https://polygonscan.com/tx/0x0f185fe6afc21a3399ccb605c98669038ba52ea994346ea5bcb6cded55fbbcfd) it seems like the error is correct? I'm not seeing any tokens being transferred in that transaction. @thelostone-mc does that seem correct to you?
I was able to verify [transactions like this](https://polygonscan.com/tx/0x19f17f936365bb29c4cbb5a381266fc35a71456299fdccf0e94210f0b6a75e36) locally that have valid tokens being transferred.


 Sorry for all the notes 🤯

**Comment by marian160** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by thelostone-mc** [comment]
Yup ! It looks like this works as expected 
I would say this seems to be an invalid txn. The user probably interacted with the contract and paid only gas fees
No actual funds were transferred -> Hence no Donation event was fired -> Hence we cannot ingest cause there is nothing to ingest.

Closing this out as it is not an error in our codebase
