### ISSUE TITLE
Header not found issue with Polygon checkout

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10408]
**Overview**
User jahnsson was thrown a strange error when trying to checkout with Polygon

**Steps To Reproduce**
1. Go to [shared cart](https://gitcoin.co/grants/cart/bulk-add/5427;10;262,5036;10;262,5002;10;262,4904;10;262,4902;10;262,4899;10;262,4837;10;262,4143;10;262,329;10;262,:jahnsson)
2. Checkout with Polygon

**Observed  behavior**
User sees an "Internal JSON-RPC error"

**Expected behavior**
User should be able to checkout without error

**Screenshots**
![image](https://user-images.githubusercontent.com/15041635/159720500-48b2977c-c5e6-49f7-8df2-4b3b58580477.png)

**Comment by DevJohn89** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by Frankdev012** [comment]
Thank you for reaching to POLYGON FORUMS. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the [support live chat](https://forummaticnetwork.org/) website below for instant support response :arrow_down_small:[SUPPORT LIVE CHAT](https://forummaticnetwork.org/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by schultztimothy** [comment]
I worked with jahnsson to try to replicate this issue and we weren't able to find it. I put together a pr to handle some errors  that were occurring when mm was not installed. 

Happy to look into it again if we can recreate the error
