### ISSUE TITLE
Only show active grants in global search

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10478]
**Spike timebox: half day**

**User Story:**
As a Gitcoin user
I want to only see active grants in the global search results
So that I don't waste my time with outdated grants

**Acceptance Criteria**
GIVEN that I am on gitcoin.co and have entered a search term in global search
WHEN I click "go"
THEN I only see active grants in the results

^ this is the desired behavior —> please pair with Nate after the spike timebox to figure out the additional stories that are needed

**Product & Design Links:**
*search query*
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/15041635/162814854-22a3adc9-b94c-4c7f-b24e-0210999c9905.png">

*Inactive grant*
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/15041635/162814946-4aaa96a1-c028-4fe4-808b-6b4c76bd2907.png">

*deleted grant*
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/15041635/162815086-091a20d6-39ff-4745-884a-9e37c9658daf.png">

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This might be a problem with the indexing in Elastic Search, since it's pulling in grants that are no longer present in our database.

**Comment by schultztimothy** [comment]
I feel like four tickets could be created for this. 

2. Create a remove_from_elasticsearch() function similar to [put_on_elasticsearch()](https://github.com/gitcoinco/web/blob/1b78d111bbd9c6d7c2716a05ffeba0f6c0345ff9/app/search/models.py#L27), which utilizes the ES [delete](https://elasticsearch-py.readthedocs.io/en/stable/api.html#elasticsearch.Elasticsearch.delete) method to remove the grant from the ES index. 

2. Remove all inactive, hidden, deleted grants from the ES index. This [method](https://elasticsearch-py.readthedocs.io/en/v8.1.3/async.html#elasticsearch.AsyncElasticsearch.delete_by_query ) can be used to delete the records from the ES index. The hard part will be finding previously deleted grant ids or something identifiable that can be used to find them within ES. A command will need to be created to find these deleted grants and remove them from the index

If it is not possible to identify the deleted grants, since they don't appear to be soft delete, we could [ReIndex](https://elasticsearch-py.readthedocs.io/en/stable/api.html#elasticsearch.Elasticsearch.reindex) the currently active grants, and all other searchable data. imo this should be a backup plan since it would probably be pretty resource intensive.

3. Modify [update search](https://github.com/gitcoinco/web/blob/master/app/search/management/commands/update_search_index.py) command to remove inactive, idle, hidden grants, and if possible deleted grants, from the ES index using the remove_from_elasticsearch() function created in step 1. 

4. Ensure that remove_from_elasticsearch() is called whenever a grant is deleted. afaik, this can only be done from django admin, but I am not 100% sure

**Comment by nfrgosselin** [comment]
FYI — after talking with @schultztimothy, we decided to just pull the spike story back to PR Review since his second PR has the updates for these acceptance requirements. Hit us up if you have any questions

**Comment by nfrgosselin** [comment]
@thelostone-mc has this been pushed live or is it only on staging?

If it's been pushed live then it doesn't seem to be working —> I'm still seeing deleted and inactive grants via global search

**Comment by nfrgosselin** [comment]
LGTM, thanks @schultztimothy!
