### ISSUE TITLE
Need Help! Changing grant information.

### ISSUE THREAD

**Issue by ahmetoznar** [gitcoinco/web#10801]
### Who

Username: ahmetoznar
Behalf of: https://gitcoin.co/grants/7297/dolven-labs-dao-based-ecosystem-catalyst-for-star

### What

We noticed that some critical information is missing from our grants like tags in the eligibility section and project summary. (Interface while creating grant.)

### Why

We want to know if there is a way to edit them, we cannot access this via the edit grant section. 
Also if possible we would like to delete this entry and make a new one, we see the cancel grant option, but we don't know if it will delete it.

Please let us know, waiting for your response. 

Thanks.

**Comment by YukiPL** [comment]
@ahmetoznar Thank you for getting in touch. 
According to [notion](https://www.notion.so/gitcoin/https-gitcoin-co-grants-7297-dolven-labs-ecosystem-catalyst-d3a1f0bad7114de7ba489b2f3ac6b1eb), your grant has been denied for your requested round. However, we are running another review for main round. Kindly send a DM to @GitcoinDisputes from the twitter account you listed on the page, so that the team can verify you. 
Also, as the support team does not monitor Github channel, I advised for future support, kindly send an email to support@gitcoin.co or create a ticket in our Discord channel. Our knowledge base support.gitcoin.co is also equipped with sufficient information, which we recommend you to read first before dropping us a line.
Thank you and all the best.
Yuki
