### ISSUE TITLE
Transaction Underpriced Issue

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#114]
a community member got a "transaction underpriced" error yesterday too inside metamask when trying to submit a new bounty, tried again today and didn't get this error

the ecosystem is trying to adapt (myself included) to the changes in transaction volume and gas prices

https://etherscan.io/chart/tx

we can clearly do a better job of providing up to date default gas values

**Comment by alx** [comment]
Here is a metamask screenshot. The error happened yesterday, I had no issue by submitting the same issue (with the same parameters) today.

![2017-12-14-170243_1366x768_scrot](https://user-images.githubusercontent.com/373/34001744-13aed020-e0f1-11e7-8091-232f32717be8.png)

**Comment by knocte** [comment]
> we can clearly do a better job of providing up to date default gas values

Amen to that. I just submitted my first bounty to an issue, and in my case it never confirms.

My metamask screenshot is slightly different to @alx's one:

<img width="351" alt="screen shot 2018-05-30 at 6 05 24 pm" src="https://user-images.githubusercontent.com/331303/40714070-313d87b4-6434-11e8-9696-4777f76717de.png">

The default gas proposed by gitcoin was 12 GWei:

https://etherscan.io/tx/0x743f05aaedf82414801b6e53c881296a820acc6bae06aa5c6f02d9effe014ff6

Which is taking ages to confirm because, according to gas station (https://ethgasstation.info/), the SafeLow gas price is 14 minimum, and standard is 40.

What to do from here from the perspective of the user? I'm going to try to increase the fee from metamask, hopefully that will not confuse the gitcoin platform.

**Comment by knocte** [comment]
> I'm going to try to increase the fee from metamask, hopefully that will not confuse the gitcoin platform.

This worked, but didn't realize it would, of course, change the transaction ID, and now the issue is not signaled to be funded:
https://github.com/knocte/gwallet/issues/2

How to recover these funds manually?

**Comment by knocte** [comment]
(New txID is https://etherscan.io/tx/0xd6878ee5f8883c5b68f9b796ef153aa0d07df63f803a8c8f16c3079ed0cc78bd )

**Comment by knocte** [comment]
Oh, it got funded in the end! Did you guys do it manually?

**Comment by thelostone-mc** [comment]
Ah no ! It just a while to sync when you resubmit the transaction  ^_^
