### ISSUE TITLE
AnonymousUser

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#117]
per chat with @ethikz about https://github.com/MyEtherWallet/MyEtherWallet/issues/558

```
ethikz [3:18 PM] 
i claimed an issue and it posted this

```The funding of 0.13 ETH (87.98 USD) attached has been claimed by @anonymoususerethikz.

@anonymoususerethikz, please leave a comment to let the funder (@owocki) and the other parties involved your implementation plan. If you don't leave a comment, the funder may expire your claim at their discretion.

Learn more on the gitcoin issue page
Questions? Get help on the Gitcoin Slack
$10290.58 more Funded OSS Work Available at: https://gitcoin.co/explorer
```

The *anonymoususer* part is what I’m referring to (edited)

owocki 
[3:19 PM] 
hmm

[3:19] 
this is… a new issue

[3:21] 
`AnonymousUserethikz` is the github user in the database… and on the blockchain.. hmm

[3:21] 
so that means something in new_bounty.js must be wrong

[3:21] 
if you go to gitcoin.co/funding/claim does anything prefill in the github username field?

ethikz [3:23 PM] 
yea `AnonymousUserethikz` but i remvoed it all last time

owocki 
[3:23 PM] 
hmm looks like `AnonymousUser`

is a thing in django

```from django.contrib.auth.models import AnonymousUser```

ethikz [3:24 PM] 
ok because i didnt change that js

[3:26] 
hmm js seems ok

owocki [3:28 PM] 
yeah

[3:29] 
hmmm… well i mean its clear `AnonymousUser` is derived somewhere from django

ethikz [3:29 PM] 
yea and i dont see it in code base

owocki 
[3:29 PM] 
do you mind if i post a github issue about this and tag you?  in the middle of something else right now

ethikz [3:29 PM] 
yea fine
```

**Comment by ethikz** [comment]
So after looking more into it and adding some breakpoints on the scripts what I've seen is that:

It must have not cleared out the input when I submitted it and just not noticed it.  So it must have appended my username to **AnonymousUser**.  The information is pulled from localstorage so if someone wants to test make sure to clear the cookies just for the page and see if it loads up **AnonymousUser**.  If it does just click and start typing and see if it clears the input or just appends whatever you type.

From my testing it just appends it which is due to having a **AnonymousUser** set as a value on the input.  Perhaps there shouldn't be a value but a placeholder of **AnonymousUser**

**Comment by owocki** [comment]
bingo! http://bits.owocki.com/3g053l3W3h1v/Screen%20Shot%202017-12-14%20at%208.05.56%20PM.png

good sleuthing @ethikz

**Comment by ethikz** [comment]
Oh ok I was going to fix it lol.

Thanks @owocki
