### ISSUE TITLE
scaling the claiming of bounties as the community grows

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#130]
Problems with claiming bounties right now:

* some people don't have metamask / web3, and need to get set up
* sometimes people start working before they claim.
* if there are many people making a claim, there is no way for a bounty submitter to choose who they want to work with, 
* It seems like someone, `in theory` could go around and claim ALL the issues and take their sweet time in completing them.   Should there be a limit on # of claims you may have active? etc..
* A way to solve would be to force the claimee to “stake” some eth so that I️t would be quite costly to just claim all the issues. However this has drawbacks as I️t creates barriers to entry for people that don’t own ETH
* https://github.com/gitcoinco/web/pull/156 Basically a submit interest button and then putting the power in the hands of the bounty creator to choose which user will be able to make a claim on the issue
* its happened a couple times in the last couple days that someone will claim the issue on github, and someone on gitcoin.. and they work on top of each other without communicating.
* this bug reported https://github.com/gitcoinco/web/issues/169

**Comment by owocki** [comment]
shamelessly stolen ideas from @ernaneluis and jack on slack

**Comment by owocki** [comment]
see also https://github.com/gitcoinco/web/pull/62

**Comment by monokh** [comment]
There might be a few ideas to "borrow" from [Burnable Payments](http://toastycoin.com/) and [OpenBounty](https://openbounty.status.im/).

1. I don't think staking ETH will necessarily increase the barrier to entry. But it would increase the barrier for new users who want to take on a large piece of work on the get go. When Gitcoin does have a scaling problem, I would hope that there would be a large enough volume and variety of tasks, that new users could pick up small/trivial tasks to build up their confidence of the system and minimize the ETH they need to stake. 
2. Another bottleneck is where approval of the claim is done manually. This has 2 side effects mentioned in the other thread. Central point of failure (the approver currently @owocki) and the project owners having to be involved in disputes. Openbounty by Status has solved both of these problems by adding an oracle in the system that takes care of processing the submitted claims. It works like this: 
  - Contributors register their github profile with a wallet address
  - The contributor submits a pull request to the project. They mention the issue with the bounty in the body of their PR. Something like "This fixes #130"
  - The project maintainer can then choose any pull request that references this issue as a valid solution. They could have different criteria to this, perhaps first come first served, or best solution. 
  - When the pull request is accepted, the bounty is automatically paid out due to having a reference to the issue that includes the bounty. 
In this system, the involvement of the Gitcoin team is minimised while at the same time creating a more streamlined and distributed mechanism for approvals.

**Comment by owocki** [comment]
> the involvement of the Gitcoin team is minimised

to be clear, the Gitcoin team is only involved when the Gitcoin team (presently, just me) is the submitter of the bounty.  

this seems very similar to me to the Status Open Bounty mechanism, wherein the submitter of the bounty chooses the claim to pay out.  

> The project maintainer can then choose any pull request that references this issue as a valid solution.

one thing i dislike about this mechanism is that it requires [spec work](https://www.nospec.com/) on behalf of the coder.  i believe the network and community participants shoudl debate whether this is something that is in-bounds ethically per our values ( https://github.com/gitcoinco/gitcoinco/issues/6 )

**Comment by owocki** [comment]
discussion on the spec work stuff => https://github.com/gitcoinco/gitcoinco/issues/9

**Comment by monokh** [comment]
Ah sorry, I misunderstood how gitcoin works. I think the difference then is that on OpenBounty, the creator of the task/bug deals with accepting the issue as valid instead of who funds it. 

I don't mean to endorse spec work, but rather to show the flexibility. Although, I would say that whether spec work is desirable or not doesn't have to be something Gitcoin endorses. Project maintainers and funders themselves can come to an agreement as to what method they would like to use. 

I always thought of Gitcoin more like a protocol than a single network. It can provide a mechanism for funders, maintainers and coders of OSS to collaborate. In that way, if for example, the funders and projects we currently have here do not endorse spec work, then great, that suits everyone within that network. At the same time though, there could be other ways of it working that gitcoin did not necessarily intend or endorse in _another network_.

**Comment by step21** [comment]
@monokh how does staking eth not increase barrier to entry?

Like @owocki said, they are much more involved in case they create a bounty.
Also, instead of adding an oracle, maybe it could just be so that the bounty creator clicks 'pay out' (which I think is how it works now?) and then possibly, if there are disputes and that is within scope for gitcoin, someone else can 'arbitrate'.?

Re work/values - of course there could be 'subcultures' - but primarily to create a decentralized platform/get started I think it would be better if gitcoin focused on 'one community' to grow, if someone really disagrees fundamentally, they can always fork maybe or do something similar?
Personally I really like about gitcoin that you can 'claim' first and then start to work. Especially compared to platforms like fiverr where I would always have the feeling that you work for free most of time. Similarly, when doing other freelance work it is also normal that you get paid for spec work, especially if you have to take into account existing systems and how to integrate with them and whatever. Or there could be an option that the bounty creator specifies which they prefer?

**Comment by monokh** [comment]
@step21 The reason I say staking won't increase the barrier to entry is that anyone using gitcoin, already needs to own ether to claim an issue and at that point, 5% of the bounty amount (which for smaller issues would be under 0.01 ETH) is not going to make a difference for someone that honestly intends to work on it. The % of staked ether could be adjusted as needed. Either way, I think this, or something similar is necessary. Otherwise a malicious user could go around wasting funder and project time.

> Also, instead of adding an oracle, maybe it could just be so that the bounty creator clicks 'pay out' (which I think is how it works now?) and then possibly, if there are disputes and that is within scope for gitcoin, someone else can 'arbitrate'.?

For me, the source of truth on whether someone has completed acceptable work is that their PR that indicates it's fixing the issue has been merged. How would the dispute resolution work? I feel like when disputes are involved, it's as human as it can get and there's little work that can be done on incentives to make sure everyone is playing right. Perhaps reputation systems could help here. 

> Re work/values - of course there could be 'subcultures' - but primarily to create a decentralized platform/get started I think it would be better if gitcoin focused on 'one community' to grow

Cryptocurrency is agnostic to it's usage, the same way I believe you can't make something truly decentralized if you set down subjective rules around what you find acceptable. These rules will ultimately be there be broken, .e.g. using gitcoin someone could ask for spec work and not approve bounties otherwise. I suppose this is a difference in taste. Maybe this is too idealistic. Gitcoin does specifically mention that it wants be a "a community":

![image](https://user-images.githubusercontent.com/11529637/34354116-fd807cc2-ea23-11e7-81f9-1678e72e9bc9.png)

**Comment by owocki** [comment]
just added a few more comments to the issue spec to capture what i've observed last couple days

> * its happened a couple times in the last couple days that someone will claim the issue on github, and someone on gitcoin.. and they work on top of each other without communicating.
> * this bug reported https://github.com/gitcoinco/web/issues/169

**Comment by owocki** [comment]
another good comment via the slack channel:

> If you want to work on a Gitcoin bounty, as soon as you’ve claimed it, how much time do you have to close-out the issue? For instance, sometimes it might take longer just to clarify the requirements with the repo owner than to actually implement the code. If you don’t formally claim a bounty (since it would be unfair to hog a bounty and prevent other users who may be able to clarify its requirements and solve it faster than you) before you’ve finished clarifying the requirements with the Github repo owner, to actually understand the requirements since sometimes the reason a task hasn’t been addressed by the open source community is because the description of the task is has not been written clearly, and determine whether it’s a task that you can actually achieve yourself), then as soon as the client responds and clarifies the requirements every other potential bounty candidate may suddenly be able to fully interpret what the requirements are (particularly if you’ve already provided screenshots that pinpoint what the problem is more clearly), and then claim the bounty entirely for themselves, even though it was a team effort and they may not have had a clue how to approach the problem if you hadn’t invested time doing the groundwork of clarifying the requirements for them

**Comment by owocki** [comment]
closing this now; any ideas that are active to be worked on need to be put into the agile story format.
