### ISSUE TITLE
As a user, I want to be notified that there are 'no fees in beta', so I can know how long the product will be free

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1582]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to be notified that there are 'no fees in beta', so I can know how long the product will be free

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
So users will know that the product will not always be free

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No notification

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
(Dismissable) Notification on top of gitcoin that notifies users that there is no fees during beta, but that we will announce our fee structure soon

**Comment by thelostone-mc** [comment]
@owocki would we be looking for something along these lines ?
https://codepen.io/thelostone-mc/pen/OEGope

**Comment by owocki** [comment]
@thelostone-mc either that or [this](https://pbs.twimg.com/media/DUte9WkVwAM0z6v.jpg)

@PixelantDesign what do you think

**Comment by PixelantDesign** [comment]
Current users might want to learn how this changes from today.
New users might wonder when this will take effect. He/she might be hesitant to sign up for a service knowing that I'll have to pay. 

From an implementation standpoint, something like this since we have the notifications built already?

![nofees](https://user-images.githubusercontent.com/238235/42407238-0859bae2-8186-11e8-8e2c-783111fdf824.png)

We may need to move this once we implement code fund + gitcoin nav

cc: @thelostone-mc @owocki

**Comment by owocki** [comment]
looks fine to me.  i'd maybe cut down the top and bottom padding though.

**Comment by thelostone-mc** [comment]
Should it be dismissable? I made it as a ribbon so that it's subtle and always stays there

**Comment by thelostone-mc** [comment]
I feel we've got too many alerts going on here and there which is I wrote up the ribbon thing!
That's my only concern :|

@SaptakS @mbeacom

**Comment by owocki** [comment]
@PixelantDesign do you think thats a good concern?
