### ISSUE TITLE
css: remove overflow hidden

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#1616]
### User Story

Url : https://gitcoin.co/tip/send/2/
Click on `Advanced` -> Page isn't scrollable

<img width="1440" alt="screen shot 2018-07-04 at 4 37 11 pm" src="https://user-images.githubusercontent.com/5358146/42273963-9651fd80-7fa8-11e8-9b56-cd127eedb7fc.png">

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
Page should be scrollable so as to fill in the other details and submit a tip 

### Definition of Done
Page should be scrollable

**Comment by SaptakS** [comment]
There's a problem bigger than just making `overflow: hidden` to `overflow-x: hidden`. This was introduced [here](https://github.com/gitcoinco/web/pull/1556). The problem is, with `overflow-y`, because of the rain animation in the background, the scroll is uneven and weird. Since the rain effect in background increases the height of page. We need to make a separate layer for the form and make that scrollable while the body remains unscrollable. @thelostone-mc does that make sense?

**Comment by owocki** [comment]
this bug prevented me from putting in a tip so i put in a few stopgaps here

https://github.com/gitcoinco/web/commit/6082a802224508af211ab44eaddd75c67d1fe640
https://github.com/gitcoinco/web/commit/5e533c20702254d776f58413e724fbc859eaae00
