### ISSUE TITLE
Bug: Clicking in the form should clear the plan template

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1852]
On the Start Work Form - when user clicks into the form, the plan template should immediately clear. User should not need to clear the text manually.

<img width="1182" alt="screen shot 2018-07-30 at 2 24 11 pm" src="https://user-images.githubusercontent.com/238235/43415813-91520f80-9404-11e8-88b2-f94be9b28d45.png">

Definition of Done:

- [ ] When user starts typing, all of the text in the form clears.

**Comment by SaptakS** [comment]
I wanted to keep it in the format which github uses for it's new issues and new PRs, so that the users still have a context while typing what kind of things they should write and remove the unnecessary parts rather than the text acting like yet another placeholder.
 So as discussed between me and @PixelantDesign over slack, we will let it be like this and see for the user response. If the users are not happy with this, then we implement this clearing of helper text.
