### ISSUE TITLE
Debug and resolve preferred_payout_address irregularities

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1902]
**Describe the bug**

We have encountered a possible bug with some users having contract addresses as their `Profile.preferred_payout_address`.  This leads to failures when attempting to claim/send tips and bounty payouts.

**To Reproduce**

Check:  https://etherscan.io/tx/0xb41d9e0f8d35829555c1cb27d08b2c1de6897a3e40cf08da6e1198c1ee12a761 for an example of a bugged transaction that was sent to the DAI stable coin contract address (which is specified as the user's `preferred_payout_address`).

**Expected behavior**

`preferred_payout_address` should never be a contract address.  There might be a bug somewhere in the tip flow that is setting the user's preferred address to a contract address versus their input address.

**Snippets**

User that experienced the bad transaction linked above:

```python
In [6]: p.preferred_payout_address
Out[6]: '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359'
```

**Comment by owocki** [comment]
i found the issue.  writing up an issue report now

**Comment by owocki** [comment]
i found the issue

here is the fix: https://github.com/gitcoinco/web/commit/50113ab3e6d77fdde78d20d8f1a80b02c0e05ac3

as you can see in the above fix; the issue was that we were treating the receive tx's `to` param as a good default preferred profile address.  this was a safe assumption EXCEPT IN THE CASE OF AN ERC20 TRANSFER, in which the actual prferred payout address was a param to that tx. derp derp.

i just ran this script to clear all preferred payout addresses on the system, since we dont have a good way of knowing which ones were set by the mgmt command and which were set by users.

```
from dashboard.models import Profile

for prof in Profile.objects.exclude(preferred_payout_address=''):
    prof.preferred_payout_address = ''
    prof.save()

```

here is a script i wrote to re-set the defaults for everyone else in the system

```
from dashboard.models import Profile, Bounty, Tip
from django.conf import settings
from enssubdomain.models import ENSSubdomainRegistration
from faucet.models import FaucetRequest
from datetime import datetime
import pytz


def get_profile(Profile, username):
    profiles = Profile.objects.filter(handle__iexact=username)
    if profiles.exists():
        return profiles.first()
    return None


def save_address(profile, address):
    profile.preferred_payout_address = address
    profile.save()


def try_to_link_address_to_profile(Profile, username, address):
    if not username or not address:
        return False
    profile = get_profile(Profile, username)
    if profile:
        save_address(profile, address)
        #print('-')
        return True
    return False


print('bounty')
for bounty in Bounty.objects.filter(network='mainnet', current_bounty=True):
    try_to_link_address_to_profile(Profile, bounty.bounty_owner_github_username, bounty.bounty_owner_address)
    for fulfillment in bounty.fulfillments.all():
        try_to_link_address_to_profile(Profile, fulfillment.fulfiller_address, fulfillment.fulfiller_address)
print('fr')
for faucet in FaucetRequest.objects.all():
    try_to_link_address_to_profile(Profile, faucet.github_username, faucet.address)
print('tip')
for tip in Tip.objects.filter(network='mainnet').all():
    try_to_link_address_to_profile(Profile, tip.from_username, tip.from_address)
    polluted_data_time = datetime(2018, 6, 24).replace(tzinfo=pytz.UTC)
    if tip.receive_address and tip.created_on < polluted_data_time:
        try_to_link_address_to_profile(Profile, tip.username, tip.receive_address)
print('ens')
for ens in ENSSubdomainRegistration.objects.all():
    if ens.profile:
        try_to_link_address_to_profile(Profile, ens.profile.handle, ens.subdomain_wallet_address)
```

hat tip @JSchiarizzi for helping me find this bug.  i will be making him whole; and to anyone else who had this bug happen to them, i am offering to the same
