### ISSUE TITLE
API call is too slow

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1986]
https://gitcoin.co/api/v0.1/bounties/?moderation_filter=&network=mainnet&tech_stack=&misc=&&coinbase=unknown&order_by=-web3_created

This API call its too slow.  

We should find a way to improve it's performance.

**Comment by mbeacom** [comment]
We just need to introduce real pagination of the queryset results.  Right now, the only thing passing limit and offset is doing is simply slicing the results of the QS and the payload that's returned from the call without offset/limit is returning an object with all results, but split into segments.  We need to page through those results instead of attempting to deliver the whole dataset at once and simulate paging.

**Comment by mbeacom** [comment]
Course of action here:

- Enable DRF OffsetLimitPagination
- Add `PAGE_SIZE` default of something like 50-100 results
- Modify the current infinite scroll functionality to check the existence of `next_page` in the payload and if it's present, request the next page.

**Comment by owocki** [comment]
here is a WIP PR https://github.com/gitcoinco/web/pull/1925
