### ISSUE TITLE
Implement "Grants Detail - Admin" Page - Frontend

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2026]
### User Story

As a Grant creator, I want to view and edit the details of my grant so that I can change details, withdraw funds, give updates, and know how many funders I have. 

### Why Is this Needed

The "Grant Detail - Admin" page is needed to allow a grant creator to edit their grant, withdraw funds, and update their supporters.

### Description

*Type*: Feature

### Definition of Done

[ ] Frontend implements designs at https://github.com/gitcoinco/web/issues/1960 on the https://github.com/gitcoinco/web/tree/grants branch

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

History of the project can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @eswarasai

**Comment by captnseagraves** [comment]
@eswarasai  can you handle this in the next week or over the weekend?

**Comment by eswarasai** [comment]
@captnseagraves -- So as per the design here -- https://github.com/gitcoinco/web/issues/1960#issuecomment-413856482, there are 4 tabs for the Updates section which are categorised. Can you let me know the Backend Model for this so that I can implement the same on the Frontend to display the data accordingly.

Also, there's pagination for the Updates section. Should we implement infinite scroll here as well in order to be in consistent with everywhere else where we avoid showing pagination options?

Another question is related to the Milestones section. Should I implement the edit view of the Milestones or hold off on it and take care of it in v1 as it's missing the UI/UX Design for the edit of milestone flow. Thanks!

**Comment by owocki** [comment]
per the call today... @eswarasai is going to be able to work on this weekend.  cc @thelostone-mc who is also working on grants details

**Comment by captnseagraves** [comment]
1. @eswarasai there is not currently a model for the milestones or updates. @mbeacom I know you said you are working on models, would it be best if you handled this, or should I? 

2. I think moving toward consistency is a good thing, but also know that the team discussed using pagination on the grants/index page. I see how infinite scroll might work better here though. @PixelantDesign do you have an opinion from the UX perspective? 

3. From the grants team call today, it seems that @timborden is working on the Milestones flow. Is this your understanding Tim? are you handling implementation or did you just take on the design piece?

**Comment by timborden** [comment]
@captnseagraves - I'm focusing on the implementation. Having said that, I've not seen designs for that flow, so have done some work in that area as well. I'm hoping that they're be some design feedback on the PR I've put up, so that the Milestones flow matches the flow in the rest of the application.

**Comment by captnseagraves** [comment]
@eswara I know it's only been a couple days since we checked in, but was wondering if you have an expected timeline for this view? There is some web3 functionality I would like to work on that depends on this view. Thank you!

**Comment by thelostone-mc** [comment]
@captnseagraves you've been tagging the wrong person. It's @eswarasai :P 
Also I've left a few questions for you over at the my grants ticket. I will make a basic template post that :)

**Comment by eswarasai** [comment]
@captnseagraves -- My bad. I've missed this out of so many GitHub notifications. I've already implemented the Admin view which is nothing but posting an update form. I need the Backend to be in place in order to get the Frontend working. I assume @mbeacom is taking care of the `Updates` Model?

Thanks for the tag @thelostone-mc :)

**Comment by eswara** [comment]
Please remove from this mailing list. I am not part of your team

**Comment by owocki** [comment]
@eswara sorry for the false tag.  you can 'unwatch' the thread using the 'unwatch' option in the top right

**Comment by captnseagraves** [comment]
Oops! Sorry @eswarasai! Thanks for catching that @thelostone-mc . Moving forward, @eswarasai can you submit a PR for what you have? The core team can carry this issue forward from here since we are getting into crunch time and trying to move fast. @thelostone-mc @SaptakS can one of you take up this issue once Eswara submits a PR? Thank you all!

**Comment by eswarasai** [comment]
@captnseagraves -- All my changes are in the `web:grants` branch on `gitcoinco` repo. No need of separate PR.

@thelostone-mc -- Yep, the Admin view is in the same view as `detail.html` with just a difference if posting update form

**Comment by thelostone-mc** [comment]
@captnseagraves 

- why do we have a button on top the image which says browse grants?  Is that supposed to be there
- I don't see the team-members being displayed on the details page itself. No place to edit that either
If that is the case -> 

- do we remove it from the create grant form ? 
- do we update the models to not accomodate it ? 

me confused 😅 

cc @mbeacom
