### ISSUE TITLE
bug - cookie header doesnt work with other languages

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2052]
screenshot =? http://bits.owocki.com/2F182s212w13/Screen%20Shot%202018-08-21%20at%2011.12.44%20AM.png

repro steps:
1. set your browser to german (or other lang)
2. go to gitcoin.co incognito
3. see bug

scope for this is to 
1. fix this issue
2. recommend any steps needed to prevent it from happeneing again (ie do we have to run auto translate once a day or something)?

**Comment by owocki** [comment]
@SaptakS this is the bug i was emailing u about

cc @PixelantDesign

**Comment by SaptakS** [comment]
Looking at it

**Comment by SaptakS** [comment]
@owocki This should be resolved [here](https://github.com/gitcoinco/web/pull/2157) since translation based on language header is now removed. I think as a step two we can implement [this](https://github.com/gitcoinco/web/issues/2159) and maybe [weblate](https://github.com/gitcoinco/web/issues/2114)?

Closing this issue and taking the discussion forward in these 2 issues.
