### ISSUE TITLE
issue funding best practices

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#22]
Right now, the system supports bug, feature, and security bounties.  Any issue that you need done is a good candidate for a bounty, provided that:

* It’s open today.
* The repo README clearly enumerates how a new developer should get set up to contribute.
* The task is well defined.
* The end-state of the task is well defined.
* The pricing of the task reflects (market rate * complexity) of the task.

What else am I missing?

**Comment by bransbury** [comment]
What about when multiple people submit PRs/solutions? 
Does there need to be something around deadlines for completion for issues that are time-sensitive? Having deadlines would also allow multiple solutions to be provided and one to be chosen. All valid solutions that meet the criteria would earn a small bounty, with the one chosen collecting the main bounty. Issues could be closed early if a user-chosen maximum number of solutions are submitted before the deadline.

**Comment by owocki** [comment]
> What about when multiple people submit PRs/solutions?

yeah, this is not something currently accounted for.  @mbeylin what do you think?

> Does there need to be something around deadlines for completion for issues that are time-sensitive? 

that's what the 'expiration' field is meant to be.  could plasubily call it deadlines though, im not married to it.

**Comment by mbeylin** [comment]
> What about when multiple people submit PRs/solutions?
@owocki in the context of the standard bounties, each PR that's submitted is identical to submitting another fulfillment for the tasks. These can also be updated by the fulfiller as long as the fulfillment hasn't yet been accepted or paid (since then it becomes the property of the bounty issuer). 
> Does there need to be something around deadlines for completion for issues that are time-sensitive?
The standard bounties contract has a deadline for the bounty, after which new fulfillments can't be submitted. This deadline can be altered while the bounty is in the draft stage, but once it is active, the deadline can only be extended (not shortened).
