### ISSUE TITLE
"Worker Approved" firing everytime I visit a Gitcoin Bounty Page

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2316]
**Describe the bug**
"Worker Approved"  is firing everytime I visit a Gitcoin Bounty Page. 

https://gitcoin.co/issue/gitcoinco/web/2287/1290?mutate_worker_action=approve&worker=limonte
https://gitcoin.co/issue/gitcoinco/web/2286/1289?mutate_worker_action=approve&worker=Anish-Agnihotri

**To Reproduce**
Visit this url: https://gitcoin.co/issue/gitcoinco/web/2286/1289?mutate_worker_action=approve&worker=Anish-Agnihotri

**Expected behavior**
"Worker Approved" action should only fire once if no other work has already been approved in a traditional bounty. 

My guess is what is happening is that I have left these windows open, so I can remember to check on them. I reload the page when I visit, but the URL has remained the same so the action is performed again. 

Possible solutions are:
1. Reload the page for the user after the action has been performed
2. Not perform the action based on url
3. Have a try/catch statement in the "approve worker" action

**Screenshots**
<img width="939" alt="screen shot 2018-10-01 at 11 18 07 am" src="https://user-images.githubusercontent.com/22862292/46304848-ff969a80-c56c-11e8-831a-06d6647e7b07.png">

**Comment by owocki** [comment]
> Visit this url: https://gitcoin.co/issue/gitcoinco/web/2286/1289?mutate_worker_action=approve&worker=Anish-Agnihotri


Looks like the URL you are going to is the worker approve URL.  https://gitcoin.co/issue/gitcoinco/web/2286/1289 is the bounty URL

My only worry about making it so that it doesnt show the approval message every time the user goes to the approve URL, is that sometimes users click that URL after approval has alrdy happened, and their reaction is "why isnt it doing anything now? is it broken?"

**Comment by kuhnchris** [comment]
This was fixed.
