### ISSUE TITLE
Profile Enhancement - Bounties in Progress

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2347]
Per feedback from @PumpkingWok 

<img width="411" alt="screen shot 2018-10-04 at 10 01 45 am" src="https://user-images.githubusercontent.com/238235/46479205-8f7e5380-c7bc-11e8-8ab6-cb18fce4340e.png">

### **User Story**
As a user viewing another user's profile, I'd like to be able to see another users bounties in progress.

As me (contributor or funder), I would like to be able to see my current bounties in progress.

<img width="1211" alt="screen shot 2018-10-04 at 9 56 14 am" src="https://user-images.githubusercontent.com/238235/46478974-08c97680-c7bc-11e8-88fc-d5a86bf19048.png">
 
Part of this task may also be looking at how to consolidate the bounties related tabs.

### **Definition of Done**

- [ ] mockups are created to solve and detail the above.

### **Review**
Please review with a core team member
@PixelantDesign @thelostone-mc

**Comment by PixelantDesign** [comment]
@willsputra

**Comment by willsputra** [comment]
@PixelantDesign @owocki  some proposed changes:
1. Add Bounties In Progress tab
2. We could borrow the 'Work Started', 'Work Submitted' etc. tags from the Funder Dashboard so that the activity entries are clearer (this would solve #2340 )
3. Shouldn’t the pictures show the repo logos, not the funder avatars?


![profile](https://user-images.githubusercontent.com/19514207/46541664-37943980-c8ef-11e8-89e2-3d485a554601.jpg)

**Comment by owocki** [comment]
@willsputra @PixelantDesign this LGTM... can i bounty it?

**Comment by PixelantDesign** [comment]
@willsputra looks good!

@owocki makes sense to bounty maybe in a clean ticket...pending feedback from @thelostone-mc @mbeacom -- Any technical guidance to provide here since the project status has been implemented on the funder form but that functionality hasn't been merged?

**Comment by thelostone-mc** [comment]
@PixelantDesign @willsputra  that looks good to me ^_^ 👍

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/2375
