### ISSUE TITLE
slack remarketing

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#239]
# what

if someone hasn't responded to their slack invite (or has been gone for > 1 month), send them an email to ask them for feedback about why they're not interested any more..

secondarily.. ask them if they'll come back and see our recent progress

# why

recapture momentum from people who joined the community and then left.  there are about 2k slack invites out there... but only 100 who are furiously active.

# implementatiojn details

the only way to do this i think is by storing slack presence in the database.  we could store it every hour of every day... and then market to folks who haven't been active in a while.   commit 20fc4220fc4bad90315916431e0781107c581fa3 accomplishes this.  give the campaign a chance in a week or two via slackuser object in database

the email shoudnlt just be a dumb automated email.. it should actually list all of our progress and will need to be maintained month over month

**Comment by owocki** [comment]
curious to try this out sometime in the next few months... cc @mbeacom and @vs77bb in case there's feedback on the idea

**Comment by thelostone-mc** [comment]
I might be a little absent minded here , so feel free to educate me :D

What's the reason behind marketing the slack channel ? To me the gitcoin channel is a where people interested and invested behind the gitcoin misson automatically check in to converse.


If someone isn't interested , that's probably why they left. Sending out an email to them might just end up in their trash mail. Also do folks really respond to this ? I say this from personal experience cause I don't 

Things you could do :
- ask them why they left 
- ask them what would it take to get them back 
- find out what they usually work on -> if we have relevant updates on that, show them that 

The first two requires folks to type in stuff = which usually never works

**Comment by owocki** [comment]
> If someone isn't interested , that's probably why they left.

yep, thats why we'd solicit their feedback.  to figure out what we can improve.  

> The first two requires folks to type in stuff = which usually never works

i agree, but there are things we can do to make it look like a reply-to-able email.  i.e. not make it look super marketing newsletter-ey

**Comment by thelostone-mc** [comment]
Fingers crossed if we can pull this off , it would be pretty sweet :D
I've worked on a few of these but I've never managed to hit the sweet spot

**Comment by tra38** [comment]
Hi Kevin, I'm interested in working on this bounty starting this Wednesday, but I have to think of some good email copy that solicits feedback first.

**Comment by owocki** [comment]
Im happy to write the copy for you.  Don't feel like you need to be the one writing the copy :)

**Comment by tra38** [comment]
Just wanted to post to state that I'm still working on this issue. Since #182 isn't completed yet, I  created a test Slack chat and generated a legacy API key so that I could connect it over to my gitcoin web-app on localhost. I'm currently experimenting with the Slack API and generating realistic-looking test data on my end before I could start writing the code to send out the remarketing emails.

**Comment by owocki** [comment]
thanks for hte update @tra38 -- your testing methodology soudns good to me.  would be happy to take a look at a WIP PR too :)

**Comment by tra38** [comment]
Just finished generating some test data. I notice that we're only querying the presence data once every day, for performance reasons. If a user does not interact with a client for 30 minutes, Slack will mark them as inactive. As a result, I am concerned we may accidentally mark certain active users as being inactive because they are "away" from Slack during the time period when we execute that query. If the user consistently stays offline during the period of

I'm not sure how to best address this issue though, although this [```presence_query```](https://api.slack.com/events/presence_query) method for the RTM API can allow you to query presence for up to 500 accounts at a time. This fear probably wouldn't be a "blocker" for Slack remarketing though, and we could address this issue later on.

As soon as I got some code that can send out emails, I'll send out a WIP PR.

**Comment by owocki** [comment]
> I'm not sure how to best address this issue though, although this presence_query method for the RTM API can allow you to query presence for up to 500 accounts at a time (though that will require learning how to use the RTM API and doing some setup). 

OMG if you can figure this out you will be my hero @tra38 - this would MASSIVELY increase the system's performance

I am more than happy to do a rewrite of the query / storage of this information on the heels of the above ☝️ 

> This issue probably wouldn't be a "blocker" for Slack remarketing though, and we could address this issue later on.

I think at the rate we're scaling right now, it actually might be a blocker.. It takes a 1/2 hour to run through each user 1 by 1 and will only get worse as the community grows.

**Comment by owocki** [comment]
@tra38 i just refactored the way we pull slack presence.. d9255ff254209d8d5b839a1a12c24ac60f76ee7c hopefully this doesnt step on the toes of the work youve done already!

> I'm not sure how to best address this issue though, although this presence_query method for the RTM API can allow you to query presence for up to 500 accounts at a time

I'd LOVE to see the ability to do this.. itd make the querys much faster

**Comment by tra38** [comment]
>hopefully this doesnt step on the toes of the work youve done already!

Cool. Think that will probably make the code much easier to understand. I haven't written any code yet (as most of my work was just understanding how the system works).

>I'd LOVE to see the ability to do this.. itd make the querys much faster

I would definitely want to work on it, but I'm busy at the moment and thus cannot promise that I can work on it. If you need to hand this project off to someone else (so that it can be finished ASAP), that'll be fine.

**Comment by owocki** [comment]
RTM documentation! https://slackapi.github.io/python-slackclient/real_time_messaging.html

**Comment by PixelantDesign** [comment]
This is still a good idea. We could look at users who haven't been back on slack in the last 3 months and send a 'We've missed you" email.
