### ISSUE TITLE
as a user, i want gitcoin to run sync_listener on their own RPC node, so they don't have to rely on infura, and bounties sync immediately

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2394]
as a user, i want gitcoin to run sync_listener on their own RPC node, so they don't have to rely on infura, and bounties sync immediately

how bounties sync:

- in theory, immediately, as long as infura doesnt break
- we do a pass on the last 200 bounties every hour
- we do a pass on ALL bounties once a day

‘fix it twice’ for the ‘wheres my bounty?’ question is here => https://github.com/gitcoinco/web/issues/2388 — i believe that if we ran our own RPC node we could probably also fix the ‘infura broke and immediate sync broke too’ thing

**Comment by mbeacom** [comment]
It's probably worth evaluating the TCO of this move to running our own nodes.

**Comment by mbeacom** [comment]
I don't think this would be a problem. We were running our own for a while, but ultimately turned it off and reverted back to Infura because we no longer saw a need for it (ENS related).  I still have our geth k8s charts and configuration files, so I could have one up relatively quickly...  I think we'd see a major performance boost with respect to sync times.

That said, we'd want to run more than a single node to ensure HA/redundancy/resilience for production use.

**Comment by kuhnchris** [comment]
@danlipert any idea if we ever moved forward with this idea or did we end up dropping it?

**Comment by danlipert** [comment]
Infura works pretty good for now I think, esp. since we are on the paid tier
