### ISSUE TITLE
Onboarding web2 users to web3.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#24]
I think that as evangelists of the ethereum and web3 ecosystem, we may be living in an echo chamber in some ways.  If you've lived & breathed blockchain for months, it can be easy to forget that the average internet user (even the average github user), doesnt have Ether, metamask installed, or even know why they can care.

What is the most efficient and impactful way you've found for telling people why they should care about understanding this ecosystem?

**Comment by owocki** [comment]
this discussion is worth a link

https://www.reddit.com/r/linux/comments/73dv1j/fund_open_source_software_with_these_5_platforms/

Some feedback I got on it from someone way smarter than me : 

```
I'll offer some thoughts on the matter

We *should* be careful about using the word *should* :stuck_out_tongue:

"Open Source Funding should be decentralized"

First, I don't think it's totally obvious why this *should* be the case, just as it's not obvious to most people why  decentralized money *should* even exist in the first place, since it's all quite complex

Perhaps instead "this *should* be that way", a more descriptive approach could be used, without as much value judgement baked in.  "A platform which enables decentralized payments to support FOSS offers great benefits, such as a) no cream scraped off the top by intermediaries, b) censorship resistance, c) legal simplicity, d)... etc"

This is getting a little Public Relations Techniques 101 here, but I think it's quite relevant we, as the crypto community, often have the habit of proclaiming decentralization and disintermediation as a self-evident good, and to people outside the community it can sound a bit religious

Decentralized vs Centralized is also couched in very binary terms, where if it's not one, then it's the other. I think it's a bit more nuanced, and a wide spectrum of design decisions exists between the two.

In working out blockchain application ideas, I've had to form a habit of taking off the "this is cool tech, and aligns with my philosophy too!" cap, and put on my monocle and tophat :tophat: to ask the more difficult questions of "does this make sense from a business perspective?" or "does the benefit of having this system be totally decentralized outweigh the costs to the user experience and complexity added to the platform?".  "Is there a centralized approach that would benefit the UX, platform simplicity, and cost less? Or perhaps, is there a hybrid approach?" (edited)

As I'm sure you know, playing your own devils advocate, as painful as it can be, is often a healthy and stimulating exercise. (edited)

>These platforms are great and all, but they're all centralized and thereby, not the long term platform for pushing open source repos forward.

I majorly dig gitcoin, and I certainly dig your perspective and philosophy. I just don't want to alienate others outside the community with an air of elitism. To frame in "it's X ergo it's wrong"  terms, even if the proposition is sound, can be alienating to those waiting to be convinced. (edited)

The functional programming community has a similar problem as well, often sounding elitist, making self evident proclamations, and shrouding the perceived complexity of FP with their wizard capes to fend off the uninitiated.  The Elm community is trying to fix this, and doing a great job at it. Open hearts, enthusiasm, and kind tones are rampant in the Elm slack, and it has attracted a ton of people, and the community has become notorious for it. (edited)

Very similarly between the Bitcoin and Ethereum communities, where Ethereum saw the toxicity that could brew up in a void of chaos that was the BTC community, and works to actively fend that toxicity off

That's my .2 ETH, don't know if it came out as I would have liked.  In conclusion, I just wanted to emphasize that...

>"These platforms are great and all, but they're all centralized and thereby, not the long term platform for pushing open source repos forward."

wording things this way could alienate or throw some people off.



My response was way too ranty. Forming words via the tubes is hard. I imagine my rant above could have come off as judgey or condescending too, not my intention. More just a constructive criticism, since you asked. All in good :heart: @owocki Cheers (edited)
```

**Comment by tra38** [comment]
As a non-Ether evangelist (and thus a person who hasn't lived and breathed the blockchain for even 2 weeks), I might be able to chip in my two Zimbabwean dollars into why I am participating in the Gitcoin ecosystem.

If Gitcoin was presented as a cryptocurrency startup, I don't think I would have bothered looking any further. Instead, Gitcoin was presented as '*Freelancer* for Open Source' and the slogans "incentivize open source contributions" and "pushing open source forward" resonated a lot with me. The ability to personally examine the codebases of potential projects and understand exactly the amount of money that maintainers would charge for me (knowing, of course, that exchange rates can fluctuate) also was helpful to me. I didn't quite get why there was an emphasis on "decentralization", and I noticed that most bounties were for projects within the cryptocurrency space (though this may be due to the fact that all the bounties are denominated in crypto, so they're the early adopters with the cash to spare).

Downloading Metamask just to be able to receive Ether was an odd step, but not really so odd considering that Freelancer and Upwork has their own unique jargon (and sometimes even software) that they might require you to do. It's just one more step you have to take to participate in the ecosystem. And I'm willing to take that step if I believe that the rewards of participating in the ecosystem would be worth my times and effort.

It seems that there are only a few competitors to Gitcoin - there are many ways to fund maintainers to keep maintaining software, but the options for maintainers to *outsource* the maintenance work seems to be very limited ([BountySource](https://www.bountysource.com/) seems to be the closest you can get to that). So I really think Gitcoin found a valuable market niche that it can be exploit. Whether Gitcoin is decentralized or not is a minor technical detail that might convince a few people. If Gitcoin can prove that its approaches can further open source, then people will be willing to deal with Ether, Metamask, etc. Give them a reason to care, and people will care.

**Comment by owocki** [comment]
> two Zimbabwean dollars

hehe

good feedback here @tra38 . thanks for typing it up!

**Comment by owocki** [comment]
convo here is related i think https://github.com/gitcoinco/web/issues/35

**Comment by owocki** [comment]
@vsingh1993 some of this might make good content for you if/when you join the team
