### ISSUE TITLE
As a funder, my issue data should be populated in the bounty

### ISSUE THREAD

**Issue by maurelian** [gitcoinco/web#2527]
**Describe the bug**

When I paste the issue URL in, no data is pulled from Github. 

**To Reproduce**

Paste this into an issue URL: https://github.com/maurelian/Newsletter/issues/1

**Screenshots**
![image](https://user-images.githubusercontent.com/23033765/47473510-e89c3e80-d7e0-11e8-8d60-70db083b6ebf.png)

Image from here: 
https://gitcoin.co/issue/maurelian/Newsletter/1/1610

**Desktop (please complete the following information):**

- OS: ubuntu 18
- Browser Chrome 69.0.3497.92 (Official Build) (64-bit)

**Comment by Anish-Agnihotri** [comment]
Hey there!

This seems to be working for me [(demo](https://streamable.com/fsdil)) if I use the link you specified. 

Are you still facing this issue? If so, would you mind sending a screenshot of your console (so that I can see if there are any issues)? Assuming you are in chrome, simply `Right Click + Inspect` and press `Console` to bring that up.

**Comment by maurelian** [comment]
Yes, working now. Thanks! I think there were issues with the GitHub API last night, as links in slack weren't expanding either.
