### ISSUE TITLE
The Gitcoin Issue Details page Github link says "Issue is Closed" even after the Github issue is re-opened, and the Gitcoin status is open. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2540]
**Describe the bug**
The Gitcoin Issue Details page Github link says "Issue is Closed" even after the Github issue is re-opened, and the Gitcoin status is open. 

**To Reproduce**
Example: https://gitcoin.co/issue/MetaMask/metamask-extension/4074/865

On Gitcoin Issue Details:
![screen shot 2018-10-25 at 16 47 05](https://user-images.githubusercontent.com/7516920/47536590-ca345280-d875-11e8-90fa-c5a3c011e17a.png)

On Github Issue:
![screen shot 2018-10-25 at 16 47 14](https://user-images.githubusercontent.com/7516920/47536593-cd2f4300-d875-11e8-84cd-48ac9a537d0c.png)

![screen shot 2018-10-25 at 16 47 22](https://user-images.githubusercontent.com/7516920/47536601-d4eee780-d875-11e8-95c8-c3e8b5e9c4a8.png)

**Expected behavior**
The Github link on the Gitcoin Issue Details page should update once an issue is reopened.

![screen shot 2018-10-25 at 16 49 38](https://user-images.githubusercontent.com/7516920/47536616-fcde4b00-d875-11e8-8a11-7ec20bc64916.png)

**Desktop:**
- OS: macOS High Sierra 10.13.4
- Browser: Google Chrome
- Browser Version: 70.0.3538.77 (Official Build) (64-bit)

**Comment by octavioamu** [comment]
@frankchen07 we have another similar examples? 
this issue seems to me have also biggest issue ConnorChristie deliver the job, get paid but was retired by abandon
![image](https://user-images.githubusercontent.com/1358093/47947896-83dd9400-df04-11e8-890a-f946f04b3c2b.png)

![image](https://user-images.githubusercontent.com/1358093/47947906-9657cd80-df04-11e8-96b1-0dbcd03c8064.png)

In general seems to me that we are not attending this flow, seems they paid before Connor submit.

**Comment by frankchen07** [comment]
^ I believe it's also a bug bounty. The funder has requested to leave the issue open to ensure that the changes aren't going to break in the future. 

Perhaps the project type should have been something like a cooperative or contest type, not traditional, which allows it to remain open and the funder can tip or use advanced payout.
