### ISSUE TITLE
As an admin who is not the funder of an issue, I'd like an easy way of removing abandoned workers.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2541]
### User Story
As an admin who is not the funder of an issue, I'd like an easy way of removing abandoned workers.

### Why Is this Needed
The admin controls currently do not incorporate a "remove worker" option if you are not the funder of an issue. For Gitcoin Core folks doing Issue Explorer checkins, it is critical that we can easily remove abandoned workers from issues with ease.

### Current Behavior
Currently, an admin who is not the funder of an issue has to click "View in Admin", scroll down, and delete the entry in "interested", and hit "save" in order to remove the worker.

Admin button:
![screen shot 2018-10-25 at 09 20 08](https://user-images.githubusercontent.com/7516920/47536791-074d1480-d877-11e8-95f7-d7041b1b1504.png)

Remove "Interested":
![screen shot 2018-10-25 at 10 36 45](https://user-images.githubusercontent.com/7516920/47536794-0916d800-d877-11e8-80f1-29acb286067c.png)

### Expected Behavior
There should be a more readable and intuitive way to remove one and/or multiple workers for abandonment by Github handle, not profile ID.

### Definition of Done
1. Remove workers option shoudl be available for non-funding admins.
2. An option to remove one or multiple workers by Github handle in the admin controls.

**Comment by spiegeleixxl** [comment]
So instead of "Interested" you actually want to have the Github Handle/Gitcoin Username, instead of "comment" you want to see the actual comment (instead of the ID) and a button to remove the person? Technically it's a admin function (assumingly a Django Admin Function, as far as I can see). For testing purposes I'd need a way to re-create something like that on testnet/a local test instance,is there any easy way to "Start work" on a issue when I impersonate a user?

Thanks!
