### ISSUE TITLE
Duplicate Kudos in the marketplace (Always Shipping)

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2573]
**Describe the bug**
Duplicate Kudos in the marketplace. 

<img width="563" alt="screen shot 2018-10-30 at 08 41 32" src="https://user-images.githubusercontent.com/7516920/47731837-2efafe80-dc22-11e8-99b6-b1a67c7177f1.png">

**To Reproduce**
Kudos page, scroll down.

**Expected behavior**
Only distinct Kudos should exist.

**Comment by jasonrhaas** [comment]
This happened due to the `mint_all_kudos.py` code.  There is code in there to handle retries for when the mint fails.  Unfortunately sometimes `web3` comes back with an error, so the code will retry, but the first mint goes through anyway.

https://github.com/gitcoinco/web/blob/master/app/kudos/management/commands/mint_all_kudos.py#L158-L175

I added some code in my branch below that doesn't retry right away, it just logs the error and moves on.  This is a better approach since we can't rely on the responses from web3py, we just need to let the thing run and see what tokens actually got minted.

https://github.com/jasonrhaas/web/blob/kudos-recovery/app/kudos/management/commands/mint_all_kudos.py#L157-L172


As far as fixing this problem right now, I think the best solution is to "burn" one of these tokens (sends to address 0x0), and then in the code, we should exclude any tokens that have `address == 0x0` here:

https://github.com/gitcoinco/web/blob/master/app/kudos/views.py#L110-L127
