### ISSUE TITLE
Missing post-synchronisation for issue founders

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2579]
**Describe the bug**
Apparently some funders of issues aren't properly connected to their profiles.

**To Reproduce**
Not sure, can't reproduce on purpose

**Expected behavior**
Have the issue funder's name displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/47752968-52f82780-dc96-11e8-9e4f-383c9a46b5b5.png)

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser Chrome
- Browser Version Latest Stable

**Comment by kuhnchris** [comment]
For reference: The affected bounty is this one:
https://gitcoin.co/issue/gitcoinco/web/2508/1650

**Comment by PixelantDesign** [comment]
Thanks for the report @kuhnchris!

**Comment by frankchen07** [comment]
Ah, beat me to it. 😄 good catch!

**Comment by thelostone-mc** [comment]
So what probably happened is that the options below were checked by default causing the name to be rendered `Anonymous`

<img width="805" alt="screen shot 2018-11-09 at 12 11 16 am" src="https://user-images.githubusercontent.com/5358146/48219977-0ad2b680-e3b4-11e8-9c41-0330e109d71e.png">

For Activities we track user action which doesn't taken into account if the funder has selected hide options.

We could either 
- remove those options 
  (personally I don't think we would need it cause it openness == transparency )
- update the Activity to keep track of that ( which might be a bit more tricker )

Here is the API response for that bounty :
https://gitcoin.co/actions/api/v0.1/bounties/?github_url=https://github.com/gitcoinco/web/issues/2508

@PixelantDesign @frankchen07

**Comment by kuhnchris** [comment]
![image](https://user-images.githubusercontent.com/761911/48227107-baeaf400-e3a1-11e8-9ed7-3e5dd0a3faf0.png)
That seems redundant at best. if any of those values is not "Anonymous" then it wouldn't make sense to hide 'any' of em...

**Comment by thelostone-mc** [comment]
So we always display the github username in the activities stream but on the footer we display the name of the funder which in this case @PixelantDesign has chosed to hide which is why that is anonymous.

The most sensible thing at this point in my head is
- Show the github username as opposed to the name of the funder in the funder info.
- Or do a check to see if funder doesn't want his name to be shown -> instead show github username

**Comment by frankchen07** [comment]
I like your thought that the default should be showing the Github username - let's implement that. 

As for checking to see if the funder wants his/her full name shown, I want to open another ticket and place it to the greater team on removing the anonymity function on the funder form completely, since it's not truly anonymous. It's also adds another concerning decision point for the funder to make about their data.

Anonymous only works if it's completely carried throughout the "All Activity" section and throughout Github (which isn't possible). To me, it doesn't make sense to be in open source, funding issues, and remain anonymous - that's sort of the reputation part of open source.

**Comment by thelostone-mc** [comment]
@kuhnchris 7 @frankchen07 we've got a fix out over at https://github.com/gitcoinco/web/pull/2759 ^_^

**Comment by kuhnchris** [comment]
Great, thanks for the hard work! :-)
