### ISSUE TITLE
as a user, i would like to be able to send kudos via *slack*, because that's where my coworkers are

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2616]
_From @owocki on October 8, 2018 4:12_

as a user, i would like to be able to send kudos via *slack*, because that's where my coworkers are

_Copied from original issue: gitcoinco/gitcoin-erc721#158_

**Comment by octavioamu** [comment]
@PixelantDesign  bring this interesting slack integration https://www.heytaco.chat/

**Comment by Anish-Agnihotri** [comment]
I know this issue is a little old now, but it caught my eye as being something pretty cool possibly. 

I don't know how exactly Kudos would tie into it (since Web3 can't be injected into Slack), but I could certainly upgrade the existing Slack Bot to have a special #kudos-appreciation notification channel possibly?

**Comment by owocki** [comment]
yeah thats a good idea
