### ISSUE TITLE
Skills Match Setting & Email - Update Keyword Description

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2817]
### User Story

As a user I'm unclear why Gitcoin recommends issues to me that do not match my skillsets.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

In the email we should make this a little more clear that we match on the description / title / keywords (not just keywords).

### Current Behavior
Only mentions Key Words

### Expected Behavior
Match what is in my profile

### Definition of Done

- [ ] Update description in the profile matching UI
- [ ] Update the Match email header so that it's clear what  Gitcoin matches on.

In the email we should make this a little more clear that we match on the description / title / keywords (not just keywords).

### Additional Information
<img width="559" alt="screen shot 2018-11-14 at 8 15 30 am" src="https://user-images.githubusercontent.com/238235/48484973-99489d00-e7e5-11e8-8d3a-3fa87a1d7e31.png">

**Comment by kuhnchris** [comment]
We could add why the bounty was selected, like "You get this bounty because of the following matching words: 'javascript'" and maybe a highlight.
Additionally, we could make this more clear by telling the user "Based on your tags and settings we found the following bounties that may also match your profile:" combined with the above info and "If you want to change this setting, please head over to (Settings) and change your keywords. 
Incase you see abuse of this system, please let us know by reporting the bounties in question!"

-Chris

**Comment by PixelantDesign** [comment]
Thanks Chris! Great ideas! I'll update the ticket.
