### ISSUE TITLE
Display Which Worker Was Approved

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2819]
### User Story

As a contributor or funder looking at the activity list, it's hard to tell who has actually been approved for work.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: It's unclear right now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
Does not say who has been approved

### Expected Behavior
It should say who has been approved

### Definition of Done

- [ ] It clearly states inline which worker has been approved.

### Additional Information

In this scenario it should say:  Worker Approved Evgeniuz

<img width="954" alt="screen shot 2018-11-14 at 10 34 47 am" src="https://user-images.githubusercontent.com/238235/48493096-3234e380-e7f9-11e8-8247-f83679317631.png">

**Comment by usmanmuhd** [comment]
Can I take this up?

**Comment by owocki** [comment]
1. link to bounty pls?
2. if you scroll up there is a 'work started' section that will list evgenius in it.

**Comment by kuhnchris** [comment]
@owocki this is fine for the "first" worker applied, yes, but if you have dozens of applied workers who start/stop and then get approved then you kind of lose track who got approved when and where. Hence the "enhancement".

@usmanmuhd sure, if you find your way around, give it a try!

**Comment by pbteja1998** [comment]
Can I work on this issue ?

**Comment by kuhnchris** [comment]
No idea, @usmanmuhd is this still open?

**Comment by usmanmuhd** [comment]
Yeah sure, @pbteja1998 please take this up. I actually needed this for #2404 .

**Comment by pbteja1998** [comment]
I am trying to setup this repo locally. Everthing is fine except that I was unable to create funded issue. I am using Rinkeby test network. It has 18+ ether in it. 
When I am trying to set the gas, it is showing `unknown min confirmation`.
Even if we ignore that time, when I clicked on fund issue, it is loading forever. 
Can someone tell me what am I missing here? ( @usmanmuhd )

![screenshot from 2019-01-06 17-05-04](https://user-images.githubusercontent.com/17903466/50735490-fa816100-11d5-11e9-8d7b-4180ef480678.png)

**Comment by kuhnchris** [comment]
please check the gas price DIRECTLY in metamask, for some reason my gas was reset to 1 GWEI, which was way too low. The unknown confirmation time is due to the missing gas cronjob that's running to determine the time (normal). 
Can you check the logs (docker-compose logs --tail=100 web) ?

Thanks!

**Comment by pbteja1998** [comment]
How to start that cronjob?

**Comment by usmanmuhd** [comment]
I don't think you need to start the cronjob. You can just increase the gas from within metamask payment.

**Comment by pbteja1998** [comment]
The thing is it is not asking for payment in metamask. when I click on Fund Issue it is just loading. No prompt for payment in metamask !

**Comment by usmanmuhd** [comment]
Have you connected Gitcoin to metamask?

**Comment by pbteja1998** [comment]
yes

**Comment by pbteja1998** [comment]
I will try to rebuild again. Will see if it works.

**Comment by pbteja1998** [comment]
Is there anything else that I can do?

**Comment by pbteja1998** [comment]
- Cloned the repo
- `cp app/app/local.env app/app/.env`
    - `BASE_URL=http://localhost:8000/`
    - `GITHUB_CLIENT_ID=xxxx`
    - `GITHUB_CLIENT_SECRET=xxxx`
    - `GITHUB_APP_NAME=xxxx`
- `sudo docker-compose up --build`

These are the steps that I followed for rebuilding. Still no luck !

**Comment by usmanmuhd** [comment]
DM on slack, we can try figuring out.

**Comment by kuhnchris** [comment]
How about the environment?
Linux? Mac? Windows?
What Browser?
Old Metamask? Incognito Mode? 
Some more infos then we can help, else pm me on Slack/Discord

**Comment by octavioamu** [comment]
Just a head up with this tasks I was discussing with @usmanmuhd and there are 2 ways at least to solve this issue, one is front end just using the data inside json metadata with `worker_handle`  but he bring me the idea of change the model and I believe is the right way to go, because we actually have the other actions related to the worker not the owner, example 
this is from activity related to this bounty https://gitcoin.co/issue/MyBitFoundation/MyBit.website/29/1953

![image](https://user-images.githubusercontent.com/1358093/50875290-e17fd800-13ae-11e9-919a-073c945d3859.png)
As we see all the actions, removed, applied, stopped work are related to the worker (that is right)  so I believe keeping the model with the *owner name*  Approved doesn't make sense in the bounty or in the gitcoin.co/activity 
So I believe we should change the field from the model to be filled with the worker and not the owner and that will be reflected in both places we need it. 
@thelostone-mc any idea if this could break something in some place?
