### ISSUE TITLE
Kudos Profile - Add Wallet Flyout Dissapears When trying to Add Wallet

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2842]
**Describe the bug**
Kudos Profile - Add Wallet Flyout Dissapears When trying to Add Wallet

**To Reproduce**
Go to Kudos Profile, try to add a wallet.

**Expected behavior**

- Flyout stays open and allows me to add a wallet
- It also defaults my current wallet address in there and doesn't allow me to input anything in the field
- The Add wallet button is also floating - we could move it up under the wallet address.

cc @octavioamu

**Comment by kuhnchris** [comment]
Where to go to Kudos Profile? Cannot see it in Kudos and in Profile. :-(

**Comment by octavioamu** [comment]
The idea is you can't write the address, is taken from metamask. This is to avoid some issues.

I think we can see a better place to put the button, in my profile doesn't fit well behind the picture because the description. 

The problem here I think is is not taking the address form metamask if metamask privacy is enabled. 
![image](https://user-images.githubusercontent.com/1358093/48555739-34ff0980-e8c9-11e8-91e1-c17628f4b04c.png)
