### ISSUE TITLE
Build - Sync with Blockchain button on the Issue Details page

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2885]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want a way to manually sync with the blockchain so I can get the latest bounty activities on the Issue Details page

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Sometimes transactions are submitted but Gitcoin doesn't properly sync with the blockchain, causing the latest bounty activities to not show up.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
There is no 'Sync with Blockchain' button.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
There should be a 'Sync' button at the top of Issue Details, next to the rest of the buttons (see design below)
![48566510-ef2c5a80-e935-11e8-9cd8-4fd48d98bdda](https://user-images.githubusercontent.com/19514207/48566509-ee93c400-e935-11e8-8ce1-194fc7934d17.png)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] A 'Sync' button is displayed at the top of Issue Details.
- [ ] Clicking on the 'Sync' button should sync Gitcoin with the blockchain and update the Issue Details page with the latest bounty activities (especially the All Activity section)
- [ ] 'Synced with blockchain X minutes ago' should be displayed at the top of Issue Details, showing when the last time Gitcoin was synced with the blockchain.
- [ ] It should be obvious when syncing is in progress:
• hide the button
• change the 'Synced with blockchain X minutes ago' text to 'Syncing...'  with a simple animated loading spinner
 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Related issues: #2388 #2403 
Same button on the Issue Explorer: #2884

**Comment by thelostone-mc** [comment]
concern with allowing user to force sync : [refer](https://github.com/gitcoinco/web/issues/2884#issuecomment-440009017)

**Comment by frankchen07** [comment]
Same concerns exist on https://github.com/gitcoinco/web/issues/2884. 

However, I believe this is not syncing with the blockchain, but with Github, since if the user is already on the issue details page, the activity is updated from Github

I can check on my end that that is the correct assumption / correct setup.

**Comment by octavioamu** [comment]
I believe the sync blockchain and sync github issue details should be separated too but also I believe that any of that 2 actions shouldn't be hunters actions maybe the funder have a button inside edit to sync the issue data here:
![image](https://user-images.githubusercontent.com/1358093/48916561-f4276780-ee69-11e8-906c-15dbce7376c5.png)

But if every user have access to that button that will became a flow process, get into the issue > press sync > go read. Because is not a real need but if is present in the UI becomes a question "so the issue is already updated?" In any case I will end as always going to the github issue to read to be sure.

**Comment by owocki** [comment]
dev note: you'll want to call the backend route `/sync/web3`with the `url` GET param passed in

**Comment by PixelantDesign** [comment]
Another reason why this is needed.
<img width="595" alt="screen shot 2018-11-27 at 4 10 47 pm" src="https://user-images.githubusercontent.com/238235/49111803-24eb1080-f25f-11e8-94e2-f5ecb92b8030.png">

**Comment by PixelantDesign** [comment]
What are the tradeoffs between 2 separate buttons vs. single button performance wise? @octavioamu @thelostone-mc

**Comment by kuhnchris** [comment]
Well it depends on what you want to do. Gitcoin<->Github sync (internally) is pretty much querying the API of Github (and run into a maximum call limit), Gitcoin<->gETH sync is a pretty heavy task since you need to grass the blockchain for changes in that bounty. (StandardBounty Contract for example)

Gitcoin<->Github: Easy on the system, but only syncs with descriptions and other "github" stuff (tags)
Gitcoin<->gETH: Hard on system, syncs bounty status

**Comment by octavioamu** [comment]
So the last call we said the button will be sync in web3 + sync the description. I think also if in the answer we don't have it will be nice to have "Last use date" so if < than 2 hours or something the button is disabled or something like that.

**Comment by PixelantDesign** [comment]
Thanks @kuhnchris!
