### ISSUE TITLE
As a user, I want a gitcoin Tax Guide, so I know my tax liability associated with crypto for diffrent parts of the world.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2953]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want a gitcoin Tax Guide, so I know my tax liability associated with crypto for diffrent parts of the world.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

To ease the burden of understanding legal compliance for bounties in various parts of the world.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No Tax Guide

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Tax guide that roughly tells you what you'd owe to various authoirities, and how gitcoin can help support, by part of the wordl.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
call me crazy, but i thikn that taxes are enough of a pain in the butt.. we might be able to charge for this @vs77bb @PixelantDesign

**Comment by kuhnchris** [comment]
Uh, tbh Gitcoin is a peer-to-peer service provider, if anyone needs to consult tax rules for his spendings he should contact an actual lawyer in his country for information. Imagine we need to provide rulesets for german bounty providers, accepting polish or russian workers and finally paying out into 3 different countries. I can hear every finance institution spinning in it's own grave already.

But wouldn't the general burden break down into: Bounty Issuer X pays Z to Contract Y, hence X has to pay taxes due to Y being a 3rd party provider without an identification/tax number, hence X has to pass through his taxes he would have to pay while commiting the bounty contract? 

Maybe that's even something that needs to be solved on a higher level, áka StandardBounties. What do they do regarding this?
