### ISSUE TITLE
Issue Explorer: Move Expiry Date to Flyout

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2962]
### Current Behavior

Issue Explorer looks a little busy with all the info below. It would be great to make it less busy and move less important info to the flyout
<img width="1337" alt="screenshot 2018-11-28 01 22 07" src="https://user-images.githubusercontent.com/19514207/49099288-0c551780-f2ac-11e8-83a7-1abced933410.png">

### Expected Behavior
1. Remove 'Expires in X days'
<img width="1325" alt="screenshot 2018-11-28 01 23 43" src="https://user-images.githubusercontent.com/19514207/49099378-432b2d80-f2ac-11e8-87f4-f62961947c29.png">

2. Move expiry date to flyout, with a clock icon
![flyoutexpiry](https://user-images.githubusercontent.com/19514207/49099407-4faf8600-f2ac-11e8-8151-2f4713c87cab.png)

Sketch file:
https://drive.google.com/open?id=1ssPVGV4_WVVrfPsEaR7mhm4lzYcc631d

**Comment by Anish-Agnihotri** [comment]
Just pushed out a fix for this in the PR above. 

Here is a screenshot of it in action: 
![fixed](https://user-images.githubusercontent.com/4398624/49122323-f5013480-f281-11e8-9bf1-e59f25bba5cd.JPG)

I've used a temporary .svg file for the clock for the time being, since I was unable to export the one you had supplied in the .sketch file. If you provide me that, I'd be glad to update the PR.

Thanks,

Anish

**Comment by willsputra** [comment]
@Anish-Agnihotri Looking good! Here's the clock .svg file :)
https://drive.google.com/open?id=1MXVttTiigtR7l4OEEBmmi7FkeOhPC7o-

**Comment by Anish-Agnihotri** [comment]
Thanks @willsputra!

Just pushed out the revised and ready-to-merge PR (with that clock .svg file, and a small bug fix to remove bold font).

**Comment by PixelantDesign** [comment]
Awesome! Thank @willsputra @Anish-Agnihotri !

**Comment by willsputra** [comment]
Thank you @Anish-Agnihotri! 🙂
