### ISSUE TITLE
as a user, i want to show off my kudos in my avatar, so i can show off my skillz at a glance

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3032]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to show off my kudos in my avatar

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
kudos are a great way to show off what i've done / can do 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
can't view kudos on avatar

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
can add an avatar item that allows me to show case all my kudos

![230123-675x450-boy-scout-patches-and-sewing-needle](https://user-images.githubusercontent.com/513929/49311741-391d5080-f49f-11e8-9bbf-6d133a4aff59.jpg)

![screen shot 2017-04-08 at 1 11 03 pm](https://user-images.githubusercontent.com/513929/49311789-581be280-f49f-11e8-8986-eafec426bd8f.png)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
just looking for photoshops / inspiration of what this could look like.  not looking for coding of it yet ( want to agree on a direction before we code it up)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@PixelantDesign @kuhnchris @Anish-Agnihotri @nasehim7 any feedback on this?

its not a top priority for the core team.. just fleshing out the idea for now

**Comment by kuhnchris** [comment]
we could have the possibility to add 1 or 2 kudos the user selects to show to appear beside his name. (for example when applying). Could be integrated into settings. You could also do something like a "show case" where user can pin the kudos they get and want to show off, for example if you want to show off a special kudos you pin it to you can have like 5 pinned kudos that will be shown on the top of your avatar page.

**Comment by nasehim7** [comment]
It's great to have kudos indeed. Integrating the kudos inside the artboard will place so many elements in a small area which I think will decrease the beauty of avatar as it will look more crowded.  I was thinking of aligning top 3, 5 or maybe more kudos surrounding the thumbnail of the avatar, similar to this:
<img width="594" alt="1" src="https://user-images.githubusercontent.com/18035782/49324775-ae019080-f55a-11e8-9499-a782c9d10f27.png">
<img width="776" alt="2" src="https://user-images.githubusercontent.com/18035782/49324776-b063ea80-f55a-11e8-861b-a68f870245bf.png">
<img width="758" alt="3" src="https://user-images.githubusercontent.com/18035782/49324778-b2c64480-f55a-11e8-9fb7-ed550ba64522.png">
Sorry for posting these images instead of creating my own as I am currently out but just to give you an idea of what I am talking about. It can be a more improvised version of this. 

Second thought would be, just place 3 or 5 kudos in a columnar fashion to the left of the Avatar thumbnail. The column needs to be well below the "OI" of the Gitcoin somewhere here:
<img width="24" alt="4" src="https://user-images.githubusercontent.com/18035782/49324848-5cf29c00-f55c-11e8-9d10-041bfe42e403.png">

Third thought would be to place some kudos just above the name, here:
<img width="152" alt="5" src="https://user-images.githubusercontent.com/18035782/49324854-785da700-f55c-11e8-9fc1-f1c77e3253fa.png">

Kindly let me know the updates. :D

**Comment by PixelantDesign** [comment]
I really like your suggestion @nasehim7. I appreciate that it doesn't overlap with the avatar. 

Think it would be cool if I clicked on a person's avatar an got a light box that shows all of the person's top Kudos either by rarity or if the user has marked them as _display on Gitcoin Circle_. Could be an interesting interactive element to a user's profile.
