### ISSUE TITLE
how do i view canceled / inactive grants? there seems to be no way

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3078]

**Comment by thelostone-mc** [comment]
As of now it can be viewed in Grant Profile!

cc @PixelantDesign / @willsputra to figure out where this would go in

**Comment by PixelantDesign** [comment]
Yes, It's under Profile > My Grants

- [ ] We do need an H1 that says **My Grants**
- [ ] Please add an Inactive Grants Tab

cc @thelostone-mc 

**NOTE**
For this release, I don't think it makes sense to rejigger the Gitcoin profile. Once we see how users are using the Grants profile vs Gitcoin Profile, we can figure out ways to combine.

**Comment by PixelantDesign** [comment]
see my comment above Aditya

**Comment by thelostone-mc** [comment]
@PixelantDesign hmm could you throw in design as I'm still not clear 
Adding My grants heading would mean that it would show up when I visit your grant profile which is incorrect

Adding an inactive tab -> We've got Funded Grants / Created Grants
Does this mean we club all inactive grants (funded & created) and throw them into the new tab ?

**Comment by willsputra** [comment]
@PixelantDesign @thelostone-mc since inactive grants could either be Inactive-Supported or Inactive-Created, what if we put it under Sort (mockup below)?

another thing to note: I'm not sure if we're using the term 'Inactive' or 'Canceled', but just make sure they're consistent.
<img width="924" alt="screenshot 2018-12-11 02 12 33" src="https://user-images.githubusercontent.com/19514207/49752120-61e8e580-fcea-11e8-9091-204582904995.png">

no comments yet for H1-My Grants. will check out how other people's grant profile look like first.

**Comment by PixelantDesign** [comment]
I like this approach @willsputra.

The only thing about cancelled is that a Grant could be a Cancelled Grant but started by someone else.

**Comment by thelostone-mc** [comment]
@willsputra yup you've got that right
