### ISSUE TITLE
grants - updates area could use some prettification

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3095]
<img width="1390" alt="screen shot 2018-12-05 at 3 08 23 pm" src="https://user-images.githubusercontent.com/513929/49547353-b251e480-f89f-11e8-9c78-b7ebf6aa09dc.png">

https://gitcoin.co/grants/2/new-soda-fountain

**Comment by willsputra** [comment]
![grants updates](https://user-images.githubusercontent.com/19514207/49736752-ec6b1e00-fcc5-11e8-9c03-5417a6ac139e.png)

@owocki @thelostone-mc cc @PixelantDesign some improvements:
1. Put some padding between 'Updates' header and the actual content
2. Switch date and title around. Since this is a chronological list of updates, date would be important hence we make it more obvious. Same goes for Milestones.
3. Divider between each updates.
4. For super long updates, maybe we could just display one paragraph? Clicking 'Read More >' would reveal the rest of the content.
5. Make sure the headers 'Updates', 'GitHub', 'Milestones', 'Project Description', 'Team Members' are consistent. I think currently 'Updates' and 'Milestones' are slightly bigger.
6. I kinda prefer the smaller tab style below. Currently it looks a little weird because all the headers are left-aligned, and only 'Updates' has some padding. This is less important though :)
![screenshot 2018-12-10 21 58 44](https://user-images.githubusercontent.com/19514207/49737063-c72adf80-fcc6-11e8-8007-d9a7f4e59e76.png)

**Comment by PixelantDesign** [comment]
Thanks for the visual @willsputra! I thinking making headers consistent will do the trick!

I also like the idea of switching the date around along with some of the other recommendations on Will's list - time permitting.

cc @thelostone-mc
