### ISSUE TITLE
grant fund bug -- you should prevent someone funding a grant on mainnet with a rinekby token

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3106]
grant fund bug -- you should prevent someone funding a grant on mainnet with a rinekby token

**Comment by owocki** [comment]
subscription 2 on mainnet had this problem

**Comment by thelostone-mc** [comment]
Do we just disable the page all together?

**Comment by owocki** [comment]
maybe just disable the submit button and show an `_alert()`?

**Comment by captnseagraves** [comment]
Hmmm, how is a rinkeby token being used for mainnet? Doesn't tokens.js only show tokens for the browsers current network?

**Comment by captnseagraves** [comment]
Ohhhh, so this grant https://gitcoin.co/grants/2/new-soda-fountain was deployed on Rinkeby and accepts a rinkeby token. The problem is not with the tokens, but is in not displaying the network of the deployed grant. So we either make the network visible so people know they are using a test grant and test tokens, or we disallow the use of test grants.  @owocki @thelostone-mc Thoughts?

**Comment by captnseagraves** [comment]
> maybe just disable the submit button and show an `_alert()`?

I see. It appears the transaction didn't go through, but an entry was still made in the db. I think we should have a sort method on `grants/index` to show by network. We should show not display the "fund this grant" button on `grants/details` if the user is on a different network, and we should do as KO suggests above for `grants/fund`

Perhaps we do KO's suggestion for hard launch and leave the rest for after? @owocki @thelostone-mc

**Comment by owocki** [comment]
works for me
