### ISSUE TITLE
Avatar purchase can be tricked to use any price

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#3146]
**Describe the bug**
You can change the "data-cost" tag to any number of costs

**To Reproduce**
Go to dev-tools, change "data-cost" to low number, send.

**Expected behavior**
Backend (and Frontend) check to see if the price is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/49696236-9acc7180-fba7-11e8-8db4-0f1aeb0ab9f0.png)

**Comment by PixelantDesign** [comment]
Thanks for the report @kuhnchris! Any recommendations on how to resolve this?

**Comment by owocki** [comment]
thanks for the bug report.  im aware of this from when i was BUIDLing it, but it was just a lean test.   if someone figures out how to hack it during this lean test, then i understand.. im just happy people are playing with the avatar builder!

i have a vision for how we'll be evolving digital goods purchases which ill share at some point in the future.

**Comment by kuhnchris** [comment]
OK, shall I close this issue then with "will not fix" and "bug as intended"?

**Comment by owocki** [comment]
lets keep it open.  i intend to fix it when i PR up my digital goods purchases evolution stuff.

**Comment by octavioamu** [comment]
This one is really with anything from the front end, because we have metamask in the middle and metamask doesn't connect to our server to know what the front end is sending is right or not. So the validation occurs in the backend, I think you can do this with others things like kudos for example.
The thing is any front end code can be changed for that reason we validate forms in the front and end.
