### ISSUE TITLE
Cannot take new bounties because a number of issues

### ISSUE THREAD

**Issue by vikaskyadav** [gitcoinco/web#3157]
I can't start work on new issues.
The plausible reasons are:

- If a bounty which was `Work Started` by someone has been canceled by the funder, the issue will be still counted as open in the profile of person who 'started working on it'.

- If a bounty was `Work Started` by somone and that account didn't submit the work and work got accepted because of some other account, the issue will be still counted as open in the profile of person who didn't submit the work.

As a result of this, if such counts reaches 3, new bounties can't be grabbed by such accounts and these accounts are stuck forever with existing logic. 

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

If work is closed by any party, it shouldn't be counted as `open`.

**Comment by kuhnchris** [comment]
@frankchen07 would it make sense to add a new tab or some kind of page to show the user which bounties currently count towards the limit? Right now it's a bit of a fuzzy gray-zone (even to me).

**Comment by vikaskyadav** [comment]
I agree with @kuhnchris. Right now, this is very messy. Open bounties can be placed in a different tab. Actually, fine level segregation can be done by creating different tabs.

**Comment by PixelantDesign** [comment]
Great idea @kuhnchris on the need to display which issues count towards the 3!

**Comment by PixelantDesign** [comment]
I created a ticket @kuhnchris https://github.com/gitcoinco/web/issues/3173

**Comment by willsputra** [comment]
@PixelantDesign what kinds of issues are currently counted?

- Work started
- Work applied, but not yet approved by the funder <== does this count?
- Work submitted, but not yet approved/paid out by the funder <== does this count?

**Comment by kuhnchris** [comment]
in THEORY: open and started, but I do not dare to say if all the status are always correct... + interest is a bad filter, isn't it? what if you apply twice? or get multiple tips? aren't those Interest objects as well? 

dashboard/views.py
```
    num_issues = profile.max_num_issues_start_work
    active_bounties = Bounty.objects.current().filter(idx_status__in=['open', 'started'])
    num_active = Interest.objects.filter(profile_id=profile_id, bounty__in=active_bounties).count()
    is_working_on_too_much_stuff = num_active >= num_issues
```

**Comment by willsputra** [comment]
Yeah I personally think applying for work shouldn't count...

Also addressing @vikaskyadav's cases:
> If a bounty which was Work Started by someone has been canceled by the funder, the issue will be still counted as open in the profile of person who 'started working on it'.

In this case, the status should be 'Closed' and shouldn't count.

> If a bounty was Work Started by somone and that account didn't submit the work and work got accepted because of some other account, the issue will be still counted as open in the profile of person who didn't submit the work.

In this case, the status should be 'Work Done' and shouldn't count.

... right?

**Comment by willsputra** [comment]
(well except for some cases where the funders forgot to press 'Closed' or 'Work Done')

**Comment by kuhnchris** [comment]
Well the question is: is the status always properly set? There currently is no way aside from checking in the backend if a status is in a certain status, as far as I know. Since all of those things are activities (please correct me if I'm wrong) then it will be counted as long as the bounty is still open (because Interest.objects.filter(profile_id=xxx,...) should at least return the first request where the Interest was registered)

**Comment by willsputra** [comment]
I think whether the bounty status is correct or not depends on whose point of view.

For example:
I'm a contributor and I submitted work on a **contest** bounty X.
• Bounty X status remains Open since from the funder's pov, they're still accepting submissions (since it's a contest bounty).
• However, from my pov, I've submitted work on Bounty X and I'm no longer interested in it.

**Comment by willsputra** [comment]
What if, regardless of the bounty status, I'm deemed as not interested if:
• I was rejected for a bounty, or
• I stopped work on a bounty, or
• I submitted work on a bounty?

(which means deleting the interest object for my profile_id if any of the cases above happens? not 100% sure how this works so correct me if I'm wrong too 😂)

**Comment by kuhnchris** [comment]
Same here, not entirely sure yet how this works - would have to test it out. 
But I think the main catch, for me, is that we actually should check:
- User has interest? -> +1 In-Work count
- User got accepted? If type = required_approval: -1 +1 (= stays +1), else +1 In-Work Count
- User submitted PR? -1 In-Work count
- PR got rejected? => What does the system do? Are you still assigned? if yes -> +1 In-Work (could exploit to go over max work then), if no -> user needs to re-apply for interest/work? -> see above
- PR go accepted, Work done -> - (nothing, as the work count was already reduced during PR submission)
- Bounty was cancelled and in Progress by us? -> -1 In-Work 
- Bounty Owner selected someone else fro interest pool -> -1 in-Work as our request got rejected

Any cases I'm missing?

**Comment by frankchen07** [comment]
> User has interest

Not sure what having interest means here - just commenting on a Github ticket or starting work on a permissionless bounty? I could be working on multiple tickets and commenting and helping out on others, in order to maximize my work, but "helping" doesn't necessarily entail taking up an entire work slot.

> User got accepted? If type = required_approval: -1 +1 (= stays +1), else +1 In-Work Count

Not sure what you mean here. If the bounty requires approval, it should still be +1, if it doesn't require approval 

> Bounty Owner selected someone else fro interest pool -> -1 in-Work as our request got rejected

This wouldn't happen unless we assigned a +1 for a simple request, which I don't think should be the case. Either for a permissioned bounty they get approved, or they start work on a permissionless bounty - or maybe I'm misunderstanding you?

Cases I see, pretty much what @kuhnchris has outlined (thanks), clarified - with 1-2 needing extra discussion.

1. User has interest by comment (+0)
2. User starts work on permissionless bounty (+1)
3. User approved on permissioned bounty (+1)
4. User rejected on permissioned bounty (+0) - no +1 was granted before, since they were just waiting.
5. User submits PR (-1) or user submits PR and is accepted by funder (-1) - this could actually serve as a rate-limiting function for how many backlogged community PRs there are.
6. Bounty cancelled and/or moved to internal team (-1)
7. Bounty expired -> bounty cancelled (-1) dependent on discussion with funder. 
8. Removed for bounty abandonment by Gitcoin Bot (-1)
9. Any admin overrides (+1, -1) 

I'll add "any missing edge cases?" to capture any other discussion points.

**Comment by kuhnchris** [comment]
> > User has interest
> 
> Not sure what having interest means here - just commenting on a Github ticket or starting work on a permissionless bounty? I could be working on multiple tickets and commenting and helping out on others, in order to maximize my work, but "helping" doesn't necessarily entail taking up an entire work slot.

Interest as in: It's a approval-required bounty and he applied for work (that's backend-side called a Interest Object, sorry for the confusion)

> > User got accepted? If type = required_approval: -1 +1 (= stays +1), else +1 In-Work Count
> 
> Not sure what you mean here. If the bounty requires approval, it should still be +1, if it doesn't require approval

User got accepted => It's a approval-required bounty and the user was accepted for work from the pool of applied/interested workers.

> 
> > Bounty Owner selected someone else fro interest pool -> -1 in-Work as our request got rejected
> 
> This wouldn't happen unless we assigned a +1 for a simple request, which I don't think should be the case. Either for a permissioned bounty they get approved, or they start work on a permissionless bounty - or maybe I'm misunderstanding you?

I think that's already happening, hence I listed it above. If my assumption is incorrect, then you are right, nothing should happen.

> I'll add "any missing edge cases?" to capture any other discussion points.
Regarding 6. - "moved to internal team" is not really a status on the bounty - let's restrict that to real status.
Regarding 9. - "Admin override" - no such thing currently. the only override is to "increase" the number of possible bounties for the user right now.

Thanks for taking a look!
Chris

**Comment by willsputra** [comment]
@frankchen07 @kuhnchris Looks like you guys covered most of the cases! 

>1. User has interest by comment (+0)
>2. User starts work on permissionless bounty (+1)
>3. User approved on permissioned bounty (+1)
>4. User rejected on permissioned bounty (+0) - no +1 was granted before, since they were just waiting.
>5. User submits PR (-1) or user submits PR and is accepted by funder (-1) - this could actually serve as a rate-limiting function for how many backlogged community PRs there are.
>6. Bounty cancelled and/or moved to internal team (-1)
>7. Bounty expired -> bounty cancelled (-1) dependent on discussion with funder.
>8. Removed for bounty abandonment by Gitcoin Bot (-1)
>9. Any admin overrides (+1, -1)

^ I agree with all this. Just one edge case I could think of:

10. If someone applies for 4 permissioned bounties and gets approved for all of them, he'll exceed the max. (I personally think this is alright.)

**Comment by willsputra** [comment]
> User starts work on permissionless bounty (+1)
> User approved on permissioned bounty (+1)
> Any admin overrides (+1,

On another note, in all these +1 cases, the status would be 'Work Started' from the contributor's point of view, right?

Which means regarding the design (#3173), if they want to know which issues are counted, they can simply see how many 'Work Started' bounties they have?

**Comment by kuhnchris** [comment]
Sadly not. Work Started doesn't correspond with the real "work started" amount.

**Comment by willsputra** [comment]
@kuhnchris yeah I know... (which sometimes  I find confusing too, looking to start a discussion on #3253)

I'm personally leaning towards fixing the profile (so it corresponds with real "work started" amount) and have issue count = work started.

but if we're keeping the current profile implementation, having the new tab like you suggested on #3173 could work too!

**Comment by owocki** [comment]
@vikaskyadav meantime i can increase your limit on the # of bounties in flight if you want
