### ISSUE TITLE
As a Gitcoin Grants User, I'd like the ability to share a grant via email or social media.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3177]
### User Story

As a user who just created a Grant, I'd like the ability to share a grant via email or social media to get some funding.

As someone who just funded a Grant, I'd like the ability to share a grant via email or social media to encourage others to fund the project.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
There is no way to share a grant right now besides copy an url and paste to twitter or email.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
None

### Expected Behavior
A sharable Grants experience.

### Definition of Done

- [ ] Discuss with product & engineering on which is the lowest lift option and best experience.
Build a new share button or use current bounties share experience.
- [ ] Design a full of experience of how a Grant might be shared.
- [ ] Test with users.
- [ ] Iterate on a design and post the final design file.

### Additional Information
Review with Grants core team members.

cc: @mbeacom @thelostone-mc @SaptakS on technical guidance.

**Comment by kuhnchris** [comment]
Twitter:
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview.html
Facebook:
https://developers.facebook.com/docs/plugins/share-button/

Which channels do we want?
I can add those buttons in really quickly. It depends on what message we want to default there tho.

**Comment by thelostone-mc** [comment]
@willsputra any ideas on the message and where we add them ?
@kuhnchris if you are taking this up -> the shareable link (ensure the default image is granted image )

**Comment by kuhnchris** [comment]
Sorry, I didn't get that, "the shareable link" as in? 
I assume the shareable link will be e.x. "https://gitcoin.co/grants/1/sitemap-grant-to-test-sitemapxml" and the graphMQ/tags/... should provide either a short description of that grant + the grant picture if available. If not available it should probably display the gitcoin image or one of the gitcoin bots. 
Anything special requested regarding the text? Since we can put anything there, from just the description to the fund limit to whatever.

Thanks
Chris

**Comment by PixelantDesign** [comment]
yes after crowd funding
