### ISSUE TITLE
capture 'freelancer' keyword terms

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3207]
per @mbeharry if we could capture 'freelancer' keyword terms, it would BE HUGE for us

**Comment by kuhnchris** [comment]
Did you do a page-wide SEO check already? We could definitly throw the "freelancer" keyword into some page template so it shows up on pretty much every page (for example in the footer), depends on if you already did some other SEO optimizations so we know if we are not punish-rated.

**Comment by aashutoshrathi** [comment]
What're plans for this @owocki?

**Comment by owocki** [comment]
i think the plan was to create a bunch of landing pages around various terms that freelancers would serach.  its not defined much beyond that

**Comment by owocki** [comment]
@mbeharry might have more details tho

**Comment by marc-at-consensys** [comment]
@kuhnchris Yes! We did create some landing pages to target the top relevant freelancer terms like "freelance python jobs / bounties" but incorporating the term "freelancer" throughout the copy where relevant will help.  Especially on templated pages like the bounties.  On top of that, the messaging on the core pages can be revisited to include this and other terms that are relevant now.  Here are examples of the landing pages: 
[https://gitcoin.co/contributor/python](https://gitcoin.co/contributor/python)
[https://gitcoin.co/contributor/javascript](https://gitcoin.co/contributor/javascript)

**Comment by aashutoshrathi** [comment]
@marc-at-consensys @owocki So, should I proceed with all the templates which are missing relevant meta tags?

**Comment by owocki** [comment]
@aashutoshrathi i guess that depends on @marc-at-consensys - do we feel we have t his fully scoped out enough to actually move forward?  maybe if we cfan get a list of the keywords; places they need changed that would be an MVP for @aashutoshrathi to work on

**Comment by marc-at-consensys** [comment]
No, we should paste the template for the "[Open Bounties pages](https://gitcoin.co/issue/knocte/NLightning/1/3448)" into a Word doc so we can recommend keywords and variables (like bounty type, cost) to populate certain parts of the page.  

Even if its just a paragraph at the bottom of the page it will help Google and users.  Another example, instead of the sub-title "Description", we can replace with "Description of Open Python Code Bounty" where the word Python is replaced by the variable "Bounty Type."
