### ISSUE TITLE
data ask - track our unit economics (LTV & CPA)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3224]
data ask - track our unit economics (LTV & CPA) on metabase

LTV == lifetime value in revenue
LTV == lifetime value in platform value

CPA = cost per acquisition of a lead (dean currently says its $6),

**Comment by frankchen07** [comment]
Linking a data-ops ticket: https://github.com/gitcoinco/data-ops/issues/20

We do have LTVs up for bounties platform value. Revenue is mock calculated by a percentage cut, and I think we'll have to add Kudos LTV value either in the full calculation or separately.

**Comment by frankchen07** [comment]
Currently, our LTV revenue metrics are calculated using several standard formulas that I've researched, specifically for Gitcoin Bounties. I'll summarize the results, and then provide the definitions below, and the caveats that I'm aware of. LTV platform value can be found on various product vertical dashboards.

Bounties OKR: https://metabase.gitcoin.co/dashboard/13
Kudos: https://metabase.gitcoin.co/dashboard/16

**Quick overview:** 

1. Average customer lifespan ~= 40 days

2. LTV ~= $94, assuming a 10% cut of completed bounty value over those 40 days

3. Multiply that LTV value by an average of 60 active users per month, which gives us around $6000 in revenue, with the assumption that we get a refresh of our users every 40 days.

Since aggregates are not as useful and serve mostly as a high-level overview, I have filters and values broken by country with the default set to the United States (second row): https://metabase.gitcoin.co/dashboard/12

The LTV by country, month over month, does not utilize average customer lifespan, and is a better representation of LTV economics by country.

**Points of interest:** 

1. Despite the average customer lifespan not being a perfect truthy model, an imperfect truth still has some truth. We want to have an eye on how we can get bounty hunters to come back and complete more bounties, because this ultimately drives revenue, if we pursue a percentage cut model. 

2. MoM LTV is highly dependent on country, and the United States is low (single digits). My thinking is that we have more bounty hunters from the United States, so the retention rate can be lower than countries with less users.

**Caveats:** 

1. LTVs drop to 0 as it approaches today, because we're using retention rate (so calculating retention in present time is going to be 0 because we don't know if someone has returned yet), so don't be alarmed.

2. The formulas for LTV-1 and LTV-2 are not quite well catered to Gitcoin, since the average customer lifespan comes out to be highly short, and obviously, we're not going to start with a new user base every 40 days. Our model might be more suited to the way Ebay calculates customer lifespan, using RFM (recency, frequency, and monetary value), which is my next investigation into our unit economics.

3. Most LTV calculations rely on a subscription model, which we are not (yet). 

4. This also doesn't capture the value that developers create, it's just the estimate off of bounties. 

**Next steps:** 

1. For Gitcoin Kudos, a similar procedure can be followed, but obviously, the numbers will be different given the retention/churn metrics for that product vertical.

2. Look into RFM calculations.

3. A good question to ask is how we can validate this LTV over time. We can perhaps take a representative sample of the active bounty hunters we have and assess the value they're bringing to the platform?

**Appendix:** 

* LTV-1 is calculated as = average customer value per month * average customer lifespan * gross margin % (the % cut that Gitcoin may take for each completed bounty)

* LTV-2 is calculated as = (LTV-1 * retention rate per month) / (1 + discount rate - retention rate per month)

* LTV-MoM is calculated as = average customer value per month * gross margin % (the % cut that Gitcoin may take for each completed bounty) * retention rate curve (probability that a new customer is active in month X of their lifetime) / (1 + discount rate - retention rate curve)

* average customer value per month = bounties they have completely completed

* average customer lifespan = average months a customer plans to stick around, calculated by the inverse of churn rate

* retention rate is calculated by = bounty hunters who have logged in, started work, submitted work, or done work, and complete work 30 days later (baseline)

* discount rate is estimated at 10%

* gross margin % (Gitcoin potential cut) is set at 10%

**Comment by owocki** [comment]
> LTV ~= $94, assuming a 10% cut of completed bounty value over those 40 days

this is for bounty hunters, funders, or both?  is the LTV of a funder the same as the LTV of a bounty hunter?

one thing i'd be interested in knowing is the LTV of ALL users, not just active users.. im assuming it's going to be about 1/100th to 1/1000th of the active user number.

the reason it's important to know this number is that thats how we frame the CPA numbers.  it costs us $6 to acquire an email from a facebook campaign

**Comment by owocki** [comment]
can we seperate out funder LTV / CPA and coder LTV / CPA?  those are probably two separate options

**Comment by frankchen07** [comment]
Updating our conversations in Slack here so we can easily track it. I made some updates on the LTV dashboard: https://metabase.gitcoin.co/dashboard/12

1. I've simplified the LTV definition to: 

```
(value per user per month * retention rate * gross margin) / (1 + discount rate - retention rate)
```

Value per user per month was calculated using a sum of bounty value and MAUs. Retention rate is rolling, calculated by month. 

In my definition of LTV, `gross margin` is the potential 10% cut of revenue that we could take, and is built in. You could interpret the final value as "if we charged a 10% cut off an opened/completed bounty, on average we'd earn X off a funder/non-funder."

2. from Slack: `active user` was denoted by contributors who completed at least 1 bounty, which I agree was a bit exclusive. Alas, point 3.

3. All users are now considered. They can be a funder or a non-funder (user & contributor).

4. LTVs have been split out by funders and non-funders (contributors & users). It makes sense that the average value brought to the platform for funders vs. non-funders is similar (if not the same), since what is "opened" will eventually "get closed". The LTV will differ because the MAUs and retention rate for the two groups is different - notably, the funder LTV is higher because if you're a funder, you've at least opened 1 bounty to the platform, whereas for non-funders, the value can be spread across a potentially infinite number of users.

Something to think about when we use LTV metrics, for funders and non-funders: For those completing bounties, a percentage cut of revenue makes sense, whereas for funders, the LTV calculation may alternatively come in handy as some kind of subscription price point for them if they are super-funders and post lots of bounties.

**Comment by owocki** [comment]
> (value per user per month * retention rate * gross margin) / (1 + discount rate - retention rate)

mind sharing each of these values in your formula?  how many MAUs are you counting?

it'd be nice on this dashboard ( https://metabase.gitcoin.co/dashboard/12 ) to be able to see at least the MAU size
