### ISSUE TITLE
DESIGN - as a user, i want a pricing sheet, so i can see how to take full advantage of gitcoin

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3289]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want a pricing sheet, so i can see how to take full advantage of gitcoin
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
explains all our revenue options in one place

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)
no price sheet

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
remove existing price sheet from gitcoin.co

add this one, which will be put at gitcoin.co/pricing:

![group 3](https://user-images.githubusercontent.com/513929/50389018-5aa9da80-06e1-11e9-8e6f-fa62d04888e0.png)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

* Page at `/pricing`
* Page Works Responsive
* Put a menu item that points at `/pricing` in the top right nav.
* If I select a plan, then I am taken to a gitcoin grant payment page to pay for that plan. (all info about my pricing will beg prefilled)
* If I select the plan, then all of the promised benefits will be there.

### Additional Info
http://bits.owocki.com/9e5bd92b1e54/Pricing.sketch

**Comment by owocki** [comment]
cc @vs77bb @PixelantDesign

**Comment by kuhnchris** [comment]
*raises hand* please provide the assets in a non-sketch format, thanks

**Comment by PixelantDesign** [comment]
Cool! I'll take up this one @willsputra

**Comment by owocki** [comment]
when this is ready for coding, will do.

thanks @PixelantDesign !

**Comment by owocki** [comment]
another thing we could add to premium featureset only
- funder dashboard
- notifications
- weekly roundups
- instant new issue notifications
- ENS subdomains
- browser extension

@vs77bb @PixelantDesign thoughts on this?  basically anything that's not a basic feature could / should be premium only

**Comment by kuhnchris** [comment]
One aspect to think about tho: especially things that are already in use (like ENS subdomains) are already used because of the fact that they are "free". you'd have to revoke all existing domains (or keep them but make them unchangable) or give those early adaptors a free pass, else you might run into problems in the long run (trust me, I had done this before, people are going to be confused and hysterical about seeing something they use getting 'pay to use'...)

**Comment by owocki** [comment]
@kuhnchris thanks.. good point; we'll have to figure out how we grandfather ppl in

**Comment by owocki** [comment]
One idea I shared with @vs77bb today was maybe making the third plan an 'enteprise' plan.  Heres what that looks like

![group 3](https://user-images.githubusercontent.com/513929/50490898-c3889f80-09cc-11e9-8cb1-c4d43cbe2f1e.png)

**Comment by PixelantDesign** [comment]
Here is an updated price sheet design. The content of it might be a good candidate for workshopping.

![pricing_am](https://user-images.githubusercontent.com/238235/50674652-481f8300-0fb6-11e9-865f-32bbedb87c3e.png)

**Comment by owocki** [comment]
some thoughts:

1. id love to see plan names that denote what will cause the user to be excited about. eg 'devflow' and 'devflow plus'; since people engage with us because they want canddiate flow.
2. i'd love to see a view where a plan is 'selected' and that is visually shown.  and the user can unsubscribe on this page.
3. i think we need a background color on one or more of the 3 columns.
4. i'd love to see this framed in terms of user flow.  what prompts them to get to this page, what is their UX before and after they select a plan?  why would they take our their credit card (er.. in this case.. sign the metamask tx), whats the big psycological driver to do this?

**Comment by PixelantDesign** [comment]
Making a note here that @ceresstation has market validation for these features:
KYC/AML (fund and pay out bounties with fiat), featured bounties, the job board, support

**Comment by PixelantDesign** [comment]
Updated here
<img width="1187" alt="screen shot 2019-01-28 at 1 32 24 pm" src="https://user-images.githubusercontent.com/238235/52059744-9fbef900-2538-11e9-9110-d968206a2476.png">

**Comment by owocki** [comment]
looks really good.  can we have a skitch file?

**Comment by PixelantDesign** [comment]
hey @frankchen07 @owocki @thelostone-mc here is and update and the general flow for opting into a pricing package.

![pricing flow 020119](https://user-images.githubusercontent.com/238235/52141787-db36f180-2624-11e9-93f5-e9a620e16035.png)

**Changes include:**

_Pricing Screen_
- updates to the pricing page design
- when user is on this page, nav is hidden so they aren't distracted to do other things.
- removed the stats below since that's something we'll need to qual survey to get some of that data. most of the feedback we received, funders weren't to concerned or focused on that section.
- added the monthly vs. yearly toggle for discussion..this something that was mentioned would be helpful and having a discount applied to yearly would be a motivator to go yearly.

_Payment Screen_
- cleaned up design
- only showing what has been selected here, if users want to change selection they'll need to go to the previous screen.

_Waiting State_
- The funder would need to wait until the payment/subscription has been processed. We would reuse our waiting state here. The only thing is depending how long it takes to complete, could be a friction point if they're wanting to get to the funding form right away. Open to ideas here.

_Fund issue Form_
- There should be some kind of congrats, subscription was successful, ready to fund message.

![gc home](https://user-images.githubusercontent.com/238235/52142273-403f1700-2626-11e9-89fe-d7b2e03d5e59.png)

![pricing sheet latest](https://user-images.githubusercontent.com/238235/52142278-446b3480-2626-11e9-997a-b784d7c40126.png)

![pricing payment page](https://user-images.githubusercontent.com/238235/52142298-48975200-2626-11e9-8126-fd7157e36a0a.png)

![waiting state](https://user-images.githubusercontent.com/238235/52142300-4af9ac00-2626-11e9-96a0-be4df8b65f53.png)

![fund issue](https://user-images.githubusercontent.com/238235/52142307-4fbe6000-2626-11e9-9d26-a37dd4df24fd.png)

[Gitcoin PRicing_02012019.zip](https://github.com/gitcoinco/web/files/2822865/Gitcoin.PRicing_02012019.zip)

**Comment by danlipert** [comment]
Looks great @PixelantDesign ! My only comment here is that the copy on the payment page is the copy from the grants page so that will need to be replaced.

**Comment by PixelantDesign** [comment]
yes! it was a screenshot @danlipert
