### ISSUE TITLE
Need a way to find bounties for specific repository

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#3350]
Some @cybercongress repos try to refer to open bounties for their repositories -  https://github.com/cybercongress/cyb/blob/master/README.md#gitcoin-tasks - but that's impossible without backed support which was not implemented in (closed) #232.

**Expected behavior**
The proposal is to extend `Organization name` in search form to accept `org/repo` hash or full repo or org URL.

**Screenshots**
![image](https://user-images.githubusercontent.com/8781107/50541854-7b7d9e80-0bbf-11e9-9609-fc790331eb91.png)

**Comment by kuhnchris** [comment]
Hmm, you could also go via your profile/org profile. It shows all bounties there.
But, yes, I agree, there should be a way to filter for repositories.

**Comment by abitrolly** [comment]
@kuhnchris no repo filter and no "open" filter on profile pages https://gitcoin.co/profile/cybercongress

**Comment by hatgit** [comment]
Could it be better to add the actual bounty url into the widget, where it can take up to a set maximum number of bounties urls to show at once in the preview (and the link would direct to the users profile rather than to the explorer?), that are either open or already closed? (i.e. if someone wanted to show not only the open ones but past ones, as a means of social-sharing/promo).

**Comment by kuhnchris** [comment]
Well, many things can be done, the django framework is very open in this respect. The only constraint we have is the database load/power such a query would result in. And naturally we need to keep this low. That may be something where @mbeacom may also have a say in, as if we'd implement some API call that destroys the performance of the app then we will prolly get shunned.
