### ISSUE TITLE
Grants: The gas price is different from what is set in UI

### ISSUE THREAD

**Issue by SaptakS** [gitcoinco/web#3357]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
Fom what I can see, the gas price is one decimal place lesser (or 10 times) the gas price that is set using the UI that we see in the metamask transaction. I did try and debug it in the gas settings UI, but seems the data going from UI is correct. @captnseagraves can you maybe see if there is something hardcoded that is causing this?

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
- Go to grants creation
- Set the price as let's say 5 gwei in gas settings UI
- Check the price in ETH shown in UI and the one autofilling in metamask. (The one in UI is the correct one)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Both the amounts in ETH should be same

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by kuhnchris** [comment]
Prices are pulled from the GasProfile database table values. Can you check those on prod, and, if those are weird aswell, check https://ethgasstation.info/json/predictTable.json ?
It'd be easy to implement "*10" if it affects everything, since the method is central in ```gas/utils.py```, just wanting to make sure the source is correct and maybe something special in grants, and not everywhere else.
