### ISSUE TITLE
in grants flow, it should be clear how to get WETH with ETH

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3389]
per user feedback at https://docs.google.com/document/d/1acaxboTHVqo4rM7BJ5e2laZpxe45qJs3oCNnp9tAlEo/edit#

in grants flow, it should be clear how to get WETH with ETH

**Comment by Anish-Agnihotri** [comment]
Would it be a good idea to have a tool-tip popup above the token selection drop-down that says something like `Why cant I use Ether?` and then on hover it reveals something like:

`Ether doesn't comply with ERC-20 standards, which means in order to keep your funds secure, you can't use it to fund a grant. You can though, use WETH (or Wrapped Ether):` Followed by maybe a short blurb on how to get WETH?

**Comment by owocki** [comment]
thatd certainly be a nice workaround in leiu of actually transfer the useres ETH into WETH

**Comment by Anish-Agnihotri** [comment]
For sure. For the latter we'd have to actually call the contract and wrap the ETH ourselves if the user chooses to deposit ETH.

Till that gets implemented or figured out, I'd be more than happy to implement the tool-tip in a few minutes. Lmk.
