### ISSUE TITLE
As a user who wants a coder, I want to use a data science tool called "Cerebro" to find all the coders, so I can source the best ones.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3439]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user who wants a coder, I want to use a data science tool called "Cerebro" to find all the coders, so I can source the best ones

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

In X men, Professor Xavier has access to a tool called 'Cerebro', that he can use to *find all the mutants*. 

![tumblr_ms4giub08v1qbwrnuo6_250](https://user-images.githubusercontent.com/513929/50800588-0e909580-129e-11e9-8de7-bc8092e9622e.gif)

Not dissimilarly, Gitcoin is a tool for finding those with special talents.  

I would like to build a data science tool that helps me filter our dataset by skillset, location, repo, and many other criteria.  

This tool will be a competitive advantage for us because it will allow us to explore our dataset in a more exhaustive way than has been previously done.

This tool will be our 'cerebro'.  It will help us find all the coders, and to visualize how they relate to each other.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No exhaustive datascience tool.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Here is what I envision for the *frontend* of the tool:

The first pane will be a query tool.  It will allow me to filter by 
* skillset
* location (city, state, country)
* repo
* type (bounty, tip, kudos, grant)
* amount
* token
* github_url
* keywords
* is_hirable
* has_resume

The second pane will say "Found X User Relationships".   It will show a success rate, a median hourly rate, and median turnaround tie.

Then below it, it will have a list of each of the user relationships.  For each user relationship, it will say:
1. Type: Grant, Bounty, Tip, Kudos
1. From User Details: Avatar, Name, Profile Link, Number of bounties completed, etc.
1. To User Details: Avatar, Name, Profile Link, Number of bounties completed, etc.
1. Details of the transfer: Amount, Context, Github URL, etc.
1. "See More" Link , which will link out to the Kudos/Bounty/Tip/etc.

The last pane will be the 3d model of the relationships within these coders.  From [this graph visualization](http://experiments.owocki.com/Graph-Visualization/all/), it looks like 

![screen recording 2019-01-07 at 05 38 am](https://user-images.githubusercontent.com/513929/50800669-6b8c4b80-129e-11e9-94fa-2e92cb7d5e85.gif)

Put all together, itll look like this: 

<img width="740" alt="screen shot 2019-01-07 at 6 12 53 pm" src="https://user-images.githubusercontent.com/513929/50803683-edcd3d80-12a7-11e9-92b4-0ab1f2c6602c.png">

1. The first pane will be the 'control panel'.
2. The second pane will allow us to view the dataset as qualitative list.
2. The second pane will allow us to view the dataset as a quantative [3d mesh network](http://experiments.owocki.com/Graph-Visualization/all/).

Here is what I envision for the *backend* of the tool:

This tool will be built off of a new data model called "ValueTransfer".  This object will have all of these fields

* skillset
* location (city, state, country)
* ..... all of the criteria listed above for pane 1 ... and 
* sender profile
* received profile

Every night when there are new Kudos, Tips, Bounty, or Grant Contributions, they will be ETL'd over to the `ValueTransfer` object

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

I may make this tool, and the learnings from it, part of my ETHDenver talk this year.

**Comment by owocki** [comment]
@frankchen07 i'd be curious to get your feedback on this ticket.  we should ask ourselves hard quetsions about whether or not this will help us visualize/explore/understand our dataset more, or if we're just creating more complex data porn. I'm thinking it'll probably be bountied, not core team.

**Comment by frankchen07** [comment]
@owocki - thanks for being patient, slowly making my way through a bunch of issues.

I think the first two "panes" you have listed here would be an interesting data science tool and honestly, can be put together in Metabase right now with medium lift. I can probably say that there are aspects of those first two panes that already coded up here and there on our dashboards that can be repurposed and a filter added to target specific users.

Some use cases I can see for that tool:

1. In the future if and when we are heavily involved with recruiting, someone asks, "hey who fulfills XYZ requirements and is around in Germany, and has done some Solidity bounties?" If we have those two panes, we can find those people with relative ease, and pass those names along.

2. Same scenario for 1, except we provide a detailed Gitcoin "resume" for whoever wants it.

3. If we want additional information for the internal team, we look up a username, and see it all laid out.

For the mesh visualization network - to me, it is a little bit of data viz porn, but I see two good use cases:

1. Mesh network of humans - it's nice to zoom in on where relationships have been established where otherwise it might not have. This means perhaps highlighting specific, well-known entities on the graph, but generally, if we just show the whole thing, it's taken in as mostly a overarching concept. (I might also be more biased towards data-business balance, rather than super deep Ph.D focused type of research).

2. For deeper network analysis and growth of Gitcoin's network. Arguably, our goals are revenue based, but there is value in being an integral part of forming a network. How we quantify that tell that story is important, but second to those business-oriented network effect metrics (LTV, CAC, retention, split out MAUs, standard growth metrics).

I'll add another note that generally for mesh visualizations, it's not something I'd use on a day to day basis - I wouldn't call it a "tool", because the results generally are not apparent to data-untrained folks, and that being said, even to some data-trained folks. You can put me in the camp of "use it to illustrate the concept right now, but as a tool, I see it as less useful.")

**Comment by owocki** [comment]
> @owocki - thanks for being patient, slowly making my way through a bunch of issues.

npnp. this is just an idea im articulating .. not necessarily a priority 

> For the mesh visualization network - to me, it is a little bit of data viz porn, but I see two good use cases:

agree.  i think that #3 might be public speaking.  having the data pron just kind of makes us look a little more thought-leader-ey

> I wouldn't call it a "tool", because the results generally are not apparent to data-untrained folks, and that being said, even to some data-trained folks. You can put me in the camp of "use it to illustrate the concept right now, but as a tool, I see it as less useful.")

i need to do more research on graph databases and how they can be analyzed... but i think that the insights will be.

1. where is there clustering?  the most 'promiscious' nodes in the network are users we should absolutely focus on.  also we should focus on those who have potential to be the most promiscious nodes.
2. each leaf node in the network is an upsell oppy.  after you've done one (and only one) interaction, if we targeted some focused energy on making that person do a 2nd bounty, then we move them along the adoption curve
3. clustering.. where nodes are clustered, can they be tagged as a specific type of portion of the network (e.g. python bounties, polymath's bounty hunters)

**Comment by frankchen07** [comment]
> i need to do more research on graph databases and how they can be analyzed... but i think that the insights will be

same I will also note that my response is limited by my knowledge of graph analysis as well - you're not far off with your three points above, but it can't hurt to learn more. I only have a passing familiarity.

 I think as we move forward with a bi-weekly data sync, the things you've shared with me (NFX articles, Andrew Chen network effects), could be a good summary knowledge and applicability share.

**Comment by owocki** [comment]
Just wrote up a new ticket that takes a more first principles approach to this  https://github.com/gitcoinco/web/issues/3522
