### ISSUE TITLE
As a Gitcoin user of gitcoin.co, I'm impatient, and I don't want to wait long for a page to load.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3512]
### User Story

As a Gitcoin user of gitcoin.co, I'm impatient, and I don't want to wait long for a page to load.

### Why Is this Needed

Impatience and long page load times do not mix. This leads to users abandoning pages after clicking, which is not good for gitcoin.co

### Description

https://gtmetrix.com/reports/gitcoin.co/C3WnhcJs

@frankchen07
Pagespeed and YSlow are two different forms of diagnostics, which are easiest to do?
Check out waterfall is for diagnostics (specific elements, dynamic avatar)

@frankchen07 to sit down with a Gitcoin engineer to figure out highest priority lowest lift changes and break this ticket into subtasks, and make sure subtasks can actually be fixed in the codebase, or if some of these things may take too much time.

### Current Behavior

We have slower page load times than desired.

### Expected Behavior

We have good page load times.

### Definition of Done

x% decrease of page loading time on y pages

**Comment by owocki** [comment]
x -post with https://github.com/gitcoinco/web/issues/3716#issuecomment-462386196

> Our site need some improvements in loading time

My 002 wei is that we should profile the pages to see whats actually causing the slowness.. (i.e. how much time is spent waiting for the HTML to be served?  how much is images being downloaded, css/scripts, etc?)

@frankchen07 @octavioamu checkout [this chart from GA](http://bits.owocki.com/92edac4b59c5/Screen%20Shot%202019-02-11%20at%209.09.26%20AM.png) of page load times.. it seems the page load times have gone way down since i got the server load issues under control!
