### ISSUE TITLE
Remove styles from dom elements

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#3519]
Description
Dom elements like h1 - h6 are styled with diff sizes depending the page.
This styles need to have it own class if needed but not changing the tag style because affect all the elements in the page and future elements, also make difficult when creating new elements and reusing components. 

Check dom elements for styles that are not styled by bootstrap and create custom classes / or reuse classes to get the expected style.

**Comment by kuhnchris** [comment]
Actually, if we already propose changes to that: please unify all the css into a single directory (assets/css/ for example) and then give them matching names. Also, only load the matching CSS files that are neccessary. Use a {% block style %} where we put it into the proper style-place within <head> instead of just throwing them in at random points.
it's fine to have multiple css per module/app/<unit of work> but we need to keep them into a tree to avoid searching all across the board for them. Same should be for templates, but that's a different topic alltogether.
