### ISSUE TITLE
bug: crowdfunded contribution not showing up

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#3549]
#### Description

```
Muhammad Usman [3:44 PM]
I think there is some bug with this bounty: https://gitcoin.co/issue/gitcoinco/web/2404/1415

If you check on the gitcoin it says 0.6 eth + 0.4 crowdfunding. But if you go to github comments there has been a crowdfunding of 125 DAI as well.
That is not displayed on the bounty page. Could you check this please?

thelostone-mc [5:36 PM]
Ah that is weird ! checking it out
```

Looks like a crowd-funded contribution was added by @Anish-Agnihotri   + @vs77bb.
The one made my vivek is not accounted for on the bounty detail activity but does not reflect on the amount

Gitcoin Issue:  https://gitcoin.co/issue/gitcoinco/web/2404/1415

cc @usmanmuhd

**Comment by owocki** [comment]
The reason the crowdfund doesnt show on the bounty is that the the txid for the crowdfund contribution dropped

https://etherscan.io/tx/0x1e3b70cca385e410671ae53f9c023d8e98aafa408c1ec45965084678dec3a53c

cc @vs77bb  since this was your crowdfund contribution

https://github.com/gitcoinco/web/issues/2404#issuecomment-428680871

**Comment by thelostone-mc** [comment]
Closing this out !
