### ISSUE TITLE
Bounty Fulfillment Suggestive Sell

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3647]
### User Story

As a funder, how might Gitcoin help me find quality contributors to fulfill the bounties I have funded?

### Why Is this Needed
- I want to be sure that my task will be completed by quality contributors.
- It's hard to suss out quality of contributors on the platform right now.

### Problem Description

As a funder sometimes my bounty gets stale if A) It doesn't get picked up by the right contributor or B) If many contributors start/stop/drop off. This in turn clogs the issue explorer workflow. How do we approach this so that funders are getting quality contributors and issues are moving smoothly through our platform?

### Ideas

1. On the funder form, add an option feature where funders can request for our help in finding the right contributors for this task. This could be a flat fee with a money back guarantee if we don't help place someone to complete the job.

<img width="1023" alt="screen shot 2019-01-31 at 9 11 06 am" src="https://user-images.githubusercontent.com/238235/52060886-2ecd1080-253b-11e9-8f9b-7364d2599c5b.png">

### Workshopping

1. This is a proposed idea, we will need to think about the full experience (what are the details, is there a time limit, how can we test this in a light lift way?).
2. Should this only be available to opt in **after the issue hasn't been taken up after X days?** 
3. What does success look like?
4. Final messaging
5. What is this worth value wise?

### Definition of Done

Coming Soon

**Comment by frankchen07** [comment]
I like this idea alot as well. I agree with Scott that it should be priced into a larger model rather than a issue by issue basis, however, we can test this idea by adding an option in the funder form, as a clickable event (perhaps that doesn't charge, or maybe it does and we find matches manually a la carte).

Question two for workshopping deals more with "how do we present this to the funder population" in a manner where we surface that going with a subscription / larger package in the long run would bring much more value than an a-la carte situation?
