### ISSUE TITLE
what do we want to use for dispute resolution long term?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3649]
https://kleros.io/
Delphi

**Comment by owocki** [comment]
@mbeylin do you think Delphi is on the roadmap still? were evaluating our options and obvi would prefer Delphi if it's going to beshipped soon.

cc @vs77bb

**Comment by mbeylin** [comment]
Yeah we're putting a bit of a pause on Delphi as it isn't something we're squarely focussed on for the immediate future. All of the code for Delphi is open source https://github.com/Bounties-Network/Delphi however we've come to realize the designs are not in a completed enough state to begin being deployed in production.

**Comment by ferittuncer** [comment]
Happy new year! 

Do you plan to implement dispute resolution anytime soon? I would like to help to integrate with Kleros.

**Comment by owocki** [comment]
its something we'd love to integrate. there is an address in standard bounties for the arbiter address that we could plug a kleros (or similar) dispute resolution framework into.

**Comment by ferittuncer** [comment]
@owocki Could you direct me to the source code please?

**Comment by owocki** [comment]
@ferittuncer `_arbiter` in https://github.com/Bounties-Network/StandardBounties/blob/master/docs/documentation_v1.md

**Comment by ferittuncer** [comment]
I think we can write an adapter contract to plug ERC 792 Arbitration Standard to Bounties Network API.

**Comment by clesaege** [comment]
I looked at the bounty contract and the issuer can call [killBounty](https://github.com/Bounties-Network/StandardBounties/blob/master/deprecated/v1/StandardBounties.sol#L489) to be reimbursed and [changeBountyArbiter](https://github.com/Bounties-Network/StandardBounties/blob/master/deprecated/v1/StandardBounties.sol#L584) to change the arbiter.
So in this contract the issuer has full control.

We could:
- Make a new contract which remove the changeBountyArbiter function and allow the arbiter contract to killBounty instead of the the issuer.
- Keep the contract, but make gitcoin users create bounties through another contract which would then call StandardBounties. This other contract would be the issuer (and not the bounty creator). Some functions allowed to the bounty creator would be proxied but not changeBountyArbiter nor killBounty.
- Have an entirely new contract.

**Comment by ferittuncer** [comment]
Hello again @owocki 

I'm starting to work on this.

My plan is: 
- Make a new contract based on StandardBounties which remove the changeBountyArbiter function and allow the arbiter contract to killBounty instead of the the issuer.
- Use resolver.kleros.io for submitting evidence and appealing so changes to Gitcoin UI would be very minimal
- Implement logic to make Gitcoin UI support both the new contract and the old contract at the same time.

Does this sound good to you?

**Comment by marsrobertson** [comment]
Interesting: 

* https://court.kleros.io/cases/169
* https://court.kleros.io/cases/170

Low tech but good enough for now.

Need some attention and publicity though.

Kleros protocol works if there is a bunch of internet trolls extracting "free money" from the appeal system.

Otherwise, it is possible that 3 guys are chosen, 2 didn't vote, 1 single juror makes the ultimate decision.

**Comment by owocki** [comment]
would it help if i gave those disputes some publicity / channeled some of the debate there? the reason we chose twitter for this round was that its simple and has wide distribution

**Comment by marsrobertson** [comment]
Posting to Twiter is great!

I happened to find it because I have a personal dispute: https://resolve.kleros.io/interact/172

Just saying the Kleros protocol works best when there is plenty of guys scrutinizing the decision, appealing to get "free money". On the other hand, a party in a dispute can fund the appeal themselves. More eyeballs mean more scrutiny.  There is a dedicated https://t.me/klerosjuror group of guys paying close attention.
