### ISSUE TITLE
Wrong issue title in gitcoin.co

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#366]
##### Description

Issue title at https://gitcoin.co/funding/details?url=https://github.com/googlecodelabs/codelab-components/issues/46 matches previously funded issue, but not the https://github.com/googlecodelabs/codelab-components/issues/46

![image](https://user-images.githubusercontent.com/8781107/35720984-1ab6799a-0801-11e8-91a4-27979a3f89c8.png)

##### Possible Implementation

Either `gitcoin.co` caches info about issue titles or there is a bug in database.

##### Environment

* **Browser**: Firefox 58.0.1

**Comment by owocki** [comment]
https://beta.bounties.network/bounty/v1/23

The title information is what was on IPFS, and it looks to me that this is what the was specified as the title when submitted at https://gitcoin.co/funding/new

Note: on that form, there is an `.blur()` action that updates the title when you enter in a new issue URL.. @abitrolly do you recall when you submitted this issue if you saw this update in the form?

**Comment by abitrolly** [comment]
@owocki I don't remember the form contents at that time, so I can't say if I would notice. Maybe I indeed pasted the wrong URL first, because I was sending tip for that other issue.

Could the reason be that there were multiple windows open and one of them overwritten IPFS content?

**Comment by owocki** [comment]
> Could the reason be that there were multiple windows open and one of them overwritten IPFS content?

we've designed the submission logic to be pretty decoupled from tab to tab, so i dont think thats it.

i think what i'd like to do here is make it so that all of the fields (especially the ones in the 'advanced' section of gitcoin.co/funding/new ) are visible by default... that way theres no chance that they get glossed over upon submission.  it makes the form a little longer, but when youre putting mainnet ETH down on an issue.. i think thats a good thing

**Comment by abitrolly** [comment]
I don't see how can we resolve this until the issue repeats itself.
