### ISSUE TITLE
As a funder I want to see previous contributions to projects and what my expected CLR match is

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3663]
# User Story

As a donor I would be more incentivized to contribute money if I knew how much Gitcoin would approximately match

# Why
Funders want to know....If I donate to this grant - how much potential scale/match so i know their contribution is counted some how.

# Assumptions

Human - People will not exploit this. Hiding this info will make it less exploitable. People wont use this to create multiple accounts, doing $1 donations. We assume that people seeing CLR donate and impact will make them donate more.
Business - We want to be on cutting edge of ethereum economic theory.
Tech - When building this, the number that we show, the number of CLR as it ended in that moment.

# Description

Vitalik has suggested that each grant donation form should have a small section (perhaps below the "total funding" amount on the form) that shows users how much additional money they are bringing to the project they wish to support. 

As a reminder, LR is calculated as the square of the sum of the square roots of all contributions to a given project. For example, the total contribution in the case where two people donated 4 dollars each would be ((sqrt(4)+sqrt(4))^2 = 16

1. backend "cache" (linear/exponential/pre-calculated ranges) formula calculated several times a day
2. live frontend data entered would be based off of the backend "calculated" formula

- @frankchen07 to get clarity with kevin on the phantom funding data model 
- phantom grant contributions will be one-time donated, which would effect the grants model (this wouldn't affect the report, but for this particular ticket, it would affect the live calculation

# Definition of Done
 - [ ] Create a new line in each grant form with the calculated marginal LR amount ([after donation]-[before donation])
- [ ] Add this same marginal LR amount to the grant itself
- [ ] Add this same marginal LR amount to the grant card

Size: **Medium**

# Mock Up

<img width="1308" alt="Screen Shot 2019-08-07 at 2 47 03 PM" src="https://user-images.githubusercontent.com/238235/62652650-d7fd2500-b929-11e9-9d55-7ae9ebc7f34f.png">

<img width="1285" alt="Screen Shot 2019-08-07 at 2 47 12 PM" src="https://user-images.githubusercontent.com/238235/62652655-dc294280-b929-11e9-82d0-72ee1fded55d.png">

# Data (requirement)
no set up needed

Metric
- increase donations

**Comment by ceresstation** [comment]
@owocki additional thoughts on if we can get this up and running? Do we have cycles for it?

**Comment by owocki** [comment]
> what their current expected level of matching is for any given donation.

@ceresstation we need a product specification, not just a paste of something Vitalik said.   things like: where does it live on the site, what does it look like, how is it calculated mathematically etc cc @PixelantDesign 

> Users should ideally see what the previous contributions to any projects are

This already exists at https://gitcoin.co/grants/profile

**Comment by ceresstation** [comment]
@owocki @vs77bb This is one of the higher priority tickets based on Vitalik's comments over the last week.

**Comment by frankchen07** [comment]
<img width="1285" alt="Screen Shot 2019-08-07 at 2 47 12 PM" src="https://user-images.githubusercontent.com/7516920/62656055-3a4d2a00-b918-11e9-94c4-ba877ea8da1d.png">

<img width="1308" alt="Screen Shot 2019-08-07 at 2 47 03 PM" src="https://user-images.githubusercontent.com/7516920/62656060-3de0b100-b918-11e9-92e5-9f8d20ad71b4.png">

**Comment by owocki** [comment]
should we add some language to reflect that this is a best guess estimate?  esp since people can game CLR matching with sybill attacks, we need to retain ROFR on excluding people

**Comment by frankchen07** [comment]
update on this: 

so from the call this morning, it sounds like:

1. there’s a little more thinking behind what will actually go up on the view grants page & the fund grant page, due to the dynamic nature of the CLR match
2. understanding the calculations is TBD, I’m talking to vitalik on telegram on the specifics of how that math works to see how we can simplify it down to something easily done (without binary search algos)
3. 1 is somewhat dependent on 2, and the design is dependent on 1

I would label this as blocked, awaiting me, but I’ll be out for the next 2.2ish weeks, so :grimacing:. Perhaps if I’m bored of relaxing sometime I can chime in with a quick update on how the calculation would work

**Comment by thelostone-mc** [comment]
From what I understand  @ceresstation @vs77bb 

The formula is the square of the sum of square root of all successful contributions on a grant till date from its creation date. 
This would mean every contribution would be counted as unique even if they are recurring payments? // list of successful contributions should be available in our database but will have to double check if we've captured all. 
@owocki / @vs77bb / @frankchen07   how do we do this right now when we have CLR matching ?

there are 2 parts in terms of UI 

- The card which simply shows LR: sum of square root of all successful contributions 
- The fund grant page : sum of ( square root of all successfull contributions + the amount entered by the user )

All this makes sense when grant conrtibutions are made in the same token.
How would it change when one has a grant with contributions in different tokens ?  
Do we take the equivalent USD in any scenario?

Additionally, we have fund gitcoin grant so when we calculate the CLR matching rate , do we take the amount entered by the user and subtract the amount set for the gitcoin grant and use that number in calculating the formula?


> Human - People will not exploit this.

Not entirely sure how this helps prevent exploitation. Could you elaborate on that bit 
@ceresstation? 

It does give more context to funders but again I strongly feel this should have a UX revisit to explain when the CLR matching happens and stuff so that they know the CLR matching rate suggested would most likely vary then what we show them (and also explain why )


cc @PixelantDesign + @frankchen07

**Comment by thelostone-mc** [comment]
UDPATE: will start on the frontend with mock data and will move this to blocked  until I get the questions above clarified ^_^

**Comment by owocki** [comment]
i dont know much about how the current CLR calcs are done.. so defer to @frankchen07  on this qusetion

**Comment by thelostone-mc** [comment]
mocked up UI + raised draft PR <img width="1514" alt="Screenshot 2019-08-20 at 12 19 01 AM" src="https://user-images.githubusercontent.com/5358146/63291221-c3813b00-c2e0-11e9-80fa-3a08f9f68c4f.png">

**Comment by owocki** [comment]
> moving this story to blocked

is this still blocked?  @frankchen07 is back from vacay right?

**Comment by frankchen07** [comment]
chatted with @thelostone-mc yesterday, I believe it's unblocked, but will check again, since he's digesting how the formula works

**Comment by owocki** [comment]
reminder to include phantom funds in this calculation https://github.com/gitcoinco/web/pull/5054
