### ISSUE TITLE
As an internal Gitcoin team member, what are the highest impact front-end fixes we can implement to increase page speed load times and reduce Search Console Errors?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3685]
### User Story

As an internal Gitcoin team member, what are the highest impact front-end fixes we can implement to increase page speed load times and reduce Search Console Errors?

### Why Is this Needed

1. Decreasing page loading times results in a better experience.
2. Having less errors results in a better experience, and better SEO.

### Description

This ticket, as of 2019-02-12, is geared more towards the internal team at Gitcoin. There are fundamental tech debt items to be resolved before simpler more automated optimizations can happen. The biggest issue is on Gitcoin's side. 

From our internal meeting we've identified some steps for tech debt that hopefully will be addressed in the upcoming sprints:

- homepage is loading alot of unnecessary stuff
- tooltips and modals are things we are changing
- marketing pages are loading things we don't need
- we can categorize and reorganize our footer loading with relevant packages
- files are not cached
- django pipeline might help with bundling

**Subtasks:** 

https://github.com/gitcoinco/web/issues/3511
https://github.com/gitcoinco/web/issues/3512

**Metrics to Track**

Lighthouse report: https://googlechrome.github.io/lighthouse/viewer/?gist=8b87924ca329da493f3404c55c71f04f

gtmetrix: https://gtmetrix.com/reports/gitcoin.co/ltHq7z1d

Google Search Console: https://search.google.com/search-console/index?resource_id=https%3A%2F%2Fgitcoin.co%2F&hl=en

Google Analytics: https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a102304388w149870992p154797887/

@octavioamu @thelostone-mc @SaptakS @danlipert I might need some help defining what kinds of metrics (3-4, or less) metrics that we can use as benchmarks. Please add anything I may have missed, or if you'd like, any additional technical details. 

### Current Behavior

Currently we have alot of outstanding issues contributing to page loading and front-end fixes that can improve performance, but we want to identify the highest impact ones and ensure these get completed in due time.

### Definition of Done

1. Formulate a list of high-impact fixes.
2. Create an actionable plan to build these high-impact fixes alongside sprint work.

**Comment by oogetyboogety** [comment]
Probably using prefetched queries like the api update

#3662
prefetch related non-pending interests, activites, and their related active profile avatar urls for api speedup
Opened by oogetyboogety 5 days ago

**Comment by Trututu** [comment]
**Ideally**

We can have almost ideal performance and cleaner architecture by using JAM stack instead of server side page generation. I like to use Gatsby.js as role model when it comes to speed, [Gatsby.js](http://gatsbyjs.org/) DOMContentLoading time can be as low as 30ms, [gitcoin.co](https://gitcoin.co/) DOMContentLoading time is more than 1.5, [djangoproject.com](https://www.djangoproject.com) DOMContentLoading time is more than 1s.

**What can we do now:**

1. Add service worker for controlling caching process (images/css/fonts/api-calls), we can even load site when being offline by using SW (try to reload gatsbyjs.org page without internet access), also some assets don't get cached automatically by browser for some reason (img below). It is easy to add caching SW and it is quite impactful.
<img width="680" alt="screenshot 2019-02-07 at 20 08 24" src="https://user-images.githubusercontent.com/5003495/52410902-dd151f00-2b14-11e9-8d0e-c7ef69a664b8.png">

2. We can get first meaningful rendering faster by using [criitical css](https://medium.com/js-dojo/critical-css-and-webpack-automatically-minimize-render-blocking-css-5390850dad45). It should be an easy fix.
<img width="550" alt="screenshot 2019-02-07 at 20 21 01" src="https://user-images.githubusercontent.com/5003495/52412792-bd80f500-2b1a-11e9-8b16-f71b29c1933f.png">

3. Reduce amount of requests, now we have > 170 request which is a lot. Amount of request heavily influence page loading time, reducing requests is more important than reducing page size.

4. Follow Audit advises

**Comment by frankchen07** [comment]
Thanks for the suggestions all!

The Gitcoin internal team has decided that there are fundamental tech debt items that we need to clean up and work into our sprints before these automated front-end optimizations and fixes can do the most good. We'll be keeping this ticket open to track the progress of these fixes.

**Comment by danlipert** [comment]
@frankchen07 Looks like the gtmetrix report linked above is expired :( Also, I don't have access to the google search console report. That being said, I think the "First Contentful Paint" as well as the "Time to Interactive" are great metrics to track, since they are both commonly used in the industry as benchmarks, as well as very focused on the customer's experience using the site.

**Comment by frankchen07** [comment]
Reupdated the link. @owocki - can dan get access to the google search console? 

First contentful paint and time to interactive - looks like we need premium access to gtmetrix, will have to get at these another way - thanks for the heads up on these

**Comment by danlipert** [comment]
@frankchen07 @owocki I have access to the google search console, but its saying gitcoin.co is unverified and wants me to add a meta tag to the site or upload this random file, etc. etc. Wasn't this already done? Did we have it verified at some point previously?

**Comment by owocki** [comment]
hmm i dont see that warning (though theres a lot of tabs, i dont know which one i should be looking at to know if i see the same thing as you)
