### ISSUE TITLE
Moai 🗿 Avatar Item doesn't render correctly

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#3693]
**Describe the bug**
The new Moai avatar item doesn't render correctly when saved, although it displays correctly in the avatar builder

**To Reproduce**
Add the Moai item and save your avatar

**Expected behavior**
The saved avatar should match the preview in the avatar builder

**Screenshots**
![screen shot 2019-02-06 at 9 33 25 pm](https://user-images.githubusercontent.com/869266/52341890-361e7d80-2a57-11e9-8626-02ff0aa78a25.png)

**Desktop (please complete the following information):**

- OS: Mac OS 10.13.3
- Browser: Google Chrome
- Browser Version: 71.0.3578.98 (Official Build) (64-bit)

**Comment by kuhnchris** [comment]
*sigh* yes that avatar builder is... a pain in the butt. I am currently overloaded with work so I cannot work on avatar revision. Basically there is a new endpoint already (/avatar/view) that can be colored via HEX (not predeteremined) and uses the same system as the "final avatar", instead of having 2 versions, one for the avatar and one for the builder.

Assign this to me please via github, I'll take care of it as soon as the backlog is gone.
