### ISSUE TITLE
As a bounty hunter, I want cooperative bounties to show in my completed bounties history, so that I can be more attractive to funders

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#3694]
### User Story

As a bounty hunter, I want cooperative bounties to show in my completed bounties history, so that I can be more attractive to funders

### Why Is this Needed

Currently, cooperative bounties are paid out such that one of the bounty hunters gets the "official" completion registered in their completed bounties, and the other bounty hunters receive payment in the form of a tip. While each hunter gets paid, only one gets the entry in their completed bounty history. Especially as we move towards things like closed-source bounties, making sure the completed bounty history is accurate will be more and more important.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
half and half

### Current Behavior
Only one bounty hunter gets an entry in completed bounties for a cooperative bounty.

### Expected Behavior
All successful bounty hunters should have this entry.

### Definition of Done
The completion of a cooperative bounty shows in each bounty hunters history.

### Additional Information
This was reported in our community slack:

> justcharlz [12:04 PM]
Hi guys. Just want to understand how a cooperative bounty(https://gitcoin.co/issue/w3f/Web3-collaboration/61/2122) works cause their seems to be a bug. After payment has been made and issue closed, it did not add to my completed bounties record. Also at the end of the github link(https://github.com/w3f/Web3-collaboration/issues/61), gitcoin bot said additional tip added and was sent to me but nothing of that nature happened as I only received my part of the bounty. (edited) 

> KuhnChris [5:34 AM]
“Advanced” Payment is basically refund of the bounty and sending all the participants “tips”
so it may be correct
but we’ll have to check to make sure nothing is broken :wink:

**Comment by kuhnchris** [comment]
actually I think we need to revise this in concept. Currently this system is based on trust. The user "gets the bounty refunded" and has to pay "the other transfers". That works while people are trustworthy, but a malicious user can abuse this system by simply paying one but not the other ones. that sucks. your problem is basically a side-effect of the 2nd part of the transfer that's based on trust. pure from a backend side we cannot "determine" if a user confirms all the tx, we do get the txids but those can be anything, even dropped. 
To get to your "all hunters see them in their profile" issue: either we work around this issue by creating some more metadata in the payout transfer, or we make a intermediate contract (say, SplitterContract).

With the meta-contract we simply store the standardbountyid and allow a certain user (gitcoin for example) to set more members/target addresses for that standardbountyid (and maybe a % or directly an amount of eth). When the Collective Bounty is finished, gitcoin sets the final distribution, the standardbounty pays out the meta/splitterContract, that one checks what the bountyid is, and refers transfers to the target addresses. that way the user has "just one button" and we can make sure that the chain of trust is verified and working.

...just my 2 weis, if you'd prefer to spice up the metadata - fine aswell, simply throw in the other payers
OR
within the geth sync, or rather the part that takes care of syncing the tx back to the backend, add additional logic that not just checks the TX, but checks the standardbountyid of that tx and add Activity Objects for all participants. (so frontend/contract side ain't chaned)

-Chris
