### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#3716]
Our site need some improvements in loading time, I will start in the home page,  creating footer scripts for the marketing pages to load only what is used there and splitting js files as needed

**Comment by owocki** [comment]
> Our site need some improvements in loading time

My 002 wei is that we should profile the pages to see whats actually causing the slowness.. (i.e. how much time is spent waiting for the HTML to be served?  how much is images being downloaded, css/scripts, etc?)

@frankchen07 @octavioamu checkout [this chart from GA](http://bits.owocki.com/92edac4b59c5/Screen%20Shot%202019-02-11%20at%209.09.26%20AM.png) of page load times.. it seems the page load times have gone way down since i got the server load issues under control!

**Comment by octavioamu** [comment]
I had generated some reports here https://googlechrome.github.io/lighthouse/viewer/?gist=8b87924ca329da493f3404c55c71f04f

**Comment by frankchen07** [comment]
Awesome. There's a quick sync tomorrow with the engineers to see what else we can bounty out to the public / prioritized items we can bring into the Gitcoin team.
