### ISSUE TITLE
As a Gitcoin engineer, I can save alot of time by setting up automated regression testing and continuous deployment

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4006]
### User Story

As a Gitcoin engineer, I can save alot of time by setting up automated regression testing and continuous deployment.

### Why Is this Needed

An investment of 5-8 story points now to get CD and automated regression testing implemented will save us tens of story points per sprint down the line.

### Description

Implementing automated regression (virtual server that helps to quickly test browser clicking and then automatically reports it).

Implementing the foundation for continuous deployment (jenkins aka job box that helps coordinate deploys based on pushes to master).

Set the foundation for both now, and then bounty out smaller testing tasks on the regression side.

### Current Behavior

Deployment is manual and testing can eat up a good amount of time.

### Expected Behavior

CD and automated regression testing. 

### Definition of Done

@danlipert to help break this down into subtasks and help Frank define what done means.

### Data Requirements
- [ ] engineering metrics that are usually tracked with CI/CD and automated regression?

**Comment by danlipert** [comment]
@frankchen07 Here's the breakdown of this task as I see it, and I think each step should be done over multiple weeks so that we can see the effect of each effort on our deployments and overall workflow:

### Automated End-to-End Regression Testing

1. A general end-to-end testing framework should be set up, with at least one extremely basic test case.
2. Additional test cases should be added to cover the steps we take currently during manual pre-deployment tests:
	- Sending a Tip
	- Sending a Kudos
	- Creating a Bounty
	- Completing a Bounty
	- Creating a Grant
	- Subscribing to a Grant

3. At this point, end-to-end testing has significant value and should be integrating into our processes at the individual level (i.e. using the automated tests to examine your changes locally.) Next, we'll integrate these tests into our Travis CI process so that these tests are applied to every PR that is submitted, both community and internal. At this stage, passing the tests successfully will be required to merge PRs.

4. Many additional regression tests can be added to cover additional functionality and new features, similar to how we require additional unit tests for new PRs that contain complex functionality.

### Continuous Deployment

1. A Jenkins (or similar) box should be set up that will allow for "one-click" deploys. The deployment scripts, keys, etc. will be set up in Jenkins "projects".

2. Deploys should be performed manually by using Jenkins with engineers standing by to monitor the process and fix any issues.

3. Deploys should be scheduled regularly (2-3x per week) with engineers standing by.

4. Full continuous deployment should be set up once the process seems smooth with solid post-deploy testing in place (vis-a-vis the automated end-to-end testing). At this stage, deployments do not require engineers standing by, and each accepted PR results in instant deployment to production.
