### ISSUE TITLE
discuss: redefine Sharing Bounties

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#404]
<img width="775" alt="screen shot 2018-02-12 at 12 01 44 pm" src="https://user-images.githubusercontent.com/5358146/36154134-7fe1df00-10f6-11e8-84a3-8dbc6438c04d.png">

##### Description

So i helped out with an issue -> and eswarasai wanted to tip me for helping out with work
It’s seems to be a cumbersome experience. 

Would it make sense to allow the system to split the bounties during issuance phase itself? 
I’m not sure how it would look and I’m not sure if standard bounties support it out of the box
but i think it’s a nifty lil feature which would encourage folks to collaborate + network

@owocki @mbeacom @jasonrhaas @mbeylin 

PS: yeah I tried to dump work on your plate @owocki  :P

**Comment by owocki** [comment]
thanks for the issue log.  this is something that should be on the roadmap !

**Comment by razordaze** [comment]
Hm... Negotiation of compensation after the work is done = recipe for exploitation.

There's definitely a Big Problem here, probably outside scope of GitCoin, more in the realm of something like integrating a 3rd party like Colony.io?

**Comment by mbeylin** [comment]
What we're working on with the new version of standardbounties is to be able to submit a fulfillment (work) with multiple individuals, where a fraction of the payout would go to different people. 

It seems to me like the splitting ratios should be determined before the collaboration begins, which we're going to be supporting in the front-end.

**Comment by owocki** [comment]
> What we're working on with the new version of standardbounties is to be able to submit a fulfillment (work) with multiple individuals, where a fraction of the payout would go to different people.

💯 

also @thelostone-mc @eswarasai i just gave the original chat a re-read. hopefully the scope didn't expand too much on that COLO issue.. perhaps its worth a 3 day chat on slack about it if it did

**Comment by eswarasai** [comment]
@owocki -- No, not really. It never did go out of the scope.
The issue was we couldn't really collaborate well together as I didn't have much clarity w.r.t. the implementation part. So @thelostone-mc helped with the initial setup for Frontend and later once the Backend is in place, I refactored the Frontend to meet the requirements. Hence we couldn't really come up with the division of bounty before hand itself.

If we're planning to support dividing the payout to fractions rather than dividing the scope of the project to separate tasks, I'm really not sure if it'd be fair for the developers who're collaborating if one of them ends up doing major part of the work and gets paid less because the issue funder might not really know who spent how many hours in getting the tasks done.

And also are we supporting to increase the bounty at later point in case it might be needed due to reasons like change of scope maybe?
