### ISSUE TITLE
profiles are slow

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4083]
https://gitcoin.co/profile/ethereum - 5s
https://gitcoin.co/profile/owocki - 20s

we'll need to find a way to keep these up to date without calculating all the info on demand..

**Comment by danlipert** [comment]
@owocki @frankchen07 @PixelantDesign @vs77bb 
I would separate caching solutions into 3 tiers:

1) Installing an html-based cache like Varnish - this is probably not feasible without refactoring the page significantly because of its dynamic content so a non-starter
2) Installing a module like Cache Machine [https://cache-machine.readthedocs.io/en/latest/](https://cache-machine.readthedocs.io/en/latest/) which is a plug-and-play Django library that works with the Django ORM (similar to a project called Johnny Cache from a few years ago). This solution might be nice because we can reuse it in other areas as well easily. I'd give this 5-8 sprint points.
3) Hand-writing custom caching in the views that that feed the profile - this is likely the highest performance boost and the sprint effort is similar to 2), but the code is unique to each page and mostly not reusable without considering further where else we'd like to add caching.

I'd recommend 2) for the quickest win with the best long term gains as well. 3) will take similar effort (maybe a bit less) but is as reusable

Another option that could be applied in addition to these would be vertically scaling our database - i.e. spending more money on our infrastructure. This can be very costly as the higher tier AWS databases are quite expensive. Also you often want to reserve scaling for when you really need it and you don't have time to do code performance improvements.

**Comment by owocki** [comment]
fwiw, this is how the results page and contributor landing pages are cached now

https://github.com/gitcoinco/web/blob/master/app/perftools/management/commands/create_page_cache.py
https://github.com/gitcoinco/web/blob/master/app/perftools/models.py

i think it fits into (3) that @danlipert said below

**Comment by owocki** [comment]
here's a starting point for this https://github.com/gitcoinco/web/pull/4316
