### ISSUE TITLE
As Gitcoin, we'd like to be able to stay afloat by charging for features that funders are currently using.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4095]
### User Story
As Gitcoin, we'd like to be able to stay afloat by charging for features that funders are currently using like reserved bounties.

### Definition of Done

- Add payment requirement for an already commonly used feature - reserved bounties
- If possible combine the many metamask popups into one would be ideal.

### Why

- We need to push on revenue

**Comment by SaptakS** [comment]
The approach I think that is feasible right now is making two metamask popups:
1. Funding for the bounty which is a transaction to the smart contract's ethAddress
2. Sum of all the payments (Featured Bounty, Platform Fee, Reserved bounty, etc.) into a single transaction which is a transaction to gitcoin's ethAddress. We can store the information about what all payments this transaction contains in the DigitalGoodsPurchase table so that we can look back and relate if needed.

cc: @danlipert @thelostone-mc @octavioamu

**Comment by danlipert** [comment]
Agree with @SaptakS 's point above, all non-contract transactions should be combined into one. @owocki suggested we can use a splitter contract as well which we can investigate further, although I'm not sure how it interacts with the bounties contract

**Comment by thelostone-mc** [comment]
This would probably have to be taken care before getting into that https://github.com/gitcoinco/web/issues/3544
