### ISSUE TITLE
Migrate the help center at gitcoin.co/help to wordpress.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4310]
This is a task to track the cleanup and migration of the help center at gitcoin.co/help to wordpress.

# Stuff to migrate
- gitcoin.co/help
- Repo maintainer guide
- Developer guide
- Case Studies doc
- Tutorials 
- FAQ
- help articles here https://github.com/gitcoinco/gitcoinco/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp

**Comment by kuhnchris** [comment]
You sure you want to migrate to wordpress?
Seems like a huge overhead for dev docs.
I can actually suggest https://www.dokuwiki.org/dokuwiki which uses Markdown mostly, but if you want we can do a wordpress migration. (except this ticket is just for yourself to check off things)

**Comment by owocki** [comment]
we tried to migrate to wagtail, but didn't have a lot of luck.  ill take a look at dokuwiki

**Comment by kuhnchris** [comment]
Wagtail was the Python integrated one, correct? I remember we had issues with the templates and stuff like that, but it would have been 1 integrated system. With Wordpress and/or Dokuwiki you'd need a separate stack (or at least a PHP stack) for it.
Also, do you guys still run on a SQLite database or did you migrate? Since else we'd also need a database (MariaDB, MySQL, PGSQL, ...) for those. This is very DevOps heavy.

**Comment by kuhnchris** [comment]
Well, according to the other tickets wordpress is already kicking, so, disregarding me/this issue then, i guess. (#4334)
