### ISSUE TITLE
Build Front End - add "worked with you" 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4332]
# User Story

As a funder I'd like to be asked to work with a contributor again.

As a contributor I'd like to be notified if a funder has other issues I can work on, on his repo. 

# Why is this important?
- We want to make it easier for funder to continue to find value in the system. Suggest interactions that are timely and relevant.
- When good working relationships happen, we want those relationships to continue and build upon good experiences.
- We want to build a loop where funders engage with contributors to increase funding of bounties/platform revenue.

# Definition of Done
- [ ] Build front end of this experience
- [ ] Update the transaction confirmation screen
- [ ] If funder clicks yes, Take user to user directory to select issue (follow that flow)
- [ ] If funder clicks no, then take funder to issue explorer
- [ ] Post on video, screenshots, or staging link for review

# Flow
- Prompt Funder after payout screen at bounty acceptance
- Do you want to work with this contributor again?
- Show Github issues funded (user directory flow)
- contributor is notified of this re collaboration opportunity (email).

- If funder doesn't see/click the prompt in app - send follow up email after 24 hrs taking a funder into the above flow.

![56821997-fc9d2780-6879-11e9-9274-29ecdcc42de8](https://user-images.githubusercontent.com/238235/56984031-13ca6680-6b53-11e9-9da1-746552b2f95a.png)

**Comment by PixelantDesign** [comment]
@willsputra please post sketch file

**Comment by willsputra** [comment]
@PixelantDesign sketch file
https://github.com/gitcoinco/creative/pull/79/commits/42e935d29bcab632e9b7e50b673a74ed7ad4f4a5#diff-84c795cede00ffa77569e7ca2cf04765

**Comment by octavioamu** [comment]
Scope changed, add "worked with you" in user directory cards. 
![image](https://user-images.githubusercontent.com/1358093/57638124-7a07ae00-7583-11e9-8cd4-aacd56ddd3b3.png)

**Comment by danlipert** [comment]
I think adding the prompt that is shown in the designs on the transaction page as the first step of the modal will be easier to implement. I think the question then becomes, do we want to have the user land on the users directory after payout to show this modal, or does the modal appear somewhere else? (maybe on the completed bounty page?) Landing back on the completed bounty page with the modal prompting the user  "Yes, invite to one of my bounties" would probably be easier to develop since we will have the completed bounty info at that time already in the page's context.
