### ISSUE TITLE
Build - Backend Working Together Again

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4333]
# User Story

As a funder I'd like to be asked to work with a contributor again.

As a contributor I'd like to be notified if a funder has other issues I can work on, on his repo. 

# Why is this important?
- We want to make it easier for funder to continue to find value in the system. Suggest interactions that are timely and relevant.
- When good working relationships happen, we want those relationships to continue and build upon good experiences.
- We want to build a loop where funders engage with contributors to increase funding of bounties/platform revenue.

# Definition of Done
- [ ] Build backend of this experience
- [ ] Update the transaction confirmation screen (if front end support needed)
- [ ] Fetch Data for If funder clicks yes, Take user to user directory to select issue (follow that flow)
- [ ] Fetch Data for If funder clicks no, then take funder to issue explorer
- [ ] Post on video, screenshots, or staging link for review

# Flow
- Prompt Funder after payout screen at bounty acceptance
- Do you want to work with this contributor again?
- Show Github issues funded (user directory flow)
- contributor is notified of this re collaboration opportunity (email).

- If funder doesn't see/click the prompt in app - send follow up email after 24 hrs taking a funder into the above flow.

![56821997-fc9d2780-6879-11e9-9274-29ecdcc42de8](https://user-images.githubusercontent.com/238235/56984031-13ca6680-6b53-11e9-9da1-746552b2f95a.png)

**Comment by thelostone-mc** [comment]
Questions / Asks

- Could I get the sketch file? 
- Why is the funder being redirected to the user directory page ? 
- Why does the invite button on the loading screen ?  The loading screen is while our transaction gets submitted in the blockchain. It could be take anywhere between 3 - 60 second 
Could I get some clarification on that on why we have this here as opposed to on the payout page ?

**Comment by frankchen07** [comment]
> sketch file

@PixelantDesign or @willsputra 

> Why is the funder being redirected to the user directory page?

From what I understood on Alisa's explanation, the modal load is currently set up with the user directory page in the back, so naturally, after submission, the modal disappears and the user is left on the user directory page.

> Why is the invite button on the loading screen? The loading screen is while our transaction gets submitted in the blockchain. It could be take anywhere between 3 - 60 second
Could I get some clarification on that on why we have this here as opposed to on the payout page?

To me, it's logical to pop the question while they're waiting for the transaction to clear. If we put it on the payout page, then it would either take them away from the funding page before they did payout, or it would clash with the actual payout itself. That's my understanding, @PixelantDesign, was there additional discussion between you and Vivek in regards to this flow?

**Comment by willsputra** [comment]
@thelostone-mc sketch file
https://github.com/gitcoinco/creative/blob/master/Product/Prompt%20Working%20Together%20Again/Prompt%20Working%20Together%20Again.sketch

**Comment by thelostone-mc** [comment]
> then it would either take them away from the funding page before they did payout, or it would clash with the actual payout itself.

Ah that makes sense. Payout page is not a smart idea. derp derp

> To me, it's logical to pop the question while they're waiting for the transaction to clear. 

@frankchen07 coolio! I can roll with it but just saying that since this is a loading page -> there are chances that the button would vanish before the user can click on them. It may be frustrating as there is no other way to access the modal. ( or is there ? )
Also right now this loading screen is used throughout the app. (grants / kudos / bounties ) 
They all use reuse the same code! 
I'm guessing the new loading page with the invite button as opposed the quotes would be shown only on the payout page right ?

PS: I've got enough to get started. Thanks @frankchen07  :D

thanks @willsputra ❤️

**Comment by frankchen07** [comment]
> older flow 

which flow exactly is this? just the normal one? (I think that's what you're talking about)

> would adding the button/modal on the bounty page be better?

so you're suggesting after the waiting / confirmation page, it deposits the user back to the bounty page with the status 'done', which is where we pop the modal or question for re-interaction with the user. 

I think the problem with that currently is the modal can only pop up with the user directory in the background (that's currently how it's set up). There's a bigger chance that the funder would just close the window before they get redirected to the bounty page directly because it explicitly says "you may now close your browser" on the loading page.

> there is a chance that the button would vanish before the user can click on them

I'm assuming that it "vanishes" because the transaction clears and they're redirected to the "done" state of the bounty. My question is what's the average wait time? Since I can see them only taking 10-20 seconds to read the statements and make a decision. As per my comment above with moving the decision to the bounty done page, this is contingent on them waiting the full transaction to clear. So weighing the two options, I feel like there's a chance of disappearing, but that chance is less risky than having them wait the full confirmation time with the message telling them they can close the browser. The greater the separation between paying out and the message to re-work is, the less likely it'll happen. Definitely happy to hear push back though!

> would the button click be on a new tab / same tab?

new tab makes more sense to me, but happy to hear different opinions if there's a strong swinging in one direction or another.

> are we okay with redirecting the users attention away from the transaction confirmation page & not redirecting them to bounty page on clicking the button?

my opinion is that because we're focused on retaining the funder contributor relationship, attention towards re-working with the contributor is prioritized over transaction confirmation and bounty done status.

> I'm guessing the new loading page with the invite button as opposed the quotes would be shown only on the payout page right?

You guessed right, thats is correct. Good qq to take into account.

**Comment by thelostone-mc** [comment]
Ah that gives me enough to start off ^_^ thanks @frankchen07 

Also 

> I think the problem with that currently is the modal can only pop up with the user directory in the background (that's currently how it's set up). 

^ is this already built out ?

**Comment by danlipert** [comment]
@thelostone-mc The modal is already built, click invite to bounty on a user tile in the users directory when you have active bounties funded
