### ISSUE TITLE
Propose Project: Gitcoin Users

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#4416]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder, I want to propose working with top Gitcoin contributors on projects on my Github issue board. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Right now, I can only engage with Gitcoin contributors if I already posted a bounty. Alternatively, if I see the right contributor, I can propose a project we could work alongside together. 

### Description
![Propose Project](https://user-images.githubusercontent.com/23297747/57810985-1de58b00-7737-11e9-9374-b27e9140d3e1.png)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
gitcoin.co/users provides ability to 'Invite to Bounty' only to funders who already have bounties. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
gitcoin.co/users provides ability for **any funder** to invite a gitcoiner to work with them on an open source repo. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- 'Propose Project' button implemented next to Gitcoin Bounty Hunters (people with profiles who actually have done bounties in the past). 
- When clicked, 'Propose Project' takes you to the [fund issue](gitcoin.co/new) page with the bounty either **reserved** for the hunter or with the hunter **invited** (<-- I'd advocate for invited, so other hunters can also apply)
- Use Gitcoin standard button colors
- Review with core team
- Post a screenshot or video of the build

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
- How many new bounties are funded via this flow? 
- How many hunters are engaged through this flow? 
- How many new hunters are activated? 
- Platform value from this feature

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by octavioamu** [comment]
So I see some problems with this task:

1. If Im a contributor and see a funder I use to work I will think I can propose that funder to fund an issue for me, so I can work on it and get paid. 

2. "invite to bounty" only appears for funders with open issues.

3 . "propose a project" is using terms that are not intuitive, what is "project"?  

4. we can do the button inside the modal, flow:  "Invite to a bounty" >  modal >  if I need to create a new one I had a "create new " inside that modal. (is how google drive "move to" do it and seems more intuitive) 

5. the Invite area in fund form is closed by default.

We can see if the users hasn't any open issue and then in that case show "fund new issue" but anyway this will be visible for anyone, funders or contributors and without context I think can be confusing I believe just having the "create new issue" inside the modal will make more sense since I will have a list of bounties as an option or the  "create new issue".

**Comment by octavioamu** [comment]
@vs77bb should be reserved or invite the one to autofill?
