### ISSUE TITLE
Funder Form - When Workers Are Selected - Contributors should be removed from the list

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4427]
### User Story
As a funder when I'm selecting workers to invite, I expect the workers to be removed from the list.

<img width="916" alt="Screen Shot 2019-05-17 at 4 06 27 AM" src="https://user-images.githubusercontent.com/238235/57912936-82990680-7859-11e9-9032-f0109f496388.png">

## Definition of Done
- Remove selected workers from the list

**Comment by willsputra** [comment]
just to make it clear to anyone who's doing this ticket, here's the expected behavior:
1. if a worker is selected, they should be removed from the list and added to the input box
2. if a worker is de-selected, they should be removed from the input box and added back to the list
![remove](https://user-images.githubusercontent.com/19514207/57936037-457e5400-78ed-11e9-9e26-f7615f3985c2.gif)

cc @octavioamu

**Comment by octavioamu** [comment]
I like it, but for other side I don't see a problem also how is today without removing on click, personally I prefer it static so it don't keep my attention in elements moving and lose the point.
Anyway Im ok with both ways
