### ISSUE TITLE
As a Gitcoin funder, having two/three Metamask transactions (Gitcoin fee and bounty amount and potentially featured bounty fee) is causing double payments if any payment in the chain of transactions fails.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4431]
### User Story

As a Gitcoin funder, having two/three Metamask transactions (Gitcoin fee and bounty amount and potentially featured bounty fee) is causing double payments if any payment in the chain of transactions fails.

### Why Is this Needed

This is pretty bad UX, and can cause alot of double fee charges.

### Description

- "I had some friction with Gitcoin because it needs to make 2 blockchain transactions (Gitcoin fee + bounty amount). In my case the first transaction passed and not the second because metamask failed somehow and I had to redo everything. Therefore, I ended paying twice the first transaction (Gitcoin fee). I am now in contact with Scott Moore on Telegram for reimbursement."

- "It's clunky" - I would have put up 5x the bounties if it wasn't as clunky. 

- There are hard stops. Most of the problems are metamask

- I say connect to Gitcoin - brings the issue, I'm gonna fill some stuff out. Lots to fill out — then a prompt that you need to fill out. 2 metamask prompts. Now I'm good - but the transaction failed and no one told me I needed to approve the DAI.

### Current Behavior

2, possibly 3 metamask transactions 

### Expected Behavior

less friction and less probability of error and double payment

### Discussion

this problem may not be able to be solved immediately, lots of UX, backend, and frontend involvement

**Comment by kuhnchris** [comment]
Actually - this all seems to inhert the issue that people can cancel parts of contract interactions.
Wouldn't it be better to simply conduct 1 transaction to a "gitcoin proxy contract", which does all the other contracts (in delegation mode, for example the standardbounty one), so there's just a simple point of contact?

**Comment by thelostone-mc** [comment]
@frankchen07 If we decide to do this -> one possible could be updating the std bounties contract / modifying it. We've got some basic code over at https://github.com/gitcoinco/web/pull/3841

Also @kuhnchris is it possible for the proxy contract to invoke the std bounties contract functions which involve transferring tokens on behalf of the user? ( Is that what you were getting at? )
I assumed those operations could be done only by the user as opposed to another contract

**Comment by kuhnchris** [comment]
Well, as far as I understand the standard bounty contract, the one who creates the bounty is the only person responsible and able to interact with it (naturally, to avoid random people releasing/adding/rejecting/... the bounty itself). So one thing that needs to be possible, or checked, is, that we can provide the standard bounty contract with the proper owner (the sender of the tx to the proxy contract, e.a. the original owner). 
If you want to "take control away from the end user" you can proxified it in the sense that only the proxy-contract can interact with the bounty, of course, but that makes the whole process less secure and the owner cannot interact with his own bounty from another homepage, the the std bounty network.

So ideally the proxy contract would fulfill the following steps:
- take in funds from the user
- send the fee to gitcoin
- create standard bounty
- set owner of that standard bounty to the sender tx which triggered the proxy contract (e.a. the bounty owner)
- ideally signal back to gitcoin if it is a "sponsored" or "advertised" bounty and send the apropriate fund

This requires following things:
- the proxy contract can interact with the standard bounty contract
- the standard bounty contract has an ability or function to "changeOwner" to the original sender
- the function of the standard bounty is not in any way restricted due to this change
- the tx fee for sending the gitcoin fee to the target address (either each time, or bulk-sent and stored on the contract) has to be covered by... something.

If we do not want the user to keep using the standard bounty contract functions, but only our proxy ones (= no ChangeOwner on the Std. Bounty), we'd restrict the user to the gitcoin bounty platform. That may be an unwanted restriction/side effect. But it depends on how business sees that, maybe they want to force the user to only use gitcoin, eventho it interacts with std. bounty? 

For an OSS and "open" and "collective" mind set i'd only proxy the tx so the user has a single point of entry and require the standard bounty to have some kind of changeOwner.

Let me know if something's unclear, we can always chat on Slack/Discord.

**Comment by thelostone-mc** [comment]
@kuhnchris yeah that's what I'd thought ! the bounties contract does have the means to switch owner.
The only thing on my mind is 

- create a proxy contract and do what you said OR
- std bounties has a v2 version and if we were to update that we'd be able to address all these issues

will have to check it out

**Comment by kuhnchris** [comment]
Does Std. Bounties Contract have a road map? Not sure if they have "include fees for services" on their road map, so it may be a futile attempt to wait...
