### ISSUE TITLE
as a user who is contributing to gitcoin grants and wants to tip gitcoin, i wnat to be able to do it on old grants too, so i can tip on the grants that accomodate 99% of the platform

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4485]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who is contributing to gitcoin grants and wants to tip gitcoin, i wnat to be able to do it on old grants too, so i can tip on the grants that accomodate 99% of the platform

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
can only tip gitcoin on grants after may 20th release.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
can tip on any grant

maybe we can just use two transactions and have one be a direct tip, and the other be the grant contribution?  we don't need to do the subminer fee thing in this case.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Measurements
Increase in grants tips revenue WoW

### Reach
All grant funders

### Impact
High Impact 

### Confidence 
80%

**Comment by danlipert** [comment]
@owocki I discussed this with some folks on the Friday war room but we could pretty easily add the optional tips to one-time donations on old grants. I didn't add it because I thought it would be odd to have the tip interface appear and disappear depending on if you select recurring or one-time, and I think optimally we'd like recurring donations as per our sustainability mission. That being said, its probably a good idea, and I really like the idea of having a one-time tip attached to recurring donations as well.

**Comment by owocki** [comment]
> I really like the idea of having a one-time tip attached to recurring donations as well.

yea, i think this is the least worst option.  short of redeploying everyones grant contracts, i think this is the way we have to go.
