### ISSUE TITLE
Remove dead and expired bounties from profile

### ISSUE THREAD

**Issue by debragail** [gitcoinco/web#4521]
Ongoing issue:

Whenever a bounty expires or is completed is not removed from the #started tag and counts towards active bounties.  I have a few that need to be manually removed.  I've always had to request that this be done manually.  Maybe create a bounty to fix this bug?

**Comment by debragail** [comment]
<img width="1324" alt="Screen Shot 2019-06-01 at 13 47 53" src="https://user-images.githubusercontent.com/552529/58753598-7d050880-8476-11e9-9dc8-c709f201c692.png">

**Comment by logeekal** [comment]
Hey guys,

First time contributor, correct me if i am wrong anywhere. I am starting to look into this.

Cheers.

**Comment by debragail** [comment]
This is an ongoing issue.  I'd be happy to test.  Basically tag for x[started] shows cancelled and work done bugs.  perhaps therein lies the issue?

**Comment by logeekal** [comment]
Thanks for inputs. It helps since i am trying to understand the stack. I may have some update next week.

I will let you know.

**Comment by logeekal** [comment]
> 
> 
> <img alt="Screen Shot 2019-06-01 at 13 47 53" width="1324" src="https://user-images.githubusercontent.com/552529/58753598-7d050880-8476-11e9-9dc8-c709f201c692.png">

I need one clarification here. 

You are talking about the results that come up on the default search that happens when someone opens https://gitcoin.co/explorer?network=mainnet&order_by=-web3_created
for the first time. Because if specially filter on a particular status, it is all working fine. ( see Screenshot below )

![image](https://user-images.githubusercontent.com/7485038/60208810-d7776600-9876-11e9-8d85-6a7ac684880d.png)

The reason it is not working in the default page is because no restriction on the status and we will add restriction for the exclusion for Cancelled or completed status bounties.

So I think it not a bug per se but an enhancement request.

You can let me know what you think and in the meantime,  I'll continue to work on this.

cheers.

**Comment by logeekal** [comment]
@PixelantDesign/ @thelostone-mc / @frankchen07 

Any thoughts on above. I just read in bug #4692 that expired bounties are open for work as well. 

So i need input on experts like you on how it should be. by default search happens on **any** status. 

From UX perspective, we should exclude only Cancelled from the list, right?

Also, what was the rational for keeping Status and Radio not checkbox? I am asking this because this complicates the exclusion of multiple statuses.
