### ISSUE TITLE
This issue is closed on Github, but we did not detect that it was closed.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4526]
https://gitcoin.co/issue/exthereum/ethereumex/25/668

**Comment by kuhnchris** [comment]
assumingly because the issue is in the wrong state. I do not think we expect to go from funded->work applied -> work start to ->cancelled.
+ even if the github issue is closed, it doesn't mean that the bounty is closed, as the money is still in escrow (think about it like some repo doing auto-close on pull request finishing, that would kick the guys on the bounty off when it merges)
