### ISSUE TITLE
As a funder my greatest fear is spending time and money on Gitcoin, and not receiving a positive relationship or result. Is there a remediation process?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4562]
### User Story

As a funder my greatest fear is spending time and money on Gitcoin, and not receiving a positive relationship or result. Is there a remediation process?

### Why Is this Needed

The greatest risk for a funder is spending time to go through the flow and not coming out with a positive relationship or result. For re-engagement purposes, is there a remediation process?

### Description
tbd

### Current Behavior
no remediation or reimbursement

### Expected Behavior
tbd

### Definition of Done
tbd

### Data Requirements
tbd

**Comment by owocki** [comment]
i think an oz of prevention is worth a lb of cure.  what are the funders expectations going in?

**Comment by kuhnchris** [comment]
I think that the expectation needs to be explored first.
Is the expectation to find a long-term worker? 
Is the expectation to solve an issue that has been pushed around due to low priority and high yield that'd be nice to have added by some third party?
Is the expectation to find short term staff upgrades?

If you know where they are comming from, you can build focus on those user groups

**Comment by frankchen07** [comment]
great comments from both of you. I think the next step of action is the figure out the varying groups of funder expectations  

so far, we've heard:

most is a combination of turning around issues via quality work at a not too crazy price point
some are job market (which can be an enhanced or opportunistic version of the first one above)
less is finding a long-term worker

we have some funder interviews coming up, so these questions and thoughts will be worth exposing

**Comment by frankchen07** [comment]
update: I believe @willsputra is investigating this!

**Comment by davidkaufman** [comment]
The sentiment is fair: in business, programmers sign contracts.  Stakeholders have legal remedies available to them if a member of the tech team violates their confidentiality or non-compete clauses.  Their fear is soothed by lawers and law.  But here, on the internet, internationally far-flung developers, hiding behind bright avatars, paid in that slippery cryptocurrency stuff... what's NOT to fear?  How do you reassure your boss that an army of anonymous hackers paid in crypto aren't going to screw over the company?

I think, to take Kevin's comment a step further, like Ebay (or even ThePirateBay!) we should stress that an ounce of _reputation_ is worth a pound of **recourse**.  You don't _know_ that "uk_techguy_6783" is trustworthy -- you **want** you send him your payment, hoping he'll send you you that mint condition 1984 Atari 800 vintage-retro game console he has listed.  But you do't trust him ...**until** you see that he has a solid stellar 4.93 star reputation! and, perusing his profile page, you see dozens of his other happy customers praising his pokemon cards and D&D paraphenalia and, honestly, with street cred like that, you have no doubt left whatsoever that you'll be playing Yar's Revenge in all of its 8-bit pixellated glory in 7 to 10 working days, as advertised.

The network effect, the FOMO, the power of all that strong social proof, is what comes together to make us feel safe doing business over the internet these days.  Why don't millionaires invest in amassing enough sha256 mining power to take over the bitcoin P2P network, and double-spend all the money?  Because they stand to make much _more_ money, over the long term, participating *honestly* in the network, than they could hope to gain by attacking it, and also, if the attack were successful, destroying it, and killing the Golden Goose for themselves, too. 

In the same way, we need to show funders that a Gitcoin bounty Hunter with a positive reputation would never screw over a gitcoin bounty *Funder*, because it would ruin her reputation, her long history of good reviews and ratings is worth much more to her because losing that would cost her future Bounties!  We have a blockchain... maybe we should add an immutable, indelible chain of 1-to-5 star ratings to every Bounty Hunter's profile page!  On Ebay, I know a seller's comment and rating from a past buyer (good or bad) carries extra weight when I see that the site says he was a "verified buyer" of Something or Other, the date and the price -- I know Ebay is saying, "I dunno if the guy just has sour grapes, but he DID buy the Something or Other from the guy last March, and this WAS his reaction..." and so the reputation system tends to keep everyone on their best behavior, and motivated to participate honestly.  It also tends to discredit outliers, the one bad review among thousands of positive ones has little effect when prospective buyers can see the seller has an otherwise 99.7% customer satisfaction rate.

Social Proof, seeing the comments and ratings of others, seeing that Bounty Hunter X filled 746 bounties last year for an average of Y eth per job, and still has a 4.84-star rating!  At the risk of becoming the uber of code, knowing that the system can't be gamed because it's blockchain-based, that fake reviews are impossible cuz the blockchain **proves** who paid how much, to whom, and when... all we have to do is add the authentincated reviews and ratings of the funders to the financial transactions, on-chain somehow, and boom -- we can tell funders: you can trust this (and onnly this) reputation system because this history can't be rewritten.

That or we could make Bounty Hunters all use DocuSign to agree to non-compete clauses 🤣

**Comment by frankchen07** [comment]
great read @davidkaufman - with some modifications, this would be a fun blog post!

reputation is definitely a strong consideration - doing bounties being the primary example of on-chain social proof (you did work, it's forever on the chain, and you got payment from it). Other things like star ratings, comments, and average stats can be obtained off-chain, but certainly in the future if and when it makes sense, having some kind of immutable profile makes sense.
