### ISSUE TITLE
My recurring grant is in a weird uncancellable state

### ISSUE THREAD

**Issue by jacob-eliosoff** [gitcoinco/web#4731]
The grant is for Austin Griffith, https://gitcoin.co/grants/122/austin-griffith-ethereum-rampd, for 100 DAI per month under my name, jacob-eliosoff.  I had trouble setting it up, accidentally created two, tried to cancel one, had further trouble, and now one is listed as inactive and the other (https://etherscan.io/tx/0x0c479ae6b11c38787db5b95cc47b2d30718d1d17207e49cabe35c28b34d05e02) is active but seems somehow uncancellable - I get a contract error when I try.

None of this is urgent!  I just want to know if my 100 DAI per month is going to successfully go to this project.  If not, I'll create another one (and ideally cancel this one).

Thanks!

**Comment by PixelantDesign** [comment]
Thanks for the report @jacob-eliosoff! Looking into this.

**Comment by owocki** [comment]
looks like the active subs isnt billing because this tx ( https://etherscan.io/tx/0x0c479ae6b11c38787db5b95cc47b2d30718d1d17207e49cabe35c28b34d05e02 ) was dropped and replaced.  we dont have automatic handling of this situation yet in the codebase... so i went in and told the sytsem that tx 0x6695db1a720f4c1a99fe520dca52f503547b6f7cde746ca9d4e1ce18ce72da6e (the replacement tx) had mined.  it will bill shortly, and your active subscription will be back in a good state
