### ISSUE TITLE
As a Gitcoin operator, how do we direct funders to the funder dashboard?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4755]
### User Story

As a Gitcoin operator, how do we direct funders to the funder dashboard?

### Why Is this Needed

We need to take inventory of our current emails and possibly design a new email experience that guides funders to the modules and features of the funder dashboard. This basically is designing an email that introduces the funder to the various features and how to use them on the new funder dashboard.

### Assumptions

1. We are assuming that funders need a notification / email / messaging to understand the new dashboard. We're also assuming that this messaging will direct them to the dashboard when in actuality, it should redirect them automatically upon login.

2. Assuming that upon login they are directed to the new dashboard, we assume that retention for funders will increase. 

3. no tech assumptions

### Description

1. taking inventory of our current emails (relevant to dashboard actions) - which ones can we retire? consolidate? which emails will this current new "introductory" take over?
2. if 1 pans out, then we'll need design on the basics of this introductory email
3. map out the entire email dashboard experience

### Current Behavior
no messaging or notification that there will be a new dashboard

### Expected Behavior
concise how-to messaging or equivalent for how to fully take advantage of the funder dashboard

### Definition of Done
- [ ] make recommendations on existing email inventory
- [ ] potential design decision and sketch file if necessary
- [ ] map out the entire email dashboard experience (end to end)
- [ ] collaborate with engineering

### Data

**Comment by willsputra** [comment]
Mapping our existing emails to a typical funder lifecycle:

1. Successfully signed up
_✉️Drip_

2. Funded an issue
_✉️Drip / (is there a 'bounty successfully funded' email?)_

3. Got applicants on an issue
_✉️
https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/start_work_new_applicant.html
https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/start_work_applicant_about_to_expire.html_

4. Applicants auto-approved
_✉️https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/start_work_applicant_expired.html_

5. Applicants started work
_✉️none_

6. Applicants submitted work
_✉️https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/new_work_submission.html
https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/funder_payout_reminder.html_

7. Applicants stopped work
_✉️none_

8. Bounty cancelled
_✉️none_

9. Bounty expiring
_✉️https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/new_bounty_expire_warning.html_

10. Funder inactive
_✉️funder_stale (https://github.com/gitcoinco/web/blob/master/app/retail/emails.py)_

cc @octavioamu in case I missed anything since you've also looked at our emails 🙂

**Comment by willsputra** [comment]
One approach could be:
1. Having an intro email as @frankchen07 mentioned (_"Introducing our new dashboard! Here's how it looks like and what you can do..."_). For existing funders, this could be sent as a one-off email. For new funders, this could be sent after they funded their first issue.
2. At the same time, we could update the CTAs of the various emails above to 'View on Dashboard'

**Comment by willsputra** [comment]
@frankchen07 @PixelantDesign we could do this for the intro email. thoughts?
![funder dashboard intro](https://user-images.githubusercontent.com/19514207/62235671-ff229680-b3ff-11e9-81b7-5acadf6caf4e.jpg)

**Comment by owocki** [comment]
design looks good.  i think we might want to make it clear that its a v0.1 in the email though, and highly encourage feedback on it via github (not slack, slack will become too unwieldy IMHO).  feedback is great, asyncronous feedback is even greater!

**Comment by willsputra** [comment]
updated the funder email with feedback from @PixelantDesign 

![funder email](https://user-images.githubusercontent.com/19514207/62313586-b16f6200-b4c3-11e9-8c2a-e12460d39b22.jpg)

**Comment by willsputra** [comment]
contributor dashboard email
![contributor dashboard](https://user-images.githubusercontent.com/19514207/62382280-d2958880-b57f-11e9-8d51-9cef6eee2664.jpg)

**Comment by danlipert** [comment]
This looks amazing! Are the UI elements screenshots from the site or are they from your designs? What's left for us to add so the site and the email sync up perfectly?

**Comment by PixelantDesign** [comment]
@danlipert looks pretty much like the dashboard already.
