### ISSUE TITLE
[Wordpress] As a Gitcoin Participant/Potential Funder I'd like to be able to see the projects from past Hackathons.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4823]
### User Story

As a Gitcoin Participant/Potential Funder I'd like to be able to see the projects from past Hackathons.

### Why

We want funders to see the kind of great work on the platform.
We want participants to see the great projects they could work on and get paid!

Potential Idea: Set up a wordpress template to make this easy for BD to spin up.

### Definition of Done

- [ ] Come up with an approach (Octavio, Alex, Will)
- [ ] Build simple template that can be used on our blog for this purpose
- [ ] Consider where this fits in on the Contributor Hackathon Experience FLow
- [ ] Consult with @octavioamu on this effort.
- [ ] Review with Hackathon Team
- [ ] Provide final files

### Additional Info
Coinlist Example: https://coinlist.co/build/0x/votes

**Comment by alexvotofuture** [comment]
@octavioamu and I just met about this to discuss the approach.

We will be creating a Wordpress site that pulls project/team info from an input source (source TBD), then adds this content to a square content block, alongside other project/team content blocks in a single page. Bonus points if these squares can be edited later by users themselves.

There are two ideas for the input source. The first idea for an input source would be a form that people fill out on the hackathon landing page or prize explorer, which would then populate a Google Sheet that we'd pull into the Wordpress content blocks. In this case it's unlikely we'd be able to let users edit the project details themselves later. But this simple approach avoids some product complexity and security considerations.

The second idea is to find a WP module with forum-like functionality that lets a user post their own project content block, then edit it later. This would be preferable, as it would allow people to post the project idea early in the hackathon by themselves, then edit the project and add team members over the course of the hackathon as the project progresses until it's time to submit. If the plugin had comment functionality, it would allow users to ask to be part of the team, would allow judges to provide input, etc.

Either way, here are my suggestions for some required fields to collect from the input source/form (@frankchen07 @PixelantDesign @vs77bb please jump in here with edits/suggestions):

- Project Name
- Gitcoin usernames (for all team members)
- Gitcoin repo/PR URL
- Project summary (280 character max)
- Prize bounty URLs (for each prize the team will submit the project to)

Future considerations: Can we use this team-centric Wordpress site to automatically auto-populate an "apply for work" plan and auto-populate a "submit work" form to the Gitcoin site (ie: automatically fill in the team members, Github URL, open multiple tabs with a submission for each prize they want to apply to, etc.) which users can finalize/approve on the Gitcoin site so that this becomes the primary hackathon coordination experience for hackers rather than the current prize explorer + Discord?

**Comment by octavioamu** [comment]
Project logo if exist

**Comment by owocki** [comment]
the new profile i specced yesterday ( https://github.com/gitcoinco/web/issues/4908 ) contains info about past hackathons.  so if we continue with that, then that'd be complimentary

**Comment by octavioamu** [comment]
I'm making some tests here, for now Im more focused on the flow (how people input data, what data is showed) than the visual https://hackathons.gitcoin.co/grow-ethereum/results/ . Also if you click "submit your project" you can see the flow of how hunters add / edit their data.
