### ISSUE TITLE
As a Gitcoin Operator, We want to explore/research opening up Issue explorer for Google

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4848]
### User Story

As a Gitcoin Operator, We want to explore/research opening up Issue explorer for Google so that we can increase traffic to our site.

Currently there is a Lot of javascript blocking the view.

### What 

- [ ] Research ways to open up the issue explorer vs Bounties network way (maybe varnish) or rendering metadata
- [ ] Provide recommendations (low, medium, high effort and tradeoffs of each path
- [ ] Review with Squad

### Why

We arent receiving traffic we deserve google cant see the 5000 bounty pages.
Impact: Extra 10,000 visitors/month. Current = 2,000 sessions/mo from SEO

**Comment by danlipert** [comment]
Largely, this involves making the site's content more visible to Google - for reference, we can check the google search console. @octavioamu has already done some good research on this 🙌

**Comment by octavioamu** [comment]
After some research I think the blocker is the rules inside a robots.txt in cloudfront https://s.gitcoin.co/robots.txt

**Comment by octavioamu** [comment]
Updates on this task.
Now the robots.txt are correct, scripts are not being blocked.

But there is a bigger problem, googlebot uses chrome 41 to render pages, with that there is no support for ECMAScript 2015 (ES6). What that means?
Means there are things in javascript we have done that googlebot can't understand. (arrow functions, let, const ...) 
### What are the options?
1. Use babel and setup a pipeline to bundle our js in a proper way so the code will be "translated" to a way googlebot can understand (best solution)
2. Refactor any ES6 code to be supported by chrome 41 (really bad solution also a high effort)
3. Create a rule to generate a static page with bounties just for bots (not very good, because then will need to change a lot of code, big investment on efforts, need to maintain this page when do changes and also will never be realistic as the users version) 

@gitcoinco/engineers @PixelantDesign @frankchen07

**Comment by PixelantDesign** [comment]
What are the trade-offs of each option? 
What is the level of effort (estimate) of each option?

**Comment by octavioamu** [comment]
The trade offs are in each point, about the estimation I believe is something we need to discuss with the eng team

**Comment by PixelantDesign** [comment]
No recommendations from Engineer right now from engineering....

All options are high lift

Refactor javascript
Rewrite javascript. At least 2 sprints for 1 engineer

Third is lower lift for low results

Cannot bounty.

**Comment by owocki** [comment]
> As a Gitcoin Operator, We want to explore/research opening up Issue explorer for Google so that we can increase traffic to our site.

doesnt `sitemap.xml` handle this already? why does this have to be done via the issue explorer?

**Comment by danlipert** [comment]
@owocki The issue is that google can't see much of the content on the issue details or explorer page because of the ES6 code

**Comment by owocki** [comment]
but why does it need to see the issue explorer?  it should be able to crawl all the bounties via `sitemap.xml`

i get why we need to update the `issue details` page, but not the explorer.

**Comment by owocki** [comment]
btw is there a task for the issue explorer page crawler?

**Comment by marc-at-consensys** [comment]
The Web3 content within the individual issues are not viewable by Search Engines, they can see the meta data and url but not the issue description so they appear as empty pages to Google.  

Explorer pages got less than 300 visits from Organic Search last month: https://analytics.google.com/analytics/web/#/report/acquisition-channels/a102304388w149870992p154797887/_u.date00=20190701&_u.date01=20190731&_r.drilldown=analytics.trafficChannel:Organic%20Search&explorer-segmentExplorer.segmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=explorer

**Comment by marc-at-consensys** [comment]
I used the "URL inspection" tool via Search Console to see how Google is rendering individual pages.  See screenshot or this link (https://search.google.com/search-console/inspect?resource_id=https%3A%2F%2Fgitcoin.co%2F&id=prJAtgF3AHJatRAdkEKYEA&alt_id=V-XV37Rxzhg06iJIdZOLfg&panel_tab=2)
![image](https://user-images.githubusercontent.com/49534637/62711197-9bcbd200-b9c6-11e9-94e6-f743e86112d1.png)

**Comment by owocki** [comment]
> The Web3 content within the individual issues are not viewable by Search Engines,

@marc-at-consensys  This ticket is not about the individual issues.  Its about the issue explorer.

so I repeat my question:

> why does it need to see the issue explorer? it should be able to crawl all the bounties via sitemap.xml

and this question

> btw is there a task for the issue explorer page crawler?

**Comment by owocki** [comment]
> https://analytics.google.com/analytics/web/#/report/acquisition-channels/a102304388w149870992p154797887/_u.date00=20190701&_u.date01=20190731&_r.drilldown=analytics.trafficChannel:Organic%20Search&explorer-segmentExplorer.segmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=explorer

i can't access this report.  a screenshot would be helpful.

**Comment by owocki** [comment]
> All options are high lift

seems to me that just 
1. adding a hidden div on the bounty_details page with some overview info
2. which is `display:none` unless the request useragent is googlebot

would sufficiently solve this task and would be pretty low lift.

**Comment by marc-at-consensys** [comment]
@owocki The **display:none** option should be a viable quick solution.  Note, Google likes to give full credit to content that is completely visible.  

The **screenshot** before was just showing that the issue explorer & related pages dont get much search traffic cause Google cant see the web3.  Pages with gibberish would likely get more.  

The **Issue Explorer page** is a great asset for SEO and should be crawlable so Google can see its a hot, top level page and return frequently for new bounties/content (numerous times per day). Google loves fresh content. 

The Issue Explorer page should also contain crawlable pathways/categories to all the existing bounties.  This is also supports having individual bounty urls under the issue explorer file path.  We have this mapped out in the new IA doc on Mural because it will further strengthen the Issue Explorer as a top level source of new bounties/content.  

The **XML sitemap** is secondary and should still be done.  Considering the size and complexity of the Gitcoin sitemap also, we cant always bank on that generating perfectly every  few hours. Recall we found a bunch of errors with it a while back and have it jerry-rigged to do certain things.  

 In terms of the "**issue explorer page crawler**," I am not sure what you are referring to.  But seems it might be this exact "Web3 crawling issue" we are talking about now.  Let me know.

**Comment by PixelantDesign** [comment]
If we were to explore option 1

Use babel and setup a pipeline to bundle our js in a proper way so the code will be "translated" to a way googlebot can understand (best solution)

- New architecture deploy
- Set up web pack

Need to discuss further with @danlipert 

Estimated Effort: 2 people, 1 sprint

**Comment by owocki** [comment]
> In terms of the "issue explorer page crawler," I am not sure what you are referring to. But seems it might be this exact "Web3 crawling issue" we are talking about now. Let me know.

sorry, i meant 'is there a separate task for showing bounty-details to google?'  seems to me that getting the bounty-detail pages crawled by google is much higher ROI than issue explorer.

> Estimated Effort: 2 people, 1 sprint

our organic search traffic is completely flat, so everything we've done thus-far on SEO has either not had an impact or it's impact is "yet to be seen". this makes me skeptical that the promised impact (pasted below) will come to fruition:

> Impact: Extra 10,000 visitors/month. Current = 2,000 sessions/mo from SEO

"2 people, 1 sprint" is a pretty high lift.   i wish we could find a way to be more lean on this.  perhaps by just doing the `display:none` thing on bounty details page.

**Comment by PixelantDesign** [comment]
@danlipert @octavioamu is it worth trying what @owocki suggested to see what kind of improvements could be made?

**Comment by danlipert** [comment]
We can definitely add the hidden content solution, although I think
previously we ruled that out since google will be pretty wise to that
trick. That being said I suppose it should help somewhat so lets start there

-Dan Lipert

**Comment by octavioamu** [comment]
The concept name is "Cloaking". Is penalised by google as I understand.  
https://support.google.com/webmasters/answer/66355?hl=en

**Comment by danlipert** [comment]
I think the above PR I submitted is good enough for now - if there are better HTML tags to use other than H2 and H3 then thats an easy fix but this should be enough for google to see the content

**Comment by PixelantDesign** [comment]
Just circled up with @danlipert we think we should still try this. Closing this research task since we have a PR open.

cc: @owocki @octavioamu @vs77bb @thelostone-mc
