### ISSUE TITLE
As a Gitcoin admin, I'd like our wordpress instances to be hardened, so that we don't get hacked

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4871]
### Who
As a Gitcoin admin, I'd like our wordpress instances to be hardened, so that we don't get hacked.

### What 
Time should be spent (3-5 points) on hardening our wordpress installs - installing security plugins, disabling non-essential and vulnerable/exploitable features, etc.

### Why
Now that we run two wordpress instances as part of our site, we should make sure they are hardened against intrusion and exploit. Wordpress is one of the most popular web servers, and therefore is the target of many automated exploits and bots. In a given day, hundreds, if not thousands of exploits are attempted against these servers.

**Comment by kuhnchris** [comment]
from my experienes with wordpress (and wordpress 'pentesting') i'd like to tell you the only thing you can surely and safely protect your wordpress instances - is to have the instance running in a VPn or non-internet connected entity, make changes, and generate static pages with that... 
or have a good update strategy in place.

Since this is too much for a "start solution" I can only suggest what i'd suggest my clients, which would be:
- Avoid external plugins as much as possible
- Lock down the plugins directly and only allow those out which are neccessary on the generated page to be displayed (e.a. lockdown TinyMCE and other thing that you only need during design time)
- Keep backups
- Unix Permissions as tight as humanly possible
- Redirect /admin to a cryptic or other URL via webserver configuration (no 304 forwarding)
- Lock down users as far as possible, only give them the most basic of needed permissions.
- Again, keep backups. 
- Filesystem Backups and Database Backups, don't skip on those, put them on google drive or on s3 or whatever.
- Have a daily run of chkrootkit and other scan tools specifically in wordpress directories.
- Subscribe to the wordpress ATOM or RSS feed
- Have daily reports about what changed on the filesystem. If something changed and nobody was working on it - something's up

Wordpress is a pain to maintain, and vulnerability pop up left and right, so a good update management is key.

**Comment by danlipert** [comment]
@kuhnchris appreciate your writeup here - @owocki this is why I want to spend a decent amount of time on this
