### ISSUE TITLE
As a Gitcoin operator, when the funder dashboard is released, I would like to understand how it is performing.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4889]
### User Story

As a Gitcoin operator, when the funder dashboard is released, I would like to understand how it is performing.

### Why Is this Needed

Data tracking on the dashboard is necessary in order to piece together proxy measurements as to how the funder dashboard is being used.

### Assumptions

Human - We are assuming that funders will use the dashboard frequently for its intended use.

Business - We are assuming that frequent use of the dashboard will increase retention, and that use of the dashboard means "successful use without frustration."

Tech - What google analytics tracks can we place on the page and have it be a reasonable lift?

### Description
metrics of interest: 

unique page views 
unique page clicks
specific cta / action elements that are specifically clicked (what actions do funders take?)
google analytics behavioral flow analysis (what is the most common flow through the app?)

### Current Behavior

no action plan for dashboard

### Expected Behavior

analytics tags on the dashboard

### Definition of Done
- [ ] action plan for data tracking on the funder dashboard
- [ ] add GA tags
- [ ] check appropriate urls for funnel analysis

**Comment by octavioamu** [comment]
tracking tickets need to have the action and event name, for example

Track when "approve worker" is clicked in the dashboard with the event dashboard_approve_worker
Depending on what you want to discover tracking is what information we need to track, 
keeping in mind events can have data but not personal data.

**Comment by octavioamu** [comment]
As didn't had the data yet I took the opportunity to setup tagmanager for us, I had a PR with the integration and created a GTM container with:
- diff environments for production and development
- Integrated GA, facebook pixel, Twitter tag 
- Activated GA User-Id
- Setup all the basic flow for tracking
- Tomo I will track actions I believe are important on dashboard, because if we want to change anything with GTM is not longer needs for deploy, so we can change / test add new stuff etc.

**Comment by octavioamu** [comment]
Tags (not fired because I setup a rule to avoid sending localhost tracking)
![image](https://user-images.githubusercontent.com/1358093/63075682-d96db500-bf08-11e9-9ff0-c4055875676d.png)

User id set in GA, so now we will be able to group sessions of the same user, understand behaviour, etc 
![image](https://user-images.githubusercontent.com/1358093/63075718-0621cc80-bf09-11e9-83a6-5dab4eadad79.png)

Why I did all of this?
- We need tracking on actions, as I always receive questions about if we know if people is clicking X 
- Be able to follow the features we have to understand how people is using it or if they are using/
- Be able to do fast tracking, without waiting a week for deploy.
- Detach tracking from the development process as we never really know what we want to track exactly.
- Give us an option to setup a user journey.
- Better performance loading 3rd parties scripts 

And of course all the GTM options of tracking data just with some clicks to do really complicate things like track by fragments of url, scroll page to certain point, referral url, clicks, id, forms, etc etc.

**Comment by octavioamu** [comment]
@owocki maybe this can interest you as you were working on #4435
