### ISSUE TITLE
Price fluctuates on the explorer stats page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#491]
<img width="1344" alt="screen shot 2018-02-23 at 3 38 13 pm" src="https://user-images.githubusercontent.com/513929/36620318-ae21223e-18af-11e8-8a73-a421a45b941c.png">

The stats on this (the USD amounts) should not fluctuate.  It should lock in at the time in which the issue was submitted to the blockchain.

**Comment by mkosowsk** [comment]
Great idea!

Whoever thought of this one is really on top of their game

**Comment by owocki** [comment]
sry @mkosowsk i should have given you credit.  brain fart

**Comment by mkosowsk** [comment]
No worries! You'll never have need to promote me because I'll always make sure to do it myself haha 😂🤣

**Comment by owocki** [comment]
possible dupe with https://github.com/gitcoinco/web/issues/693#issuecomment-378514081

**Comment by owocki** [comment]
hey @PixelantDesign @mkosowsk -- @cryptomental and i are wrapping up some changes on the code here. which prices do we want to show for each individual bounty on the explorer page?  

for `open` (started, submitted) bounties,  im thinking we show the CURRENT value of the bounty.
for `closed` (done, expired, cancelled) bounties,  im thinking we show the historical value of the bounty.

does that work?

**Comment by PixelantDesign** [comment]
Makes sense to me!

**Comment by mkosowsk** [comment]
@owocki sounds good! One minor clarifying question, for `closed` when you say historical value of the bounty does that mean when the bounty was first issued or when the bounty was done?

For expired and cancelled, think it might make sense to have the historical value be when the bounty was first issued. But for issues that are done, it might make sense to be the value in fiat that was paid out when the PR was accepted 🤔

In the first case of expired and cancelled, this was the amount in fiat that the **Funder** wanted to pay out. In the case of when the issue is done, this is the amount that the **Contributor** actually received. If it's not super complex to differentiate these I think it's worth it

**Comment by owocki** [comment]
[stats with the requested changes -- local vs prod!](http://bits.owocki.com/1N0v0u2X430w/Screen%20Shot%202018-04-11%20at%2011.37.27%20AM.png)

> One minor clarifying question, for closed when you say historical value of the bounty does that mean when the bounty was first issued or when the bounty was done?

last mutation of the bounty.. so for done, when it became done.. or for cancelled, when it was cancelled

**Comment by mkosowsk** [comment]
Great work @owocki and @CryptoMental! Think is a pretty big QoL change for Gitcoin, quantifies the real value transfer on the platform and not daily fluctuations in the crypto market 💪🏻🤠👍🏻

**Comment by owocki** [comment]
one thing i'm noticing from testing.. do we want to show the conv rate date on [this module](http://bits.owocki.com/2q1f1e0W0v2j/Screen%20Shot%202018-04-11%20at%2011.54.30%20AM.png) in addition to the conv rate ? if you look at old bounties, the user is kind of left guessing when the conv rate is pegged to.. or maybe i just am because im focused on this now

**Comment by mkosowsk** [comment]
@owocki I would include the date, think it's good info that provides context

**Comment by owocki** [comment]
[screenshot](http://bits.owocki.com/323Q2z0Q3a0n/Screen%20Shot%202018-04-11%20at%2012.45.22%20PM.png)

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/853 is live now
