### ISSUE TITLE
Bounty has been rewarded but is not displayed as closed in the gitcoin explorer.

### ISSUE THREAD

**Issue by kuberlog** [gitcoinco/web#4929]
https://gitcoin.co/issue/centrifuge/precise-proofs/88/3225 

has a discrepancy with

https://github.com/centrifuge/precise-proofs/issues/88

**Comment by kuhnchris** [comment]
Hi there,

this happens if there are multiple bounties opened for the same issue.
The "standard_bounty id" for the correct one is 3226

https://gitcoin.co/issue/centrifuge/precise-proofs/88/3226

It seems two bounties were opened, since the first link goes to /3225, as mentioned by you, and the 2nd goes to /3226 (the one that finished).
Maybe ping lucasvo over at that repository that he should cancel the other one.

![grafik](https://user-images.githubusercontent.com/761911/62285068-2e172780-b455-11e9-978b-673d22bdc100.png)

Thanks for reporting tho!
