### ISSUE TITLE
Dashboard Clean Up Before Roll out V1

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4979]
### User Story
As Gitcoin core, we'd like to shore up the first version of the dashboard so that Funders will find this useful.

### Description

Solve the bugs below prior to launching V1 Dashboard

BUG - this bounty shows up twice
http://bits.owocki.com/d6a05870382e/Image%202019-08-02%20at%2011.17.50%20AM.png(184 kB) https://gitcoin.co/issue/gitcoinco/skunkworks/93/3185

BUG - https://gitcoin.co/issue/gitcoinco/web/4112/2734
http://bits.owocki.com/5acc467cf49a/Image%202019-08-02%20at%2011.18.17%20AM.png(81 kB) why does this bounty show 0 applicants when I have 4 people working on it?

UX - when there is no action to take, the whole dashboard dissapears, and we display a no data state.
We should display a message at the top that says: "You're all caught up! Nothing to do at this time."

Open Bounties should stay on the dashboard even if there isn't anything to act on.

![Dashboard - no action (1)](https://user-images.githubusercontent.com/238235/62647435-87cc9580-b91e-11e9-8d88-7393be90f29a.jpg)

![Dashboard - with action (1)](https://user-images.githubusercontent.com/238235/62647440-89965900-b91e-11e9-8be1-fe6aa4b6c653.jpg)

### Definition of Done

- [x] Fix the top 2 bugs

- [ ] When there is no action for the funder to take - Funder is caught up, display a small message at the top of the dashboard and show open bounties (even though they don't need any action).

### Why
we want this dashboard to be useful!

**Comment by octavioamu** [comment]
> UX - when there is no action to take, the whole dashboard dissapears, and we display a no data state.

Actually  the dashboard doesn't disappears what happens is each block have his own empty state, the design is kind of diff of the one proposed had 2 tabs. You can check this in https://gitcoin.co/dashboard

![image](https://user-images.githubusercontent.com/1358093/62981803-a04a1d80-be00-11e9-9933-90fcab4772bd.png)
   

![image](https://user-images.githubusercontent.com/1358093/62981529-d2a74b00-bdff-11e9-8ef4-01329182410a.png)

![image](https://user-images.githubusercontent.com/1358093/62981565-e357c100-bdff-11e9-9d9e-dec68e3446f9.png)

When the bounty is open and has not applicants you get 2 actions not that empty screen (invite, feature bounty)
![image](https://user-images.githubusercontent.com/1358093/62981905-f028e480-be00-11e9-8c1e-29fb663f27e9.png)


There is no way to check in that moment if there is nothing todo, actually the only moment when is nothing todo is when you haven't any bounty funded or applied that shows 0 on top.
there are 2 groups of independent queries  (3 for funders and 3 for contributor) that works totally different. Also the actions are diff 

**Open bounties** have applicants with approve reject, if not applicants it shows featured bounty or invite. 

**Submitted Bounties** have submissions if not, well empty state since there is no action todo. 

**Expired**  hasn't applicants just the extend button or empty. 

So there is not "all done" situation to apply this banner design.

Then the other thing is **contributors tab** has 3 queries and hasn't dropdowns just actions if exist 
 
**Bounties in Progress** action submit work
**Bounty Applied ** action stop work 
**Work Submitted** no actions 

Please @willsputra and @PixelantDesign check what we have in production if you need help seeing the diff cases ping me and I can show you.

**Comment by PixelantDesign** [comment]
How do we display active bounties that are open...?
