### ISSUE TITLE
Unable to Redeem Codefund Kudos

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4994]
**Describe the bug**
Unable to Redeem Eric's Kudos

**To Reproduce**
1) Went to this URL, logged in to Github (Metamask Activated)
2) https://gitcoin.co/kudos/redeem/codefund_influencer_v10
3) Clicked both checkboxes and Redeem
4) Got this screen

<img width="1643" alt="Screen Shot 2019-08-08 at 12 37 09 PM" src="https://user-images.githubusercontent.com/238235/62721093-7dbb9d00-b9d9-11e9-8fb1-cd6a8193605e.png">

**Expected behavior**
To be able to redeem

**Desktop (please complete the following information):**

- OS: Mac
- Browser: CHROME
- Browser Version: Version 75.0.3770.142

**Additional context**

- Other Codefund Clients completing the surveys are unable to redeem the kudos as well.
- Also not sure why it popped 3 alerts.

**Comment by owocki** [comment]
https://sentry.io/organizations/gitcoin/issues/1134826924/?project=1398424&query=is%3Aunresolved&statsPeriod=14d&utc=true

"{'code': -32000, 'message': 'insufficient funds for gas * price + value'}"

**Comment by owocki** [comment]
this is because the bulk transfer coupon needs to pay the gas + purchase price of the kudos redemption.  we need to either:

1.  make https://etherscan.io/address/0x28e21609ca8542Ce5A363CBf339529204b043eDe (eric's account) the `sender_address` and `sender_pk` of the bulk transfer coupon ( https://gitcoin.co/_administrationkudos/bulktransfercoupon/20453/change/ )

or 1. remint the kudos to be owned by gitcoin instead of eric, and re-assign the bulk transfer coupon ( https://gitcoin.co/_administrationkudos/bulktransfercoupon/ ) to the new kudos.

**Comment by octavioamu** [comment]
So sorry I accidentally delete your comment

**Comment by octavioamu** [comment]
Js problem solved, @danlipert is reminting the kudos right now

**Comment by thelostone-mc** [comment]
Closing this out as it's been taken care 🙌
