### ISSUE TITLE
[SEVERE] "Closed" Bounties are listed under "Expired" 

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/web#500]
### Done Mainnet Funded Issues (60 worth 8309.92 USD, 9.68 ETH)

This is really a not-so-well metric / success-rate.

But!

The gitcoin metrics are currently out of order. Look here:

As an example, this issue ethereum/web3.py/issues/430 is listed as "expired" instead of "closed".

So, you should verify each and every "Expired" issue, and see if its possibly a "Closed" one.

Note that this has quite a priority, as this means "false data", which is bad for a public transparent system.

(sidenote: "closed"  should possibly be renamed to something more positive-end sounding, like "Fulfilled")

**Comment by lazaridiscom** [comment]
Great, it seems nobody cares.

**Comment by thelostone-mc** [comment]
@vs77bb @owocki this looks like a valid concern !!

**Comment by owocki** [comment]
> Great, it seems nobody cares.

I think you'd be better served if you did not climb [the ladder of inference](https://www.mindtools.com/pages/article/newTMC_91.htm) so quickly.

> [SEVERE] "Closed" Bounties are listed under "Expired" 

Additionally, I'll remind you that this project is open source, and if the issue is SEVERE as you tagged it, you are welcome to put in a code fix yourself or bounty it.

I am putting this in our `to do` column.

**Comment by owocki** [comment]
just coded up a fix on my local..  here are the status before and after migration

```
before migration:
Expired Mainnet Funded Issues (104 worth 19902.79 USD, 23.02 ETH)
Done Mainnet Funded Issues (61 worth 8542.03 USD, 9.88 ETH)

after migration:
Done Mainnet Funded Issues (144 worth 24986.21 USD, 28.90 ETH)
Expired Mainnet Funded Issues (25 worth 4889.57 USD, 5.66 ETH)
```

**Comment by owocki** [comment]
just applied the fix in prod.  here are the scripts i used => http://bits.owocki.com/0F0z143O2N3l/Archive%202018-02-28%20at%209.36.02%20AM.zip

here is a prod commit 9cf610f28f6fe6b33ea2db54930c533d9c832c71

**Comment by lazaridiscom** [comment]
No "sarcasm", but "disappointment".

I guess I simply stop filing issues in this project.

Feeling unwelcome and my individuality rejected.

Just fix the database, please.

In its current state one cannot look for issues in peace.

**Comment by owocki** [comment]
> No "sarcasm", but "disappointment".

> Great, it seems nobody cares.

"Great" is pretty sarcastic in this context.  As is the inference that no one cares because there was no response in 24 hours.   A better way to word this would be "This seems severe to me.  Anyone else?"

> I guess I simply stop filing issues in this project.

I'd love to have you stick around because I think you care a lot and have good ideas .  But if you can't take constructive feedback about your tone, then I agree - it's better that you stop filling issues.

I'm on slack if you want to talk more.

> Just fix the database, please.

Please see the above fix.

**Comment by lazaridiscom** [comment]
Yeaii!!! @owocki, just saw it:

* Done Mainnet Funded Issues (144 worth 25118.22 USD, 28.90 ETH)
* Expired Mainnet Funded Issues (25 worth 4915.39 USD, 5.66 ETH)

Looks much much better, and you're so fast... Me not good in fast solutions, I usually have to think much. So I guess we would be "complementing skills" or so.

> A better way to word this would be "This seems severe to me. Anyone else?"

You don't give up, teacher, e???

All fine here!!!

(Promise: will work on my tone...)

**Comment by owocki** [comment]
> So I guess we would be "complementing skills" or so.

Amen brother!

❤️ alls well that ends well.. thanks for the bug report + the tough convo :)
