### ISSUE TITLE
As a hackathon participant (funder & contributor), I want a curated flow on how to proceed successfully through the hackathon.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5008]
### User Story

As a hackathon participant (funder & contributor), I want a curated flow on how to proceed successfully through the hackathon.

### Why?

1. As a gitcoin funder, it's not easy to see which team(s) are working on your bounty / prize.

2. As a gitcoin contributor, it's not easy to form teams, express what they want to build, and build together.

3. As a gitcoin funder, I don't have a clear and easy place to see my hackathon submissions.

4. As a gitcoin funder, I don't have a clear and easy place to do judging on my hackathon projects.

5. As a gitcoin funder, payout of my hackathon bounties is very confusing.

There will be a design/UX and build component to each of the above.

### Assumptions

Human - We assume that a curated onboarding flow that is positively directed will simplify and enhance the hackathon experience for both funders and contributors.

Business - We assume by building this feature, funders will have more insight and feel more confident about the submissions they'll be receiving, as per the hackathon feedback we've received from multiple parties about each stage of the process.

Tech - We will need new architecture to support this.

### Workshop

- @frankchen07 to create sub-tickets for the hackathon flow
- use tickets as a kickoff workshop discussion with @alexvotofuture, @PixelantDesign, and @frankchen07 to understand problems
- get UX and design templates for each stage
- review with core team and alex
- begin build cycles
- marketing and surface sharing feature for teams

**Comment by PixelantDesign** [comment]
Ideas:
Require hackers for GitHub orgs and use as teams.

We have a concept of orgs for funders.
shared payment, shared permissions

Bring the concept of organization to funder groups
- Contributor orgs can:
- Apply to work as an org
- Submit work as an org
- Does that mean they will be able to get paid as an organization?

Flow
signup (with github) >
retrieve organizations you own >
pick the organization you want to connect with gitcoin >
users in this organization can manage projects (organizations repos)
for funders > approve, payout
for hunters > apply as a group, edit projects.

**Comment by owocki** [comment]
following this closely... team formation is a pretty high order bit for hackathons

**Comment by owocki** [comment]
the funnel as i see it (each step is probably its own ticket)

1. team formation
2. team management & updates
3. submission
4. judging 
5. payout

**Comment by frankchen07** [comment]
@PixelantDesign - your comment above I believe is for **organizations**, which is different than team formation for hackathons.

@willsputra 

> the funnel as i see it (each step is probably its own ticket)

agree with owocki here that this is somewhat of a loaded ticket. let's focus on the first two steps for this ticket:

1. the page that the contributor visits in order to create, see, and join a hackathon team, and how that ties into the available projects.

2. the page that the funder visits in order to see which teams have been formed, and which of those have begun working on their projects.  

based on this flow, https://app.mural.co/t/consensys3989/m/consensys3989/1563911847026/d5cda0df03c2e49b29992a0f1b5f72842524f4d5

team formation should occur right after onboarding

I'll be opening tickets for each stage in preparation for a workshop early next week

**Comment by frankchen07** [comment]
closing, multiple smaller tickets to chunk down
