### ISSUE TITLE
as a admin of gitcoin, i'd like to integrate blockstack app mining, so i can generate revenue for having users login

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5028]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a admin of gitcoin, i'd like to integrate blockstack app mining, so i can generate revenue for having users login

https://app.co/mining

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Revenue

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No blockstapp app mining

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
blockstapp app mining integration

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
blockstapp app mining integration

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
How does this change the number of logins?  How much revenue does this generate?
### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@PixelantDesign @vs77bb i think we could get to the top of blockstack's leaderboard (which is worth about $20k). probably worth a look.

**Comment by kuhnchris** [comment]
I see two possible problems: 
![grafik](https://user-images.githubusercontent.com/761911/63370757-288d6d00-c383-11e9-906f-d803442a6dc5.png)
* do we have active user DRM in place (as in, unsubscribing, the email exposure issue, etc)?
* and - most obviously - not "updating" the product for a month...

**Comment by ohsix1** [comment]
@kuhnchris As far as I understood, as long as Gitcoin follows Blockstacks take on "users owning their data", then there would be no problem getting app mining up and running. 

Im thinking there would need to be some reworking of Gitcoin so that all user related data is stored with the users themselves. This would mean that Gitcoin would basically do away with the need for the django backend and just focus on the bootstrap front end. It also means that login would be handled through Blockstack.
