### ISSUE TITLE
As a Funder, I'd like to see the latest information on who has submitted or applied to work on my bounty.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5036]
# User Story
As a Funder,  I'd like Gitcoin to clearly surface information I need to decide who I should choose for my bounty.

As a Funder, I'd like to see the latest information on who has submitted work on my bounty.

# Why
It’s too hard for funder to vet quality applicants  because I don’t know who are good people to work on my bounties.

# Assumptions

1. We are assuming that funders want to look for and select their contributors.

2. We are assuming that having the appropriate information to select contributors will keep our funders satisfied and therefore, positively affect retention through an enhanced user experience.

3. Tech - use same logic that exists today

# Definition of Done 
- [ ] Move Accept and Submit sections to the top of the issue details - only Funders and people in their org would see this on the issue details (it can still display publicly on github).
- [ ] Build in a success rate (number of bounties started / bounties completed)
- [ ] Display flyout with additional information - for performance.
- [ ] Review with squad

# Data
* ideally the data tracked should be which contributors were surfaced
* which contributors they selected to approve/accepted submission

# Additional Notes
Gitcoin Match will not be working until keywords and matching are fixed.
Related https://github.com/gitcoinco/web/issues/4888

![discoverability (1)](https://user-images.githubusercontent.com/238235/63287149-9eaca980-c287-11e9-8698-3cb2385a2359.jpg)

**Comment by danlipert** [comment]
Looks good - note that the "people in their org" mention of the first item in the Definition of Done will change based on Andrew's work with syncing the Github permissions for shared manangement

**Comment by PixelantDesign** [comment]
Sounds good. Just to confirm - backend work will change in a future sprint once Andrews part is complete, correct?

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/4714

**Comment by androolloyd** [comment]
While debugging the addition of Organizations, I noticed that there is a mention to the profile.organizations object, originally indicating it was apart of the profile table, it seems to be that the organizations object it references in user_popover.js is an array of interactions on the site, bounties, etc, and the concept is to showcase the logos(i think) of each org that they have worked with.

**Comment by octavioamu** [comment]
@danlipert @thelostone-mc I have some technical questions about the data on that popover. Right now the data is not right because is using activity data:

![image](https://user-images.githubusercontent.com/1358093/63899311-ccee5f80-c9d2-11e9-86f4-bad5f47edb1a.png)

So the problem with activity data is that data is not at state of an application, if you apply to work, stop to work, submit work in the same bounty that actually will be 3 entries in the activity when we actually want the state of the application "work submitted" 

So I believe we can solve this in many ways but I want to discuss since the correct data could be from bounties, but also a lot of queries (?)  

Or maybe we can use the activity but  checking the last activity related to a bounty instead of counting all activities in that bounty?

Then also we have the other bounties a user made and contain the same keywords and the ratings (if exist)  related to that bounty. 

Not sure what will be better

@willsputra There is a "view more..." at the bottom where that goes?

**Comment by danlipert** [comment]
I think what we'll have to do is to go through each Profile's bounties they've interacted with, and check for different types of activity in priority order, then go to the next bounty once the highest priority activity for each bounty has been found. Example:

```
activities = Activity.objects.filter(profile=profile)
bounties = [a.bounty for a in activities]
count_work_completed, count_work_in_progress... etc = 0
for bounty in bounties:
  if Activity.objects.filter(profile=profile, bounty=bounty, activity_type='work_done'):
    count_work_completed++
  elif Activity.objects.filter(profile=profile, bounty=bounty, activity_type='stop_work'):
    count_work_abandoned++
  elif bounty_removed_by_funder: etc...
```

Performance will probably suck but it might be the best we can do because of the logic behind activities being a series of actions that take place over time, and us not having any logic in the backend codebase that orders them properly. We have to do the ordering here by checking for the latest possible activities first and assigning the count for that bounty, then going to the next bounty...

**Comment by octavioamu** [comment]
in that case is not better to just fetch bounties + interest? instead of activity? since also we need to filter the ones related to skills of the current bounty.
something like Bounty.objects.filter(profile=profile)

**Comment by danlipert** [comment]
From our engineering chat:
Dan will add a cronjob to calculate success rate and store in user profile daily
Other data will be loaded directly on mouseover

**Comment by danlipert** [comment]
@octavioamu @thelostone-mc So I ended up with something similar and quick to calculate in #5104 - Its the same calculation that we show in the quarterly stats so I figure we can start there and adjust with a more sophisticated algorithm that we can cache if we need to in the future
