### ISSUE TITLE
As a sponsor of a hackathon prize, I don't exactly know how hackers are approaching the work on my prize (v2)

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5038]
### User Story

As a funder of a hackathon bounty, I'd like to know how hackers are approaching the work on a prize bounty

### Business Problem

Solves tracking from funder perspective, and sets the stage for a better issue details that highlights projects teams

### What 

Create a new customizable hackathon express interest from with the details outlined below.

Another problem that this addresses is for funders to know which team members to payout, when an in-app ability for team formation is created. Thus, when hackers start work / express interest on a hackathon issue, asking for Gitcoin usernames (teammates) would be useful for the sponsors, otherwise the sponsors can't reliably find the right teammates to pay out. 

This will be blocked by 

1. the data bounty changes, since currently if a team starts work and stops work, all the information will be dropped.

2. we don't have a proper way for a group of people to submit work

### Assumptions

Human - We assume that hackers will complete all of this information. We're also assuming that they have previously thought about forming teams and have started on discord.
Business - By adding this new work form, we are hoping that we will get an increased number of submissions at the end of the hackathon.
Tech - Use current work plan display behavior where funder clicks to collapse and expand, to preserve performance.

### Potential Blockers

1. The way interest is currently set up in the bounty states data model affects this ticket. Is there a way to break the interest portion out of the larger bounty states overhaul? (#5102) @danlipert 

2. Previously when we implemented "start work", this was not operable with the original "express interest" in the standard bounties contract v1. With the implementation of standard bounties v2, is there additional thinking with the bounty states data model that we need to understand / implement in order to achieve interoperability with SBv2?

### Definition of Done

This work plan information is to be displayed on issue details. 

- [ ] build a customizable hackathon work form (new type = hackathon)
- [ ] show this express interest form only if the event_id field for the bounty is not null
- [ ] add a required field called Project Name 
- [ ] add a required field called Project Description
- [ ] add an optional field: team members (gitcoin profiles dropdown that can handle selecting multipel gitcoin profiles)
- [ ] **add an optional field called "Discord Handle" for entering their discord handle, have link text there that says "Don't have a Discord? Sign up" (links to gitcoin hackathon discord)**
- [ ] remove logo upload (simplifies technical complexity)

### Mockup

<img width="1002" alt="Screen Shot 2019-08-20 at 10 05 45 AM" src="https://user-images.githubusercontent.com/238235/63354268-26e78900-c332-11e9-8839-dc109daf7708.png">

**Comment by octavioamu** [comment]
how the project submission address the problem? **How do we 3x the # of final submissions in a future hackathon?**

**Comment by alexvotofuture** [comment]
The idea is to show hackathon projects people are working on directly within the Gitcoin platform so other hackers can see the projects and get involved as they're browsing prizes, rather than having to go to Discord or a separate page. The form would include information to help people get involved and join the team (Discord channel name, Github repo link, Gitcoin usernames of the teammates, etc.), and hopefully make it more easy to see what people are building than browsing Discord.

This also would help sponsors see all the projects that have been started for their prize right on the prize details page.

Content would need to be editable (so that teams can keep the work plan updated), and I think we should have a way to select whether to make the plan private just to the funder or to make it public so other hackers can see the plan and join.

The same form could be edited one last time as people submit their final project, locking in details like teammates' Gitcoin usernames and the final PR/Repo link, along with the summary of the project and other details.

Octavio: This could eventually perform a similar function to the Hackathon results WP site you created, but inside of Gitcoin. This ticket is an exploration of which would provide an easier experience for hackers to share this information. The results page already works well, but there might be a benefit to having this info live on the Gitcoin platform so that it feels native. Want to hear your thoughts on this, and the tradeoffs of putting it into the platform itself (I know speed of implementation is one drawback, especially since the separate results page already works).

**Comment by danlipert** [comment]
I'll rate this an 8 given we don't know much about the final spec and design

**Comment by PixelantDesign** [comment]
Will Github allow us to edit the workplans?

**Comment by frankchen07** [comment]
the tradeoff here: better user experience (no onboarding disruptions) versus more of a headache for gitcoin core to later match up discord usernames with github usernames and projects.

from a product perspective, we're more inclined to make the user experience a smooth one, which means we make the discord handle field non-required and find a workaround solution to ask folks to join discord and match discord names to github usernames.

**Comment by octavioamu** [comment]
Now I realised there is a security problem @frankchen07 only users owners of the profile can add the discord username because we can let others edit profile informations.
Since this will open the option to people change personal data from others, example:
 I can go to apply just say pixelant is on my team and with that change your discord username on the db

My suggestion is:

Sent an email for the team members asking to add their discord if they didn't yet.
Each time user A applies with member B C, they will receive an email
"User A had applied to work with you as part of his team, {if not discord is found on the profile} please follow the link to add your discord username"

**Comment by octavioamu** [comment]
Also we need a rule "if someone is already on a team application that someone can't be in another team or alone" 
Because that can be dangerous, again User A alone applies and won,  then User B create a Team with A inside. Then the sponsor will payout and can get confuse and payout B

**Comment by frankchen07** [comment]
kevin made a PR to work off of here: https://github.com/gitcoinco/web/pull/5210

**Comment by frankchen07** [comment]
building on top of related PR: https://github.com/gitcoinco/web/pull/5210

**Comment by frankchen07** [comment]
@frankchen07 - the scope of this ticket (where this information is stored) affects how the rest of the ticket (aside from discord is coded up), discord PR is currently stored in the profile

perhaps the information we want should be developed with team formation, which may end up a a separate data model from interest. 

frank to make sure that the principle (value that's guiding our behavior) is a true need from hackathon contributors, research pending!
