### ISSUE TITLE
Gitcoin Product Updates

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#5057]
<h3>Multi-Collateral Dai Support is Live!</h3>
<p>Hello from the Gitcoin team - we are pleased to announce that support for the new Multi-Collateral Dai token is now live on our platform.</p>
<p>If you haven't heard, MakerDAO launched a new version of their Dai token recently, and you can now use it on Gitcoin. To use the new version of Dai here on Gitcoin, click <a href="https://gitcoin.co/settings/tokens">here</a> to go to your token settings, then select DAI and click Enable. For more info on everything thats happening with Dai, along with instructions and tools to help you transition to the new token, check out MakerDAO's upgrade guide <a href="https://blog.makerdao.com/looking-ahead-how-to-upgrade-to-multi-collateral-dai/">here</a>.</p>

**Comment by octavioamu** [comment]
test

**Comment by willsputra** [comment]
@frankchen07 @PixelantDesign 
I can adapt this content below for the modal. Take a quick look below and see if we want to add/remove anything?
https://docs.google.com/document/d/1Loya0ZvM_IRNuPqIZDaU5och_SCP-mrHpD_pepwVy-4/edit?usp=sharing

@octavioamu if the content is long, would the modal get really tall or is it scrollable?

**Comment by frankchen07** [comment]
# DRAFT 2019-09-23

<p>Hello from the Gitcoin team! Here’s what the core team and our community have been busy working on in the last few weeks.</p>

<p>Among the most recent releases are a new and enhanced CLR matching view for Gitcoin Grants, a new start work form that captures Discord usernames, and a nifty view on the contributor dashboard for new bounty matches! There are also two releases that are less obvious - one being the release of a new CLR matching mechanism, pairwise matching. The second one is more of a test for Gitcoin administrators - a powerful bulk invite feature that will be tremendously useful to funders. We'll get that to you soon!</p>

<p>Check out these new improvements that will help you grow open source!</p>

<h2>Gitcoin Grants CLR Round 3</h2>

<p>We've been heads down on a new CLR matching mechanism, and we're happy to announce that with Vitalik's help, we've launched a pairwise matching mechanism that hopefully reduces collusion. We're tracking the results closely and we're excited to see how it goes.</p>

<p><a href="https://gitcoin.co/grants/">Check it out here</a> - you can see how much your contribution is worth, and an estimate on what the current matches are. You can also view the expected match on the fund contribution page!</p>

<img src="https://user-images.githubusercontent.com/7516920/65475955-3036aa80-de36-11e9-8be1-68831422e7cc.png">

<img src="https://user-images.githubusercontent.com/7516920/65475974-40e72080-de36-11e9-9be0-7c18caf24837.png">

<p>We've also added something called "phantom funding" to this CLR round. With this, you can signify grants that you want to support, and at the end of the period, Gitcoin will provide and split 5 DAI across the grants that you signaled. The resulting contribution and the CLR match from the phantom signal would be contributed to the grant!</p>

<img src="https://user-images.githubusercontent.com/7516920/65475981-4c3a4c00-de36-11e9-8bce-db55f865fd50.png">

<h2>Start Work Form</h2>

<p>We're asking for your Discord username in order to facilitate team creation for the hackathon, and it allows us to get better statistics to our hackathon sponsors. All of this culminates into a better experience for you and the hackathon sponsors. It's a win win for everyone!</p>

<img src="https://user-images.githubusercontent.com/7516920/65476031-6f64fb80-de36-11e9-92e8-8a13fbbfde9e.png">

<h2>Contributor Dashboard Matching Bounties</h2>

<p>We hope, as a contributor, you'll appreciate that the dashboard we've provided helps you keep tabs on your bounties, but what's even better is a dashboard that helps you keep track of your bounties, and introduces you to new ones that match your skillset! There are now additional bounty matches that you can view to continue your work streak on Gitcoin. Grow open source and get paid. Dope.</p>

<img src="https://user-images.githubusercontent.com/7516920/65476078-93c0d800-de36-11e9-9485-a9421eb9aa13.png">

<b>Have a feature in mind that’ll power your workflow?</b> Let us know! We love to hear suggestions from our community. Happy Gitcoining!

**Comment by frankchen07** [comment]
# DRAFT 2019-10-28

<p>Hello from the Gitcoin team! Here’s what the core team and our community have been busy working on in the last few weeks.</p>

<p>We're going to rattle off the biggest changes machine gun style, and then we'll be talking a little more in depth about them!</p>

<ol type="1">
    <li>Gitcoin Grants CLR Round 3</li>
    <li>Gitcoin Quests</li>
    <li>Gitcoin Profiles v2 & New Profile URLs</li>
    <li>Github Username Changes</li>
    <li>Revamped Hackathon Registration Flow</li>
    <li>Self-serve Kudos</li>
</ol>

<h2>Gitcoin Grants CLR Round 3</h2>

<p>As many of you know, we've released the results of the latest CLR round. This time we were working with Vitalik to implement the new pairwise matching mechanism to fund open source projects. The results are up, and we couldn't be more excited for what it means for the future of open source.</p>

<p>You can find the Gitcoin reported results <a href="https://gitcoin.co/blog/gitcoins-q3-match/">here</a>. In addition to that, Vitalk wrote a <a href="https://vitalik.ca/general/2019/10/24/gitcoin.html"> blog post</a> on the results of the quadratic funding, compared to the results of previous rounds. He raises some interesting points on the meta-view of project funding, as well as comparisons to how pairwise matching performs in relation to normal quadratic funding that was implemented in rounds before. Payouts are proceeding as we speak, so congratulations and thank you for everyone who participated!</p>

<img src="https://user-images.githubusercontent.com/7516920/67724933-e6456500-f99d-11e9-97a7-40ea725d29d9.png">

<h2>Gitcoin Quests</h2>

<p>We've released an interesting, gamified way of learning about the web3 ecosystem. It's called <a href="https://gitcoin.co/quests/"> Gitcoin Quests</a>. There are beginner, intermediate, and expert quests that can be completed! There's also a place to create quests for review by the internal time that allows the maintainers of open source to host interesting, relevant content on Gitcoin Quests. Quests was designed to educate, inspire, and entertain web2 and web3 developers alike. It was designed to guide users to their 'a-ha' moments about cryptocurrency, decentralization, and the potential of a free and open source financial system. We're looking forward to guiding community members through an engaging learning experiment!</p>

<img src="https://user-images.githubusercontent.com/7516920/67725155-91561e80-f99e-11e9-8f97-c5f0f9a5dace.png">

<img src="https://user-images.githubusercontent.com/7516920/67725156-91561e80-f99e-11e9-9a27-45fd116f229e.png">

<h2>Updated Gitcoin Profile & Profile URLs</h2>

<p>We now have augmented profiles and profile links to your Gitcoin profile. This is in preparation for the hope that your Gitcoin profile will be the home of your open source portfolio. You can find your unique profile at `gitcoin.co/<your profile name>`. We also have a couple of new metrics and tabs that elucidate the Kudos's (Kudi?) you've earned, your Gitcoin activity, participation on bounties, and leaderboard rank compared to others! We're especially proud of some of the summary metrics up top. As a funder, you'll eventually be able to filter by these metrics, along with skills to target specific contributors!</p>

<img src="https://user-images.githubusercontent.com/7516920/67724938-e9405580-f99d-11e9-9145-298c4b2cf06d.png">

<h2>Ability to Change Your Github Username</h2>

<p>You can now change the Github account that is connected to you Gitcoin profile by navigating to Settings > Account > Account Preferences.</p>

<img src="https://user-images.githubusercontent.com/7516920/67724896-c0b85b80-f99d-11e9-852b-e24bde917a20.png">

<h2>Revamped Hackathon Registration Flow</h2>

<p>We've revamped the hackathon registration flow for the Web3 World hackathon. You'll see a tidier landing page, as well as a more straightforward flow for registration, either from the landing page, or from the hackathon explorer itself. It might not seem like much, but internally, it makes data collection much cleaner and really simplifies the process behind the scenes so Gitcoin Core can serve our hackers and sponsors better. This sets us up nicely to help sponsors understand how their prizes are performing, and opens up alot of avenues for communication and continuining the hacker relationship!
</p>

<img src="https://user-images.githubusercontent.com/7516920/67725028-24428900-f99e-11e9-8eca-fab030b20ed6.png">

<img src="https://user-images.githubusercontent.com/7516920/67725071-518f3700-f99e-11e9-9ea1-e35822cbf00e.png">

<h2>Self-serve Kudos</h2>

<p>Minting new Kudos is now self-serve over <a href="https://gitcoin.co/kudos/new"> here</a>. This means if you have Kudos you want to put on the marketplace, all you've got to do is fill out of a form, add your artwork, and watch it make its way to the Gitcoin Kudos marketplace!</p>

<img src="https://user-images.githubusercontent.com/7516920/67725038-29073d00-f99e-11e9-863f-c0f8206e22c8.png">

<b>Do you have a feature or improvement in mind that’ll power your workflow? Let us know! We love to hear suggestions from our community. Happy Gitcoining!</b>

**Comment by danlipert** [comment]
<h2>Archived 11/18/19</h2>

<p>Hello from the Gitcoin team! Here’s what the core team and our community have been busy working on in the last few weeks.</p>

<p>We're going to rattle off the biggest changes machine gun style, and then we'll be talking a little more in depth about them!</p>

<ol type="1">
    <li>Gitcoin Grants CLR Round 3</li>
    <li>Gitcoin Quests</li>
    <li>Gitcoin Profiles v2 & New Profile URLs</li>
    <li>Github Username Changes</li>
    <li>Revamped Hackathon Registration Flow</li>
    <li>Self-serve Kudos</li>
    <li>Self-serve Grants</li>
</ol>

<h2>Gitcoin Grants CLR Round 3</h2>

<p>As many of you know, we've released the results of the latest CLR round. This time we were working with Vitalik to implement the new pairwise matching mechanism to fund open source projects. The results are up, and we couldn't be more excited for what it means for the future of open source.</p>

<p>You can find the Gitcoin reported results <a href="https://gitcoin.co/blog/gitcoins-q3-match/">here</a>. In addition to that, Vitalk wrote a <a href="https://vitalik.ca/general/2019/10/24/gitcoin.html"> blog post</a> on the results of the quadratic funding, compared to the results of previous rounds. He raises some interesting points on the meta-view of project funding, as well as comparisons to how pairwise matching performs in relation to normal quadratic funding that was implemented in rounds before. Payouts are proceeding as we speak, so congratulations and thank you for everyone who participated!</p>

<img src="https://user-images.githubusercontent.com/7516920/67724933-e6456500-f99d-11e9-97a7-40ea725d29d9.png">

<h2>Gitcoin Quests</h2>

<p>We've released an interesting, gamified way of learning about the web3 ecosystem. It's called <a href="https://gitcoin.co/quests/"> Gitcoin Quests</a>. There are beginner, intermediate, and expert quests that can be completed! There's also a place to create quests for review by the internal team that allows the maintainers of open source to host interesting, relevant content on Gitcoin Quests. Quests was designed to educate, inspire, and entertain web2 and web3 developers alike. It was designed to guide users to their 'a-ha' moments about cryptocurrency, decentralization, and the potential of a free and open source financial system. We're looking forward to guiding community members through an engaging learning experiment!</p>

<img src="https://user-images.githubusercontent.com/7516920/67725155-91561e80-f99e-11e9-8f97-c5f0f9a5dace.png">

<img src="https://user-images.githubusercontent.com/7516920/67725156-91561e80-f99e-11e9-9a27-45fd116f229e.png">

<h2>Updated Gitcoin Profile & Profile URLs</h2>

<p>We now have augmented profiles and profile links to your Gitcoin profile. This is in preparation for the hope that your Gitcoin profile will be the home of your open source portfolio. You can find your unique profile at gitcoin.co/your_profile_name. We also have a couple of new metrics and tabs that elucidate the Kudos's (Kudi?) you've earned, your Gitcoin activity, participation on bounties, and leaderboard rank compared to others! We're especially proud of some of the summary metrics up top. As a funder, you'll eventually be able to filter by these metrics, along with skills to target specific contributors!</p>

<img src="https://user-images.githubusercontent.com/7516920/67724938-e9405580-f99d-11e9-9145-298c4b2cf06d.png">

<h2>Ability to Change Your Github Username</h2>

<p>You can now change the Github account that is connected to you Gitcoin profile by navigating to Settings > Account > Account Preferences.</p>

<img src="https://user-images.githubusercontent.com/7516920/67724896-c0b85b80-f99d-11e9-852b-e24bde917a20.png">

<h2>Revamped Hackathon Registration Flow</h2>

<p>We've revamped the hackathon registration flow for the Web3 World hackathon. You'll see a tidier landing page, as well as a more straightforward flow for registration, either from the landing page, or from the hackathon explorer itself. It might not seem like much, but internally, it makes data collection much cleaner and really simplifies the process behind the scenes so Gitcoin Core can serve our hackers and sponsors better. This sets us up nicely to help sponsors understand how their prizes are performing, and opens up alot of avenues for communication and continuining the hacker relationship!
</p>

<img src="https://user-images.githubusercontent.com/7516920/67725028-24428900-f99e-11e9-8eca-fab030b20ed6.png">

<img src="https://user-images.githubusercontent.com/7516920/67725071-518f3700-f99e-11e9-9ea1-e35822cbf00e.png">

<h2>Self-serve Kudos</h2>

<p>Minting new Kudos is now self-serve over <a href="https://gitcoin.co/kudos/new"> here</a>. This means if you have Kudos you want to put on the marketplace, all you've got to do is fill out of a form, add your artwork, and watch it make its way to the Gitcoin Kudos marketplace!</p>

<img src="https://user-images.githubusercontent.com/7516920/67725038-29073d00-f99e-11e9-863f-c0f8206e22c8.png">

<h2>Self-serve Grants</h2>

<p><a href="https://gitcoin.co/grants/new"> Gitcoin Grants</a> is now self-serve and public! This is super exciting. This means, if you're a great contributor, you can apply for a Grant to get recurring funding to work on your favorite open source projects. Previously, we were taking Grant applications on a invite-only basis, but now it's open.</p>

<img src="https://user-images.githubusercontent.com/7516920/67790640-5520cd80-fa33-11e9-9bb7-773c18aeb523.png">
<img src="https://user-images.githubusercontent.com/7516920/67790642-5651fa80-fa33-11e9-9202-46d2ab818b6d.png">

<b>Do you have a feature or improvement in mind that’ll power your workflow? Let us know! We love to hear suggestions from our community. Happy Gitcoining!</b>
