### ISSUE TITLE
DESIGN - Display Match on Contributor Dashboard

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5075]
### User Story

DESIGN - Build Display Match on Contributor Dashboard

As a Gitcoin Contributor I'd like my matched bounties to be displayed on the dashboard to surface interesting projects that I could potentially work on.

As a funder I'd like contributors to see my bounties that match their skills on the dashboard so that I can automatically have developer flow into my bounties.

### Assumptions
Human - We assume contributors would want this feature on the dashboard
Business - We assume that if we build this, funders would have more dev flow into their bounties
Tech - We assume that we will need to build a new view or filter by skills on issue explorer.

### What 
Build Display Match on Contributor Dashboard

### Definition of Done
- [ ] Build display of bounty matches on the contributor dashboard
- [ ] Refer to mockup to be provided

![contributor dashboard](https://user-images.githubusercontent.com/238235/64256870-4960d100-cef2-11e9-9c59-f6c0adf3f1b8.jpg)

**Comment by owocki** [comment]
a few Qs:
- what is 'express interest'? why not make the CTA into something that our platform does? how about 'start bounty'??
- when do we want to actually link the dashboard in  the nav and start showing it off?
- is there a funder dashboard version of this, such that funders can view contributors for their bounties?
- how often do the bounties on this list cycle through? as a coder ill stop paying attention to this module if it just always shows the same bounties.

**Comment by frankchen07** [comment]
a few Qs:

> what is 'express interest'? why not make the CTA into something that our platform does? how about 'start bounty'??

if the bounty is approval only - express interest is the way the contributor would submit a work plan and apply. if it's non-approval, then it's "start bounty" - we could just make the CTA "start work".

> when do we want to actually link the dashboard in the nav and start showing it off?

it's live already 

> is there a funder dashboard version of this, such that funders can view contributors for their bounties?

yes its part of the funder dashboard

> how often do the bounties on this list cycle through? as a coder ill stop paying attention to this module if it just always shows the same bounties.

the dashboard should have three sections (bounties in progress, applied, work submitted), so depending on the status it should show up in the correct section.

**Comment by frankchen07** [comment]
@willsputra how is this progressing? if the design is complete feel free to post it here so the build can proceed!

**Comment by willsputra** [comment]
@octavioamu updated with the same design as the other sections as you recommended, since it would be simpler to build and we don't really have space for the sidebar.

could we make it look slightly different though (see the blue background on the header and the tags)? we want to make it easy for users to distinguish between their own bounties (in progress, applied, submitted) and matching bounties.

cc @frankchen07 

![contributordashboard-matching](https://user-images.githubusercontent.com/19514207/64749787-67a97b00-d549-11e9-8c60-1a6eaa917526.jpg)

**Comment by octavioamu** [comment]
@willsputra I like visually but I see some designs problems going in this way. Originally we started with some dashboard design with separated areas, then we planned a minimal version for first release. The problem I see is going without separate areas and just section doesn't escalate very well.
Elements fight for hierarchy and sometimes what is on the first section is not what the user want to see, also the match query need to be separated from this bounties you are working because the screen will take a lot of time to load.
On the future I believe we will be adding more data, favourites, grants, kudos stuff, new features /sections, etc and that will make impossible to manage in a design way and technically inviable.

The only way I see this is creating a logic architecture with tabs or buttons opening the diff areas and having (on future) a main area with general stats like actually other dashboards. 

- Funders
   - Main future area (graph and general stats)
   - bounties
   - other areas

- Contributors  
   - Main future area (graph and general stats)
   - bounties
   - Matching 
   - other areas

- Grants 
   - grants contributions
   - grants owned

**Comment by octavioamu** [comment]
Architecture proposal:

![Desktop HD](https://user-images.githubusercontent.com/1358093/64875748-1621ee80-d624-11e9-92cc-4f7f6b55f5f1.jpg)

**Comment by frankchen07** [comment]
@octavioamu - appreciate the thinking ahead. the idea for this ticket was as an iterative test to see how seeing your matched bounties works on the dashboard. We want to avoid scope creep in this case, since we're now running additional elements (tabs, etc) into the dashboard. The dashboard is supposed to be the clear, easy place for actions, and we don't want to muddle that.

@willsputra - is it possible to cut down on the horizontal "space"? (Alisa linked in Slack) - Will will also be syncing with @octavioamu for ideas.

**Comment by octavioamu** [comment]
@frankchen07 exactly because need to be clear I believe having an easy architecture is fundamental to help the users understand, Adding a new section mixed with the bounties you are working is not going to be clear, also will be on the deep bottom of that page scroll and very heavy to fetch (we already having issue fetching the last request on the dashboard "explorer")  So I don't see how we can add a new and heavy request to that screen.

**Comment by frankchen07** [comment]
issues that still exist - constraints to design around:

1. regardless of design, the request is heavy, too many requests on that page
2. not over-tabulate and preemptively  overhaul the dashboard

**Comment by owocki** [comment]
what was the performance issue that came up for this during estimation?

**Comment by sarawut8128** [comment]
ช่วยแก้ไขและแนะนำถึงวิธีใช้งานที่ถูกต้องแก่ผม

**Comment by octavioamu** [comment]
Blocked that user since is making random comments in our issues in Thai

**Comment by frankchen07** [comment]
@owocki 

> performance issue

octavio mentioned in the comment above that having new section mixed with bounties won't be clear, and it would be heavy to fetch and would cause a deep scroll on the dashboard. 

> constraints to design around

there is octavio's mentioned constraint above, balanced with his suggestion that we can consider tabs, but my thinking was the addition of tabs will defeat the purpose of a simplified dashboard, and would largely increase the scope of this ticket

> sidebar

will's design solution was to have the matches show up on the side (in a sidebar) instead of another section, but that crowds the space on the page, and interferes with "good design"

the state right now is trying to balance these constraints, keeping an eye on solving the problem, which is finding a good place to surface more relevant bounties for our contributors

**Comment by willsputra** [comment]
@frankchen07 @octavioamu 

throwing another rough idea here, based on these considerations:
1. if possible, we don't want to hide matching bounties in another page since we want it to be easily accessible.
2. related to point 1, it might take some time for us to plan the structure of the tabs/sections (out of this ticket's scope), depending on what additional stuff we want to add to the dashboard in the future.
3. heavy query. we'll only fetch the matching bounties once the user clicks on 'View Matching Bounties'.

![matching](https://user-images.githubusercontent.com/19514207/65138408-84f4b280-da3d-11e9-8bb9-c606cfb0692b.jpg)

we can brainstorm and discuss this together further :)

**Comment by frankchen07** [comment]
@PixelantDesign to finalize designs with @willsputra (spacing & copy of the bar & link to settings page)

@frankchen07 to keep tabs on how this is performing via google tag manager

**Comment by willsputra** [comment]
TODO:
• change button label from 'Express Interest' -> 'View Details'
• show skills on the blue bar - 'Here are some bounties matching your skills: Javascript, HTML..."
• add link to settings for people to change skills
• add link to view more bounties on the issue explorer
• on each bounty row, indicate if the bounty belongs to a hackathon

@octavioamu maybe order bounties by event first? (prioritize hackathon bounties)

**Comment by willsputra** [comment]
@frankchen07 @octavioamu updated based on yesterday's discussion
![matching](https://user-images.githubusercontent.com/19514207/65198900-7519b480-dab7-11e9-9db8-a5b562e94aea.jpg)

**Comment by octavioamu** [comment]
Great, how do you want the empty state to look?

**Comment by willsputra** [comment]
@octavioamu how about this?
cc @frankchen07 @PixelantDesign 
![matching](https://user-images.githubusercontent.com/19514207/65234337-f5b3d180-db06-11e9-911e-16d28ef116d6.jpg)
