### ISSUE TITLE
DESIGN - As a funder, I'd like to be know how to co manage **payment** of a bounty with my team members.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5130]
### User Story

As a funder, I'd like to be know how to co manage **payment** of a bounty with my team members.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: Market validated customer need. Currently there is no ability to co manage the payout of bounties with team members at this time.

### Description

**New Feature: Shared Payment**

This feature addresses only one of two parts to allow funders to share bounty permissions and share bounty payment.

- Build the Mockup  a how to use shared management and shared payment intro screen

### Definition of Done

- [ ] - Build the front-end experience of a how to use shared payment intro screen - this looks to be the org management screen

### Data Requirements
- [ ] data metrics tbd based on the experience created
- [ ] funder retention could increase since this was a highly requested feature.

### Additional Information
https://github.com/gitcoinco/web/issues/4843
https://github.com/gitcoinco/web/issues/4954

**Comment by frankchen07** [comment]
@willsputra - did you say you had a design for this, and would add it to this ticket?

**Comment by willsputra** [comment]
@PixelantDesign @frankchen07 
![shared payout](https://user-images.githubusercontent.com/19514207/64546036-11271b80-d354-11e9-9ab4-5b33e6c26c30.jpg)

**Comment by frankchen07** [comment]
lookin' good - some quick feedback:

we can remove the side bar rockets, I think it's kind of distracting.
![Screen Shot 2019-09-09 at 14 46 44](https://user-images.githubusercontent.com/7516920/64568888-c801a800-d310-11e9-849c-8c43fbec5401.png)

this copy is okay for now, I'd add an indent for the bullets.
![Screen Shot 2019-09-09 at 14 47 03](https://user-images.githubusercontent.com/7516920/64568905-d64fc400-d310-11e9-94a4-a07a1c06dc89.png)

does every admin / member have an info bubble? seems a little repetitive. I was thinking maybe the first two, but then it's inconsistent.
![Screen Shot 2019-09-09 at 14 49 27](https://user-images.githubusercontent.com/7516920/64569009-17e06f00-d311-11e9-933e-6cd74712850d.png)

nit copy change "organization permissions"
![Screen Shot 2019-09-09 at 14 47 21](https://user-images.githubusercontent.com/7516920/64568920-e2d41c80-d310-11e9-8d1a-57d851b252ff.png)

**Comment by willsputra** [comment]
@frankchen07 the rockets already exist in the current Manage Settings page. do we want to remove them?

(i kinda agree that removing the rockets would make the whole page cleaner!)

<img width="1660" alt="Screenshot 2019-09-12 10 43 07" src="https://user-images.githubusercontent.com/19514207/64749973-28c7f500-d54a-11e9-9eb8-00b02cb316be.png">

**Comment by frankchen07** [comment]
@willsputra  agree with removing the rockets on the settings page too to clean it up

**Comment by danlipert** [comment]
I've got some notes here based on the technical implementation:
- First off, I wonder if we need to have the role information and popover shown at all? Its my understanding that the permissions are binary, in that people who have write access to your org/repo can control the bounties, and those who don't cannot. We have the role information in our database but I'd like to see more consideration of what is most effective for role-based permissions differences here.
- Secondly, doing a separate sync for one user isn't really feasible since we have to sync each user on the platform at once to figure out what the permissions are. For example, if I sync my account, then I know what orgs/repos I have access to, but to know which of my teammates will share access to my bounties, I need to sync their accounts as well. We currently have a backend task for this that will run multiple times a day to refresh this information for each user on the platform.
- Lastly, regarding whether or not this is an "opt-in" experience - we will be manually revoking each user's access token once this goes live, and then once they login again the new permission will be added to their Github access token and they'll see the 4th screen shown above. Whether or not this information is shown to each user can be behind a button, but we'll still be collecting the data, and its easier to just enable the new features for everyone across the board rather than feature flag it.

**Comment by willsputra** [comment]
@danlipert thanks for the feedback! :)

> * First off, I wonder if we need to have the role information and popover shown at all? Its my understanding that the permissions are binary, in that people who have write access to your org/repo can control the bounties, and those who don't cannot. We have the role information in our database but I'd like to see more consideration of what is most effective for role-based permissions differences here.

Gotcha, will explore more on how to display the info effectively.

> * Secondly, doing a separate sync for one user isn't really feasible since we have to sync each user on the platform at once to figure out what the permissions are. For example, if I sync my account, then I know what orgs/repos I have access to, but to know which of my teammates will share access to my bounties, I need to sync their accounts as well. We currently have a backend task for this that will run multiple times a day to refresh this information for each user on the platform.
> * Lastly, regarding whether or not this is an "opt-in" experience - we will be manually revoking each user's access token once this goes live, and then once they login again the new permission will be added to their Github access token and they'll see the 4th screen shown above. Whether or not this information is shown to each user can be behind a button, but we'll still be collecting the data, and its easier to just enable the new features for everyone across the board rather than feature flag it.

Just to clarify, so the permissions will be asked during the initial Gitcoin login right? Which means we don't need to ask them again on orgs onboarding?

**Comment by willsputra** [comment]
@danlipert if the permissions are binary, should we just show the people who have write access?

**Comment by willsputra** [comment]
@frankchen07 @danlipert updated based on today's discussion
![sharedpayout](https://user-images.githubusercontent.com/19514207/65062783-621bbd00-d9af-11e9-9c83-396a00b9cfcb.jpg)

**Comment by octavioamu** [comment]
@willsputra can you post the sketch file?

**Comment by willsputra** [comment]
@octavioamu sketch file:
https://github.com/gitcoinco/creative/blob/master/Product/Shared%20Management/Shared%20Management%20-%20Milestone%20I%20and%20II.sketch
