### ISSUE TITLE
BUILD - As a Gitcoin funder, I want an organizations view page

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5203]
### User Story

BUILD - As a Gitcoin funder, I want an organizations view page.

### Why Is this Needed

funder-requested need

### Description

view organizations like I can view someone's profile

### Current Behavior

no organizations view

### Expected Behavior

build out the front-end view of organizations

### Definition of Done
- [ ] front end built out to design specifications

### Design
https://github.com/gitcoinco/web/issues/4576

**Comment by octavioamu** [comment]
@frankchen07 seems the design ticked had some movement and some data had changed on production, maybe this will need some work from @willsputra until get ready to be coded.

**Comment by frankchen07** [comment]
I believe @owocki already coded this up.

> some data had changed on production

what specifically changed here?

**Comment by octavioamu** [comment]
@frankchen07 Yes with "some data had changed" I mean Kevin did some changes and added groups of new informations on that page http://gitcoin.co/profile/gitcoinco And now the design doesn't satisfy the new data loaded on that page.

**Comment by owocki** [comment]
i made a good faith effort at getting the data added to the org profile on my ticket (live exaple: https://gitcoin.co/profile/gitcoinco/people ) but the prod stuff still doesnt have wills design applied

**Comment by frankchen07** [comment]
update: @willsputra to take a look to see what portions of his designs have been implemented or not, given new metrics

**Comment by willsputra** [comment]
@frankchen07 @octavioamu  did some small tweaks to the tabs based on the current deployed version. let me know your thoughts!

1. 'Active Bounties' sounds ambiguous (do bounties that are on 'Work Started' fall here?). Maybe 'Open Bounties' is clearer for contributors who want to look for open bounties in an org.

![Orgs-OpenBounties](https://user-images.githubusercontent.com/19514207/65970852-d3706b00-e499-11e9-97b6-3bd8fb8e29b1.jpg)

2. I combined 'Core Team' and 'Leaderboard' into one tab last time, but @octavioamu as you mentioned it might be confusing to put them together, maybe we can separate those.

![Orgs-Team](https://user-images.githubusercontent.com/19514207/65970998-1c282400-e49a-11e9-8a8b-f68a8bbd51fd.jpg)
![Orgs-Leaderboard](https://user-images.githubusercontent.com/19514207/65970996-1c282400-e49a-11e9-824d-db5235ca06a1.jpg)

**Comment by frankchen07** [comment]
@willsputra 

1. is there a design for the activity tab? or do we want to keep the activity as an element under the top square (below the company info and above the tabs) and not let it have it's own tab?

2. does the "update header photo" and "update" on the logo show up all the time, or only when it's hovered over?

3. The follow button seems quite large, and perhaps in a little bit of an awkward place. The way the gitcoin.co/profile/gitcoinco currently is with the metrics right aligned looks better to me, but perhaps there's a design reason for having it more centered? If the follow button was placed elsewhere and re-sized, how would you do it? What happens when someone "follows"?

4. open bounties for now is fine, I'd restrict over designing it without plentiful user feedback

5. "#6 on the Leaderboard?" (add the), I think it sounds better. Also, if the leaderboard is technically in a tab, do we still need the "view" link under organization rank?

**Comment by willsputra** [comment]
@frankchen07 thanks for the feedback!

1. The current deployed design of the Activity tab looks fine for now, so I think we can keep that. It probably should still have its own tab since the activity list is super long.

2. I think it should show up all the time if you're the owner of the page, since the actual photos would be less important for you than knowing that you can change it (it's also good to encourage people to check out the new avatar stuff and profile headers!)

3. Let me play around with it a bit more. Wanted to put the left-align the 'Follow' button but then we're left with so much empty space in the top box. I don't think we have a "Follow" feature yet (although I think there were some discussions in the past) so this one will probably be skipped on this version.

4. Agreed.

5. Agreed on adding "the". The "Contributor Leaderboard" tab and org rank are two different metrics actually. The former is the rank of contributors contributing to that org (=which contributors worked on the most bounties), while the latter is the rank of the orgs relative to other orgs (=how much has this org spent compared to other orgs). I can see how the confusion might arise though, will try to fix it.

**Comment by frankchen07** [comment]
1. sounds good
2. sounds good
3. sounds good
5. ah I mixed up that small detail re: contributor and org leaderboard.

**Comment by willsputra** [comment]
updated based on the feedback above
![Orgs-Leaderboard](https://user-images.githubusercontent.com/19514207/66844275-a09d9b00-efa0-11e9-811d-0193be66fd1b.jpg)

**Comment by frankchen07** [comment]
I like the changes. The leader board makes it clear, and the follow button makes more sense here. 

Anyone else have any additional comments before we upgrade the build?
