### ISSUE TITLE
As a hackathon admin, how can I get mailing list signups before and during a hackathon event?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5237]
### User Story

As a hackathon admin, how can I get mailing list signups before and during a hackathon event?

### Why is this needed?

We currently cannot distinguish contributor logins as those who are interested/have intent in an ongoing hackathon, unless they perform a work action (participate). Completely capturing mailing list signups:

1. captures interest before a hackathon starts
2. allows Gitcoin to update hackathon members during a specific hackathon
3. allows Gitcoin to provide accurate post-hackathon statistics to their sponsors (was the hackathon successful)

### Description

We have data coverage for the hackathon currently broken down:

1. Aggregate metrics on Google Analytics as to the funnels and dropoffs
2. We know who has started, submitted, and stopped work (participated).
3. We do not know who logged in / joined with the intent of working on hackathon issues (but have not yet performed a work action).

Because we do not have the information in step 3, it's difficult to:

1. target reminders and marketing messages to those who "have intent" but haven't done any significant action

2. calculate what percentage of those who "have intent" actually bit the bullet and started participating (activation rate)

3. have concrete numbers on the actual number of people who "joined" (had intent + participated) in a hackathon

### Current Behavior

we are currently missing the ability to identify gitcoin profiles who join/login with the intent of working on hackathon issues

### Expected Behavior

We need a solution that allows identification of of gitcoin profiles / gitcoin profile ids that express intent to participate in a hackathon. 

### Possible Solutions

1. octavio mentioned that adding a flag to the hackathon onboarding login is a possible solution. The drawback is it may not capture all logins from different areas of the gitcoin site.

2. another solution would be add a step in the onboarding process asking what the intent of a contributor is when they arrive on the gitcoin platform. The drawback here is what happens for those who have already joined, and won't go through the new onboarding process?

3. TBD workshop

### Definition of Done

TBD

**Comment by octavioamu** [comment]
Idea 1 now is not possible since the new designed onboard doesn't have login button. 
I think the idea of having to check why are you on gitcoin, as part of funder / contributor, also "are you here for hackathon, bounties, grants?

**Comment by frankchen07** [comment]
@alexvotofuture to input your thoughts on this

**Comment by alexvotofuture** [comment]
This ticket captures the problem well, thanks for putting this together, @frankchen07 and @octavioamu.

I don't think a questionnaire on a user's profile is going to fit our needs for this. Too many ways for people to not fill that out (they may already be signed in, may already have a Gitcoin profile and not feel the need to answer, may rush through and make up answers to get into the hackathon quickly, etc.)

Could we just have a button on the prize explorer that allows people to explicitly register? This button could be on the prize explorer even before the hackathon launches, so that people can get email updates leading up to the hackathon. Could make the button indicate "Registered" when they successfully register. Could also make it mandatory to add the user's Discord name in their Gitcoin profile to successfully register.

Would also need to create a similar registration button that people must click in order to start/submit work on any bounty flagged as being part of a hackathon. This means no matter whether a person comes in through the prize explorer or directly through a prize, they will have to register explicitly to participate, and will automatically be opted in to receive email updates and have their profile logged as a participant.

This approach would allow us to capture interest and get mailing list signups before and during an event (even if people haven't started/submitted work), would allow people to see the prize explorer and prizes but limit them from starting/submitting unless they are logged as a participant, and would make participation more explicit in general which would help make people feel more involved.

**Comment by frankchen07** [comment]
I slightly changed the ticket to ensure that we're capturing the correct problem.

I'm going to encourage that we focus more on problem oriented statements, rather than outright suggestions. 

> This approach would allow us to capture interest and get mailing list signups before and during an event

This is the true problem that we're trying to solve. I agree with this.

> would allow people to see the prize explorer and prizes but limit them from starting/submitting unless they are logged as a participant

I believe this is already true, they can't start or submit without logging in.

> create a similar registration button that people must click in order to start/submit work on any bounty flagged as being part of a hackathon

this is then registration on top of logging in in order to start an issue - I'll refrain from saying if this is something that works not - and leave it up to @willsputra to see how it affects the user exp

Octavio and Will are workshopping this problem statement tomorrow and I'll add the findings here.

**Comment by octavioamu** [comment]
Closing, now last bugs are fixed
