### ISSUE TITLE
New Github Profile Feedback / catch-all issue

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#5239]
**Describe the bug**
Add bugs/errors/... from the new profile page in here

**Additional data**
Please provide screenshots and browser/OS info!

**Comment by kuhnchris** [comment]
Numbers are too small
![grafik](https://user-images.githubusercontent.com/761911/65459945-31290580-de51-11e9-9555-bb98ced3434f.png)

**Comment by kuhnchris** [comment]
I see myself listed in "Spent", the Y-axis has no description, Earning seems to include broken profiles.
![grafik](https://user-images.githubusercontent.com/761911/65459954-371ee680-de51-11e9-82c2-81c0299320b2.png)

**Comment by kuhnchris** [comment]
Is the missing space between Rank and "Contributor" or "Funder" on purpose?
![grafik](https://user-images.githubusercontent.com/761911/65460055-62a1d100-de51-11e9-8b55-e81d7c377ea7.png)

**Comment by kuhnchris** [comment]
"Spent" shows wrong transactions, i never did... 39 "spend" transactions, especially not the same action 5-9 times:
![grafik](https://user-images.githubusercontent.com/761911/65595538-50c94680-df95-11e9-8ce8-21b47f022756.png)

**Comment by willsputra** [comment]
**Improvements**

It should be explained clearly what the grids meant.
![1](https://user-images.githubusercontent.com/19514207/66413814-b7854000-ea2a-11e9-9019-18a5132f697f.jpg)

Add "Status" and "Quests".
![2](https://user-images.githubusercontent.com/19514207/66413860-d4217800-ea2a-11e9-96d1-bd0a70feb688.jpg)

It seems like the "Share" button on Status is disabled until the text reached a certain number of characters/sentences. There should be an error message that clearly communicates this.
![3](https://user-images.githubusercontent.com/19514207/66413918-f2877380-ea2a-11e9-8fa6-dcd0afabd1c0.jpg)

Remove the "Only visible to you" icon and text since the ratings are visible to everyone now. 
![4](https://user-images.githubusercontent.com/19514207/66414176-780b2380-ea2b-11e9-8906-a3363fb3814d.jpg)

**Comment by willsputra** [comment]
"Reliability" tooltip should show up next to "Reliability", not "Avg Hourly Rate". 
![5](https://user-images.githubusercontent.com/19514207/66414591-50688b00-ea2c-11e9-95a9-5e550bcdb716.jpg)
