### ISSUE TITLE
as a user; i want to chat other users, so i can have a direct line with anyone on the site

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5352]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user; i want to chat other users, so i can have a direct line with anyone on the site

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
you have to go to github/discord to chat a user

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
v1
mattermost out of the box:
- you get everything you get out of slack on the gitcoin site
- gitcoin.co/chat - place where you can chat with anyone on the site
- tuned to as much out of the box  that mattermost can do -- milestones - demo & documentation writeup

v2
chat widget on the gitcoin site
- allows you to send a message to anyone online or not
- if receiving user is offline, send them an email to let them know there is a message
- if online, their online window shows the message + a realtime chat experience can happen
- multiple chats at once
- notifications in browser icon if theres a new message

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above ^^

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
- number of messages sent
- WAUs and MAUs => DAUs

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by frankchen07** [comment]
![chat](https://user-images.githubusercontent.com/7516920/67791173-3cfd7e00-fa34-11e9-9020-1dc47c3994eb.jpg)

uploaded an old chat sketch by @willsputra

**Comment by androolloyd** [comment]
chat on gitcoin update.
- [x] Embedding webapp
    - [x] build oauth provider on mattermost for gitcoin
    - [x] Removed same origin, removed content security policy, need to update these and do a proper install so they share the same origin
    - [x] build oauth on gitcoin
Deploy
- [ ] kubernetes/ecs/some way to do high availability, what scale before comfort is there, lots of moving parts that'll need scaling sooner than later.
- [ ] S3 buckets and access for uploads
- [ ] ec2 -> we will need to compile ourselves, should give us something like a linux binary, would like self hosting jira at that point

- [ ] If you have previously author gitcoin, then revoke, and try to auth sign in, you end up at the explorer, likely the Hand off from when you try to do a sign in from the chat, and it captures you as not auth and redirects the whole flow to put you at the explorer, set something to ensure that if we’re coming from chat we want to go back to chat.

- [ ] As apart of auth, authenticating we need to define the team id for the server everyone is going to join, HARD CODE if needed, would be great to sort how this flow works for potential tribes usage, 
- [ ] Default theme setup to match (Will’s slack codes, its been setup but when new users are created they still don’t get the proper default, it must be hardcoded somewhere
    - [ ] Sync active user avatar on login
       -  [ ] MM needs to store a copy of the avatar, so it’ll have to sync from where gitcoin hosts, ideally we hack in an ipfs filestore here to sync up with what gc already uses
    
    - [ ] User onboarding flow gets stuck with Django social auth, in cases where the user is not apart of Django, and has to auth through GitHub, we end up in this weird situation where the auth state is not being set correctly, we need to redirect to signup/complete on lattermost, but we end up at the /explorer.

- Gitcoin web chat service
    - [ ] Putting users into the same channel on bounty creation
    - [ ] How does that work for onboarding users who haven’t gotten onto chat yet? 
    - [ ] Commenting on bounties about an open channel about the bounty and hot linking valid users into the channel
    - [ ] Grants could have a team that their donors can be auto joined into
    -

**Comment by androolloyd** [comment]
Github application is trivial to setup and is pretty robust.

**Comment by androolloyd** [comment]
slack has invite codes, we'll want to leverage a mattermost python library and query user existance and adjust their flow accordingly, https://github.com/Vaelor/python-mattermost-driver is pretty all encompassing by the looks of thing, mattermost has a robust api.

**Comment by androolloyd** [comment]
<img width="963" alt="Screen Shot 2019-11-04 at 11 04 49 AM" src="https://user-images.githubusercontent.com/1237259/68131183-f6f06080-fef2-11e9-993e-3e475325e192.png">

**Comment by androolloyd** [comment]
![Screen Shot 2019-11-04 at 11 05 54 AM](https://user-images.githubusercontent.com/1237259/68131245-17b8b600-fef3-11e9-946b-6c9c3c956e31.png)

**Comment by androolloyd** [comment]
https://github.com/gitcoinco/mattermost-server/pull/1

**Comment by androolloyd** [comment]
https://github.com/gitcoinco/web/tree/chat/oauth

**Comment by androolloyd** [comment]
> ### Deploy
> * [ ]  ec2 -> we will need to compile ourselves, should give us something like a linux binary, would like self hosting jira at that point
 - this isn't entirely correct, more research needed, it does compile and give us a tar.gz, but what its running when it spins up is likely just mattermost and not its dependencies, which in the dev instances is run on docker.

> * [ ]  S3 buckets and access for uploads
- Mattermost uses minio, its a storage microservice that uses the amazon format as a standard and has connectors to underlying locations, amazon, google, otherwise.

> * [ ]  kubernetes/ecs/some way to do high availability, what scale before comfort is there, lots of moving parts that'll need scaling sooner than later.
- mattermost has[Helm](https://helm.sh) scripts for all of its deployment https://helm.mattermost.com -> github.com/mattermost/mattermost-helm with some configuration the deployment of Gitcoin's chat instances could become scripted and pretty trivial to manage, the authentication changes would need to be included inside of these builds and have the helm charts updated accordingly.

> ### Issues Discovered
> * [ ]  Default theme setup to match (Will’s slack codes, its been setup but when new users are created they still don’t get the proper default, it must be hardcoded somewhere
- this is annoying, ive dug through everything and absent some hardcoded value I haven't discovered I'm not sure why the default theme is so hard to override as a default. 

Users can manually activate the new theme without issue, more digging into the code to trace this is needed.
> * [ ]  Sync active user avatar on login
- this should be easy to do if we pass the user url and hook into one of the user save routines, the current code expects a file, so we'd have to write a method to retreive the file from gitcoin -> ipfs, and at that point we might want to consider how minio -> ipfs could work.

> * [ ]  If you have previously authorized gitcoin, then revoked access, and proceed to auth again, you end up at the explorer, likely the Hand off from when you try to do a sign in from the chat, and it captures you as not auth and redirects the whole flow to put you at the explorer, set something to ensure that if we’re coming from chat we want to go back to chat
- this is a problem with the social auth provider pipeline we're using, we might want to handle the login request for oauth needs seperately than use the social auth, how this works with github not allowing multiple redirects for requests is an unknown.

> * [ ]  slash commands have issues due to websockets not being available, the Github application works well in a Mattermost served application.
- the issues are because hte authentication fails on the thirdparty request, not sure why but likely because it is dynamically loaded, 
- attempts were made to work around this by including the root into the gitcoin web application, this doesn't work as a result of how the mattermost application is built, you could create a new webpack entry point and compile the application differently to include and render via the web app instead of iframe, 
> * [ ]  desktop client uses the oauth workflow to login via gitcoin, and then is unable to render some portion of the experienced in the iframe, likely some weird loop scenario, a better handle on onboarding will fix this.(there is a gitcoin header inside the electron shell.
- the redirect issue here with oauth login is directly related

> * [ ]  As apart of auth, authenticating we need to define the team id for the server everyone is going to join, HARD CODE if needed, would be great to sort how this flow works for potential tribes usage.
- could be apart of the token response we provide is a team id of the team they are joining.
> 
> ### Documentation
> * [ ]  Setup Mattermost and link it to your local docker instance.
- currently its compiled locally for testing and is being run as a go binary, it can be run as a docker instance when running for debugging, will work on building for docker and linking the chat network to the web network.
> * [ ]  Setup an oAuth application and link Mattermost to your locally running Gitcoin
- docs are available online with the provider we use, having internally directed and to context of the usage makes the most sense
> * [ ]  Driving Mattermost via gitcoin
- bounty-channels, hackathons, etc.
> * [ ]  Building
- current build scripts work
- modifications needed to account for server changes to enable Gitcoin oAuth
> * [ ]  Deploying
- where and how its going to live are not yet known, but deploying locally will be considered to be the start, and we'll build on that.
> * [ ]  Troubleshooting
- How to get data from the application, and how to setup debugging for the go app are pretty straight forward if you've done anything with remote debugging of docker containers. 
Might be good to get a vscode example put together.

**Comment by androolloyd** [comment]
https://forum.mattermost.org/t/how-to-change-the-default-theme/4965 found something its because the internal store has defaults now too, okay that will be easy to update.

**Comment by androolloyd** [comment]
SMTP settings have been setup on the deployed server and emails are being sent correctly.

**Comment by androolloyd** [comment]
- [ ] GC Web
    - [x] lock behind is_staff
    -  [ ] Review and deploy the chat/oauth branch
    -  [ ] Create a new oAuth Application for Mattermost
- [ ] MatterMost Whats needed
    - [x] Linux binaries are building and able to be deployed and setup
    - [x] Proxy Config Nginx
        - [x] setup
        - [x] TLS
    - [x] Mattermost host Server setup and dependencies
    - [ ] Mattermost setup and configuration
        - [ ] Giphy application key
        -  [x] Github Application Setup
          - [ ] transfer ownership to Gitcoinco
        - [x] Database
        - Storage(s3)
            - [ ] Needs an IAM setup and provisioned a bucket with access, public only if the app enables, I think it sets it up 
        - config.json
            - [x] SMTP setup with SendGrid relay
            - GitCoinAppSettings
                - [x] Login urls
                - oAuth Application id/secret
    - Once deployed
        - [ ] Setup admin account
        - [x] Setup default team
               - setup logos
        - [x] Create contributor and funder general channels
        - [x] Setup welcome bot to greet new users

**Comment by androolloyd** [comment]
can we close this out? @owocki

**Comment by owocki** [comment]
yar
