### ISSUE TITLE
Tried to run locally the web repo with docker and had an issue with port bindings

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5371]
**Describe the bug**

I tried to install the web repo locally with docker but had some errors with the port bindings saying the port was already allocated:
`Error starting 
userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated`

Had to use a quick fix explained [here](https://github.com/docker/compose/issues/4950#issuecomment-398879461)

**To Reproduce**

Run the web repo in a new machine 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by kuhnchris** [comment]
sounds like you are running something on that port. Since you did not state what OS you use I cannot help you with finding that out.
On UNIX you should be able to check ```netstat -nap``` and on windows probabbly ```netstat -ano```.
From there you should be able to see what program is blocking that port. You can simply remove the exposure of any other port than the www port for internal uses without any bigger harm.

**Comment by Solexplorer** [comment]
I was sure it wasn't my fault, booted up a new machine and the issue wasn't there anymore looks like I messed something with ports
