### ISSUE TITLE
info needed to list kudos purchases on etherscan 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5620]
```
1. Contract address - 0x2aea4add166ebf38b63d09a75de1a7b94aa24163
2. Direct image link - this should be in the IPFS hash

3. If using API - https://nft.com/[id] -  n/a/
4. Interval before image generated and published - 1 min
5. Retry interval - 30 mins
6. Copyright page/section link for the images 0 gitcoin.co/kudos/

```

**Comment by owocki** [comment]
@kvrnc does this look ok?

**Comment by kuhnchris** [comment]
I assume they will not be able to handle the IPFS hashes? I'd prolly suggest that we need to generate a API call for them (as the nft.com/id example) so they can fetch the data...

**Comment by kvrnc** [comment]
@kuhnchris is right since the contract is not verified, we are unable to determine the function and field available to pair the token id with the ipfs hash. @owocki by any chance you have the ABI for the contract? Here is a sample of an un-verifiable contract with ABI, Read and Write function works.

**Comment by kuhnchris** [comment]
It's basically a ERC721, minimal ABI provided here: https://github.com/kuhnchris/KudosDisplayCards-dApp/blob/master/src/web3wrapper.ts

Alternative the 'official' ABI available but not matching up the contract(s) 1:1 is here: https://github.com/OpenKudos/python_client/blob/master/abi/kudos.json

**Comment by owocki** [comment]
i dont understand why this is so complicated.  we use ERC721 standards in the Kudos.  it should be easy to integrate the kudos data; verified or not (Kudos is not *verified* on OpenSea for example).

**Comment by kuhnchris** [comment]
well, the main issue is that you have deployed a contract that is simply not verifiable, and hence not trustworthy... since nobody can check what you actually got in the contract. for all purposes and for the history that had happened before, your token could have an exit scheme/exit function that allows you to empty the contract. that's the reason why some things require verified contracts. 

...not sure why we'd need that for displaying images with the tokenURI function tho, but, yeah...
