### ISSUE TITLE
MetaMask browser extension conflicts with Opera native CryptoWallet if enabled

### ISSUE THREAD

**Issue by aahutsal** [gitcoinco/web#5665]
**Describe the bug**
If native Opera CryptoWallet is enabled on desktop Opera browser MetaMask chrome extension conflicts and user can't operate with MetaMask wallets.

**To Reproduce**
- Go to Settings -> Features -> CryptoWallet and enable it.
- Login to https://gitcoin.co/
- Navigate to https://gitcoin.co/explorer URL.

See this:
![image](https://user-images.githubusercontent.com/1643117/71354215-2296db00-2573-11ea-8118-f607c65b4cac.png)

**Expected behavior**
Should not throw any Javascript exceptions regardless to CryptoWallet state (enabled or disabled)

![image](https://user-images.githubusercontent.com/1643117/71354239-35111480-2573-11ea-86e6-5d87b7c78faa.png)

**Screenshots**

**Desktop**

- OS: 4.15.0-1056-aws #58-Ubuntu SMP Tue Nov 26 15:14:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Browser: Opera
- Browser Version: 65.0.3467.69

**Mobile**
OS: Android 
Browser: Opera Touch
Version: 2.1.3

MetaMask is not installed
![Screenshot_2019-12-23-17-15-59](https://user-images.githubusercontent.com/1643117/71365669-5fc99000-25a8-11ea-9b3c-2de0307c2ef0.png)

**Comment by kuhnchris** [comment]
I see you have the Opera and Metamask combined in use - I also see Metamask complaining about that - sure that this is not connected somehow?
Can you try to disable Metamask if you enable the Opera Internal CryptoWallet?

Thanks

**Comment by Sirlupinwatson1** [comment]
For me I still had this issue, i did not have the time to look why it was hapenning. Maybe i can have a look today after i am done with another one.

**Comment by agutsal** [comment]
Sorry for being not concrete enough. If I disable native wallet, it work smoothly with MetaMask. Haven't tried to work with native Opera Crypto wallet. I think coffee should be revised. I'll try to take that part myself if @owocki is ok with it.

**Comment by molecula451** [comment]
This same thing it's happening with Brave Browser. If Native Brave Browser Crypto Wallet it's enabled and you have Metamask too,   it will throw web3 conflict and in some cases if you Disable the native Crypto wallet and you try to use the MetaMask it will redirect to a page where it showing you have your crypto wallet disabled.

I Believe pretty much it's MetaMask having conflict when recognized other cryptowallets (native)

**Comment by Sirlupinwatson1** [comment]
@molecula451 HI, i just started to use Brave. Not sure about getting interference or not. I also use Metamask and Dapper, Arweave . Dapper always buggy the version i have anyway is still in beta but it did work still pretty good. Metamask, since a while there is many bug. It make me learn at least haha, learn to have other option

**Comment by kuhnchris** [comment]
Hello all,

thanks for clarifying the issue @agutsal . If you know where to lever the issue or could pin-point the issue I'm sure @owocki is fine with you opening a PR here. If you can give the engineering team a pointer or a hint where the issue may occour it will also help them finding the precise steps neccessary to reproduce it.

I assume there may be a conflict with the different providers trying to add their version or flavor of the web3 object into the website. Since this may cause confusion for the providers itself it may be a question of how to solve it in general. This actually makes me wonder:

Does this issue only occour on gitcoin, or does, for example radar-relay, cryptokitties or other crypto projects also have issues with those multi-provider-setups when you try to open them?


Thank you for all your help guys,
Chris

**Comment by Sirlupinwatson1** [comment]
> Hello all,
> thanks for clarifying the issue @agutsal . If you know where to lever the issue or could pin-point the issue I'm sure @owocki is fine with you opening a PR here. If you can give the engineering team a pointer or a hint where the issue may occour it will also help them finding the precise steps neccessary to reproduce it.
> I assume there may be a conflict with the different providers trying to add their version or flavor of the web3 object into the website. Since this may cause confusion for the providers itself it may be a question of how to solve it in general. This actually makes me wonder:
> Does this issue only occour on gitcoin, or does, for example radar-relay, cryptokitties or other crypto projects also have issues with those multi-provider-setups when you try to open them?
> And, on related note, what's the reason you guys use the native browser wallet and MetaMask? Just for testing purposes or is that you 'productive' setup you use for you every-day work?
> Thank you for all your help guys,
> Chris

On my side, i was using Metamask because it was the one who was mainly pointed at on web source. 
I use other walltets to try them and see. I am a pretty conservative guy, but if you try nothing you are not living any experience. 

My experience with Metamask, was bad.

**Comment by kuhnchris** [comment]
@Sirlupinwatson1 yeah, no doubt there - everything has it's own pros and cons. The question is: why using 2 different wallets at once within the same browser

**Comment by Sirlupinwatson1** [comment]
@kuhnchris Good answer i guess. If you look it that way, we can then keep going on into this lol.

But only because right now there is many but many difference in the variations of cryptocurrency. Anybody can make his own and build up some stats and offer crypto to all of us. And they are not offering any alternative to work with either their web site or the way to get the crypto.

Metamask is just not made right now for beginner or Mister and Mme anyone, but for Novice player. This is my opinion after using it for a while. 

Now there is something going on with all the new wallet available and new browser, giving away crypto and the option to let you mine online with a apparently boost…. this make me still perplex about it but really

**Comment by octavioamu** [comment]
I been using opera a lot on my test with gitcoin and is working fine. Of course any web3 browser + wallet enabled + metamask will fail as creating a big conflict. 
About "opera touch"  that is not a web3 browser
opera + opera mobile is a web3 browser (note opera depends on opera mobile app to work as web3 browser)
- Brave if you setup your wallet works out of the box also (doesn't need mobile or extensions)  but if you install metamask you need to disable the internal wallet since is the same as trying to work with 2 metamaks extensions at the same time.
