### ISSUE TITLE
As a hackathon sponsor it is difficult to review which users I’m paying out for a hackathon prize and ensure I’m paying out the right people

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5670]
### User Story

As a hackathon sponsor it is difficult to review which users I’m paying out for a hackathon prize and ensure I’m paying out the right people.

### Why Is this Needed

Hackathon sponsors are finding it difficult to review and keep track of all payments to hackathon prizes. The sponsors are using their own spreadsheets to track payments. The value from those spreadsheets should be the value that Gitcoin provides, in terms of hackathon ease of use, and ability to keep track of relationships post-hackathon.

### Description

As an example, Consensys Labs has been tracking this information on their own:

payouts:
![Screen Shot 2019-12-23 at 15 37 56](https://user-images.githubusercontent.com/7516920/71385122-59341c00-259a-11ea-89ed-1a9eba096542.png)

### Current Behavior
There's no easy way for a sponsor to have a high-level overview of all prize payments for their sponsorship in one glance. There's also an aspect of relationship management that is missing from the Gitcoin Hackathon product. 

### Expected Behavior
Gitcoin helps sponsors keep track of prize payout, and who has worked on the hackathon prizes.

### Definition of Done
- [ ] solution for tracking payments to prizes that are open
- [ ] possible solution for relationship management, or at the very least, tracking applicant information for those who worked on sponsor prizes for a given sponsor
- [ ] decision on if this will be included in the dashboard

### Data Requirements
This can probably be pulled from our DB quite easily.

**Comment by frankchen07** [comment]
@PixelantDesign & @frankchen07 believe it's best to extend the dashboard, but let's discuss how we want to add to the dashboard (add a hackathon tab? extend the funder tab?)

**Comment by danlipert** [comment]
Interesting which data points ConsenSys Labs is tracking in their tool - maybe its worth doing some research into what sort of data points people would like to have. From what information CL has in that screenshot, we have that info readily available in our DB, plus a call to something like Etherscan for the on-chain metrics like block number

**Comment by PixelantDesign** [comment]
Definition of Done:
How do I track the people I need to pay? How do we create a view like this in Gitcoin app? Where does it make sense? How do funders get to it? How do funders view it?

**Comment by thelostone-mc** [comment]
Agree that this fits into the definition of dashboard but 

- would adding another tab be an overkill ? (too many tabs)
- how would the UI gracefully handle when sponsors have bounties in multiple active hackathons 
- could we explore adding a neat filter onto dashboard  ?
- would having a table view on the dashboard (like what consensys have) make it easier? 
It's less pretty but feels more wholesome/useful

**Comment by frankchen07** [comment]
one person need or general need?

invoice issue or a payout issue? or to check complete payouts?

where should people go to see this (whatever "this" is?)

**Comment by alexvotofuture** [comment]
Responding to @frankchen07 's summarized questions:

> is this a one-person need or a general need?

General need. A number of our sponsors have found the process of selecting the right people to pay out and keeping track of recent payouts painful and terrifying. This led to a mis-paid payout in the last hackathon, the creation of heavyweight spreadsheets like the one shown above, and delays in payouts that have caused immense hackathon hacker dissatisfaction.

> is this a need for an summary invoice, need to check complete payouts somehow, or an actual issue with payout itself?

I think there are multiple issues here that have accidentally been rolled into one. 

On one hand we need an easier way for sponsors to pay out the right people who worked on a prize, since advanced payout doesn't make it clear who's been paid already and which people worked on a given submission. This is the more pressing need, as it affects all hackathon payouts.

On the other we need a way for sponsors to get reports on everyone they paid out, including KYC/AML info where needed, and ideally some summary statistics. This is an emerging need of slightly less importance, but makes it easier for sponsors to feel confident in the correctness of their final payout results, helps them provide crucial payment/compliance information to their orgs for administrative purposes, and helps them judge their ROI as a sponsor of our hackathons so they can join us again and strategize on ways to increase their engagement/cost ratio.

**Comment by frankchen07** [comment]
@frankchen07 & @PixelantDesign to further define the problem

**Comment by frankchen07** [comment]
two problems exist:

advanced payout doesn’t make it clear who has already been paid, and which exact people worked on a submission. This is the use case where a funder may pay out individuals over time, at different time points, and when they come back to the advanced payout page, they don’t remember who and how much they paid someone.
when the hackathon is said and done, sponsors should be able to “generate” an invoice that tells them all of their payout results within a period of time, with a very specific set of information (any information required for compliance)
