### ISSUE TITLE
DAI twice in select element

### ISSUE THREAD

**Issue by TimDaub** [gitcoinco/web#5774]
<img width="334" alt="Screen Shot 2020-01-11 at 10 39 56" src="https://user-images.githubusercontent.com/2758453/72202360-bb2bc700-345e-11ea-9ac5-d4993427f1a8.png">

to reproduce:

- try creating a new grant
- search for "DAI" in "Required Token For Subscription" input
- search shows two different "DAI" options

Which one do I chose to use correct DAI? Are they both correct?

**Comment by Solexplorer** [comment]
Looks like this issue is happening because there are duplicate records in the `tokens.json` [here](https://github.com/gitcoinco/web/blob/e2a6f81280315ab3db1b54f850da05a737570cef/app/economy/fixtures/tokens.json#L2756) and [here](https://github.com/gitcoinco/web/blob/e2a6f81280315ab3db1b54f850da05a737570cef/app/economy/fixtures/tokens.json#L5816)

@TimDaub Choose the first one and it will be fine
@thelostone-mc This appears also at bounty creation
