### ISSUE TITLE
Make "One-Time" grant contributions the default

### ISSUE THREAD

**Issue by paulrberg** [gitcoinco/web#5864]
During CLR Round 4, I brought around 10 friends and family members into Ethereum by telling them how to install and use MetaMask and go to the Sablier grant page.

Pretty much everyone said they were confused about the recurring aspect, when I initially asked them for a one-time contribution.

This might be just an isolated case, but I think it'd be great if the "One-Time" option in the dropdown would be the default.

**Comment by owocki** [comment]
good idea

**Comment by owocki** [comment]
one idea were toying with is letting u subscribe to next N grant rounds instead of next N weeks/days/month for recurring. i wonder if that would be more used than the existing recurring functionality

**Comment by PaulRBerg** [comment]
Hard to tell. Just my 2 cents, but people have a hard time remembering Netflix subscriptions, let alone new shiny blockchains fundraisers.

That, plus some of the grantees raise private investment in-between rounds. As Hayden mentioned on the last community call, he was thinking to cancel the Uniswap grant because they have plenty of funding now.
