### ISSUE TITLE
Submitted Works are not displayed in dashboard

### ISSUE THREAD

**Issue by cervoneluca** [gitcoinco/web#5999]
Currently I'm participating in 3 bounties. I have submitted my work for all of them. If I navigate to bounties pages then I can see that I have submitted the work. 

However, when I'm in my dashboard, all the bounties are still in the "work in progress" section.

I attach screenshots of my dashboard and of one of the bounties were I've submitted my work. 

<img width="806" alt="Schermata 2020-02-17 alle 09 54 08" src="https://user-images.githubusercontent.com/3637606/74638226-cd8ad600-516b-11ea-9021-12495b7aeacb.png">

<img width="1340" alt="Schermata 2020-02-17 alle 09 54 47" src="https://user-images.githubusercontent.com/3637606/74638238-d4194d80-516b-11ea-9a52-5d29d8dc1879.png">

**Desktop**

- OS: MacOs Catalina 10.15.3
- Browser: Brave Browser
- Browser Version: 1.2.43

**Comment by Solexplorer** [comment]
This is an ongoing issue, related to #5808

**Comment by cervoneluca** [comment]
Thank you!

**Comment by octavioamu** [comment]
So just a help for you because I built that dashboard, in that time to make the query we needed to look at the state (open, work started ...) so to replicate that the bounty need to be cooperative or any where more than one person can work at the same time. That is when that query fails to fetch the group "work submitted" as the query is looking for bounties > closed

We changed now the model to have ui-state with that changes maybe now is possible to fetch the other new states

**Comment by octavioamu** [comment]
Also I want to know more about how people is using the dashboard and what they expect to have there.

**Comment by cervoneluca** [comment]
Hi octavioamu! Thank you for your answer! I think that the dashboard should be a place to see all my activities in all sections of the site. Since now, this is allowed but I have to jump from the "Dashboard" page to the "My Profile" page to have everything under control. Maybe everything can be merged in a single summary (Dashboard) page (but it must be well organised, otherwise it could be confusing). 

Anyway, I didn't understand, is this issue a bug or a wanted feature?
