### ISSUE TITLE
Should addresses tied to two more more grants be noted?

### ISSUE THREAD

**Issue by tjayrush** [gitcoinco/web#6106]
### Discussion

I've been reviewing the earlier rounds of grants as part of the testing for my work, and I've noticed something interesting. Of the 150-200 grants in round 4 of the CLR, at least 10-12 are for addresses that appear as the recipient of two or more grants.

I'm 100% not casting dispersions on anyone, I think whoever set these grants up had two legitimate projects, but as a donor to multiple grants, I think I'd like to know if the recipients are the same for two or more projects. I might chose to give to one or the other.

Of course, any solution to this won't solve this issue of a person just creating a different wallet if they wanted to hide the fact that the two projects were related, but for those project that have the same wallet as recipient, I might like to know that.

Just an idea. No real biggy.

**Comment by owocki** [comment]
i think whats more suspioucuos is if two different *donors* are tied to the same address 

both are probably worth noting in the UX tho

**Comment by marsrobertson** [comment]
I was thinking about it.

https://gitcoin.co/marsrobertson/grants - I am currently the creator of 3 live grants.

Simply because I'm active and I prefer doing, rather than talking about doing!

Of course "don't trust verify" so one is multisig, one is Aragon DAO.

There is plenty on-chain data, I'd love to see more information about the people.

Here example from Kickstarter:
![image](https://user-images.githubusercontent.com/44369284/78374896-f3f1bd00-75c3-11ea-82d7-aa58e4321fac.png)

**Comment by thelostone-mc** [comment]
This would best be explore behing the scenes.
cc @frankchen07 if you think this is something we should track on metabase

Closing this out for now as we have no action item here. Will reopen if there is
