### ISSUE TITLE
Donation never leaves pending state, tx confirmed in the blockchain

### ISSUE THREAD

**Issue by poapxyz** [gitcoinco/web#6378]
I received a donation and it confirmed on the blockchain but the Gitcoin interface always shows it in pending state. I'm attaching a screenshot of it.

On Etherscan it can be seen that the transaction was apparently dropped and rebroadcasted with a higher gas price and same nonce:
https://etherscan.io/tx/0xa321e00d338e2d99f0c018e3ee872923e2d9068fd5dfbc45aa9a09c0e09267b2

![image](https://user-images.githubusercontent.com/52794365/78457982-a1c4a080-7684-11ea-8416-0180b0beb798.png)

Thank you !

**Comment by LefterisJP** [comment]
This is the same issue we also saw in the last round I suppose right @owocki ?
Issue is still open: https://github.com/gitcoinco/web/issues/5741

I also saw it happen to Rotki's grant yesterday.
Transaction hash: https://etherscan.io/tx/0xde8d74c3b7c6dbcf2fb82aa62398a1b6320020715709b1a39c6002d45b4e89aa
![2020-04-05-085128_759x80_scrot](https://user-images.githubusercontent.com/1658405/78468709-a89df280-771a-11ea-832e-3060e771b7d2.png)

**Comment by owocki** [comment]
hey guys, i just went in and manually updated the transactions for each of these grants that failed to track bc they were dropped and replaced

at the end of the round, i was planning on going through all the contributions with https://github.com/gitcoinco/web/pull/6331 (which can find the dropped/replaced txns) and automatically correcting them.  which will be the final fix for https://github.com/gitcoinco/web/issues/5741 - for round 6 i'd love to have this script running for ALL grants estaimtes DURING the round instead of during the end.
