### ISSUE TITLE
Combine Start Work & Project Creation Forms

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6444]
### User Story

As a contributor I'd like a seamless form to let the sponsor know my plan for the prize bounty.

### Why Is this Needed

We want to make it simple for hackers to start working! 

1. It helps our operations team absolutely track all projects and participants on projects
2. It facilitates more accurate recording between start work and number of projects

### Description

Combine the two forms that exist today into one form. Displaying information progressively depending on the option the contributor chooses (solo or with team).

The way the interest model data is sent and the way projects are set up are 2 different things.

Start work is not necessarily related to the project. As an example:
        + alex and octavio are both hackers (im looking for someone)
        + alex didn't start work
        + octavio put alex in team (project)
        + start work doesn't necessarily reflect number of projects

We need to definitively understand the use cases we want to track. The ultimate goal from our latest discussion is knowing and being able to contact "all people working on a project." This includes those who have:

1. started a project (the one who started work)
2. started a project and added a team member (one who started work, and one who didn't but is added to the project.
3. for every individual who started work, they must have a project

Limitations:
1. how many projects are allowed per contributor on a hackathon?

### Current Behavior
Two forms

### Expected Behavior
Single form

### Definition of Done

- [ ] Build the form to capture the two scenarios outlined in the mockups (hacking solo, hacking as a team).
- [ ] Allow users to designate whether they are looking to accept team members
- [ ] On looking for a skill, we should pre populate the tags that we use on the funder form (front end, backend, design, etc)
- [ ] Project name, logo, summary, plan, repo should be editable
until you submit work
- [ ] Hackers should be able to edit their project details via that same modal

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information

https://user-images.githubusercontent.com/19514207/80598518-0ee90d00-8a5c-11ea-80ea-250cb85970a1.jpg

**Comment by developerfred** [comment]
@PixelantDesign I can work on this feature?

**Comment by alexvotofuture** [comment]
I don't think we need a distinction between solo or team hacking, so I would remove that field. Just let someone create the project, add team members if they have them, and let them indicate if they are looking for additional ones. I'd also move the two team question fields to the bottom.

If people are already updating their project summary we don't need a "project plan" field. I'd remove that too.

I would like to think through a Town-Hall-style status update system that would allow people to post on the project's individual Town Hall, offering or requesting help and providing status updates. Maybe that could come later.

I would use "Project Repository or Github Pull Request Link" Instead of the short-hand "repo...PR". This will help people who are new to GitHub (or who choose to host their project files in another kind of "repository") to know what we mean.

I'd add a "How To Get In Touch: " field, with a checkmark for Gitcoin Chat (with the auto-generated URL, which can be edited later, and would update the chat channel name concurrently in Mattermost) or let them select "Other" and have them fill in a URL.

I don't think anyone really provides updates as a result of checking that "I agree to keep project owner..." box. I'd either link to a formal contributor code of conduct/TOS, or leave that out.

**Comment by PixelantDesign** [comment]
Thanks for the feedback @alexvotofuture! @developerfred yes! Let me make the updates first before you get started!

**Comment by willsputra** [comment]
@alexvotofuture what do you think? cc @PixelantDesign 
![hackathon_form](https://user-images.githubusercontent.com/19514207/80598518-0ee90d00-8a5c-11ea-80ea-250cb85970a1.jpg)

**Comment by alexvotofuture** [comment]
Looks awesome, @willsputra! I'd say this is ready to get wired up.

**Comment by alexvotofuture** [comment]
This is higher priority for us - let's keep it moving!

**Comment by PixelantDesign** [comment]
@zoek1 ^

**Comment by zoek1** [comment]
ETA Wednesday 13th in the morning @PixelantDesign

**Comment by PixelantDesign** [comment]
Thanks @zoek1!

**Comment by zoek1** [comment]
PR https://github.com/gitcoinco/web/pull/6661
TODO: Just wire the start work and create a project in the same step.

Quick question, this questions aren't important? 
![image](https://user-images.githubusercontent.com/660973/82038713-94c6a400-9669-11ea-944e-bde8ec02f88e.png)

**Comment by willsputra** [comment]
@zoek1 I believe these are important for bounties but less so for hackathons. @alexvotofuture what do you think?

**Comment by PixelantDesign** [comment]
agree with @willsputra here @zoek1
