### ISSUE TITLE
Hackathon About Tab

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6445]
### User Story

As a contributor I'd like to have one place to reference for materials related to the hackathon.
Links to workshops, repo guides, getting started guides etc.

### Why Is this Needed

Consolidation

### Description
Create a place to house learning materials and getting started guides making it easily editable by a Gitcoin core team member.

### Current Behavior
Just Getting started guide, nothing else

### Expected Behavior
A place to house all materials

### Definition of Done
Build this view that is **editable** by any core team member of Gitcoin.

### Additional Information

<img width="1501" alt="Screen Shot 2020-05-14 at 9 17 44 AM" src="https://user-images.githubusercontent.com/238235/81939071-dac92c80-95c3-11ea-81f8-80acfcab1819.png">

**Comment by alexvotofuture** [comment]
If we have an "About" tab that might be a better place to put this information (In a "How to Participate" sub-section under the introductory info). It would be the first thing people see when they come to the hackathon. That way the "Learn" tab is fully focused on valuable sponsor educational content, not on the administrative details of how to participate.

Either way, Quests would be a good field to pull actual data and cards for, since it lives on our site. For everything else (until we can find a way to automate workshop creation/invites) I would just leave it as one large, editable space.

**Comment by PixelantDesign** [comment]
Curious what @octavioamu and @willsputra think about the Guide page.

**Comment by willsputra** [comment]
If I remember correctly on our discussion with @octavioamu , the separate onboard page (https://gitcoin.co/hackathon/cross-chain/onboard) was there so we could 'block' people from seeing an empty prize explorer if the hackathon has not started.

but since right now there are stuff that people can do inside the integrated hackathon page (town square, check out participants, chat...), I think we can put the onboard page into an 'About' tab.

I also personally find the current 'Guide' tab redirecting you to a separate page pretty jarring, since other tabs are... normal tabs.

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/6584
