### ISSUE TITLE
Gitcoin Chat Fix Requests 5/4/20

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6580]
To be fixed:
-Ensure 100% of registered hackers are in chat
-Ensure 100% all projects created get a team channel (fix creation bug)
-Make project channels public by default
-Hackathon slug before project channel name
-Resolve URL issues (gitcoin.co/chat not working sometimes, chat.gitcoin as fix)

To discuss:
-New Mattermost Team for each hackathon

**Comment by alexvotofuture** [comment]
@androolloyd @connoroday @vs77bb @frankchen07 @PixelantDesign Anything I missed here that we need to fix/upgrade, or that @androolloyd is already working on?

Thoughts on the tradeoffs of doing a new Mattermost Team for each hackathon? My biggest one is that we lose continuity on some channels from hackathon to hackathon (company-specific channels and general hackathon channel). But would be great to reduce clutter, archive swiftly, eliminate the need for hackathon slugs on each channel name.

**Comment by frankchen07** [comment]
hm just as context, using gitcoin chat is a little difficult because of the unreads section, it sort of throws everything up there, public channels, hack channels, 1:1 messaging:

![Screen Shot 2020-05-05 at 10 22 06](https://user-images.githubusercontent.com/7516920/81095831-66eb9d80-8eba-11ea-8d1b-267ac034a045.png)

It's also a little weird that my direct messages are persisted across GC hackathons and GC internal. Maybe this is an intended feature?

what would creating mattermost teams look like? Would it be creating a "GC hackathons" for each hackathon?

we might lose out on general channels, unless we can persist them like direct messages?

**Comment by androolloyd** [comment]
You can disable grouping unread messages(its on by default) Account Settings -> Sidebar -> Uncheck 

Yes, your DM's carry with you to any team, AFAIK this is intended, most likely because we allow Cross Team messaging vs just team silioed messaging.

Yes we would have a new "GC Hackathons" for each Hackathon, with all of the channels inside being unique to that team.

**Comment by androolloyd** [comment]
@alexvotofuture I have a script that can be made into a job to get run every few minutes to ensure that the right people are there.

I would add the ability to have mentors specified for the hackathons, and perhaps even mentors associated to the sponsors so we only drop them into the project channels that matter.

**Comment by alexvotofuture** [comment]
> I would add the ability to have mentors specified for the hackathons, and perhaps even mentors associated to the sponsors so we only drop them into the project channels that matter.
Yes, this would be super helpful for us!

**Comment by danlipert** [comment]
@androolloyd how we looking on closing this ticket out? @PixelantDesign is hoping for it to be deployed Wednesday, what are your thoughts on that?

**Comment by androolloyd** [comment]
The last issue is not yet solved and there at present don't seem to be really great solutions available, 

I have attempted to solve this through X_FRAME_OPTIONS but haven't had any success as of yet. The oauth step fails, but i believe this to due to how the local chat is setup. Lots of debugging needed here. 


I have another working idea about a redirect inside the mattermost chat server that after logins will send you back to the page you came from(feels insecure), but the idea is that from gitcoin, you would login hit gitcoin/chat, which then, redirects entirely to the chat ecosystem, handles oauth, and then redirect back to gitcoin/chat for the embedded view, with a session fully established. 

This feels like the nuclear option and if we're unable to solve it through X_FRAME_OPTIONS we should consider.

**Comment by androolloyd** [comment]
speaking with @owocki today we've decided to move away from the iframe embed and add a return to gitcoin button into the chat application itself.
