### ISSUE TITLE
As a new user, I want to add recently processed bounties to the landing page, so I know this thing is for real

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#659]
Inspired by https://github.com/gitcoinco/web/issues/633#issuecomment-373938494

> Makes a lot of sense to me! One note, I learn best from specific examples so think it could be nice to include specific examples of real contributions made to Gitcoin linked in the tutorial... always good to learn from the real thing 👍

We should have a a module that showed some recently compelted bounties on the landing page.. The module could/should also have a link to the issue explorer in it.

**Comment by mkosowsk** [comment]
A big 👍 to this idea... always nice to show what off what the community is accomplishing 😍

**Comment by davidkaufman** [comment]
I think this would be really great, too.  I would like to stare at the Recently Paid Bounties list :-)

What needs to be defined?
- Where, exactly this would would appear on the dashboard?
- What, exactly it should look like?  
- Are there any substantial technical questions to be answered?

Anything I can help with to revive this idea and get it moving along to implementation?

thanks!

-dave

**Comment by owocki** [comment]
note that we now have [the activity feed](http://bits.owocki.com/5a3b635d5e95/Screen%20Shot%202018-10-14%20at%202.10.29%20PM.png) on the landing page... i wonder if this suffices for the purposes of this ticket, or if we need to have 'recently done' bounties only...

**Comment by davidkaufman** [comment]
Well, yeah i guess what I was looking for was payouts.  All its showing right now is Work Submitted, started work, funded issue, Worker Applied, stopped work, Worker Approved and "Warning for Abandonment of Bounty" ...Interesting but y'know what I'm looking for is Show Me The Money heheh.  

Also i never noticed this way at the bottom of the home page -- it needs some caching or something because it loads so slowly for me that I thought the thing above it was the bottom of the page and (more than once) said to myself, "that's an odd way to end the page..." ¯\_(ツ)_/¯

**Comment by davidkaufman** [comment]
speaking of the bottom of the page -- there's an iPhone app?!? awesome!
