### ISSUE TITLE
Feedback mechanism funder + contributor for each project

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#660]
Feedback mechanism so that funders and contributors can comment on the experience they've had working together.

**Comment by owocki** [comment]
this is a good idea

**Comment by PixelantDesign** [comment]
@mbeacom are we still considering delighted?

**Comment by thelostone-mc** [comment]
Since reputation would eventually be part of the system. We could us this as a means to decide the score (kinda like uber ratings which works for both the driver + rider)
In my head -> in most scenarios 

Feedback form for Bounty Issuer
- Rating of Hunter
- (If rating is low -> show options like poor response , submitted work is incomplete / poor quality , others )
- Rating of Gitcoin experience  (prompted once in n times)
- (If rating is low -> ask why )



Feedback form for Bounty Hunter
- Rating of Issuer
- (If rating is low -> show options like low funding, poor response , tight timelines, scope creep, others )
- Rating of Gitcoin experience  (prompted once in n times)
- (If rating is low -> ask why )


It's not more than 4 touch points in worst case scenario and 2 in best case scenario 
Need to figure out when to prompt the gitcoin experience question ( Cause it ends up being annoying to ask them to fill it out the gitcoin experience -> not sure how we'd go about this )

**Comment by PixelantDesign** [comment]
@thelostone-mc should we build this?

**Comment by thelostone-mc** [comment]
We can build it out now ->  but it would be super effective once the reputation system is ready!
Any thoughts @SaptakS @mbeacom  ?

**Comment by PixelantDesign** [comment]
I kind of prefer plug and play but not sure what it would take to get something installed.

**Comment by mbeacom** [comment]
All set via Hotjar.  Dean Ramadan with marketing and the rest of the GC/CF team now have access to Hotjar.

**Comment by thelostone-mc** [comment]
Closing this cause we've got hotjar \m/
