### ISSUE TITLE
Granular Hackathon Email Subscribe/Unsubscribe

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6621]
### User Story
As a Gitcoin Hackathon registrant I want to be able to manage which emails I receive when I register for a given hackathon.

### Why Is this Needed
We currently send emails to all users who have registered for a Gitcoin hackathon. Hackers have reached out asking how they can unsubscribe from specific kinds of emails (like workshop invitation calendar invites) and hackathon-related emails as a whole.

We need a way to let users subscribe/unsubscribe from specific kinds of hackathon email communications, in a way that is in sync with one's general Gitcoin profile communication preferences.

### Description
*Type*: Feature

### Current Behavior
Emails sent to all hackers who registered, need to manually remove Gitcoin users' email from our DB or remember who not to send emails to in a given hackathon.

### Expected Behavior
Ability to select/deselect hackathon preferences alongside other preferences, both on the hackathon page during registration and anytime at https://gitcoin.co/settings/email/

### Definition of Done
-Flags in db for whether someone wants to subscribe/unsubscribe from specific hackathon emails
-Expose checkboxes to user in https://gitcoin.co/settings/email/
-Expose checkboxes to user upon hackathon registration
-Queries we can run that exclude unsubscribed hackers when we pull emails to contact participants
-A way to subscribe/unsubscribe a user from hackathon emails as an admin

Kinds of emails we want to have explicit consent for:
-Hackathon-related administrative update emails
-Reminder emails (Hackathon is live, create a project, 72 hrs left to submit, etc.)
-Hackathon workshop email invitations
-Share email with sponsors for promotional purposes

### Data Requirements
Will need to merge the subscribe/unsubscribe preferences between the current hackathon list (on Mailchimp) and SendGrid.

Would be great to get metrics on subscribes/unsubscribes and what led people to take that action.

### Additional Information

**Comment by alexvotofuture** [comment]
@vs77bb @connoroday Anything I'm missing on the categories of emails we'd need people to opt in to?

**Comment by hydr063n** [comment]
Hi @frankchen07 @alexvotofuture @vs77bb @connoroday @owocki 

I’m stuck at the crossroads with the following data requirement:
_Able to merge the subscribe/unsubscribe preference between the currrent hackathon list on mailchimp and sendgrid_

This whole issue requests that each hackathon event have its own separate email preferences from other hackathon events. So I’ve designed the following data model for them:

![Data model](https://i.imgur.com/Kiw503T.png)

This will enable rendering the preferences for each hackathon separately on the profile settings and hackathon guide/onboard.

![Profile settings](https://i.imgur.com/eHGxiqr.png)

![Veep Hackathon guide/onboard](https://i.imgur.com/SkRJoYR.png)

![TricOrTreat Hackathon guide/onboard](https://i.imgur.com/Re0eqkW.png)

With regards to where to save these email preferences I thought about the tradeoffs of storing them in Gitcoin’s internal database or storing them in the Mailchimp/sendgrid contact list (via [tags](https://mailchimp.com/help/getting-started-tags/)) . I believe storing the data in mailchimp/sendgrid makes filtering the data during the mass email easier with their built in filtering tools. As opposed to storing it in Gitcoin internal databases which will require implementing internal filtering queries.

After doing some research on the codebase, I’ve seen that there’s only one giant hackathon list stored at mailchimp and accessible via `settings.MAILCHIMP_HACKER_LIST`.

There’s two ways this data model can be merged into mailchimp and sendgrid:

### 1. One giant hackathon email list:
After doing a little research the best way I can see storing the preference data is by [creating tags](https://mailchimp.com/help/getting-started-tags/) and attaching them to the user profile (according to what they have selected) with the hackathon event slug as a prefix eg `veep_hack:reminder`, `veep_hack:workshop_invite`, etc. When someone wants to send out a workshop invite they can just select the `veep_hack:workshop_invite` tag to filter the list.

For Sendgrid I can’t find an attribute associated with email contacts that enables me to store extra data.

The downside to this is that deletion queries to remove the unwanted tags will have to be implemented to execute when the hackathon event ends to ensure the dataset remains lean.

### 2. A separate hackathon email list for each hackathon event:

The integration with Mailchimp will be smooth, since their premium account allows for unlimited audiences/lists. The email preferences stored as tags on the user’s profile would be readable (because they won't need the hackathon slug prefix) like in the screenshot below eg just `reminder` or `workshop_invite`. When a reminder mail is sent out the sender can just select the reminder tag. The data would be neatly segmented.

![Hackothon email audience/list](https://i.imgur.com/VApSzJI.png)

![Sending out an email with a tag selected](https://i.imgur.com/7zbWXIc.png)

I’m not sure how this will go down for Sendgrid since they only allow about [25 suppression groups](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/groups.html) for each user.  There probably won’t 25 hackathons running at once, so to handle this number correctly I could delete a group every time a hackathon event is over. (This goes for Mailchimp too if we can only create about 5 and lower audiences/lists.)

This deletion also make sure the dataset remains lean. And the process of just deleting the list is easier than running a deletion query if the data was stored on on giant hackathon list.

---

Both ways will require calling the Mailchimp/Sendgrid API a couple of times in order to render and save the preferences where their checkboxes are exposed, namely, the Profile Settings and Hackathon Guide pages . In order to adhere to [API rate limits](https://mailchimp.com/developer/guides/get-started-with-mailchimp-api-3/#Reduce_response_time) I’ve considered storing the preferences in cache and only requesting the data when the cache is empty and during a save preferences operation.

What do you as Gitcoin’s core team think is the best way to go about this? 
1. Store the dataset with sendgrid/mailchimp and retrieve through the api utilizing the cache to lower [API request count](https://mailchimp.com/developer/guides/get-started-with-mailchimp-api-3/#Reduce_response_time). 
If yes, 
(a) keep the hackathon contact list as on giant list or 
(b) segment it into a seperate list for each hackathon event.

2. Store the data in Gitcoin’s internal and expose queries to return the require list and dump into mailchimp/sendgrind before sending?

**Comment by frankchen07** [comment]
hey @hydr063n - first off, thank you for the comprehensive write up. Just wanted to let you know I'm sorting through it, and will respond in a bit after I confer with engineers. We're juggling alot, but want to make sure you're not ignored!

**Comment by hydr063n** [comment]
@frankchen07 thanks it's no worries. Plz excuse the length, I wanted to make sure my point was understood 😅
