### ISSUE TITLE
Identify Trust Wallet (instead of Metamask)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#680]
https://github.com/TrustWallet/trust-web3-provider

If the user is using a non metamask wallet, we should be able to handle that in both name / imagery:

![unnamed](https://user-images.githubusercontent.com/513929/37733605-4543c8d4-2d0e-11e8-816f-9836058b28dc.jpg)

**Comment by kziemianek** [comment]
Seem's like gitcoin works well with trustwallet so this issue involves only icon/text modifcation. 
What about changing metamask icon to 'wallet' or 'ethereum' and replacing metamask word with 'wallet' ?

**Comment by jvluso** [comment]
I'd like to also be able to use the frame provider. https://github.com/floating/frame . Some of the hardcoded references to metamask appear to have been added back in when privacy mode was introduced.

**Comment by ceresstation** [comment]
Hey @owocki wanted to bump this once more just since it came up in conversation today.

**Comment by owocki** [comment]
its in the green team sprint backlog

**Comment by ceresstation** [comment]
Hey @octavioamu we don't have to prioritize this ticket for the coming sprint as we won't be able to announce the integration at Aracon, we should aim to do this by end of March though but if you have other items you think are more important I think we can put them ahead.

**Comment by octavioamu** [comment]
@ceresstation Just to know, why won't be able to announce the integration at Aracon? 
Anyway I believe as you is very important to handle All wallets or as many as we can. Not sure if you was able to check in the channel but this is the current progress so far
https://share.vidyard.com/watch/PjEbzuatUY7R941EpCULq8

**Comment by kuhnchris** [comment]
@octavioamu did this ever make it to prod?

**Comment by octavioamu** [comment]
not sure this original ticket has a merged PR my video is about using opera wallet

**Comment by kuhnchris** [comment]
guess i'll have to throw the question back to you then @owocki . :-( (sorry)

**Comment by octavioamu** [comment]
but what do you want to know?

**Comment by kuhnchris** [comment]
I just wanted to know if:
a.) this issue is still being relevant
b.) there are still hardcoded references to metamask and
c.) if this was superseeded by your aforementioned PR. 

Thanks!

**Comment by octavioamu** [comment]
answering from my side
a) I believe making gitcoin open to other wallets more than metamask is very relevant.
b) yes the metamask code is not modularised that why I just added support to opera just to tips in my pr.
c) My approach is kind of more general to use add web3js and use it, with that adding support to opera, wallets browsers etc. Not sure about "trust wallet" specific.

One of the things I tested is metamask mobile, and is not working on gitcoin, this time because the browser version they use is old and github doesn't support it, so you can't login into github there. (I already submitted a feedback for them about this)
