### ISSUE TITLE
When you make tips in the Town square, the info message should not get duplicated

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6846]
**Describe the bug**

When you make multiple tips in the Town square, the info message saying that the payment got sent should not be duplicated as you can see here: 
![image](https://user-images.githubusercontent.com/50027175/84566061-6f16e280-ad6e-11ea-9978-7126333c8dfa.png)
I've experienced this issue only this week, I think it might have to do with the recent web3 deploy
**To Reproduce**

Make a tip to multiple users and you will see info messages appearing

**Expected behavior**

Only one info message should be there and if you are making more than 1 tip, it should just get overwritten and then after some time, it should disappear alone. That's how it behaved in the past

**Desktop (please complete the following information):**

- OS: Pop_OS!
- Browser: Chromium
- Browser Version: Version 79.0.3945.130 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by octavioamu** [comment]
@Solexplorer actually this was intentional but, wonder what others think. 
The reason why I removed the timeout on that alert was because other wallets (like fortmatic)  create a modal to interact with the wallet, and fortmatic doesn't auto close it when finish the transaction. With that, you don't have time to click the link on our alert.
That was the reason on removing the "auto remove alert".
Should be come back with it?
