### ISSUE TITLE
Only 3 out of 13 "shopping cart" contributions are appearing in Gitcoin

### ISSUE THREAD

**Issue by dmihal** [gitcoinco/web#6882]
I used the shopping cart feature to make the following contribution:

https://etherscan.io/tx/0x794e93d7f8fe23d8bbda41426ac12e7e76b79dcfb8f6317c78acaa828d3244d7

However, in my profile, I only see 3 of those contributions listed
https://gitcoin.co/dmihal
![image](https://user-images.githubusercontent.com/1661138/84712573-54479800-af3f-11ea-888c-c73e6c088199.png)

**Comment by mds1** [comment]
@owocki Can you check if these were properly logged in the DB? Can't tell if this just a display error or if the actual POST requests were not sent.

I think it's a display issue because the checkout process shouldn't complete until all requests are sent. Additionally, the requests are sent in order of the donations, and you can see the 3 logged in the screenshot above were not the first three donations as shown below (assuming Etherscan shows this in the correct order, which I believe it should)

![image](https://user-images.githubusercontent.com/17163988/84714304-27d15300-af22-11ea-996a-cac9d0bd80ef.png)

**Comment by owocki** [comment]
they are not properly in the DB no.  we are going to have to re-ingest them unfortunately, i think that the nginx rate limiter got them.

@dmihal thanks for the bug report. well get these properly loaded as soon as we can hack together a script to do oso

**Comment by dmihal** [comment]
Any idea when these contributions will get re-indexed?

I made sure to contribute early to provide some signal for grants. Many of these grants still display 0 contributions on the site.

**Comment by owocki** [comment]
im super underwater rn, and i wasnt havent any luck ingesting the existing txns with a script with the time pressure, so i just contributed to these grants myself under your username, so that the grants could get the signal.

heres the cart if you need to reference it or access it https://gitcoin.co/grants/cart/bulk-add/653,596,584,576,329,275,237,223,220,199,40,740,152

hope thats ok

**Comment by dmihal** [comment]
Awesome, thanks for your hard work @owocki!
