### ISSUE TITLE
grants - 2 tx need to be saved, 1 is

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6895]
this is an approve and transfer from grants round 6 to the rotki grant

https://etherscan.io/tx/0xfbc9320cac2f41ea0d120d86b89d3457ed75463ec3ad992d8c7b90cd22b10b4f
https://etherscan.io/tx/0xe6fab7e707b9e4cafd0bd1d5996af725e50b7c3c3718cec0accbbab4be14218e

when i look at it in the DB, it looks like only the first txn is saved in our DB. https://bits.owocki.com/X6uooYNy

can i get the 2nd txn (the actual xfr, 0xe6fab7e707b9e4cafd0bd1d5996af725e50b7c3c3718cec0accbbab4be14218e) isnt saved to the DB. it should be in the split tx field

**Comment by mds1** [comment]
Huh, that is odd.

Both the approval tx hash and the donation tx hash are included in the same payload, and the function is only called once the donation tx hash is received.

https://github.com/gitcoinco/web/blob/6b76d0fab333a7232c0c39d43ed3a6b8e6968e70/app/assets/v2/js/cart.js#L625-L628

@apbendi Any ideas on the cause here?

**Comment by owocki** [comment]
@mds1 good call. i think 940e6041702b1d2b1e8a747d00838e25355f2202 should fix this. testing now

**Comment by owocki** [comment]
yay it works. thanks @mds1 ! https://bits.owocki.com/BluOOQmP
