### ISSUE TITLE
Wallet Connect Tx's Not Showing In Matching

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6896]
This grant not showing any tx's: https://gitcoin.co/grants/275/walletconnect-2

But in DM, there are at least 2 onchain tx's? Will keep thread update with more info. 

![image](https://user-images.githubusercontent.com/23297747/84812070-d5546d00-afdb-11ea-9beb-d5595940bf09.png)

**Comment by vs77bb** [comment]
![image](https://user-images.githubusercontent.com/23297747/84819208-a80cbc80-afe5-11ea-86c4-1dbaf6de90a6.png)

@mds1 @apbendi would be curious if you can take a look here, seems high priority if true across site

https://etherscan.io/address/0xcBec15583A21C3ddAD5fab658be5b4FE85Df730b#tokentxns

**Comment by mds1** [comment]
Looks like this is the same cause as #6882 

@owocki pushed a fixed for that issue earlier today, where bulk transactions with over 3 donations don't all get logged. It looks like WalletConnect has 4 donations this round:
- The two from today show up as expected
- The two from yesterday don't, because of the issue from #6882, and you can see both of the ones from yesterday were cart checkouts with over 3 donations

Unless this is a separate case, I don't think it should happen again going forward. Those two missing ones will be fixed in the UI by the end of the round once we write a script to add missing DB entries

**Comment by vs77bb** [comment]
Sweet sounds good. @owocki also mentioned he noticed another fix he needed to make here which would clear up why his tx (made today) wasn't loading
