### ISSUE TITLE
tx validator does not handle correctly when there are two transfers to the same eth addr

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6911]
grants tx validator does not handle correctly when there are two transfers to the same eth addr

it does not know which one to validate, and if it picks the wrong one itll look like the txn failed

https://gitcoin.co/_administrationgrants/contribution/21453/change/?_changelist_filters=success%3Df

**Comment by owocki** [comment]
https://gitcoin.co/_administrationgrants/contribution/21650/change/?_changelist_filters=success%3Df

https://gitcoin.co/_administrationgrants/contribution/21602/change/?_changelist_filters=success%3Df

**Comment by danlipert** [comment]
@mds1 here's another to look into

**Comment by mds1** [comment]
A few questions on this:
1. I don't have access to those links, so could you send me screenshots of the relevant info / post them here? 
2. The validation process is handled in `process_grant_contribution()` of `app/grants/tasks.py`—is that correct?
3. Just want to make sure I'm understanding this issue—this happens when one bulk donation has 2 or more transfers, whether ETH or tokens, to the same destination address?

**Comment by owocki** [comment]
i've put in some fixes in for this using the live data. ill take this one.
