### ISSUE TITLE
Participants tab isn't showing the correct numbers.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#7051]
**Describe the bug**

The participants tab on a hackathon's page is not displaying the correct number of participants

**To Reproduce**

1. go to any hackathon prize explorer view and look at the participants tab with the number after it

<img width="1267" alt="Screen Shot 2020-07-01 at 11 31 59" src="https://user-images.githubusercontent.com/7516920/86279524-006bbe80-bb8f-11ea-87ec-fb442a3719b8.png">

2. compare to metabase registrant numbers

![Screen Shot 2020-07-02 at 23 51 02](https://user-images.githubusercontent.com/7516920/86440233-f3e68380-bcbe-11ea-8d9b-f882ec3925fb.png)

**Expected behavior**

registrants and participants counts should match

**Comment by walidmujahid** [comment]
Where is the metabase number coming from? Or perhaps: what do mean by 'metabase'?

Currently, the `hacker_count` for the page is the counting all `HackathonRegistration` instances. After tests in my local docker build, I believe I have identified a design oversight in the `hackathon_registration` endpoint connected to the onboarding page. When "Join Now" is pressed on the onboarding, a user can continue pressing the button from the frontend and the `hackathon_registration` endpoint will continue creating duplicate `HackathonRegistration` instances.

Now, the most straightforward solution to this probelm that I can think of is to just use whatever queryset or method that the metabase number uses. 

However, correcting the `hackathon_registration` endpoint design flaw by adding some validation would also solve this problem and should be done anyway in my opinion -as a separate issue although it may be connected to this current issue. Furthermore, changing the query for `hacker_count` for the hackathon page so that it ensures dinstinct users per hackathon event could be of benefit.

**Comment by frankchen07** [comment]
the metabase number is just counting distinct profile_ids that have completed the registration. 

It could be that the participants number is just creating duplicate hackathon_registration instances, and that is being counted more than once. It seems to make sense because the participants number is higher than the metabase number.

in our case metabase = psql database that I'm working off of.

**Comment by walidmujahid** [comment]
> the metabase number is just counting distinct profile_ids that have completed the registration.
> 
> It could be that the participants number is just creating duplicate hackathon_registration instances, and that is being counted more than once. It seems to make sense because the participants number is higher than the metabase number.
> 
> in our case metabase = psql database that I'm working off of.

Okay. I believe then counting distinct registrants should solve this problem. PR opened: https://github.com/gitcoinco/web/pull/7071

I opened another issue for the duplicate `HackathonRegisteration` instances: https://github.com/gitcoinco/web/issues/7070
