### ISSUE TITLE
DESIGN - As a grant contributor, I want new & more powerful ways to select the amount I contribute to each grant, so I can express my preferences efficiently and accurately

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7133]
per vitalik, the whole idea of QF is to express varying degrees of preference.  

so we need to add tools that easily allow them to express preference differently across diff grants

SOME options:
<img width="575" alt="Screen Shot 2020-06-23 at 9 54 22 AM" src="https://user-images.githubusercontent.com/513929/88062923-ab382280-cb26-11ea-84ac-2a921f6b7de0.png">
<img width="567" alt="Screen Shot 2020-06-23 at 9 54 27 AM" src="https://user-images.githubusercontent.com/513929/88062929-ad9a7c80-cb26-11ea-9de8-cea6529d5200.png">
<img width="1204" alt="Screen Shot 2020-07-21 at 7 46 09 AM" src="https://user-images.githubusercontent.com/513929/88062937-affcd680-cb26-11ea-86c7-6a3562b7bc5d.png">

(Sorry I can't compelte this ticket more, I think its going to depend on Alisas convo with Vitalik what comes out of this)

**Comment by owocki** [comment]
@PixelantDesign is this ongoing?  should i back it out of the backlog for round 7 + reconsider for round 8?

**Comment by PixelantDesign** [comment]
![Match_Visual](https://user-images.githubusercontent.com/238235/90466751-8cef2380-e0e0-11ea-891d-a4364533fe8b.png)

In general a screen in between directly adding to cart will be another step in in the decision making. I'm thinking we should provide a few options that users can click without having to think too much as well as a diagram option for those who really want to play with it. It definitely adds effort. Curious what you think @owocki

**Comment by apbendi** [comment]
Something to consider on this: the algorithm is going to return some pretty weird numbers early on in the round, here. Also, do these designs make it clear that this value will change (often drastically!) by the time the round en ds?

**Comment by walidmujahid** [comment]
This looks like an interesting thing to work on. I am not very familiar with the proposed algorithm/Vitalik's conversation, so is there a potential link to read up on or listen to? And also, might there be dummy data available for local use to save some time?


@PixelantDesign I am slightly conflicted between options. I like both for different reasons. The first option I like because the custom and suggested contribution amounts are visibly separate while, on the hand, in the second option, it is kind of confusing to see the custom amount field while also having a suggested amount field selected. As for what I like in the second option that is not in the first is that the graph is visible for all amounts.

Perhaps, to take inspiration from both options, we could  take option 2 and hide the custom amount section behind a selection box -of similar design or perhaps different to the slect boxes of the suggested amount in option 2- while greying out and disabling the suggested options if custom amount is selected. This way, it takes the single view strengh that I personally think is in option 2, while removing some potential confusion.

**Comment by walidmujahid** [comment]
@owocki I would be interested in taking this on, however, I will need to familiarise myself with how QF is implemented in Gitcoin -an area which I have yet to touch/look at in detail. As well as it would seem that further discussion on the algorithm design is needed for Vitalik's suggestion. Has the mentioned conversation between Alisas and Vitalik happened?

**Comment by walidmujahid** [comment]
@owocki I would be interested in taking this on, however, I will need to familiarise myself with how QF is implemented in Gitcoin -an area which I have yet to touch/look at in detail. As well as it would seem that further discussion on the algorithm design is needed for Vitalik's suggestion. Has the mentioned conversation between Alisas and Vitalik happened? 

Also, I am not sure if this can be accomplished by Round 7.

**Comment by owocki** [comment]
@walidmujahid we never got a response from vlitalik, so we are deprioritizing this for now.

**Comment by walidmujahid** [comment]
> @walidmujahid we never got a response from vlitalik, so we are deprioritizing this for now.

Understood.
