### ISSUE TITLE
normalize early

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7250]
@thelostone-mc @fronk is there an easy way to make the gitcoin grants round reach saturation later in the round?  we chatting with @vivek on our 1:1 today about how to make the grants round less zero sum for less time

rest of the convo is here https://gitcoincore.slack.com/archives/CBDTKB59A/p1597787033020200

**Comment by thelostone-mc** [comment]
@frankchen07 + me synced up and we'll be implementing what we discussed the other day 
which is 

until the clr match doesn't exceed the actual pot.
we'll have a pseudo total pot which is x% higher than the clr match 

This would give the feeling that that pot is growing slowly as contributions come in so that grant owners don't feel like each time another contribution comes in -> they end up losing a small chunk of the match.
