### ISSUE TITLE
kevins grants feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7445]
- https://bits.owocki.com/RBuOQdW1 - why does the 'verify my nubmer' show up here + the trust tab?  we should just defer all verification stuffv to the trust tab
- would it be easy or hard to have the cart estimates update itself every few hours? https://twitter.com/owocki/status/1306318254395109376

**Comment by owocki** [comment]
- when i first create a grant, its not put in any active CLR rounds upon creation, leading to emails likst this https://bits.owocki.com/p9uGqKyG

**Comment by thelostone-mc** [comment]
> when i first create a grant, its not put in any active CLR rounds upon creation, leading to emails likst this https://bits.owocki.com/p9uGqKyG

^ this get's picked up when the clr estimate runs ! 
We could invoke that section of the code at grant creation as well 🤔

**Comment by owocki** [comment]
would it be easy or hard to have the cart estimates update itself every few hours?

https://twitter.com/owocki/status/1306318254395109376

**Comment by owocki** [comment]
unpkg causing issues

**Comment by owocki** [comment]
duplicate contribution/subscription objects

**Comment by owocki** [comment]
https://gitcoin.co/grants/1224/yfistats-protocol-dashboard?tab=description

https://gitcoin.co/grants/1224/yfistats-protocol-dashboard?tab=description

hey guys this grant has an ENS name as its address

can we make the grant new form turn ENS names into eth addresses pls?

ill add to a ticket

**Comment by owocki** [comment]
some feedback from EPNS and @androolloyd @mds1 
```
androolloyd Am hearing some complaints about the zk checkout.
8:00 AM
Epns tried to contribute to the kernel panvala league, but ended up with failures and ended up going through zksync directly resulting in I believe an improperly funded account.
8:01 AM
*went through zksync to find before trying to contribute. 100 Dai sitting in some account and contributions not showing up on the grants page.
8:01 AM
Will get post some txns when I get them

From epns:
https://etherscan.io/tx/0xfb4472eaa3a8d3506ac70387fb67f4c94212937fc6d7f5a981e094ebcefeb8e8
https://etherscan.io/tx/0xe7f50c6132c437cfed626a5a058402ae521c5133d7e57093b1edf003bd8fdbb3
https://zkscan.io/explorer/accounts/0xb64c92cda04cce0424febb66a42cab16ef6aa2d0

````

**Comment by mds1** [comment]
Hey @androolloyd, aside from contributions not showing up on the grants page, can you provide any details about what else went wrong during checkout? Both of those Etherscan txs were successful (but I'm guessing they were done manually through zkSync like you said?), and from taking a quick look at the zkScan account it seems the transfers went through as well

**Comment by owocki** [comment]
hey @mds1 - @BitcoinLouie checked out with a 35 dai cart by depositing 100 DAI into zksync on brave/metamask, but it didnt recognize the DAI deposit.

**Comment by Bitcoinlouie** [comment]
Thanks Kevin!
I'll share the full experience here.

UserName: BitcoinLouie <https://gitcoin.co/bitcoinlouie>
Browser: Brave (shields disabled)
Wallet: Metamask w/ ledger
Balance: 100 DAI

Cart was 35 DAI + 0.1 ETH. The ETH was an accident because one of the users
didn't accept DAI.
1st error - unable to approve ETH token spend. (no big deal)
I decided to send 100 DAI to my https://wallet.zksync.io/ wallet.
Deposit Successful.
Balance: 0 DAI in Metamask | 100 DAI in zksync
Check out attempt #2 hoping it will recognize 100 DAI in zksync but ERROR
shows Metamask has low balance.
I withdraw DAI back to MM wallet. This leads to 3 hour wait for zkblock to
process.
I fund MM with more 40DAI from another wallet.
Check out attempt #3, ERROR of low balance. Balance: 40 DAI -> cart wants
40+ but UI showed 33 DAI subtotal.
Removed some donations to bring it down to 28 DAI subtotal.
Check out attempt #4, was successful with 28 DAI subtotal and 40 DAI
balance.

Final Note: I received an email it was accepted but the website didn't
visually show donations successful until a few hours later.

All in all, the donations are complete so I don't need any additional
support. Just wanted to share the customer journey for improving UX. 👍
I will be doing another round later so I'll try and screen record if it
helps.

**Comment by Bitcoinlouie** [comment]
Correction: Account linked to Metamask /no ledger. Ledger is 2nd wallet I
use to fund.

Ok, donation round 2: Error is shown at 11/36 transactions, red bar up top
(I closed), Window has been open for 40 minutes. 1 email confirmation of 1
donation was successful, although 47.55 DAI tx completed. <
https://etherscan.io/tx/0x95797e9e446a915caa4f07fcf8882cac9f068e03ca3d424f95bd2eed87566770
>
[image: image.png]

**Comment by owocki** [comment]
just got this erorr when checking out. https://bits.owocki.com/xQuLy6P2

i think its because my metamask wasnt logged in when the page loaded. IMHO we should default to mainnet currency list, or fix this when the user does log into metamask @mds1

**Comment by owocki** [comment]
dropped/replaced txns not working

...we have a task to implement blockscout txid tracking; but hasnt been done yet

sorry blocknative; jinx

**Comment by mds1** [comment]
@Bitcoinlouie Thanks for all the details! I have a few follow up questions just to make sure I'm understanding what went wrong so I can fix bugs.

> 1st error - unable to approve ETH token spend. (no big deal)

Spending ETH does not require an approval transaction, so just want to check what exactly you mean here?

> Balance: 0 DAI in Metamask | 100 DAI in zksync
> Check out attempt #2 hoping it will recognize 100 DAI in zksync but ERROR
shows Metamask has low balance.

How long was it between this error and the time you deposited into zkSync? It takes about 2-3 minutes for your deposit to be finalized and recognized by zkSync, so it's possible that was the error

> Check out attempt #3, ERROR of low balance. Balance: 40 DAI -> cart wants
40+ but UI showed 33 DAI subtotal.

The amount in the UI doesn't show fees, so that explains the bug here. The amount in cart + the fees (in DAI) required were over 40 DAI. We'll be fixing this to make it more clear what the fees are! You can read more about this in https://github.com/gitcoinco/web/issues/7469 if interested

> Ok, donation round 2: Error is shown at 11/36 transactions, red bar up top
(I closed), 

I'll have to look into this one. By any chance do you remember what the red bar said?

Thank you!

**Comment by Bitcoinlouie** [comment]
Hi @mds1, ok let me try my best to recall the issue.

> 1st error - unable to approve ETH token spend. (no big deal)

What I remember is a 2nd approval required but tbh I've forgotten now.


> How long was it between this error and the time you deposited into zkSync? It takes about 2-3 minutes for your deposit to be finalized and recognized by zkSync, so it's possible that was the error

I had DAI in zksync wallet for 2 hours with no luck. BUT recently it worked perfectly fine so maybe an early bug.

> The amount in the UI doesn't show fees, so that explains the bug here. The amount in cart + the fees (in DAI) required were over 40 DAI. We'll be fixing this to make it more clear what the fees are
Gotcha, now I make sure to have enough DAI, no problem.

> Error is shown at 11/36 transactions, red bar up top.
Unable to replicate this error. All donations were successful regardless. 

Thanks for your support!

**Comment by owocki** [comment]
still getting a lot of questoins like this one: https://bits.owocki.com/wbuPor7Q

it'd be great if the cart match amounts could refresh when the user goes to cart.  @mds1 @thelostone-mc pls sir

**Comment by owocki** [comment]
grant page looks like crooked teeth. design bounty to fix?

**Comment by owocki** [comment]
Total CLR Match Amount  on checkout, for grants i'm a member of, should not show up with a match

**Comment by owocki** [comment]
> Now that I can add my own grant to cart, "Total CLR Match Amount"  on checkout, for grants i'm a member of, should not show up with a match to correctly designate that those contributions are not matched.

@mds1 can we make this change pls?

**Comment by mds1** [comment]
> @mds1 can we make this change pls?

@owocki I'll get a PR in for this today
