### ISSUE TITLE
Insufficient DAI balance to complete checkout

### ISSUE THREAD

**Issue by MysticRyuujin** [gitcoinco/web#7469]
I have 72.622 DAI in my MetaMask wallet / L1 account

I'm donating 70 DAI in total

I click "Checkout with zkSync"

I click "Sign In"

I click "Approve"

I receive big red banner that says "Insufficient DAI balance to complete checkout"

**Comment by owocki** [comment]
thansk @MysticRyuujin can u send us your addr?  what browser/wallet u using?
.
cc @mds1

**Comment by MysticRyuujin** [comment]
`0x61d21716c9af33d522A98ec82bEFE3588f6a76fF`

Linux / Brave / MetaMask

**Comment by mds1** [comment]
Hey @MysticRyuujin, this is the expected behavior.

The zkSync fees are additive (e.g. if you're donating 70 DAI you'll need to provide 70 DAI + X DAI for zkSync fees). We estimate the conservatively to ensure that you don't run out of funds on L2 when doing all the transfers. 

I believe right now each DAI transfer on zkSync is (on average) between 0.10 DAI to 0.70 DAI (the latter being for an address that has never used zkSync, as the initial transfer to it is more costly, and the exact amount is dependent on gas prices and conversion rates). We estimate all fees as "new transfers" to avoid excessively pinging zkSync's server's to get fee estimates for every item in the cart. 

Let's say you had two grants in your cart plus the optional tip to Gitcoin, in your case you'd have:
- 70 DAI in the cart
- 2 transfer to the grants, 1 to Gitcoin, and 1 to transfer any unused DAI back to your regular zkSync wallet (details on that [here](https://github.com/gitcoinco/web/blob/master/docs/GRANTS.md)), which gives you 2.80 DAI in fees putting you at 72.8 DAI which is above your DAI balance

**Comment by MysticRyuujin** [comment]
...uhh... then maybe you should have some sort of fee estimation provided in the UX and some sort of useful message or indication of such requirement / fees. No? I mean...where on this page does it mention these fees?

Not here:
![image](https://user-images.githubusercontent.com/8877131/93653357-29f1f480-f9de-11ea-937b-17a6305904b4.png)

Not here:
![image](https://user-images.githubusercontent.com/8877131/93653384-4d1ca400-f9de-11ea-89aa-684604d0bb95.png)

Finally:
![image](https://user-images.githubusercontent.com/8877131/93653425-79382500-f9de-11ea-9737-302437f2b811.png)

Only by clicking into that 3rd layer deep documentation is the first mention of needing DAI to pay for transfer fees...

**Comment by mds1** [comment]
Yep, good point! If you already have funds in zkSync, the signature prompt in step 3 will show the fee amount denominated in DAI. But in the scenario where you have an L1 deposit for step 3 (like in your case), you're correct that the fee estimate is missing and should be shown to the user.

Hey @PixelantDesign and @willsputra — let me know where/how you think we should display this fee and I can add that in quickly. We only need to display it when the user has an L1 deposit for zkSync, so I'd think somewhere in the modal in a good place?

**Comment by willsputra** [comment]
@mds1 yep! we can put it on a small font under Step 3 inside the modal.

I was thinking we should also put it on the Summary section in the cart (something along the lines of "If this is your first time using zkSync, make sure you have $X (contribution) + $Y (estimated zkSync fees).) What do you think?

**Comment by mds1** [comment]
@willsputra My only pushback about also putting it in the summary section is that then you're showing unnecessary information to users who are doing the standard L1 checkout. Open to being convinced though 🙂

**Comment by willsputra** [comment]
@mds1 hmm true that! yea i guess for now putting it in the modal should be enough

**Comment by mds1** [comment]
#7489 has been deployed, which shows the fees on the modal during checkout
