### ISSUE TITLE
Display github status on issues next to comment count?

### ISSUE THREAD

**Issue by dolebas** [gitcoinco/web#749]
### User Story

As a user who wants to claim issues, I want to see which issues are open/closed on github so that I can assume closed issues on github are not likely "open".

### Solution

Add github open/closed status next to the github comment count?

**Comment by owocki** [comment]
We should also maybe have the github issue status affect the gitcoin issue status

**Comment by dolebas** [comment]
Either of would be great!

**Comment by PixelantDesign** [comment]
Would filtering by open/closed help here?

**Comment by PixelantDesign** [comment]
Yes it'd be great if it was in sync with Github!

**Comment by maryam21** [comment]
Hi, I would like to work on this one.

**Comment by pinkiebell** [comment]
Another scenario: The funder closes the issue because some parts got merged into other issues but the bounty still applies.

Would it be better to introduce a 'only open issues on github' filter?

**Comment by thelostone-mc** [comment]
@owocki @PixelantDesign do we still want this ?

**Comment by owocki** [comment]
defer to alisa

**Comment by PixelantDesign** [comment]
#2184 and #2185 could help with this.

I could see using this (!) icon on the issue details, but hopefully our filters should work properly and show the issues that are open.

<img width="59" alt="screen shot 2018-09-10 at 2 43 32 pm" src="https://user-images.githubusercontent.com/238235/45317575-61cd2400-b508-11e8-9245-dcb7f32c70d9.png">

Otherwise, we might have too much clutter on the issue explorer.

**Comment by PixelantDesign** [comment]
Let's see how things are after we launch #2184 and #2185. Closing for now.
