### ISSUE TITLE
Gitcoin tour button (onboarding screen)

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/web#7498]
### Why Is this Needed

We have a lot of new devs, but (start work/new devs) is pretty low. Hence, doing an airmeet session of 1 hour with 30 people where I can give a rundown of gitcoin + share some stories. 

@PixelantDesign @frankchen07 @jdorfman

**Comment by frankchen07** [comment]
Can you fill in additional details on this ticket?

From the slack conversation, I believe we were aligned that right now, we don't need to have product/engineering intervention to actually add any buttons.

In order to successfully measure the success of this initiative, we need to collect github handles (gitcoin handles) so that we can identify by profile ID who has joined our platform. This is the only way we can cohort who has done an introductory call or not, and follow those cohorts over time.

The results of this experiment won't be evident until 5-6 weeks down the line, when we get the first bit of retention. It is probably possible to set up some kind of histogram of frequent actions to see if they're initially performing actions beyond just logging in and visiting Gitcoin.
