### ISSUE TITLE
Incorrect "Insufficient DAI balance to complete checkout" Error

### ISSUE THREAD

**Issue by jo-tud** [gitcoinco/web#7508]
**Describe the bug**
When using zkSync checkout the UI incorrectly shows the error "Insufficient DAI balance to complete checkout". 

**To Reproduce**
Put stuff in cart. Pledge DAI. Use zkSync to check out. Complete step 1.
My DAI balance is about 1 DAI higher than what is needed. But the process fails with the above error message.

I'm using an Argent wallet connected through WalletConnect.

**Expected behavior**
Check out proceeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/1543640/94017465-c38b1e80-fdaf-11ea-84fe-81915c2b1418.png)
I debugged a bit and it seems that `totalRequiredAmount` contains the wrong amount.

**Desktop (please complete the following information):**

- OS: fedora
- Browser: chrome
- Browser Version: current

**Comment by mds1** [comment]
Hi again @jo-tud 🙂

This is the expected behavior, but it's currently not clear in the UI
- PR https://github.com/gitcoinco/web/pull/7489 is a fix for this waiting to be deployed
- Issue https://github.com/gitcoinco/web/issues/7469 has more details, as does [this page](https://github.com/gitcoinco/web/blob/master/docs/GRANTS.md)
- [This comment](https://github.com/gitcoinco/web/issues/7469#issuecomment-695126435) from the above issue explains what's going on.

Let me know if you have any more questions!

**Comment by mds1** [comment]
If you don't want to wait for it you can roughly estimate the total amount as `amount in cart + 0.80 * (number of items in cart + 3)`

Basically the 0.80 DAI value is the current the worst-case fee per transfer (typically this is ~0.10 DAI). We multiply by number of zkSync transfers (and add 3 to account for Gitcoin's tip if you had that checked, then 2 additional transfers required by the architecture explained in the GRANTS.md doc linked above)

**Comment by mds1** [comment]
Going to close this one, but feel free to re-open if you still have issues insufficient balance issues!
