### ISSUE TITLE
zkCheckout Issues

### ISSUE THREAD

**Issue by leafs4life** [gitcoinco/web#7509]
**Describe the bug**
Tried zkSync Checkout on Sept. 19th, and although the payment window estimated that it would take 2-4 minutes, after 40+minutes, it was still pending. So, I went into MetaMask and "sped it up", which then "dropped and replaced" that tx.

Interestingly, inside the zkCheckout window, it never showed as confirmed/paid, however, when I check my Gitcoin account history, it does show that all of the grant funds that I made DID, in fact, go through. So, I thought, great! 

After listening to the Bankless podcast today, I was fired up and wanted to give back even more, and was determined to use L2! 

For the first hour or so, time after tim e when I tried to use zkCheckout the loading screen would pop up, and after spinning for some time, a red "network error" message would appear on the top of the webpage, and I would start over. 

I logged out and in, disconnected and reconnected my MM wallet, and still the same. 

Magically, I tried again (an hour or so later), did nothing differently, and it worked *hooray*...sorta...(screenshot attached below)

So, now, the zkCheckout window loaded, BUT, it is still pending, and it tells me that I must complete the checkout process that was not completed before, and when I click on the link to etherscan, it takes me to the tx from the 19th...that was dropped and replaced, NOT to the successful tx that replaced it...

SO, it seems that I'm stuck in some sort of zkCheckout death spiral because it seems to want me to finish the "dropped and replaced" tx, that is, in fact, successful, before I can give any additional money via L2! 

PLEASE HELP! 

**To Reproduce**
Not sure, but perhaps speeding up a tx that is taking longer than expected with MM, would be able to reproduce this error. 

**Expected behavior**
I expected that once the sped up tx was successfully mined, which it was, I would be able to go back into gitcoin and again use zkCheckout to fund more projects. 

**Screenshots**

![Screen Shot 2020-09-23 at 2 39 03 PM](https://user-images.githubusercontent.com/59677184/94021306-d5d87d00-fdee-11ea-8a34-beac7a1031ce.png)

![Screen Shot 2020-09-23 at 2 40 50 PM](https://user-images.githubusercontent.com/59677184/94021347-dffa7b80-fdee-11ea-86f4-5c971b05abd0.png)

![Screen Shot 2020-09-23 at 2 40 56 PM](https://user-images.githubusercontent.com/59677184/94021398-edb00100-fdee-11ea-84e5-855a9c221a23.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.6
- Browser: Chrome
- Browser Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hi @leafs4life, sorry for the struggles!

So as you may have guessed, what happened is that you never actually finished the checkout from your dropped/replaced transaction. This is because the backend function that typically manages dropped/replaced transactions is down and we need to fix it. Gitcoin optimistically assumes things will succeed, which is why you thought everything was complete.

Can you send me the Etherscan links to the original and replaced transaction hashes? I can then update the backend manually with your new transaction hash. I'll let you know once that's complete, then you can revisit the cart page, it will prompt to finish the checkout (for real this time!), and then you can make more donations afterwards

**Comment by leafs4life** [comment]
Hi Matt,

Thanks for the quick response.

I can't seem to get back to the original tx hash, but I can get to the
replaced (and successful) tx hash
here: 0x2bb2dcb0b7d84e78ba6ba59499648524651a1264fd4c59efc79bf4e4f69a8b05

Also, just now, I clicked on zkCheckout, just to see what would happen, and
I got a new error message: "Cannot read property 'status' of null"

[image: Screen Shot 2020-09-24 at 8.20.42 PM.png]

However, I was able to close that and carry on with the tx, but, I noticed
a massive discrepancy in the estimabted tx cost: 1.414DAI
[image: Screen Shot 2020-09-24 at 8.22.04 PM.png]
And a $7.52 gas fee estimate in MM:

[image: Screen Shot 2020-09-24 at 8.21.57 PM.png]

So, I rejected the tx, until I heard back from you!

Thanks in advance!

Jason

**Comment by mds1** [comment]
I just updated things on the backend so if you go back to the cart page, you should be able to complete checkout successfully now!

I can't see the images you sent. Perhaps because you replied via email they don't show up on GitHub?

To clarify the fees:
1. Since I just updated the backend, your MetaMask tx is complete and the fees were already paid in the tx hash you provided. So you won't need another MM transaction!
2. There are two fees, so I can see how that is confusing: The amount shown in MM is the cost to deposit funds into zkSyn, which you already did. The fees shown in the modal (denominated in DAI) are the fees to execute the zkSync transfers (and these fees are usually much lower than the estimate you see)
