### ISSUE TITLE
ZkSync Checkout Issue for Refreshed Page

### ISSUE THREAD

**Issue by GWintery** [gitcoinco/web#7541]
**Describe the bug**

On step 3 while **waiting to confirm** deposit to L2, when the page is hard refreshed, the checkout page does not recognize the current transaction that was still pending.

Currently my current transaction is already deposited to the L2 (as seen in the ZkSync block explorer), however I do not see those funds being moved after the deposit (which I thought should be moved to the projects' ZkSync accounts), not sure if this is normal.

**To Reproduce**

Go through the ZkSync checkout process
On any of the steps press CTRL+F5 to hard refresh
You will have to repeat all the previous transactions, even if you already have a pending one ongoing/finished.

**Expected behavior**

After a CTRL+F5 I believe we should not have to reconfirm the ERC-20 token spend.
A successful deposit even after a hard refresh should be processed.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 86.0.4240.53 (Official Build) beta (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hey @GWintery, you're right that it should have recognized your deposit after the refresh. The expected behavior is that once you re-visit the cart page you should see a prompt asking you to complete checkout, and once the L1 deposit transaction is complete it will initiate the zkSync transfers.

Can you send me the L1 deposit transaction hash so I can see what went wrong here and get this resolved? If you don't want to share it publicly feel free to message me on Twitter @msolomon44, or Telegram @msolomon4

**Comment by mds1** [comment]
Worked with @GWintery to get this resolved so checkout is now completed
