### ISSUE TITLE
Don't require re-approving ZKSync approval each time

### ISSUE THREAD

**Issue by dmihal** [gitcoinco/web#7556]
**Describe the bug**
I need to re-approve each time I try to check out with ZKSync

**To Reproduce**
Check out with ZK Sync. Approve token allowance. Refresh page before completing step 3. When checking out again, the user will need to re-approve.

**Expected behavior**
The site should check the current token allowance and skip step 2 if already approved.

Note: I was able to work around the issue by simply un-disabling the step 3 button using devtools.

**Screenshots**
![image](https://user-images.githubusercontent.com/1661138/94526338-c6509e00-020b-11eb-9c95-631da0b4ab94.png)

**Comment by mds1** [comment]
> I need to re-approve each time I try to check out with ZKSync

This is by design since the zkSync contract is upgradeable. So for security we intentionally don't approve MAX_UINT and only approve what you need + some margin. You can override the amount manually using MetaMask (and maybe other wallets) on the approval screen if you want.

> The site should check the current token allowance and skip step 2 if already approved.

This is what we currently do—if you already have sufficient allowance, clicking Approve will just change to "Not required" instead of prompting you for a transaction. If this wasn't the case for you let me know since there may be a bug!

**Comment by mds1** [comment]
> clicking Approve will just change to "Not required" instead of prompting you for a transaction.

Worth noting that we do it this way instead of showing "Not required" earlier because of the ability to deposit more funds in the "Advanced settings" section. If you change the amount there, your approval amounts change, so the Approve button also acts to lock-in the additional deposit amounts
