### ISSUE TITLE
Cannot donate $PAN through zksync

### ISSUE THREAD

**Issue by makoto** [gitcoinco/web#7572]
**Describe the bug**

Cannot donate $PAN through zksync

**To Reproduce**

- Add https://gitcoin.co/grants/1139/metacartel-builder-awards-panvala-league to the cart
- Donate 150 (or 100 if some of the PAN has to be used to pay the gas)
- Follow 3 steps in the wizard (sign in, approve, confirm)

**Expected behavior**

- After going through the 3 steps, I expect my donation to get confirmed and donated.
- However, the wizard keeps showing spinning button and I see "not enough balance" on console log.
- I tried with 150 PAN as well as 100 PAN and both failed.
- I wasn't quite sure whether I pay gas in PAN or ETH but I had about 0.2 ETH as well so shouldn't be the lack of balance problem.
- I had some tweet exchange with zksync team and they said I was able to `deposit` before going through the wizard but I don't think I have seen any.

**Screenshots**

https://twitter.com/owocki/status/1311417730562617345

**Desktop (please complete the following information):**

- OS:Mac
- Browser:Chrome
- Browser Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

I was able to donate DAI using zksync a day before

**Comment by owocki** [comment]
hey @mds1 know whats going on here?

**Comment by mds1** [comment]
Hey @makoto! Posting the screenshot you shared on Twitter here for convenience.

![image](https://user-images.githubusercontent.com/17163988/94755325-0e290f80-0349-11eb-8aad-2b59d41bf4fa.png)

That modal is the "Complete Checkout" modal, indicating that you never actually finished checkout for your DAI contributions that you did the other day. This can be confirmed by looking at your Gitcoin zkSync account on  [zkScan](https://zkscan.io/explorer/accounts/0x7d585082c45a4d025bc76c62020261ff1dac61c5). You'll see the Deposit for DAI, no DAI transfers to the grants, and failed PAN transfers. This incomplete checkout is likely because you closed the page before waiting for the deposit transaction to be mined and confirmed by zkSync. However, it seems somehow your cart was cleared and you were able to add a new grant to the cart? (Also, if you're wondering what a Gitcoin zkSync account is, see [here](https://github.com/gitcoinco/web/blob/master/docs/GRANTS.md)).

The transfers in the screenshot failed because it tried to transfer PAN (since that is what's in your cart), but you only have DAI in zkSync. First let's complete your DAI checkout, and once you do that, you will get the right modal to complete your PAN donation and it will succeed.

So let's do the following:
1. View the cart page and close that modal once it pops up
2. Remove the existing grant from your cart
3. Add the old grants that you tried to contribute to your cart. It seems you had 8 items in your cart totaling 20 DAI, with amounts of 5, 1, 1, 5, 1, 1, 1, and 5 DAI. If you need help remembering which grants they were DM me on Telegram @msolomon4 or Twitter @msolomon44
4. View the cart page and the complete checkout modal will pop up. Walk through the steps on the modal to finish that checkout
5. DAI checkout completed!
6. Now re-add the MetaCartel Builder Awards grant back to your cart and complete that checkout, and you should be all set

**Comment by makoto** [comment]
Hi, @mds1 thanks for the follow up.

`you never actually finished checkout for your DAI contributions `

@owocki you may have separate bug as I received  "Thank you for supporting ***" emails for all the project I donated.

`5, 1, 1, 5, 1, 1, 1, and 5 DAI` Does the order matter? I can get the list of all the project based on the confirmation email but I don't think they arrived in that order.

**Comment by makoto** [comment]
it also shows on the list of grants I contributed (though in other page it says "pending") at https://gitcoin.co/makoto/grants.

<img width="941" alt="Screenshot 2020-10-02 at 10 12 33" src="https://user-images.githubusercontent.com/2630/94907312-e09eac00-0497-11eb-89f6-399f4b6a4a94.png">

**Comment by makoto** [comment]
Ok, managed to make it work. https://etherscan.io/tx/0x1fe1f4c5c013a87f2be60db70f5c95ba39cb809d7ffe1d1f0c9d876360680126

One extra feedback.

I suggest it shows "Approve" button only if it needs to approve. I already paid for "Approve" transaction when I did initial try so I endedup paying for "approve" twice.

https://etherscan.io/tx/0x1b5f41b6829a18e085a74074dc0ff6d43e01faaeee3391eb05a00eb005f29d61
https://etherscan.io/tx/0xb9d2f0fbc34f46c7871a3c6a5535048eb88d1aae3805b71c25d4ce35838084f1

**Comment by mds1** [comment]
Glad it's worked out! 

> you may have separate bug as I received "Thank you for supporting ***" emails for all the project I donated even when the transaction failed.

Yea this can be misleading, since those emails are sent optimistically before everything goes through. It probably would be better to send those later in the process

> 5, 1, 1, 5, 1, 1, 1, and 5 DAI Does the order matter? I can get the list of all the project based on the confirmation email but I don't think they arrived in that order.

Looks like you figured out that the grant order in your cart does not matter 

> I suggest it shows "Approve" button only if it needs to approve. I already paid for "Approve" transaction when I did initial try so I endedup paying for "approve" twice.

There should only be approval txs when necessary. It seems in this case the original approval was for the regular L1 BulkCheckout contract, whereas the new approval was for zkSync, which is why you had two approval txs.
