### ISSUE TITLE
Failded funding

### ISSUE THREAD

**Issue by kautir** [gitcoinco/web#7650]
I funded a project 11 days ago. Now I noticed my funding transaction was failed. Here is the project that I funded:

https://gitcoin.co/grants/1376/swash-your-data-your-income?tab=transactions

Why the transaction is failed? 
![image](https://user-images.githubusercontent.com/72108515/95679431-a5128900-0bdf-11eb-9ba6-2c89ca19ba98.png)

**Comment by owocki** [comment]
@mds1 the db says "zkSync with L1 deposit. Found deposit but no transfer. User likely closed page before transfers were sent and should revisit cart to complete checkout. User may not be aware so send them email reminders" - i just manulaly marked it as successfsul

**Comment by mds1** [comment]
Hey @kautir, can you visit http://gitcoin.co/grants/zksync-recovery and follow the steps on that page? That will ensure that your contribution made it to the grant owner even though it was marked as failed. Thanks!

**Comment by kautir** [comment]
It get stuck on step 2
![image](https://user-images.githubusercontent.com/72108515/95783538-ea69b000-0cde-11eb-9795-23e89fadc08a.png)

**Comment by mds1** [comment]
Turns out there's now a bug due to a recent zksync update. Let me get a fix in and I'll update this issue to let you know once it's deployed!

**Comment by mds1** [comment]
Ok just deployed an update, give this another try and let me know how it goes!

**Comment by kautir** [comment]
The issue is still there.

**Comment by mds1** [comment]
Do you mind sending me your address and the transaction hash of the original transaction you made on September 29? That will help me debug this. If you don't want to share publicly you can DM me on Telegram @msolomon4 or Twitter @msolomon44

Also, can you open the browser console (keyboard shortcut Command+Option+J on Mac or Control+Shift+J on Windows/Linux) and send me a screenshot of the output there when it is stuck? Thanks!

**Comment by kautir** [comment]
Here is the transaction [link](https://etherscan.io/tx/0x45583f5253ad77cb5e85e0cce8f900105b7a49578a1bd8b46bcd62bacb798b7c) on Etherscan.

And here is the whole console log when it stuck:
[console.log](https://github.com/gitcoinco/web/files/5380735/console.log)

**Comment by mds1** [comment]
Hm so just to sanity check, make sure your wallet is connected and on the mainnet before trying any of the below.

From the console logs it seems to have just silently failed without any error message. But it did get stuck at the part where the fix was implemented, so perhaps your browser was caching the old code. Can you try doing a hard refresh once you're on the zksync-recovery page then trying again? 

Alternatively, if you visit https://gitcoin.co/grants/cart you should see a popup to complete checkout. If there are still items in your cart from when you tried checking out, you can try this flow also. But if you visit the cart page and it's empty, this flow will not work for your case.

Also, what browser and wallet are you using?

**Comment by kautir** [comment]
I try hard refresh on chrome but it didn't work. Then tried on Firefox, the issue is still there. 
I see this item in my cart:
![image](https://user-images.githubusercontent.com/72108515/96175391-b3420b80-0f37-11eb-91b8-8a8bdc0f4d0f.png)
When I try checking out it, I get this error:
![image](https://user-images.githubusercontent.com/72108515/96175539-e8e6f480-0f37-11eb-9e0e-47f936c986cd.png)
It seems the checkout process tries to withdraw the grant from my wallet again!

**Comment by mds1** [comment]
Ah, awesome, the item is still in your cart!

Try reducing the value to 0.78 ETH exactly, that way there's enough of a balance between your wallet and the fees. Now, if you use the "Complete Checkout" modal (that is popping up for you, right?) and follow the steps it should complete the contribution using the funds you have on zkSync here: https://zkscan.io/explorer/accounts/0xfa99bc3cfe7fd5d04e60ee58387cdb74af58965e

**Comment by kautir** [comment]
I completed the checkout and errors disappeared. Now transactions fail due to "Not enough balance" and I can't edit the transaction value. [This ](https://zkscan.io/explorer/accounts/0xfa99bc3cfe7fd5d04e60ee58387cdb74af58965e) is the link for transactions.

**Comment by mds1** [comment]
Ok, we are making progress! Apologies for all this hassle!

So that successful transfer looks like it was from the zksync-recovery page, because it transferred your full balance from your "[Gitcoin zkSync account](https://github.com/gitcoinco/web/blob/master/docs/GRANTS.md)" to your regular zkSync account. The rest of the transfers failed since your account had no balance left.

So, if you login to https://wallet.zksync.io you will see those funds there. You have the 0.782313 ETH on zkSync.

Anyway, to *finally* get your funds to the grant owners, add the grants to your cart. Make sure the total in your cart is about 0.78 or 0.775 ETH, that way you have enough to cover fees. Here's how to tell if you've set it low enough—click "Checkout with zkSync" and follow the prompts. If you ever get asked to send an L1 transaction that costs gas, cancel it and reduce the total amount in your cart. Since you have funds in zkSync, you should only have to sign messages with MetaMask, no L1 transactions needed!

Afterwards, you should be all set!

**Comment by kautir** [comment]
It seems everything is okay now. Thank you so much for helping 👍

**Comment by mds1** [comment]
No problem, glad we got it worked out!
