### ISSUE TITLE
Export submission view to a spreadsheet

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7706]
### User Story

As a hackathon sponsor, I'd like to be able to share the details of the hackathon submissions with my internal team so that we can decide on the winners and track payout.

As a hackathon operator, we need a way to allow customers to download a spreadsheet of the submissions view so that they can share it with their internal team.

### Why Is this Needed

- The V1 of submissions view did not include this feature, we wanted to see how customers would use this view.
- 5-10 customers have asked Connor for an expired spreadsheet.
- It takes about 30-60 minutes to export the information from metabase and properly organize it to send to sponsors. In some cases, it's additional work to organize finalists for demo day payouts by manually collecting addresses.
- Sometimes metabase export misses people

### Description

The goal of this ticket is to research ways we can solve for this. Outline an experience and design it. Get customer feedback. Get it built. This ticket is part of a self service hackathon epic. 

### Definition of Done

Solve for above ^

### Data Requirements
Happy customers
High NPS
Core team time saved on hack ops

**Comment by connoroday** [comment]
"5-10 customers have asked Connor for an expired spreadsheet."
I think you mean exported :) 

Overall, it looks great! I think the main steps here are:
1. Organizing the standard submissions metabase query such that we remove unnecessary fields (Start boolean, profile ID) and sensitive fields (Emails, payout addresses), possibly remove projects not submitted as well
2. Filter data by sponsor organization
3. Enable sponsors to export the new metabase query directly from the sponsor dashboard into a formatted excel sheet
4. Formatting data in a human friendly way (clean + simplified column headers) rather than backend variables (ie. “interest_handle” -> “Handle”)

**Comment by danlipert** [comment]
@connoroday really good context here, appreciate that. Is there a list of the fields that are essential to have for this export? That way we can be sure to limit any sensitive data being exported.  Also, who should be able to run this export? Just Gitcoin staff members?

I'm not sure about the excel requirement, that will add a decent amount of complexity to this ticket. Can we start with CSV? That will be much easier.

**Comment by zoek1** [comment]
ETA 13 November, 2020
