### ISSUE TITLE
Verify Grant Issue (wont verify my verification tweet)

### ISSUE THREAD

**Issue by WeTeachBlockchain** [gitcoinco/web#8012]
### Why: I've done it 6 times. The tweet always works when I sent it, I paste the grant page URL into the tweet and send it. Then I go back to the grant page, click "Verify" (step 3), and get the big red bar saying it cant verify.

**Comment by thelostone-mc** [comment]
I see only 1 tweet which is for https://gitcoin.co/grants/1129/weteachblockchain-free-decentralized-education
which has been verified!
Question:
- Did you intend to create another grant? https://gitcoin.co/grants/1643/weteachblockchain-decentralized-education
- I don't see a tweet with the verification of the new graant

**Comment by WeTeachBlockchain** [comment]
The 6 times refers to the me attempting to verify the same grant multiple times, because it would not work.. I deleted the extra tweets so that only one would be visible on our account. Yes, I need to create another grant, thats the issue. Here is a link to the tweet: https://twitter.com/bchaininstitute/status/1334381549500960768?s=20

https://gitcoin.co/grants/1643/weteachblockchain-decentralized-education needs verification. I have tried multiple times.

**Comment by developerfred** [comment]
@WeTeachBlockchain look https://github.com/gitcoinco/web/issues/8009

**Comment by zoek1** [comment]
@WeTeachBlockchain i saw two tweets that don't complain with the checks required to validate the grant:
1. The text will match the generated by the system, this includes also the name of the grant, url and the emoji code.
2. The emoji code is important due it allows don't impersonate accounts since its unique per grant, per people
So please don't modify the text like in the following image:

![image](https://user-images.githubusercontent.com/660973/101132522-bf0f8d00-35cc-11eb-8a52-81d19fafee18.png)

Also, @thelostone-mc seems the user is trying to verifiy a different grant :)

1. https://gitcoin.co/grants/1643/weteachblockchain-decentralized-education
2. https://gitcoin.co/grants/1129/weteachblockchain-free-decentralized-education

**Comment by octavioamu** [comment]
This error was related to special characters like "#" "&" encoding wrong as an actually url characters and was failing.
The other problem is you cannot verify 2 grants with the same twitter account. Seems you have 2 grants that seems the same.
