### ISSUE TITLE
Transactions not showing up for grant

### ISSUE THREAD

**Issue by SLRead** [gitcoinco/web#8099]
**Describe the bug**

I was contacted by someone who was trying to donate to my grant (https://gitcoin.co/grants/1761/women-of-crypto-art).
They did so yesterday, however, today, they saw that it was still listed as being in their cart.  So they tried to contribute again.  They verified that, in fact, both transactions were confirmed on etherscan:
Yesterdays
 https://etherscan.io/tx/0xda6a7dc147751b9f36395c49294533715a973ebe571d8ab6f5b0209b659352bc
And todays:
https://etherscan.io/tx/0xd39805fb8013a637b8cc848628eed5e680f219ac2d8ccd196c90a7485bc36924

However, neither have shown up as donations to the grant.

**To Reproduce**

**Expected behavior**

Other people have been able to contribute today, so I am unsure why this is happening for (at least) one person.

I have checked both etherscan and zkscan for the transactions & I do not see them there either.
https://etherscan.io/address/0xCCa88b952976DA313Fb928111f2D5c390eE0D723
https://zkscan.io/explorer/accounts/0xCCa88b952976DA313Fb928111f2D5c390eE0D723

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

Please let me know if I need to do something in particular about this.  Otherwise, I will relay your response back to my donor.  Thank you!!

**Comment by thelostone-mc** [comment]
Hey @SLRead could you tell us which user made the contribution ?

**Comment by mds1** [comment]
Hi, please tell the user they need to visit their cart and complete checkout with zkSync! In both cases they only did the first step—deposit to zkSync—but never did the second step of actually sending the transfers

**Comment by mlibty** [comment]
> Hey @SLRead could you tell us which user made the contribution ?

Me

**Comment by mlibty** [comment]
> Hi, please tell the user they need to visit their cart and complete checkout with zkSync! In both cases they only did the first step—deposit to zkSync—but never did the second step of actually sending the transfers

How to do it? After my first checkout with zkSync, for the first contribution, (see this tx:https://etherscan.io/tx/0xda6a7dc147751b9f36395c49294533715a973ebe571d8ab6f5b0209b659352bc), I visited back my cart and it had still the pending checkout. I checked out with zkSync again and created this tx: https://etherscan.io/tx/0xd39805fb8013a637b8cc848628eed5e680f219ac2d8ccd196c90a7485bc36924.
Ma cart has still pending checkout, after charging me two times...

**Comment by SLRead** [comment]
> Hi, please tell the user they need to visit their cart and complete checkout with zkSync! In both cases they only did the first step—deposit to zkSync—but never did the second step of actually sending the transfers

Thank you very much for your response!
Please see comment  above this one.  

Is there doc or details of the steps needed that you can link to?

**Comment by mds1** [comment]
@mlibty Even though you were "charged" twice, this really means the funds were moved to a different wallet twice. You can access the unused funds at https://wallet.zksync.io/

When you visit https://gitcoin.co/grants/cart and click "Checkout with zkSync" and it takes you to the zkSync site, Step 1 should now be complete by default because you already deposited funds into your zkSync account (that's what those two transactions are). Then you just need to complete step 2 and you should be all set.

The reason your second transaction was so small is because gas prices had risen, and you were a few cents short to cover the fees, so it asked you to deposit more funds to cover the fees. Instead of repeating step 1, you can:
1. Close the zksync window
2. Decrease the value of the items in your cart by a little bit
3. Try checking out with zkSync again and you should go straight to step 2

I tried to send a screenshot, but it seems zkSync is having some server issues, so you may want to wait a few hours before trying this

**Comment by mds1** [comment]
Ok it should be good if you give it a try now!

**Comment by mlibty** [comment]
> Ok it should be good if you give it a try now!

Big thanks for clarifying! :) Tried now, but seems it still has issues... will get back on it later!

**Comment by mlibty** [comment]
Done! Thank you very much!  Even after quite some time in crypto, I still don't get some things... :))

**Comment by thelostone-mc** [comment]
Closing this out cause the issue has been resolved. Do reopen if it still persists ^_^ 

>Even after quite some time in crypto, I still don't get some thing

I can relate to this @mlibty  :P

**Comment by SLRead** [comment]
Thank you guys so much for your excellent support!
