### ISSUE TITLE
Cannot check out my Grant

### ISSUE THREAD

**Issue by RalphHofacker** [gitcoinco/web#8110]
I am trying to do the checkout for my grant, but it does not work. Neither with zkSync (the tab does not open), nor with Standard Checkout (I get the error message Cannot read property '0' of undefined), I am connected to the grant site with my Ethereum account using MetaMask.
My gitcoin username is ralphhofacker
![image](https://user-images.githubusercontent.com/26342946/102118112-8cbd2580-3e3f-11eb-94cf-c0f291ef3f63.png)
![image](https://user-images.githubusercontent.com/26342946/102118156-9ba3d800-3e3f-11eb-83ee-fbe272149407.png)

**Comment by Solexplorer** [comment]
@RalphHofacker For zksync, do check that you have popups enabled, I've seen multiple instances having this issue, but for standard checkout, it seems that you don't have the wallet connected because of the red dot there in the wallet section. If any of this works then I will leave it to the engineering team

**Comment by RalphHofacker** [comment]
Thanks a lot @Solexplorer, this morning the MetaMask icon showed up after connecting and it even worked then with the zkSync popup. So it seems somehow yesterday the connection to my wallet didn't work even though I tried it on two different laptops.
Thanks anyways.
