### ISSUE TITLE
Zksync check out says insufficient funds

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#8138]
I tried zksync the last round and had some funds left which I wanted to give out this round.

Deposit transaction: https://zkscan.io/explorer/transactions/0xdd6d1f92980faf622c09acd84dbff4fe0bd7ae466a23c2479df709f8996d250e

When I try to checkout for this round I get an insufficient funds error
![2020-12-17_01-21](https://user-images.githubusercontent.com/1658405/102422104-4e259780-4006-11eb-8e4c-075a43a5de64.png)

even though the account should have a bit over 12 DAI left: https://zkscan.io/explorer/accounts/0x957a50da7b25ce98b7556afef1d4e5f5c60fc818

**Comment by thelostone-mc** [comment]
@mds1 any idea what might be up with this?

**Comment by LefterisJP** [comment]
Would love to get this solved before the end of this round if possible.

**Comment by mds1** [comment]
The zkSync architecture changed from last round to this round. Based on your transaction hashes it seems your regular wallet address is 0x2B888954421b424C5D3D9Ce9bB67c9bD47537d12, which I'm guessing is the address you used to connect to zkSync in the screenshot. And checking Etherscan and zkScan for the address we see it does in fact have insufficient DAI balance.

The other address, 0x957a50da7b25ce98b7556afef1d4e5f5c60fc818, was a "Gitcoin zkSync address" that we used last round. That leftover 12 DAI should have been sent back to your regular address, but for some reason it seems it wasn't. Unfortunately right now there is no easy way to transfer those 12 DAI to your main address—we'd have to re-stand up the `/grants/zksync-recovery` page, but that will likely not happen before the round ends since there's only ~3 hours left.

You can read more about the round 7 vs. round 8 architecture [here](https://github.com/gitcoinco/web/blob/master/docs/GRANTS.md).

**Comment by LefterisJP** [comment]
> we see it does in fact have insufficient DAI balance

Yes I don't have any DAI in mainnet in my public address. I had them deposited in ZKSync as instructed in the last round, so that I can use them again in this round.

> The other address, 0x957a50da7b25ce98b7556afef1d4e5f5c60fc818, was a "Gitcoin zkSync address" that we used last round. That leftover 12 DAI should have been sent back to your regular address, but for some reason it seems it wasn't. Unfortunately right now there is no easy way to transfer those 12 DAI to your main address—we'd have to re-stand up the /grants/zksync-recovery page, but that will likely not happen before the round ends since there's only ~3 hours left.

Oh that's a pity :(

All grant zksync participants should have been sent an email or something about this, as I find myself unable to access the funds now. That's not really nice.

Is it possible for someone else, not me, to send them to a few grants and make it still for this round? I don't want them back. Just want to donate them.

If not I guess nothing can be done about this now. Just please ping me here or in twitter or somewhere when it's possible to reclaim those 12 DAI. It would be cool if they could stay in ZKSync and become accessible by my `0x2B888954421b424C5D3D9Ce9bB67c9bD47537d12` address again.

**Comment by mds1** [comment]
We did send emails to users last round who were affected by a bug which resulted in leftover funds in their zkSync account, and pointed them to the zkSync recovery page. I just checked that list though an it seems your account wasn't on it, so perhaps you were affected by a different bug? Sorry about that 😕

If yours got missed, I'm sure others did too, so we probably should just keep that recovery page up for now.

Either way, I have enough extra DAI in my zkSync account, so I'll happily donate the 12 DAI on your behalf (since that will be much easier/quicker for now than recovering your 12 DAI). Feel free to post the cart link here or message me on Twitter @msolomon44 or Telegram @msolomon4 if you prefer!

**Comment by LefterisJP** [comment]
The issue is closed but I still don't know how to recover that DAI. If for nothing else to pay @mds1 back!

**Comment by mds1** [comment]
@thelostone-mc Have you heard any other reports of stuck funds? Assuming not, below is my current thinking. To jog your memory, this was added in #7623 and later removed in #7942 because we no longer use the checkout approach that led to this as a potential issue

------------------------

Thanks @LefterisJP, appreciate that—but no worries at all!

We haven't heard any other reports of stuck funds (which I'm actually bit surprised by, since issues rarely occur for just one person) so we probably won't stand up that recovery page again for the time being. If you wanted, you could build Gitcoin locally and switch to a commit that has the recovery page. But for only 12 DAI it's arguably not worth the time investment to do so. Plus, as a happy Rotki user, I'd rather you have more time to keep working on that! 😉
