### ISSUE TITLE
grant donation not showing up.  2 days ago I gave eth to voskcoin grant on videos for eth grant.  I pledged 5.00 of eth.  the transaction was successful,  and funds where taken out if my metamask but the grant is still showing up in my cart.  Transaction: 0xf14a0c4d66b87bee6adb070e848f76a5ac187549294d3afc71349e3680467bb7  

### ISSUE THREAD

**Issue by juneto9** [gitcoinco/web#8153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hi @juneto9! It looks like you never completed your checkout. If you look at [your account](https://zkscan.io/explorer/accounts/0x36ed95265f81032640454487ab2443a7f1b5e510) on zkSync, you'll see you deposited funds, but never completed the transfer. 

To complete your donation you'll need to visit your cart, click "Checkout with zkSync", and complete the checkout

**Comment by juneto9** [comment]
Thanks for the quick response Matt.  I did complete the checkout process as
the 10.00 in eth was successful withdrawn from my metamask wallet.  The
webpage also stated that the transaction was completed and pending
verification.   I'm afraid if I try to complete the transaction again I
will be charged again, which I do not want to happen.

Elioe Burgos
juneto9@gmail.com
386-631-8500

**Comment by mds1** [comment]
The funds were withdrawn from your MetaMask wallet, but because you used zkSync, they were not sent to the grant owner. Instead, they were sent to your zkSync wallet. You can access the funds of this wallet here: https://wallet.zksync.io/. Alternatively, you can view your account here: https://zkscan.io/explorer/accounts/0x36ed95265f81032640454487ab2443a7f1b5e510

If you look at your account on zkScan, you will see there is only one transaction of type "Deposit". This means you deposited funds from your MetaMask wallet to your zkSync wallet. The next step is to actually send those fundss to the grant.

To do this, visit https://gitcoin.co/grants/cart and click "Checkout with zkSync". Step 1 should be complete, because you already have funds in zkSync. Then just do step 2 to complete your checkout

**Comment by juneto9** [comment]
Ohhhhhhhhh!  I was unaware that was going to happen.  Ok I will finish up
the transaction then.  Thank you so much for your help.  I thought the eth
was gone and Vosk was out of luck.  Thank you again.

Elioe Burgos
juneto9@gmail.com
386-631-8500

**Comment by mds1** [comment]
No problem, let me know if you have any issues completing checkout!

**Comment by juneto9** [comment]
my cart is now empty.  can I still get credit for participating in the
round 8 so I can get my match and earn free Badger tokens?

Elioe Burgos
juneto9@gmail.com
386-631-8500

**Comment by thelostone-mc** [comment]
@juneto9 we aren't tied upto badger but logically yes -> since you've contributed -> you should qualify (but this is just me guessing) 😅 
Closing this out as looks like issue was resolved
