### ISSUE TITLE
New Marketing Landing Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#846]
New marketing landing page for repo owners

refer to google doc

**Comment by owocki** [comment]
i wonder if calling this landing page something like ["do more faster"](https://medium.com/gitcoin/tutorial-leverage-gitcoins-firehose-of-talent-to-do-more-faster-dcd39650fc5) would orient it around what customers want to achieve, instead of just showing off our product and it's features?  put another way, how does this landing page elicit hope / action out of the end user.

@vs77bb i wonder if we could also fold in some of our recent insights about selling (e.g. customers want services, not software -- we become an extended part of their team, Enterprise selling is trust model - fighting to be the trusted technical advisors, etc)

cc @PixelantDesign

**Comment by PixelantDesign** [comment]
@owocki The top part of the landing page (in the google doc) is set up to focus on the value delivered vs. features...lets collaborate in the Google Doc.

**Comment by PixelantDesign** [comment]
https://docs.google.com/document/d/1xYxFyQQaRN8AUDNdsNIa9bTK3kmCcLc_eR3ECAOn7Jk/edit?usp=sharing

**Comment by PixelantDesign** [comment]
Hmmm... that could work, will try it out and see how the content flows.

**Comment by PixelantDesign** [comment]
bountied the build task. Closing
