### ISSUE TITLE
Is it possible to keep our campaign running without CLR matching?

### ISSUE THREAD

**Issue by PhilH** [gitcoinco/web#8505]
### Who
We have a grant created on Gitcoin for our project Web3API.
We've been very successful so far, with more than 400 individual contributions.

### What 
We would like to keep our grant running, while not receiving the CLR matching funds.

### Why
Since we closed a round of seed funding in December, we feel that it would be fairer to have self-funded projects being supported by CLR matching funds.

However, we don't want to cancel our grant, since we're still a community-led, decentralized project, and we value the support of individual donators. It's a great way to get some exposure and to expand our community and engage with supporters.

Would that be possible?
Thank you!

**Comment by thelostone-mc** [comment]
Hey @PhilH  
Yes this is possible. I've gone ahead and marked this grant from taking part in CLR round.
https://gitcoin.co/grants/1252/web3api

We will roll this out as a feature soon , so that grant owners can enable / disable depending on what they want.
Meanwhile let us know if you we should enable CLR participation flag in the future meanwhile ^_^
