### ISSUE TITLE
5 ETH Donation didnt go thru?

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#8570]
**Describe the bug**

I see this transaction 

369500 | 2021-03-11T16:00:00 | duyson1003 |   | griffgreen | Everywhere you want to be! | grant | 8390.61 | 0x22fa54e00a3cc44bfbb1d8d15d5a3d1c64527e3b1d94fab89e4096a3a7726ac7 | ETH | 5 | /grants/539/the-commons-stack-iteration-0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

but the tx hash doesnt show up and I don't see the ETH in CS's wallet...

**Expected behavior**

Either the donation is real and shows up... or the donation isnt real and doesnt show up ;-) I almost tweeted an awesome meme... thankfully i did fact checking first

![5 eth](https://user-images.githubusercontent.com/14945613/111007808-fb067b00-838f-11eb-96dc-7ca4ce9ec382.gif)

**Comment by GriffGreen** [comment]
This account did the same thing... we have 10 ETH "pending" and so do a few other grants 
https://gitcoin.co/minhkhoi310

**Comment by owocki** [comment]
mind submitting the txn again here? http://gitcoin.co/grants/add-missing-contributions

**Comment by GriffGreen** [comment]
> mind submitting the txn again here? http://gitcoin.co/grants/add-missing-contributions

I have the exact opposite problem, a couple of big transactions are on the UI but not the blockchain.

It looks like 2 anons "donated" in total ~$150,000 in ETH to a few grants... their txs are "pending" 


of the top 11 grants, 10 of them got phantom donations from the 2 same anons 

Top grants: https://gitcoin.co/grants/explorer/?sort=-amount_received_in_round 

Anon 1: https://gitcoin.co/duyson1003

Anon 2: https://gitcoin.co/minhkhoi310

I'm prepared for the worst (these anons are just messing with us) and hoping for the best (they sent a low gas fee and it will go thru this weekend)

**Comment by owocki** [comment]
We are aware of this.  Here's why it happened.

When a user checks out on Gitcoin Grants, our system ingests a (transaction_id, amount, profile) tuple, and records it immediately, and applies it to the QF matching algorithm.

Because ethereum transactions can take minutes or days to clear (sometimes never clear'ing), we run a backend job that keeps track of these txns - but the optimistic assumptions here still come with some risks.  There is a tradeoff:

- pessimistic UX (assumes txns will never clear, but if they do, updates the UI/match formula) - users dont get to see the match estimates update immediately 
- optimistic UX (assumes txns will clear eventually, follows them until they do)  - users get instant recognition of their txns, but if the tx takes a while to clear, it can represent some risk that the numbers were moving around.

right now the UX is optimistic, and it looks like unfortunately this user never broadcast'ed their txns ( i dont know if this was user error or user being nefarious )

**Comment by gdixon** [comment]
I'm closing this out - but feel free to reopen if you need any more information.
