### ISSUE TITLE
Faulty contributions on grant

### ISSUE THREAD

**Issue by TSnark** [gitcoinco/web#8616]
**Describe the bug**
Several contributions are notified via email and displayed on the grant page but are not on chain or on zkSync
At a first glance these are always contributions of 0.1ETH. 

Latest Example:
Contribution link: https://gitcoin.co/townsquare?tab=activity:752519
Link to tx in email(non existent): https://etherscan.io/tx/0xe61cefd3e4d567da207aff1355a4a65382e8cf5f8a4636b1b3eceb8d2182547d

**Comment by ethanchiasson** [comment]
@TSnark I had this same issue. Went to be with $129 or so in grants and woke up to $2200+. I couldn't believe it, but I let myself and I instantly started getting worried because none of that was showing up in my wallet. I was scared I did something wrong by using Coinbase and lost my contributors donations, however I decided to send some ETH to my CB ETH address and the payments instantly went through.

You can read my issue here: https://github.com/gitcoinco/web/issues/8610

However, I am still not receiving any ETH on Coinbase from the grants contributions. I do receive some DAI every so often, but none of the ETH donated is showing in my wallet ( which again, it should, given that I tested sending 2 ETH transactions and both went through near instantly ... maybe 45 seconds ).

Anyone have any ideas why this is happening ? Also, if there is someone who can show me the transactions or confirm that the ETH transactions are confirmed that would be nice, because they do not appear on Coinbase and CB customer support is near non-existent.

 I just want to be sure that the people donating to me aren't sending their ETH off to the Ether (pun totally intended )

**Comment by ethanchiasson** [comment]
Update: Just checked my profile...

https://gitcoin.co/ethanchiasson/earnings

As you can see, I have $2k+ in earning, yet I never received $2k in earnings in my wallet. What is odd is that if you go to the grant page itself ( https://gitcoin.co/grants/2149/stakegg-open-markets-for-gamers-by-gamers ), you will see that I received $137 ( not $2000 + ).

More evidence to this being a UI bug, but still not sure why my ETH transactions ( from Gitcoin grants ) aren't coming through , but ETH transactions sent from me or my friends wallet appear just fine.

**Comment by jacksanford1** [comment]
Yes -- I am having this same issue. Had ~$2700 in grant funding yesterday morning. It was down to ~$500 by midday. We've got 15 donations for 0.1 ETH showing up on our profile and 82 contributions in total but only a few show up in Etherscan.

https://gitcoin.co/grants/2035/sherlock
https://etherscan.io/address/0xE400820f3D60d77a3EC8018d44366ed0d334f93C

**Comment by disruptionjoe** [comment]
Hey all. fill this out to help us fix quickly https://gitcoin.co/grants/add-missing-contributions

**Comment by ethanchiasson** [comment]
> Hey all. fill this out to help us fix quickly https://gitcoin.co/grants/add-missing-contributions

Is this for contributors or for those receiving grants ?

**Comment by gdixon** [comment]
We optimistically include all contributions in our calculations, this allows us to accurately display the best case scenario - however we have noticed quite a few contributions have been sent with a really low gas fee which has caused them to fall out of the mempool and they are eventually dropped. We are constantly monitoring the chains for updates and allow up to 24hrs for these contributions to either go through or fail before we rollback the totals in our db.

Please note that only confirmed contributions will count towards QF matching.

I'm going to close out this issue, but if there's anything else we can help with, please don't hesitate to get in touch.

Thank you for your support and understanding!
