### ISSUE TITLE
EthCc Grant is a Kraken Wallet -- would prefer matching in ETH

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#8699]
Discussion with Nathan from EthCc on Telegram, documenting if there is a 'fix it twice' to remind users to use an ETH Wallet which is a multisig / wallet they own that isn't on a CEX. 

"the old one is an ETH address on Kraken and caused problems on the round 8."

For now, the ask is if matching funds can be donated in ETH instead of DAI. Tracking here for when time for payouts. 

https://gitcoin.co/grants/1577/ethcc-by-ethereum-france-panvala-league

**Comment by nsexer** [comment]
Thanks @vs77bb @owocki, kindly asking if we could switch the [EthCC Grant](https://gitcoin.co/grants/1577/ethcc-by-ethereum-france) address 
from: "0xD8FF82D36D1439eD3eF8cBb4b28178Ff7F6b7209" which is a CEX Address 
to: "0x04A8A22e5eF364c5237Df13317c4F083f32C2Cc4" 

I created a new grant with the new address: https://gitcoin.co/grants/2426/ethcc-by-ethereum-france-panvala-league-2

Please let us know if you can wire the funds to this new address instead so that we do not suffer from loss of funds and troubles with CEX 🙏🏻

**Comment by owocki** [comment]
@jdetychey. do you consent to this change? 

FYI payouts are in DAI, we don't have infrastructure built to pay out in ETH unfortunately.  You can always exchange the DAI to ETH tho.

**Comment by jdetychey** [comment]
I consent @owocki thanks so much for the help

**Comment by owocki** [comment]
updated the addr!

**Comment by nsexer** [comment]
Thank you very much @owocki do you confirm funds of GR9have been wired to the new address?

**Comment by owocki** [comment]
payments havent been setnt yet ( https://twitter.com/gitcoin/status/1376527668431089670 ) but when they are available itll be tied to the new addr

**Comment by nsexer** [comment]
Perfect Kevin, thank you so muck

--
Nathan Sexer

**Comment by Kweiss** [comment]
Looks like we got to a good spot here. I am going to close this :)
