### ISSUE TITLE
Tips for me.

### ISSUE THREAD

**Issue by Adrian2dd** [gitcoinco/web#8867]
Hello Gitcoin team, I wanna ask a question, I hope you dont mind, some posts, from my profile generated tips, but how do i get those tips, I linked my metamask wallet, 1 month, and i didnt got nothing.Can you help me please?

**Comment by thelostone-mc** [comment]
@Adrian2dd you should have gotten an email to claim the tip and you should be able to use that
You can also access it from the https://gitcoin.co/inbox to see the tip link

If you've already claimed the tip and the funds have not been sent -> it's likely due to low gas fees and you'll have to wait until the txn clears
