### ISSUE TITLE
Create custom page  for suspicious users, instead of displaying 404

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#9013]
### Discussion

Grants contributions that kept missing during GR8 and GR9 are a major issue that I've encountered during the rounds, sending them to the page to add contributions themselves is not the long term solution.

Everyday at least one person asks the reason for the error
"it's gonna reduce CS queries" - Nerte
Can we actually add a custom page for blocked users instead of the Error 400 page?

This is what the user sees today
<img width="1226" alt="Screen Shot 2021-06-08 at 3 06 01 PM" src="https://user-images.githubusercontent.com/238235/121242886-11c34d80-c86b-11eb-8c25-5eda65f6746f.png">

**Comment by frankchen07** [comment]
I'm not sure what you're talking about when you're talking about blocked users.

I believe Aditya and Matt Solomon are working / put in a PR for a solution to the missing contributions problem: https://github.com/gitcoinco/web/issues/8852

if we fix the missing contributions problem there won't be a need to have a missing contributions page at all.

**Comment by Solexplorer** [comment]
Hey @frankchen07 Blocked users are the ones that have been suspected of bad behaviour(mostly because suspected of sybil attacks) and therefore have been blocked from any activity on the website. 
The error page we show is a generic one, if we could actually just make a page that says that the account has been suspended, it would be really helpful
