### ISSUE TITLE
GR11 Feedback 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#9422]
**Internal feedback ticket**

still working on fixes for: 
- [x] landing grants collections
- [x] filters styles 
- [x] mobile filters 
- [x]  and other general things

**Comment by willsputra** [comment]
Thanks for this! A few feedback, other than the filter styles that you're working on:

• The new Discover section on grants landing doesn't seem to work. When I clicked on Undiscovered Gems, it still brings me to Weighted Shuffle view. There seems to be two sorts in the url?
![Screenshot 2021-09-02 at 2 57 52 AM](https://user-images.githubusercontent.com/19514207/131728249-1bbc72b0-e167-45fd-999e-3820c7760865.png)

• When I add Region filters, it seems like the numbers on More Filters are changed too
![Screenshot 2021-09-02 at 3 02 43 AM](https://user-images.githubusercontent.com/19514207/131728896-a68e0e08-43b4-4768-92ea-714232ac6521.png)

• After clicking Apply on the filters, we should close the filter popup. Example airbnb:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/19514207/131729541-d3a064b3-52fb-4fbb-a255-db7707225169.gif)

• Me menu > My Grants > Projects doesn't seem to work (grants that aren't mine are still showing)
![Screenshot 2021-09-02 at 3 11 06 AM](https://user-images.githubusercontent.com/19514207/131730035-c58aa674-60ea-4ea8-b9da-21635b293394.png)

• Are we going to sticky make the cart sticky? Design:
![Screenshot 2021-09-02 at 3 00 50 AM](https://user-images.githubusercontent.com/19514207/131728609-3a1bcc2a-75b9-42cd-997d-6ddec3def2bc.png)

• We should show how many grants are added to cart in the sidecart. Design:
![Screenshot 2021-09-02 at 3 01 49 AM](https://user-images.githubusercontent.com/19514207/131728748-fd46702a-909a-4820-8679-af2764546464.png)

**Comment by abitrolly** [comment]
https://gitcoin.co/hackathon/gr11/onboard the link to `wiki` page https://gitcoin.co/wiki/grants/ is 404.

![image](https://user-images.githubusercontent.com/8781107/131735964-e30a03b5-a401-4cdf-aed7-43fb9ad11db7.png)

**Comment by abitrolly** [comment]
And it would be nice to get these implemented before GR11 starts. As I've messed up a Twitter handle in my submission.

* https://github.com/gitcoinco/web/issues/8876
* https://github.com/gitcoinco/web/issues/7222

**Comment by frankchen07** [comment]
- looks like some of the filter menus pop up and some pop down, bug, or intended?

<img width="1170" alt="Screen Shot 2021-09-01 at 17 40 35" src="https://user-images.githubusercontent.com/7516920/131763527-d5c05a5a-a92d-4c8d-8287-b7f196dc1947.png">

<img width="1195" alt="Screen Shot 2021-09-01 at 17 40 43" src="https://user-images.githubusercontent.com/7516920/131763538-251ffd0a-7ab0-4bae-97bd-1fa86df431df.png">

<img width="1185" alt="Screen Shot 2021-09-01 at 17 40 52" src="https://user-images.githubusercontent.com/7516920/131763543-62a34582-dc80-4056-8813-5ffa9773e1e0.png">

**Comment by frankchen07** [comment]
- search bar functionality does seem to work?

I was looking for "kyle land" to see if it would single out the one grant currently in view, but it doesn't seem to do anything when I hit enter

<img width="1146" alt="Screen Shot 2021-09-01 at 17 43 55" src="https://user-images.githubusercontent.com/7516920/131763766-69ccfbf3-17ea-432a-abb8-a5eaf550d6c9.png">

**Comment by PixelantDesign** [comment]
Lookin' good! Feels smooth and fast.

Aside from some of the items mentioned above...

- [ ] When filtering term didn't match, there is no feedback on the page (this might still be wip still). 

- [ ] New cart menu, it wasn't apparent that there were more grants to see, I saw 4 grants but the checkout button said 9 grants, consider displaying scrollbar by default)
<img width="373" alt="Screen Shot 2021-09-01 at 9 11 24 PM" src="https://user-images.githubusercontent.com/238235/131765745-f52c2536-a1bd-4e8d-b4c4-1482c5b7ee25.png">

- [ ] When in checkout page I was able to click remove a grant from the new cart menu, but the item was not removed from the actual checkout page and the number of cart items in checkout page did not reflect.<img width="1538" alt="Screen Shot 2021-09-01 at 8 46 41 PM" src="https://user-images.githubusercontent.com/238235/131764267-d38187c7-2e4a-4690-b824-21999a42c520.png">

- [ ] After creating a collection _from the cart_, return the user back to their cart instead of explorer.

- [ ] After user adds a grant to their collection, display the collection that Grant has already been added to.
<img width="1587" alt="Screen Shot 2021-09-01 at 8 57 50 PM" src="https://user-images.githubusercontent.com/238235/131764827-d3d4de75-b4a0-48dd-abe2-6e9d4f69834f.png">

**Comment by octavioamu** [comment]
wrong filter condition probably when empty https://stage.gitcoin.co/grants/cards_info?page=1&limit=6&sort_option=weighted_shuffle&network=mainnet&state=active&collections_page=1&grant_types=&grant_tags=&tenants=&idle=true&sub_round_slug=gr11-uniswap&round_num=1&customer_name=Uniswap&tab=grants

**Comment by octavioamu** [comment]
missing landing featured collections

**Comment by octavioamu** [comment]
filter my collections from menu doesn't work, query need to be changed to be parameters

**Comment by octavioamu** [comment]
not handling api server error messages

**Comment by thelostone-mc** [comment]
- [x] ensure page param is reset to 1 on applying any filter
- [x] enure URL param of types, tags, tenant is loaded as an array and not string when only 1 value is present
- [x] fix dropdown auto-flip

**Comment by willsputra** [comment]
>  When filtering term didn't match, there is no feedback on the page (this might still be wip still).
Aditya: could you share design for this?

@thelostone-mc @octavioamu tagged you with the empty state designs on Figma!

**Comment by willsputra** [comment]
tried creating grants:
https://stage.gitcoin.co/grants/11/grant1-with-gaming-wallet-tags
https://stage.gitcoin.co/grants/12/grant2-with-daos-tag

- [ ] tags don't show up in grants detail page
- [ ] my grants don't show up on my profile (Grants tab is missing and there's nothing in the Activity)

**Comment by octavioamu** [comment]
change bg politicities to match new params patterns

**Comment by willsputra** [comment]
**UI / styles tweaks (will keep updating this post for UI/styles stuff):**

- [ ]  Desktop: When one or more filters are active, they go to the new line. Consider increasing the space for the filters to be more than 50% width. If needed, we could also make the search bar shorter (since it will expand anyway when people click on it). 
![Screenshot 2021-09-02 at 11 44 15 PM](https://user-images.githubusercontent.com/19514207/131875075-e1218e99-e84b-43d9-8d19-674c75660c6a.png)
- [ ] Add search icon to search bar
![Screenshot 2021-09-02 at 11 48 48 PM](https://user-images.githubusercontent.com/19514207/131875834-ae0b6709-49e9-4a9b-9824-cec25ddffebc.png)
- [ ] Add more space between round title ("GR11 - Community") and filters
![Screenshot 2021-09-02 at 11 48 50 PM](https://user-images.githubusercontent.com/19514207/131875883-5c10d216-d9c0-4024-9d3b-a9b1612a3c3e.png)

**Comment by frankchen07** [comment]
the round buttons look slightly cut off on the top and bottom

![Screen Shot 2021-09-02 at 09 13 10](https://user-images.githubusercontent.com/7516920/131879671-0596a3a7-3c4c-4e50-9b52-0a81fe81660d.png)

**Comment by owocki** [comment]
all testing done on chrome/osx with metamask

layout is funny on amount raised here => https://bits.owocki.com/04uxLNbb

when i click apply nothing happens https://bits.owocki.com/9ZuQD0GB

add all to cart button doesnt work => https://bits.owocki.com/Wnu0ql4R

sort by select box should have a hover cursor on it not a text curosr https://bits.owocki.com/lluo6n10

cannot test related grants or contributions (or contributions not working) despite this grant having had funding on it https://bits.owocki.com/P8uG6mWK


if i add 4 grants to my cart on this page ( https://stage.gitcoin.co/grants/explorer/?page=1&limit=6&sort_option=-metadata__gem&network=mainnet&state=active&collections_page=1&grant_types=&grant_tags=&tenants=&idle=true&tab=grants ) then i go to the carts page, only 2 grants show up in cart

https://bits.owocki.com/eDuRlw6B
https://bits.owocki.com/rRubN09g

the back button on the grant doesnt ever seem to update https://bits.owocki.com/P8uG6kO2
everytime i browse a category or a collection it should be updated.

when i go to checkout on standard checkout i get an insufficient dai balance error ( https://bits.owocki.com/xQu6zYD8) even tho i have plenty of DAI in my wallet

on polygon checkout ( https://bits.owocki.com/7KuEqbq2 ) , itd be nice to give the user a link to polygon support so they dont have to fish for it.  itd alos be nice to let the user know they need MATIC (not just DAI) to checkout on the matic chain.

when i swtich my network to polygon i get this error https://bits.owocki.com/12uv0o5b

if i click on 'community' from https://stage.gitcoin.co/grants/13/owocki-stuff it takes me to https://stage.gitcoin.co/grants/explorer/Community?page=1&limit=6&sort_option=weighted_shuffle&network=mainnet&state=active&collections_page=1&grant_types=&grant_tags=&tenants=&idle=true&tab=grants  which does not actually filter on community grants

why is there a random ether logo floating over here? https://bits.owocki.com/9ZuQD09Z  what does this mean?  theres no label, no descriptor, no alt text. what is it? its bugging me.

when i try to connect with idena i get this error https://bits.owocki.com/qGuJrlQP  might be a staging issue thing tho?

i ran out of time testing all the trustbonus tabs at https://stage.gitcoin.co/owocki/trust (did brightid, POH, idena). but itd be ncie if someone could verify they all work.

did not get a chance to test emails either.  since stage doesnt support it.  has anyone tested those? have they been updated with info about polygon checkout, etc?

is there a way to test with a matching campaign live?
its hard to test any QF functionality with an ENV that doesnt have any QF rounds going

**Comment by octavioamu** [comment]
@willsputra how did you created this 2 grants? seems are without tenant that the reason on showing up on the cart since not eth grants and not indication of other tenant
![image](https://user-images.githubusercontent.com/1358093/131884312-1d8710e3-4f45-47e6-ba14-2fcf5fbbba46.png)

**Comment by octavioamu** [comment]
grant address field on form accepting any random character

**Comment by willsputra** [comment]
> @willsputra how did you created this 2 grants? seems are without tenant that the reason on showing up on the cart since not eth grants and not indication of other tenant
> ![image](https://user-images.githubusercontent.com/1358093/131884312-1d8710e3-4f45-47e6-ba14-2fcf5fbbba46.png)

hmm I chose ETH on the create grant form, although I think I put "0x0" on the recipient wallet address field

**Comment by octavioamu** [comment]
> hmm I chose ETH on the create grant form, although I think I put "0x0" on the recipient wallet address field

Lol that is the issue 0x0 is the "default" on our form so actually is taking as not ethereum grant, this land into my latest comment here we need to validate the address

**Comment by frankchen07** [comment]
didn't we change the language and functionality to be a % on top of their original contribution?

![Screen Shot 2021-09-02 at 12 03 20](https://user-images.githubusercontent.com/7516920/131901690-6ff98b46-c2cf-483e-bcfd-b93cb034a367.png)

**Comment by PixelantDesign** [comment]
Explorer List view
- [ ] $0 out of alignment on card
<img width="1181" alt="Screen Shot 2021-09-02 at 3 37 02 PM" src="https://user-images.githubusercontent.com/238235/131905704-cbd95b57-3444-47dc-9dc0-39d575281fc1.png">

**Comment by octavioamu** [comment]
> $0 out of alignment on card
that is due to the other bug on the form not having validation on address then not getting tenant, as there is not icon with the chain the template create that break

**Comment by octavioamu** [comment]
when on cart page if you decide to create a collection then you get redirected , this shouldn't happen as we don't even know if the user want to go to another place, maybe he just want to checkout next

**Comment by octavioamu** [comment]
Missing filtering parameters on collection tab to get my collections from the me menu on nav 
query : https://stage.gitcoin.co/api/v0.1/grants_collections/?profile=35

**Comment by PixelantDesign** [comment]
>when on cart page if you decide to create a collection then you get redirected , this shouldn't happen as we don't even know if the user want to go to another place, maybe he just want to checkout next
agree @octavioamu, lets keep the user in the checkout page after collections creation is complete.

**Comment by PixelantDesign** [comment]
from @owocki comment
> why is there a random ether logo floating over here? https://bits.owocki.com/9ZuQD09Z what does this mean? theres no label, no descriptor, no alt text. what is it? its bugging me.

The intent was to denote what chain that grant accepted payment on. This is a confusion point for users as well.
We could add a tooltip to clarify that. Thoughts @octavioamu ?

**Comment by owocki** [comment]
per the team call today, make sure we test the new endpoints with productionlike data pls.    if a grant with 10k contributions takes several seconds to load, that ll be a problem when the code hits prod

**Comment by Kweiss** [comment]
Looks like most of the "sort by" are not working:

- [ ] Selecting "Oldest Grants" and "Updated Recently" are two example, but its most of them not working.

**Comment by octavioamu** [comment]
- [ ]  Reverse Pagination
- [ ]  Remove add-all
- [ ]  Organise the filters/sort bar
- [ ]  Reset page to 1 for sorting (DONE)
- [ ]  Contributors email
- [ ]  Gas estimations
- [ ]  Cart page work
- [ ]  fix the collections image source
- [ ]  reintroduce collections to the landing
- [ ]  Replace CLR function with clr3.py
- [ ]  Ensure banner matches latest version of figma (with category bar above banner)
- [ ]  Run through optimisation stuff (asset servers loadbalancer && a replacement celery4)
- [ ]  Turn on the crontabs for celery servers

**Comment by PixelantDesign** [comment]
- [ ] Grants Home page - Clicking on the mini clr banner (uniswap) does not map to the filtered view (for uniswap) on the explorer.

**Comment by Kweiss** [comment]
- [] Grants checkout not working on Rinkeby during testing - https://cloudup.com/coh7mEglojT

**Comment by Lerog1724** [comment]
Good day, should I return the old address or I'll be sticking with the
metamask?

Rogeljoanclitonkevin17242111$$$

**Comment by PixelantDesign** [comment]
- [ ] In the cart dropdown, it felt unnatural to not be bale to click on each grant to go to the detail of the grant. Can we consider linking and opening those grants in a new window?

Cart dropdown - no link on each grant
<img width="397" alt="Screen Shot 2021-09-07 at 11 20 47 AM" src="https://user-images.githubusercontent.com/238235/132370905-aed0ba03-c84d-4f6d-83e5-23523effbfe0.png">


Checkout page - link exists for each grant
<img width="322" alt="Screen Shot 2021-09-07 at 11 20 36 AM" src="https://user-images.githubusercontent.com/238235/132370840-5fb9dd98-e886-4855-a969-e083ad5bba65.png">

**Comment by PixelantDesign** [comment]
- [ ] Need to set an image constraint here
<img width="1143" alt="Screen Shot 2021-09-07 at 11 41 15 AM" src="https://user-images.githubusercontent.com/238235/132373833-67d97e5e-24ca-409e-9502-347ec3ecc6d6.png">

- [ ] Create Form - If user is unable to freely create tags, we should update the Sorry message to say "Please select from the list of tags below".
<img width="1144" alt="Screen Shot 2021-09-07 at 11 43 47 AM" src="https://user-images.githubusercontent.com/238235/132373935-ebd911ab-7904-489c-97fb-580962aa6966.png">

**Comment by octavioamu** [comment]
Guys if you have something not related to the changes we did on the sprint and is not a blocker please create a separate ticket.

**Comment by willsputra** [comment]
testing on prod:

- [ ] tag filter: can't see the Clear and Apply button since the list is very long. maybe add either scroll or tag search?
- [ ] filters: checkmark is missing on checkboxes
<img width="1147" alt="Screenshot 2021-09-08 at 7 57 18 PM" src="https://user-images.githubusercontent.com/19514207/132505443-83f154f3-68b0-48ce-9899-c62ee2ecc8ec.png">

**Comment by PixelantDesign** [comment]
- [ ] when no filters are selected, the clear option is still present, when there is nothing to clear
<img width="422" alt="Screen Shot 2021-09-08 at 8 38 21 AM" src="https://user-images.githubusercontent.com/238235/132510796-5a00187a-1d37-4c1d-91dc-10afaa511ca4.png">

- [ ] alignment issues: buttons bumping into each other on mobile number of grants and sort by not properly aligned
<img width="380" alt="Screen Shot 2021-09-08 at 8 37 41 AM" src="https://user-images.githubusercontent.com/238235/132510851-8e9bc2a7-a5ce-4afa-b9d7-ba4b8e4d2725.png">

- [ ] on mobile user can't get to the bottom of the full list of tags, can we consider a scroll bar within the dropdown?
<img width="341" alt="Screen Shot 2021-09-08 at 8 44 23 AM" src="https://user-images.githubusercontent.com/238235/132511607-ab5cd31b-d6ea-47cb-bcc1-ee5d3789c076.png">

**Comment by PixelantDesign** [comment]
- [ ] NFT category might not be hooked up to the right banner, showing explorer default banner
<img width="1217" alt="Screen Shot 2021-09-08 at 12 28 25 PM" src="https://user-images.githubusercontent.com/238235/132548696-f0b02a0b-edbb-44f0-9522-5ea1fb1b717a.png">

**Comment by octavioamu** [comment]
Closing for bug reports create a new issue or use internal CS-L2
