### ISSUE TITLE
API Index Performance Improvements: Dynamic Calculated Information

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#950]
related to https://github.com/gitcoinco/web/pull/936#issuecomment-383610724 : 

The API takes about 6s to return when 'any' is selected from https://gitcoin.co/explorer

Some quick profiling shows that when you disable the dynamic lookups in the API ( 6bd14d66b2cc3a61ff23dade68bded857a53da0c ), then the performance for the same query is down to 1.5s.

For this reason, I believe we should take each of the values that are currently dynamically calculated on API request and store them as part of the model.  This information should then be refreshed in the `refresh_bounties` command which runs every 15 minutes or so.

This will drastically improve API performance

**Comment by owocki** [comment]
yes. since i think this is (1) different scope (2) gonna be done in models.py not the api

**Comment by mbeacom** [comment]
While I agree it's different scope, I just figured this applies to some degree.

I suppose my question was more about whether or not the scope of this issue might be defined differently.

If we're considering migrating those property methods over to actual fields or using some stored value, I don't think it pertains to the API specifically since it's more of a performance burden platform wide to access any of those properties and carry a heavy DB footprint when considered at scale. One solution would be to eliminate the property fields that aren't in use throughout JS files from `dashboard/api.py@BountySerializer.fields` and migrate properties that are used over to something less hindering to performance **OR** cache the offending querysets with a defined TTL, but I don't think caching or property modifications would be considered API centric changes, though.

In any case, it would appear that we're targeting an issue that's independent from the API.

**Comment by owocki** [comment]
while i agree that the changes that need to be made are not API-centric, the only place where this issue manifests is within the API.  

happy to have a convo about tradeoffs of the diff approaches next chance we get

**Comment by kuhnchris** [comment]
This was superseeded by (at least) #3628
