### ISSUE TITLE
Maximum matching showing when it shouldn't 

### ISSUE THREAD

**Issue by tshabs** [gitcoinco/web#9838]
**Describe the bug**
As discussed on the support channel on discord, our grant @ https://gitcoin.co/grants/403/swap-box keeps showing "Maximum matching reached" while we are around $7k matching.  Unfortunately this has caused a massive slowdown in contributions and our matching is just being diluted away bit by bit.

**To Reproduce**
Go to https://gitcoin.co/grants/403/swap-box and see for yourself

**Expected behavior**
Matching to display correctly.

**Screenshots**
![sb_wtf](https://user-images.githubusercontent.com/44111/144901260-be9a50f8-68f3-4786-b12c-8ddee1267cec.png)
![gc_support](https://user-images.githubusercontent.com/44111/144901279-6973c206-c5a7-46ea-a3ee-4f2b97c46672.png)
![gc_support2](https://user-images.githubusercontent.com/44111/144901291-56aa5d79-8d63-4e97-adb1-bee26b18c6ef.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser:  Chromium & Firefox
- Browser Version: Latest. (95 & 94 respectivley)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by frankchen07** [comment]
heyo @tshabs - thanks for being patient with us.

The match cap was part of a [community proposal](https://gov.gitcoin.co/t/proposal-gitcoin-gr12-matching-pool-allocations/9007) that folks voted on, which was the first reason why it found it's way into Grants Round 12. It's currently experimental, so first off, we appreciate your patience with Gitcoin while we work out the kinks.

On Discord, the estimated match display is not a bug, but we're still in the process of figuring out how to appropriately deal with the the combination of how the match cap is affected by the saturation point, which is the cause of the match cap slowly dwindling down.

That being said, we please ask for a little bit more patience as we bring these issues forth to the community and not just our core team for the sake of absolute transparency in order to assess next steps.

We will keep you updated here on how you can follow that conversation as things unfold.

**Comment by tshabs** [comment]
Hi @frankchen07 thanks for getting back to me.

I've managed to figure this out via twitter discussion also.  I think communication about these changes could have been clearer (i know its difficult when experimenting in the open but this was frustrating).

> That being said, we please ask for a little bit more patience as we bring these issues forth to the community and not just our core team for the sake of absolute transparency in order to assess next steps.

I very much appreciate this sentiment and look forwards to see what can be learned.  Thanks :)

**Comment by frankchen07** [comment]
hey @tshabs - here's the latest blog post we've written up about it. We've had a ton of discussion that changes up how we run the normalization and the cap to make it more inline with what was outlined in the governance proposal.

Governance Proposal: https://gov.gitcoin.co/t/proposal-gitcoin-gr12-matching-pool-allocations/9007

Explanatory Blog Post: https://gitcoin.co/blog/grants-round-12-matching-caps/

**Comment by gdixon** [comment]
I'm going to close out this issue, but please feel free to reopen if you have any more questions regarding the recent QF changes.

Thanks again for you patience and understanding @tshabs!
