### ISSUE TITLE
grant funding warning "zkSync checkout not supported due to the use of the token BNB" can this be changed to simply ETH

### ISSUE THREAD

**Issue by Hay-sharptech** [gitcoinco/web#9840]

**Comment by Hay-sharptech** [comment]
"grant funding warning "zkSync checkout not supported due to the use of the token BNB" can this be changed to simply ETH." How do I rectify this?

**Comment by Hay-sharptech** [comment]
I would appreciate if i can change my wallet address from this 0x0b94428af08c6a78fcb303f778de6c53e78fabd5 to this 0x46DCeaf588C5a1A1759935dc07824ffA9f9a4891 to allow more flexibility to the donors of the project.

**Comment by gdixon** [comment]
Hi @Hay-sharptech,

BNB is not supported by zksync!

Could you provide more information regarding the request to change your address? Which grant is this in relation to? We would normally ask that you make this request via twitter from the handle which is associated with your grant.

**Comment by TrustwalletAdmin** [comment]
Hello, good day , due to time difference and interval we are not supposed to text you first at this time,but we were worried and concerned about the support you need,and please note..non of our admins will ask you for your private key, kindly beware of scammers,By the way ;has anyone been able to answer and solve the complaint for you among our admins?

**Comment by Hay-sharptech** [comment]
Yes! Thank you.

**Comment by lthrift** [comment]
If you are still trying to make changes to your grant, please contact support@gitcoin.co
