### ISSUE TITLE
Update Polygon wallet on grant page

### ISSUE THREAD

**Issue by cryptoekof** [gitcoinco/web#9857]

**Comment by gdixon** [comment]
Hey @cryptoekof, 

Thank you for getting in touch. Unfortunately we don't have the functionality in place to set an alternative wallet for just polygon, however please be assured that contributions to any contract wallet are currently being blocked in order to prevent the situation you describe.

A user will see the following error if they attempt to checkout with your grant in their cart:

<img width="767" alt="Screenshot 2021-12-09 at 06 40 08" src="https://user-images.githubusercontent.com/5897836/145347454-a51ad20f-630a-4176-bd5c-c6a93c3dc9d3.png">

--

I'm going to close out this issue for now, but please don't hesitate to reopen/get in touch if we can help with anything else!
