### ISSUE TITLE
Update standard/Polygon Tx Hash flow

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#9989]
**User Story:**
As a grant donor
I want to know when it's safe to close my cart
So that my contribution will count towards my chosen grant(s) matching funds

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/cart
WHEN I click "I'm ready to checkout" and select "standard checkout"
THEN I see the "Confirming transaction..." overlay 
AND I see my wallet overlay

GIVEN that I am checking out on gitcoin.co/grants/cart
WHEN my transaction has been confirmed
THEN I am redirected to gitcoin.co/grants/explorer/
AND I see the "Thank you for contributing..." overlay

**Product & Design Links:**
Figma Link: "[Ready for Dev: Tx Hash](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=48%3A5246)" -> "Tx Hash (Standard)"
Product Brief: [Streamline donor checkout experience](https://www.notion.so/gitcoin/Streamline-donor-checkout-experience-4c70c5926a044facbdb65105d1316a44)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
This all looks good to me.

**Comment by EmHsiehGitcoin** [comment]
hmm, maybe because I'm using Rinkeby? it didn't function as it should for me:
1/ the confirming transaction modal popped up before my metamask opened or click confirm CTA on metamask
2/ when I clicked elsewhere both the metamask and confirming transaction modal go away
3/ when I go to my browser plug-in, clicked on metamask, and confirm the transaction, the confirming transaction modal popped up properly 
4/ however, it went to the thank you modal when it's still pending and before transaction is confirmed 

[Link to video](https://drive.google.com/file/d/1oZe-HcPIdQAO8VL3sckbnnAAMEwdhl_m/view?usp=sharing)
