### ISSUE TITLE
Add pre-commit hook handlers

### ISSUE THREAD

**Issue by eswarasai** [gitcoinco/web#999]
### Why Is this Needed?

*Summary*: Avoid Developer having to run the code linting command before committing the changes -- `npm run eslint:fix; npm run stylelint:fix; isort -rc --atomic .`

### Solution
*Summary*: We can leverage [lint-staged](https://github.com/okonet/lint-staged) to run the above command before adding the files to commit

**Comment by mbeacom** [comment]
We intentionally opted to not automatically run the fixer functionality.  What if the linter results in undesired changes or adversely modifies the files and they're committed?  I don't think it's a huge ask to run `make fix` if you hit the `pre-commit` restrictions and inspect your code before committing it.

If the community wants the automatic fixer functionality to automatically run these, I don't see an issue... but it could result in more questions around local development setup and installation questions since it'll result in a failure if they're missing any of the associated packages (this would clearly happen more frequently because `pre-commit` installation instructions are in the contributing.md documentation but still doesn't seem to be used by some contributors.

**Comment by thelostone-mc** [comment]
Makes things difficult for newbies but makes our life easier as code reviews becomes quicker !

**Comment by mbeacom** [comment]
I think they both have the same result, honestly.  If you commit something that doesn't meet the requirements, it's not going to pass tests, so it shouldn't be merged.  In any case, I'm fine with exploring this option.
